KD Chart 2: KDChartRelativePosition.h File Reference
KDChartRelativePosition.h File Reference
#include <QDebug>
#include <QMetaType>
#include <Qt>
#include <QPointF>
#include <QSizeF>
#include "KDChartGlobal.h"
Classes
class KDChart::RelativePosition
Defines relative position information: reference area, position in this area (reference position), horizontal / vertical padding, and rotation.
Namespaces
KDChart
Functions
KDCHART_EXPORT QDebug operator<< (QDebug, const KDChart::RelativePosition &)
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDChart::RelativePosition, Q_MOVABLE_TYPE)
Function Documentation
operator<<()
KDCHART_EXPORT QDebug operator<< (QDebug , const KDChart::RelativePosition &)
Definition at line 221 of file KDChartRelativePosition.cpp.
References KDChart::RelativePosition::alignment(), KDChart::RelativePosition::horizontalPadding(), KDChart::RelativePosition::referenceArea(), KDChart::RelativePosition::referencePosition(), KDChart::RelativePosition::rotation(), and KDChart::RelativePosition::verticalPadding().
Q_DECLARE_TYPEINFO()
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDChart::RelativePosition , Q_MOVABLE_TYPE)
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/