KD Chart 2: KDChartLayoutItems.cpp File Reference
KDChartLayoutItems.cpp File Reference
#include "KDChartLayoutItems.h"
#include "KDTextDocument.h"
#include "KDChartAbstractArea.h"
#include "KDChartAbstractDiagram.h"
#include "KDChartBackgroundAttributes.h"
#include "KDChartFrameAttributes.h"
#include "KDChartPaintContext.h"
#include "KDChartPainterSaver_p.h"
#include "KDChartPrintingParameters.h"
#include <QTextCursor>
#include <QTextBlockFormat>
#include <QTextDocumentFragment>
#include <QAbstractTextDocumentLayout>
#include <QLayout>
#include <QPainter>
#include <QDebug>
#include <QCoreApplication>
#include <QApplication>
#include <QStringList>
#include <QStyle>
#include <KDABLibFakes>
#include <math.h>
Functions
QRectF rotatedRect (const QRectF &rect, qreal rotation)
static void updateCommonBrush (QBrush &commonBrush, bool &bStart, const KDChart::AbstractArea &area)
Function Documentation
rotatedRect()
QRectF rotatedRect (const QRectF & rect, qreal rotation)
Definition at line 329 of file KDChartLayoutItems.cpp.
Referenced by fitFontSizeToGeometry().
updateCommonBrush()
static void updateCommonBrush (QBrush & commonBrush, bool & bStart, const KDChart::AbstractArea & area) static
Definition at line 927 of file KDChartLayoutItems.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::brush(), KDChart::AbstractAreaBase::frameAttributes(), and KDChart::FrameAttributes::isVisible().
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/