KD Chart 2: KDChartRadarDiagram.cpp File Reference
KDChartRadarDiagram.cpp File Reference
#include "KDChartRadarDiagram.h"
#include "KDChartRadarDiagram_p.h"
#include <QPainter>
#include "KDChartPaintContext.h"
#include "KDChartPainterSaver_p.h"
#include <KDABLibFakes>
Macros
#define d d_func()
Functions
static qreal fitFontSizeToGeometry (const QString &text, const QFont &font, const QRectF &geometry, const TextAttributes &ta)
static QPointF scaleToRealPosition (const QPointF &origin, const QRectF &sourceRect, const QRectF &destRect, const AbstractCoordinatePlane &plane)
Macro Definition Documentation
d
#define d d_func()
Definition at line 43 of file KDChartRadarDiagram.cpp.
Referenced by KDChart::RadarDiagram::clone(), KDChart::RadarDiagram::closeDatasets(), KDChart::RadarDiagram::fillAlpha(), KDChart::RadarDiagram::paint(), KDChart::RadarDiagram::reverseData(), KDChart::RadarDiagram::setCloseDatasets(), KDChart::RadarDiagram::setFillAlpha(), and KDChart::RadarDiagram::setReverseData().
Function Documentation
fitFontSizeToGeometry()
static qreal fitFontSizeToGeometry (const QString & text, const QFont & font, const QRectF & geometry, const TextAttributes & ta) static
Definition at line 110 of file KDChartRadarDiagram.cpp.
References rotatedRect(), and KDChart::TextAttributes::rotation().
Referenced by KDChart::RadarDiagram::paint(), and KDChart::TextLayoutItem::paint().
scaleToRealPosition()
static QPointF scaleToRealPosition (const QPointF & origin, const QRectF & sourceRect, const QRectF & destRect, const AbstractCoordinatePlane & plane) static
Definition at line 136 of file KDChartRadarDiagram.cpp.
References KDChart::AbstractCoordinatePlane::translate().
Referenced by KDChart::RadarDiagram::paint().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/