KD Chart 2: KDChartPieDiagram.cpp File Reference
KDChartPieDiagram.cpp File Reference
#include <QDebug>
#include <QPainter>
#include <QStack>
#include "KDChartPieDiagram.h"
#include "KDChartPieDiagram_p.h"
#include "KDChartPaintContext.h"
#include "KDChartPieAttributes.h"
#include "KDChartPolarCoordinatePlane_p.h"
#include "KDChartThreeDPieAttributes.h"
#include "KDChartPainterSaver_p.h"
#include <KDABLibFakes>
Macros
#define d d_func()
Functions
static bool doArcsOverlap (qreal a1Start, qreal a1End, qreal a2Start, qreal a2End)
static bool doSpansOverlap (qreal s1Start, qreal s1End, qreal s2Start, qreal s2End)
static QLineF labelAttachmentLine (const QPointF &center, const QPointF &start, const QPainterPath &label)
static qreal normProjection (const QLineF &l1, const QLineF &l2)
static QPolygonF polygonFromPainterPath (const QPainterPath &pp)
static int wraparound (int i, int size)
Macro Definition Documentation
d
#define d d_func()
Definition at line 49 of file KDChartPieDiagram.cpp.
Referenced by KDChart::PieDiagram::clone(), KDChart::PieDiagram::isLabelCollisionAvoidanceEnabled(), KDChart::PieDiagram::labelDecorations(), KDChart::PieDiagram::setLabelCollisionAvoidanceEnabled(), and KDChart::PieDiagram::setLabelDecorations().
Function Documentation
doArcsOverlap()
static bool doArcsOverlap (qreal a1Start, qreal a1End, qreal a2Start, qreal a2End) static
Definition at line 701 of file KDChartPieDiagram.cpp.
References doSpansOverlap().
doSpansOverlap()
static bool doSpansOverlap (qreal s1Start, qreal s1End, qreal s2Start, qreal s2End) static
Definition at line 692 of file KDChartPieDiagram.cpp.
Referenced by doArcsOverlap().
labelAttachmentLine()
static QLineF labelAttachmentLine (const QPointF & center, const QPointF & start, const QPainterPath & label) static
Definition at line 385 of file KDChartPieDiagram.cpp.
References normProjection(), and wraparound().
normProjection()
static qreal normProjection (const QLineF & l1, const QLineF & l2) static
Definition at line 379 of file KDChartPieDiagram.cpp.
Referenced by labelAttachmentLine().
polygonFromPainterPath()
static QPolygonF polygonFromPainterPath (const QPainterPath & pp) static
Definition at line 367 of file KDChartPieDiagram.cpp.
wraparound()
static int wraparound (int i, int size) static
Definition at line 293 of file KDChartPieDiagram.cpp.
Referenced by labelAttachmentLine().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/