KD Chart 2: KDChartDataValueAttributes.h File Reference
KDChartDataValueAttributes.h File Reference
Declaring the class KDChart::DataValueAttributes.
#include <Qt>
#include <QMetaType>
#include "KDChartGlobal.h"
#include "KDChartEnums.h"
#include "KDChartRelativePosition.h"
Classes
class KDChart::DataValueAttributes
Diagram attributes dealing with data value labels.
Namespaces
KDChart
Functions
KDCHART_EXPORT QDebug operator<< (QDebug, const KDChart::DataValueAttributes &)
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDChart::DataValueAttributes, Q_MOVABLE_TYPE)
Detailed Description
Declaring the class KDChart::DataValueAttributes.
Definition in file KDChartDataValueAttributes.h.
Function Documentation
operator<<()
KDCHART_EXPORT QDebug operator<< (QDebug , const KDChart::DataValueAttributes &)
Definition at line 330 of file KDChartDataValueAttributes.cpp.
References KDChart::DataValueAttributes::backgroundAttributes(), KDChart::DataValueAttributes::decimalDigits(), KDChart::DataValueAttributes::frameAttributes(), KDChart::DataValueAttributes::isVisible(), KDChart::DataValueAttributes::negativePosition(), KDChart::DataValueAttributes::positivePosition(), KDChart::DataValueAttributes::showOverlappingDataLabels(), KDChart::DataValueAttributes::showRepetitiveDataLabels(), and KDChart::DataValueAttributes::textAttributes().
Q_DECLARE_TYPEINFO()
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDChart::DataValueAttributes , Q_MOVABLE_TYPE)
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/