KD Chart 2: KDChartRulerAttributes.h File Reference
KDChartRulerAttributes.h File Reference
#include <QMetaType>
#include "KDChartGlobal.h"
#include "KDChartEnums.h"
Classes
class KDChart::RulerAttributes
A set of attributes controlling the appearance of axis rulers.
Namespaces
KDChart
Functions
KDCHART_EXPORT QDebug operator<< (QDebug, const KDChart::RulerAttributes &)
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDChart::RulerAttributes, Q_MOVABLE_TYPE)
Function Documentation
operator<<()
KDCHART_EXPORT QDebug operator<< (QDebug , const KDChart::RulerAttributes &)
Definition at line 308 of file KDChartRulerAttributes.cpp.
References KDChart::RulerAttributes::majorTickMarkPen(), KDChart::RulerAttributes::minorTickMarkPen(), KDChart::RulerAttributes::tickMarkPen(), and KDChart::RulerAttributes::tickMarkPens().
Q_DECLARE_TYPEINFO()
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDChart::RulerAttributes , Q_MOVABLE_TYPE)
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/