KD Chart 2: TernaryPoint.h File Reference
TernaryPoint.h File Reference
#include <QtDebug>
#include <QPointF>
Classes
class TernaryPoint
TernaryPoint defines a point within a ternary coordinate plane.
Functions
QDebug operator<< (QDebug stream, const TernaryPoint &point)
QPointF translate (const TernaryPoint &)
Function Documentation
operator<<()
QDebug operator<< (QDebug stream, const TernaryPoint & point)
Definition at line 68 of file TernaryPoint.cpp.
References TernaryPoint::a(), TernaryPoint::b(), TernaryPoint::c(), and TernaryPoint::isValid().
translate()
QPointF translate (const TernaryPoint &)
Definition at line 86 of file TernaryPoint.cpp.
References TernaryPoint::a(), AxisVector_C_A, TernaryPoint::b(), and TernaryPoint::isValid().
Referenced by KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), and KDChart::AbstractDiagram::paintMarkers().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/