KD Chart 2: KDChart::LineAttributes Class Reference
KDChart::LineAttributes Class Reference
Set of attributes for changing the appearance of line charts.
#include <KDChartLineAttributes.h>
Public Types
enum MissingValuesPolicy {
MissingValuesAreBridged,
MissingValuesHideSegments,
MissingValuesShownAsZero,
MissingValuesPolicyIgnored
}
MissingValuesPolicy specifies how a missing value will be shown in a line diagram.
Public Member Functions
int areaBoundingDataset () const
bool displayArea () const
LineAttributes ()
LineAttributes (const LineAttributes &)
MissingValuesPolicy missingValuesPolicy () const
bool operator!= (const LineAttributes &other) const
LineAttributes & operator= (const LineAttributes &)
bool operator== (const LineAttributes &) const
void setAreaBoundingDataset (int dataset)
Sets the lower or upper (depending on the displayed value being positive or negative, resp.) bounding line (i.e., the dataset with the line data).
void setDisplayArea (bool display)
void setMissingValuesPolicy (MissingValuesPolicy policy)
void setTransparency (uint alpha)
uint transparency () const
~LineAttributes ()
Detailed Description
Set of attributes for changing the appearance of line charts.
Definition at line 34 of file KDChartLineAttributes.h.
Member Enumeration Documentation
MissingValuesPolicy
enum KDChart::LineAttributes::MissingValuesPolicy
MissingValuesPolicy specifies how a missing value will be shown in a line diagram.
Missing value is assumed if the data cell contains a QVariant that can not be interpreted as a qreal, or if the data cell is hidden while its dataset is not hidden.
MissingValuesAreBridged the default: No markers will be shown for missing values but the line will be bridged if there is at least one valid cell before and after the missing value(s), otherwise the segment will be hidden.
MissingValuesHideSegments Line segments starting with a missing value will not be shown, and no markers will be shown for missing values, so this will look like a piece of the line is missing.
MissingValuesShownAsZero Missing value(s) will be treated like normal zero values, and markers will shown for them too, so there will be no visible difference between a zero value and a missing value.
MissingValuesPolicyIgnored (internal value, do not use)
Enumerator
MissingValuesAreBridged
MissingValuesHideSegments
MissingValuesShownAsZero
MissingValuesPolicyIgnored
Definition at line 55 of file KDChartLineAttributes.h.
Constructor & Destructor Documentation
LineAttributes() [1/2]
LineAttributes::LineAttributes ()
Definition at line 56 of file KDChartLineAttributes.cpp.
LineAttributes() [2/2]
LineAttributes::LineAttributes (const LineAttributes & r)
Definition at line 61 of file KDChartLineAttributes.cpp.
~LineAttributes()
LineAttributes::~LineAttributes ()
Definition at line 76 of file KDChartLineAttributes.cpp.
Member Function Documentation
areaBoundingDataset()
int LineAttributes::areaBoundingDataset () const
Definition at line 127 of file KDChartLineAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
displayArea()
bool LineAttributes::displayArea () const
Definition at line 105 of file KDChartLineAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
missingValuesPolicy()
LineAttributes::MissingValuesPolicy LineAttributes::missingValuesPolicy () const
Definition at line 95 of file KDChartLineAttributes.cpp.
References d.
Referenced by operator==().
operator!=()
bool KDChart::LineAttributes::operator!= (const LineAttributes & other) const
Definition at line 88 of file KDChartLineAttributes.h.
References KDGantt::operator==().
operator=()
LineAttributes & LineAttributes::operator= (const LineAttributes & r)
Definition at line 66 of file KDChartLineAttributes.cpp.
References d.
operator==()
bool LineAttributes::operator== (const LineAttributes & r) const
Definition at line 81 of file KDChartLineAttributes.cpp.
References areaBoundingDataset(), displayArea(), missingValuesPolicy(), and transparency().
setAreaBoundingDataset()
void LineAttributes::setAreaBoundingDataset (int dataset)
Sets the lower or upper (depending on the displayed value being positive or negative, resp.) bounding line (i.e., the dataset with the line data).
The area is then drawn between this line and the line of the specified dataset. Pass -1 to draw the area between this line and the zero line.
Definition at line 122 of file KDChartLineAttributes.cpp.
References d.
setDisplayArea()
void LineAttributes::setDisplayArea (bool display)
Definition at line 100 of file KDChartLineAttributes.cpp.
References d.
setMissingValuesPolicy()
void LineAttributes::setMissingValuesPolicy (MissingValuesPolicy policy)
Definition at line 90 of file KDChartLineAttributes.cpp.
References d.
setTransparency()
void LineAttributes::setTransparency (uint alpha)
Definition at line 110 of file KDChartLineAttributes.cpp.
References d.
transparency()
uint LineAttributes::transparency () const
Definition at line 117 of file KDChartLineAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
The documentation for this class was generated from the following files:
KDChartLineAttributes.h
KDChartLineAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/