KD Chart 2: KDChart::PrivateAttributesModel Class Reference
KDChart::PrivateAttributesModel Class Reference
Internally used class just adding a special constructor used by AbstractDiagram.
#include <KDChartAbstractDiagram.h>
Public Types
enum PaletteType {
PaletteTypeDefault = 0,
PaletteTypeRainbow = 1,
PaletteTypeSubdued = 2
}
Signals
void attributesChanged (const QModelIndex &, const QModelIndex &)
Public Member Functions
int columnCount (const QModelIndex &) const
[reimplemented]
bool compare (const AttributesModel *other) const
Returns true if both, all of the attributes set, and the palette set is equal in both of the AttributeModels.
bool compareAttributes (int role, const QVariant &a, const QVariant &b) const
QVariant data (int role) const
Returns the data that were specified at global level, or the default data, or QVariant().
QVariant data (int column, int role) const
Returns the data that were specified at per column level, or the globally set data, or the default data, or QVariant().
QVariant data (const QModelIndex &, int role=Qt::DisplayRole) const
[reimplemented]
int datasetDimension () const
virtual QVariant defaultHeaderData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns default values for the header data.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
[reimplemented]
QModelIndex index (int row, int col, const QModelIndex &index) const
void initFrom (const AttributesModel *other)
Copies the internal data (maps and palette) of another AttributesModel* into this one.
bool isKnownAttributesRole (int role) const
Returns whether the given role corresponds to one of the known internally used ones.
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
QVariant modelData (int role) const
PaletteType paletteType () const
QModelIndex parent (const QModelIndex &index) const
PrivateAttributesModel (QAbstractItemModel *model, QObject *parent=0)
bool resetData (const QModelIndex &index, int role=Qt::DisplayRole)
Remove any explicit attributes settings that might have been specified before.
bool resetHeaderData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole)
Remove any explicit attributes settings that might have been specified before.
int rowCount (const QModelIndex &) const
[reimplemented]
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::DisplayRole)
[reimplemented]
void setDatasetDimension (int dimension)
Set the dimension of the dataset in the source model.
void setDefaultForRole (int role, const QVariant &value)
Define the default value for a certain role.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::DisplayRole)
[reimplemented]
bool setModelData (const QVariant value, int role)
void setPaletteType (PaletteType type)
Sets the palettetype used by this attributesmodel.
void setSourceModel (QAbstractItemModel *sourceModel)
[reimplemented]
Detailed Description
Internally used class just adding a special constructor used by AbstractDiagram.
Definition at line 734 of file KDChartAbstractDiagram.h.
Member Enumeration Documentation
PaletteType
enum KDChart::AttributesModel::PaletteType inherited
Enumerator
PaletteTypeDefault
PaletteTypeRainbow
PaletteTypeSubdued
Definition at line 51 of file KDChartAttributesModel.h.
Constructor & Destructor Documentation
PrivateAttributesModel()
KDChart::PrivateAttributesModel::PrivateAttributesModel (QAbstractItemModel * model, QObject * parent = 0) explicit
Definition at line 737 of file KDChartAbstractDiagram.h.
Member Function Documentation
attributesChanged
void KDChart::AttributesModel::attributesChanged (const QModelIndex & , const QModelIndex &) signal inherited
Referenced by KDChart::AttributesModel::setData(), and KDChart::AttributesModel::setHeaderData().
columnCount()
int AttributesModel::columnCount (const QModelIndex & index) const inherited
[reimplemented]
Definition at line 510 of file KDChartAttributesModel.cpp.
References KDChart::AbstractProxyModel::index(), and KDChart::AbstractProxyModel::mapToSource().
Referenced by KDChart::AttributesModel::setHeaderData().
compare()
bool AttributesModel::compare (const AttributesModel * other) const inherited
Returns true if both, all of the attributes set, and the palette set is equal in both of the AttributeModels.
Definition at line 123 of file KDChartAttributesModel.cpp.
References KDChart::AttributesModel::compareAttributes(), d, and KDChart::AttributesModel::paletteType().
Referenced by KDChart::AbstractDiagram::compare().
compareAttributes()
bool AttributesModel::compareAttributes (int role, const QVariant & a, const QVariant & b) const inherited
Definition at line 185 of file KDChartAttributesModel.cpp.
References KDChart::BarAttributesRole, KDChart::DataHiddenRole, KDChart::DatasetBrushRole, KDChart::DatasetPenRole, KDChart::DataValueLabelAttributesRole, KDChart::AttributesModel::isKnownAttributesRole(), KDChart::LineAttributesRole, KDChart::PieAttributesRole, KDChart::StockBarAttributesRole, KDChart::ThreeDAttributesRole, KDChart::ThreeDBarAttributesRole, KDChart::ThreeDLineAttributesRole, KDChart::ThreeDPieAttributesRole, and KDChart::ValueTrackerAttributesRole.
Referenced by KDChart::AttributesModel::compare().
data() [1/3]
QVariant AttributesModel::data (int role) const inherited
Returns the data that were specified at global level, or the default data, or QVariant().
Definition at line 299 of file KDChartAttributesModel.cpp.
References KDChart::AttributesModel::isKnownAttributesRole(), and KDChart::AttributesModel::modelData().
Referenced by KDChart::AbstractDiagram::brush(), KDChart::AttributesModel::data(), KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::AbstractDiagram::pen().
data() [2/3]
QVariant AttributesModel::data (int column, int role) const inherited
Returns the data that were specified at per column level, or the globally set data, or the default data, or QVariant().
Definition at line 314 of file KDChartAttributesModel.cpp.
References KDChart::AttributesModel::data(), KDChart::AttributesModel::headerData(), and KDChart::AttributesModel::isKnownAttributesRole().
data() [3/3]
QVariant AttributesModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const inherited
[reimplemented]
Definition at line 330 of file KDChartAttributesModel.cpp.
References d, KDChart::AttributesModel::data(), KDChart::AbstractProxyModel::index(), and KDChart::AbstractProxyModel::mapToSource().
datasetDimension()
int AttributesModel::datasetDimension () const inherited
Definition at line 712 of file KDChartAttributesModel.cpp.
References d.
defaultHeaderData()
QVariant AttributesModel::defaultHeaderData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual inherited
Returns default values for the header data.
Definition at line 273 of file KDChartAttributesModel.cpp.
References d, KDChart::DatasetBrushRole, KDChart::DatasetPenRole, KDChart::AttributesModel::headerData(), and KDChart::AttributesModel::modelData().
Referenced by KDChart::AttributesModel::headerData().
headerData()
QVariant AttributesModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const inherited
[reimplemented]
Definition at line 247 of file KDChartAttributesModel.cpp.
References d, and KDChart::AttributesModel::defaultHeaderData().
Referenced by KDChart::AttributesModel::data(), KDChart::AttributesModel::defaultHeaderData(), KDChart::AbstractDiagram::itemRowLabels(), and KDChart::AttributesModel::setHeaderData().
index()
QModelIndex KDChart::AbstractProxyModel::index (int row, int col, const QModelIndex & index) const inherited
[reimplemented]
Definition at line 87 of file KDChartAbstractProxyModel.cpp.
References KDChart::AbstractProxyModel::mapFromSource(), and KDChart::AbstractProxyModel::mapToSource().
Referenced by KDChart::AttributesModel::columnCount(), KDChart::AttributesModel::data(), KDChart::AbstractProxyModel::parent(), KDChart::AttributesModel::resetData(), KDChart::AttributesModel::rowCount(), KDChart::AttributesModel::setData(), and KDChart::AttributesModel::setHeaderData().
initFrom()
void AttributesModel::initFrom (const AttributesModel * other) inherited
Copies the internal data (maps and palette) of another AttributesModel* into this one.
Definition at line 92 of file KDChartAttributesModel.cpp.
References d.
Referenced by KDChart::AbstractDiagram::setModel().
isKnownAttributesRole()
bool AttributesModel::isKnownAttributesRole (int role) const inherited
Returns whether the given role corresponds to one of the known internally used ones.
Definition at line 368 of file KDChartAttributesModel.cpp.
References KDChart::BarAttributesRole, KDChart::DataHiddenRole, KDChart::DatasetBrushRole, KDChart::DatasetPenRole, KDChart::DataValueLabelAttributesRole, KDChart::LineAttributesRole, KDChart::PieAttributesRole, KDChart::StockBarAttributesRole, KDChart::ThreeDAttributesRole, KDChart::ThreeDBarAttributesRole, KDChart::ThreeDLineAttributesRole, KDChart::ThreeDPieAttributesRole, and KDChart::ValueTrackerAttributesRole.
Referenced by KDChart::AttributesModel::compareAttributes(), KDChart::AttributesModel::data(), KDChart::AttributesModel::setData(), and KDChart::AttributesModel::setHeaderData().
mapFromSource()
QModelIndex KDChart::AbstractProxyModel::mapFromSource (const QModelIndex & sourceIndex) const inherited
[reimplemented]
Definition at line 55 of file KDChartAbstractProxyModel.cpp.
Referenced by KDChart::AbstractProxyModel::index(), and KDChart::AbstractProxyModel::parent().
mapToSource()
QModelIndex KDChart::AbstractProxyModel::mapToSource (const QModelIndex & proxyIndex) const inherited
[reimplemented]
Definition at line 68 of file KDChartAbstractProxyModel.cpp.
Referenced by KDChart::AttributesModel::columnCount(), KDChart::AttributesModel::data(), KDChart::AbstractProxyModel::index(), KDChart::AbstractProxyModel::parent(), KDChart::AttributesModel::rowCount(), and KDChart::AttributesModel::setData().
modelData()
QVariant KDChart::AttributesModel::modelData (int role) const inherited
Definition at line 496 of file KDChartAttributesModel.cpp.
References d.
Referenced by KDChart::AttributesModel::data(), KDChart::AbstractDiagram::dataValueAttributes(), KDChart::AttributesModel::defaultHeaderData(), and KDChart::AbstractDiagram::isHidden().
paletteType()
AttributesModel::PaletteType AttributesModel::paletteType () const inherited
Definition at line 477 of file KDChartAttributesModel.cpp.
References d.
Referenced by KDChart::AttributesModel::compare().
parent()
QModelIndex KDChart::AbstractProxyModel::parent (const QModelIndex & index) const inherited
[reimplemented]
Definition at line 93 of file KDChartAbstractProxyModel.cpp.
References KDChart::AbstractProxyModel::index(), KDChart::AbstractProxyModel::mapFromSource(), and KDChart::AbstractProxyModel::mapToSource().
resetData()
bool AttributesModel::resetData (const QModelIndex & index, int role = Qt::DisplayRole) inherited
Remove any explicit attributes settings that might have been specified before.
Definition at line 410 of file KDChartAttributesModel.cpp.
References KDChart::AbstractProxyModel::index(), and KDChart::AttributesModel::setData().
resetHeaderData()
bool AttributesModel::resetHeaderData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) inherited
Remove any explicit attributes settings that might have been specified before.
Definition at line 451 of file KDChartAttributesModel.cpp.
References KDChart::AttributesModel::setHeaderData().
rowCount()
int AttributesModel::rowCount (const QModelIndex & index) const inherited
[reimplemented]
Definition at line 501 of file KDChartAttributesModel.cpp.
References KDChart::AbstractProxyModel::index(), and KDChart::AbstractProxyModel::mapToSource().
Referenced by KDChart::AbstractDiagram::itemRowLabels(), and KDChart::AttributesModel::setHeaderData().
setData()
bool AttributesModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::DisplayRole) inherited
[reimplemented]
Definition at line 397 of file KDChartAttributesModel.cpp.
References KDChart::AttributesModel::attributesChanged(), d, KDChart::AbstractProxyModel::index(), KDChart::AttributesModel::isKnownAttributesRole(), and KDChart::AbstractProxyModel::mapToSource().
Referenced by KDChart::AttributesModel::resetData(), KDChart::BarDiagram::setBarAttributes(), KDChart::AbstractDiagram::setBrush(), and KDChart::AbstractDiagram::setPen().
setDatasetDimension()
void AttributesModel::setDatasetDimension (int dimension) inherited
Set the dimension of the dataset in the source model.
See also
AbstractDiagram::setDatasetDimension
Definition at line 706 of file KDChartAttributesModel.cpp.
References d.
setDefaultForRole()
void AttributesModel::setDefaultForRole (int role, const QVariant & value) inherited
Define the default value for a certain role.
Passing a default-constructed QVariant is equivalent to removing the default.
Definition at line 691 of file KDChartAttributesModel.cpp.
References d.
Referenced by KDChart::AttributesModel::AttributesModel(), and KDChart::TernaryLineDiagram::TernaryLineDiagram().
setHeaderData()
bool AttributesModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::DisplayRole) inherited
[reimplemented]
Definition at line 415 of file KDChartAttributesModel.cpp.
References KDChart::AttributesModel::attributesChanged(), KDChart::AttributesModel::columnCount(), d, KDChart::AttributesModel::headerData(), KDChart::AbstractProxyModel::index(), KDChart::AttributesModel::isKnownAttributesRole(), and KDChart::AttributesModel::rowCount().
Referenced by KDChart::AttributesModel::resetHeaderData().
setModelData()
bool KDChart::AttributesModel::setModelData (const QVariant value, int role) inherited
Definition at line 482 of file KDChartAttributesModel.cpp.
References d.
Referenced by KDChart::AbstractDiagram::setBrush(), and KDChart::AbstractDiagram::setPen().
setPaletteType()
void AttributesModel::setPaletteType (AttributesModel::PaletteType type) inherited
Sets the palettetype used by this attributesmodel.
Definition at line 456 of file KDChartAttributesModel.cpp.
References d, KDChart::Palette::defaultPalette(), KDChart::AttributesModel::PaletteTypeDefault, KDChart::AttributesModel::PaletteTypeRainbow, KDChart::AttributesModel::PaletteTypeSubdued, KDChart::Palette::rainbowPalette(), and KDChart::Palette::subduedPalette().
setSourceModel()
void AttributesModel::setSourceModel (QAbstractItemModel * sourceModel) inherited
[reimplemented]
Definition at line 519 of file KDChartAttributesModel.cpp.
Referenced by KDChart::AttributesModel::AttributesModel().
The documentation for this class was generated from the following file:
KDChartAbstractDiagram.h
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/