KD Chart 2: KDChart::Measure Class Reference
KDChart::Measure Class Reference
Measure is used to specify relative and absolute sizes in KDChart, e.g.
#include <KDChartMeasure>
Public Member Functions
qreal calculatedValue (const QObject *autoArea, KDChartEnums::MeasureOrientation autoOrientation) const
The reference area must either be derived from AbstractArea or from QWidget, so it can also be derived from AbstractAreaWidget.
qreal calculatedValue (const QSizeF &autoSize, KDChartEnums::MeasureOrientation autoOrientation) const
KDChartEnums::MeasureCalculationMode calculationMode () const
Measure ()
Measure (qreal value, KDChartEnums::MeasureCalculationMode mode=KDChartEnums::MeasureCalculationModeAuto, KDChartEnums::MeasureOrientation orientation=KDChartEnums::MeasureOrientationAuto)
Measure (const Measure &)
bool operator!= (const Measure &other) const
Measure & operator= (const Measure &)
bool operator== (const Measure &) const
const QObject * referenceArea () const
The returned reference area will be derived from AbstractArea or QWidget or both.
KDChartEnums::MeasureOrientation referenceOrientation () const
void setAbsoluteValue (qreal val)
This is a convenience method for specifying a value, implicitly setting the calculation mode to MeasureCalculationModeAbsolute.
void setCalculationMode (KDChartEnums::MeasureCalculationMode mode)
void setReferenceArea (const QObject *area)
The reference area must either be derived from AbstractArea or from QWidget, so it can also be derived from AbstractAreaWidget.
void setReferenceOrientation (KDChartEnums::MeasureOrientation orientation)
void setRelativeMode (const QObject *area, KDChartEnums::MeasureOrientation orientation)
The reference area must either be derived from AbstractArea or from QWidget, so it can also be derived from AbstractAreaWidget.
void setValue (qreal val)
const QSizeF sizeOfArea (const QObject *area) const
qreal value () const
Detailed Description
Measure is used to specify relative and absolute sizes in KDChart, e.g.
font sizes.
Definition at line 51 of file KDChartMeasure.h.
Constructor & Destructor Documentation
Measure() [1/3]
KDChart::Measure::Measure ()
Definition at line 39 of file KDChartMeasure.cpp.
Measure() [2/3]
KDChart::Measure::Measure (qreal value, KDChartEnums::MeasureCalculationMode mode = KDChartEnums::MeasureCalculationModeAuto, KDChartEnums::MeasureOrientation orientation = KDChartEnums::MeasureOrientationAuto)
Definition at line 48 of file KDChartMeasure.cpp.
Measure() [3/3]
KDChart::Measure::Measure (const Measure & r)
Definition at line 59 of file KDChartMeasure.cpp.
Member Function Documentation
calculatedValue() [1/2]
qreal KDChart::Measure::calculatedValue (const QObject * autoArea, KDChartEnums::MeasureOrientation autoOrientation) const
The reference area must either be derived from AbstractArea or from QWidget, so it can also be derived from AbstractAreaWidget.
Definition at line 137 of file KDChartMeasure.cpp.
References sizeOfArea().
Referenced by KDChart::TextAttributes::calculatedFontSize(), and KDChart::RelativePosition::calculatedPoint().
calculatedValue() [2/2]
qreal KDChart::Measure::calculatedValue (const QSizeF & autoSize, KDChartEnums::MeasureOrientation autoOrientation) const
Definition at line 81 of file KDChartMeasure.cpp.
References KDChartEnums::MeasureCalculationModeAbsolute, KDChartEnums::MeasureCalculationModeAuto, KDChartEnums::MeasureCalculationModeAutoArea, KDChartEnums::MeasureCalculationModeAutoOrientation, KDChartEnums::MeasureCalculationModeRelative, KDChartEnums::MeasureOrientationAuto, KDChartEnums::MeasureOrientationHorizontal, KDChartEnums::MeasureOrientationMaximum, KDChartEnums::MeasureOrientationMinimum, KDChartEnums::MeasureOrientationVertical, sizeOfArea(), and value().
calculationMode()
KDChartEnums::MeasureCalculationMode KDChart::Measure::calculationMode () const
Definition at line 65 of file KDChartMeasure.h.
Referenced by operator<<(), operator=(), and operator==().
operator!=()
bool KDChart::Measure::operator!= (const Measure & other) const
Definition at line 118 of file KDChartMeasure.h.
References KDGantt::operator==().
operator=()
Measure & KDChart::Measure::operator= (const Measure & r)
Definition at line 68 of file KDChartMeasure.cpp.
References calculationMode(), referenceArea(), referenceOrientation(), and value().
operator==()
bool KDChart::Measure::operator== (const Measure & r) const
Definition at line 180 of file KDChartMeasure.cpp.
References calculationMode(), referenceArea(), referenceOrientation(), and value().
referenceArea()
const QObject* KDChart::Measure::referenceArea () const
The returned reference area will be derived from AbstractArea or QWidget or both.
Definition at line 104 of file KDChartMeasure.h.
Referenced by operator<<(), operator=(), and operator==().
referenceOrientation()
KDChartEnums::MeasureOrientation KDChart::Measure::referenceOrientation () const
Definition at line 107 of file KDChartMeasure.h.
Referenced by operator<<(), operator=(), and operator==().
setAbsoluteValue()
void KDChart::Measure::setAbsoluteValue (qreal val)
This is a convenience method for specifying a value, implicitly setting the calculation mode to MeasureCalculationModeAbsolute.
Calling setAbsoluteValue(value) is the same as calling
    setValue( value );
    setCalculationMode( KDChartEnums::MeasureCalculationModeAbsolute );
Definition at line 89 of file KDChartMeasure.h.
References KDChartEnums::MeasureCalculationModeAbsolute.
setCalculationMode()
void KDChart::Measure::setCalculationMode (KDChartEnums::MeasureCalculationMode mode)
Definition at line 64 of file KDChartMeasure.h.
setReferenceArea()
void KDChart::Measure::setReferenceArea (const QObject * area)
The reference area must either be derived from AbstractArea or from QWidget, so it can also be derived from AbstractAreaWidget.
Definition at line 99 of file KDChartMeasure.h.
setReferenceOrientation()
void KDChart::Measure::setReferenceOrientation (KDChartEnums::MeasureOrientation orientation)
Definition at line 106 of file KDChartMeasure.h.
setRelativeMode()
void KDChart::Measure::setRelativeMode (const QObject * area, KDChartEnums::MeasureOrientation orientation)
The reference area must either be derived from AbstractArea or from QWidget, so it can also be derived from AbstractAreaWidget.
Definition at line 71 of file KDChartMeasure.h.
References KDChartEnums::MeasureCalculationModeRelative.
Referenced by KDChart::Chart::addHeaderFooter().
setValue()
void KDChart::Measure::setValue (qreal val)
Definition at line 61 of file KDChartMeasure.h.
Referenced by KDChart::CartesianAxis::titleTextAttributes().
sizeOfArea()
const QSizeF KDChart::Measure::sizeOfArea (const QObject * area) const
Definition at line 144 of file KDChartMeasure.cpp.
References KDChart::GlobalMeasureScaling::currentFactors(), KDChart::GlobalMeasureScaling::instance(), KDChartEnums::MeasureCalculationModeAbsolute, and KDChart::CartesianCoordinatePlane::visibleDiagramArea().
Referenced by calculatedValue().
value()
qreal KDChart::Measure::value () const
Definition at line 62 of file KDChartMeasure.h.
Referenced by calculatedValue(), operator<<(), operator=(), and operator==().
The documentation for this class was generated from the following files:
KDChartMeasure.h
KDChartMeasure.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/