KD Chart 2: KDChart::PlotterDiagramCompressor Class Reference
KDChart::PlotterDiagramCompressor Class Reference
#include <KDChartPlotterDiagramCompressor.h>
Classes
class CachePosition
class DataPoint
class Iterator
Public Types
enum CompressionMode {
SLOPE = 0,
DISTANCE,
BOTH
}
typedef QVector< DataPoint > DataPointVector
Signals
void boundariesChanged ()
void rowCountChanged ()
Public Member Functions
Iterator begin (int dataSet)
void cleanCache ()
DataPoint data (const CachePosition &pos) const
QPair< QPointF, QPointF > dataBoundaries () const
int datasetCount () const
Iterator end (int dataSet)
qreal maxSlopeChange () const
QAbstractItemModel * model () const
PlotterDiagramCompressor (QObject *parent=0)
int rowCount () const
void setCompressionModel (CompressionMode value)
void setForcedDataBoundaries (const QPair< qreal, qreal > &bounds, Qt::Orientation direction)
void setMaxSlopeChange (qreal value)
void setMergeRadius (qreal radius)
void setMergeRadiusPercentage (qreal radius)
void setModel (QAbstractItemModel *model)
~PlotterDiagramCompressor ()
Detailed Description
Definition at line 43 of file KDChartPlotterDiagramCompressor.h.
Member Typedef Documentation
DataPointVector
typedef QVector<DataPoint> KDChart::PlotterDiagramCompressor::DataPointVector
Definition at line 114 of file KDChartPlotterDiagramCompressor.h.
Member Enumeration Documentation
CompressionMode
enum KDChart::PlotterDiagramCompressor::CompressionMode
Enumerator
SLOPE
DISTANCE
BOTH
Definition at line 49 of file KDChartPlotterDiagramCompressor.h.
Constructor & Destructor Documentation
PlotterDiagramCompressor()
PlotterDiagramCompressor::PlotterDiagramCompressor (QObject * parent = 0) explicit
Definition at line 789 of file KDChartPlotterDiagramCompressor.cpp.
~PlotterDiagramCompressor()
PlotterDiagramCompressor::~PlotterDiagramCompressor ()
Definition at line 795 of file KDChartPlotterDiagramCompressor.cpp.
References d.
Member Function Documentation
begin()
PlotterDiagramCompressor::Iterator PlotterDiagramCompressor::begin (int dataSet)
Definition at line 926 of file KDChartPlotterDiagramCompressor.cpp.
References d.
boundariesChanged
void KDChart::PlotterDiagramCompressor::boundariesChanged () signal
Referenced by setForcedDataBoundaries(), and setMaxSlopeChange().
cleanCache()
void PlotterDiagramCompressor::cleanCache ()
Definition at line 898 of file KDChartPlotterDiagramCompressor.cpp.
References d.
data()
PlotterDiagramCompressor::DataPoint PlotterDiagramCompressor::data (const CachePosition & pos) const
Definition at line 841 of file KDChartPlotterDiagramCompressor.cpp.
References d, KDChart::PlotterDiagramCompressor::DataPoint::index, KDChart::PlotterDiagramCompressor::DataPoint::key, and KDChart::PlotterDiagramCompressor::DataPoint::value.
Referenced by KDChart::PlotterDiagramCompressor::Iterator::Iterator(), and KDChart::PlotterDiagramCompressor::Iterator::operator++().
dataBoundaries()
QPair< QPointF, QPointF > PlotterDiagramCompressor::dataBoundaries () const
Definition at line 910 of file KDChartPlotterDiagramCompressor.cpp.
References d.
Referenced by setMergeRadiusPercentage().
datasetCount()
int PlotterDiagramCompressor::datasetCount () const
Definition at line 903 of file KDChartPlotterDiagramCompressor.cpp.
References d.
Referenced by KDChart::PlotterDiagramCompressor::Iterator::Iterator(), and setModel().
end()
PlotterDiagramCompressor::Iterator PlotterDiagramCompressor::end (int dataSet)
Definition at line 932 of file KDChartPlotterDiagramCompressor.cpp.
maxSlopeChange()
qreal PlotterDiagramCompressor::maxSlopeChange () const
Definition at line 879 of file KDChartPlotterDiagramCompressor.cpp.
References d.
model()
QAbstractItemModel * PlotterDiagramCompressor::model () const
Definition at line 815 of file KDChartPlotterDiagramCompressor.cpp.
References d.
Referenced by setModel().
rowCount()
int PlotterDiagramCompressor::rowCount () const
Definition at line 893 of file KDChartPlotterDiagramCompressor.cpp.
References d.
Referenced by KDChart::PlotterDiagramCompressor::Iterator::Iterator(), and KDChart::PlotterDiagramCompressor::Iterator::operator++().
rowCountChanged
void KDChart::PlotterDiagramCompressor::rowCountChanged () signal
Referenced by setCompressionModel(), and setMergeRadius().
setCompressionModel()
void PlotterDiagramCompressor::setCompressionModel (CompressionMode value)
Definition at line 699 of file KDChartPlotterDiagramCompressor.cpp.
References d, and rowCountChanged().
setForcedDataBoundaries()
void PlotterDiagramCompressor::setForcedDataBoundaries (const QPair< qreal, qreal > & bounds, Qt::Orientation direction)
Definition at line 801 of file KDChartPlotterDiagramCompressor.cpp.
References boundariesChanged(), and d.
setMaxSlopeChange()
void PlotterDiagramCompressor::setMaxSlopeChange (qreal value)
Definition at line 870 of file KDChartPlotterDiagramCompressor.cpp.
References boundariesChanged(), and d.
setMergeRadius()
void PlotterDiagramCompressor::setMergeRadius (qreal radius)
Definition at line 860 of file KDChartPlotterDiagramCompressor.cpp.
References d, rowCountChanged(), and SLOPE.
Referenced by setMergeRadiusPercentage().
setMergeRadiusPercentage()
void PlotterDiagramCompressor::setMergeRadiusPercentage (qreal radius)
Definition at line 884 of file KDChartPlotterDiagramCompressor.cpp.
References dataBoundaries(), and setMergeRadius().
setModel()
void PlotterDiagramCompressor::setModel (QAbstractItemModel * model)
Definition at line 821 of file KDChartPlotterDiagramCompressor.cpp.
References d, datasetCount(), and model().
The documentation for this class was generated from the following files:
KDChartPlotterDiagramCompressor.h
KDChartPlotterDiagramCompressor.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/