KD Chart 2: KDChart::RingDiagram Class Reference
KDChart::RingDiagram Class Reference
RingDiagram defines a common ring diagram.
#include <KDChartRingDiagram.h>
Signals
void aboutToBeDestroyed ()
This signal is emitted when this diagram is being destroyed, but before all the data, i.e.
void attributesModelAboutToChange (AttributesModel *newModel, AttributesModel *oldModel)
This signal is emitted just before the new attributes model is connected internally.
void boundariesChanged ()
Emitted upon change of a data boundary.
void dataHidden ()
This signal is emitted, when the hidden status of at least one data cell was (un)set.
void layoutChanged (AbstractDiagram *)
Diagrams are supposed to emit this signal, when the layout of one of their element changes.
void modelDataChanged ()
This signal is emitted, when the model data is changed.
void modelsChanged ()
This signal is emitted when either the model or the AttributesModel is replaced.
void propertiesChanged ()
Emitted upon change of a property of the Diagram.
void viewportCoordinateSystemChanged ()
Emitted upon change of the view coordinate system.
Public Member Functions
bool allowOverlappingDataValueTexts () const
bool antiAliasing () const
virtual AttributesModel * attributesModel () const
Returns the AttributesModel, that is used by this diagram.
bool autoRotateLabels () const
QBrush brush () const
Retrieve the brush to be used for painting datapoints globally.
QBrush brush (int dataset) const
Retrieve the brush to be used for the given dataset.
QBrush brush (const QModelIndex &index) const
Retrieve the brush to be used, for painting the datapoint at the given index in the model.
virtual RingDiagram * clone () const
Creates an exact copy of this diagram.
int columnCount () const
bool compare (const AbstractPieDiagram *other) const
Returns true if both diagrams have the same settings.
bool compare (const RingDiagram *other) const
Returns true if both diagrams have the same settings.
bool compare (const AbstractDiagram *other) const
Returns true if both diagrams have the same settings.
AbstractCoordinatePlane * coordinatePlane () const
The coordinate plane associated with the diagram.
const QPair< QPointF, QPointF > dataBoundaries () const
Return the bottom left and top right data point, that the diagram will display (unless the grid adjusts these values).
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
[reimplemented]
QList< QBrush > datasetBrushes () const
The set of dataset brushes currently used, for use in legends, etc.
int datasetDimension () const
The dataset dimension of a diagram determines how many value dimensions it expects each datapoint to have.
QStringList datasetLabels () const
The set of dataset labels currently displayed, for use in legends, etc.
QList< MarkerAttributes > datasetMarkers () const
The set of dataset markers currently used, for use in legends, etc.
QList< QPen > datasetPens () const
The set of dataset pens currently used, for use in legends, etc.
DataValueAttributes dataValueAttributes () const
Retrieve the DataValueAttributes specified globally.
DataValueAttributes dataValueAttributes (int dataset) const
Retrieve the DataValueAttributes for the given dataset.
DataValueAttributes dataValueAttributes (const QModelIndex &index) const
Retrieve the DataValueAttributes for the given index.
virtual void doItemsLayout ()
[reimplemented]
virtual bool expandWhenExploded () const
qreal granularity () const
virtual int horizontalOffset () const
[reimplemented]
virtual QModelIndex indexAt (const QPoint &point) const
[reimplemented]
QModelIndexList indexesAt (const QPoint &point) const
This method is added alongside with indexAt from QAIM, since in kdchart multiple indexes can be displayed at the same spot.
QModelIndexList indexesIn (const QRect &rect) const
bool isHidden () const
Retrieve the hidden status specified globally.
bool isHidden (int dataset) const
Retrieve the hidden status for the given dataset.
bool isHidden (const QModelIndex &index) const
Retrieve the hidden status for the given index.
virtual bool isIndexHidden (const QModelIndex &index) const
[reimplemented]
QStringList itemRowLabels () const
The set of item row labels currently displayed, for use in Abscissa axes, etc.
virtual QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
[reimplemented]
virtual qreal numberOfDatasets () const
virtual qreal numberOfGridRings () const
[reimplemented]
virtual qreal numberOfValuesPerDataset () const
[reimplemented]
void paintDataValueText (QPainter *painter, const QModelIndex &index, const QPointF &pos, qreal value)
virtual void paintMarker (QPainter *painter, const MarkerAttributes &markerAttributes, const QBrush &brush, const QPen &, const QPointF &point, const QSizeF &size)
void paintMarker (QPainter *painter, const DataValueAttributes &a, const QModelIndex &index, const QPointF &pos)
void paintMarker (QPainter *painter, const QModelIndex &index, const QPointF &pos)
QPen pen () const
Retrieve the pen to be used for painting datapoints globally.
QPen pen (int dataset) const
Retrieve the pen to be used for the given dataset.
QPen pen (const QModelIndex &index) const
Retrieve the pen to be used, for painting the datapoint at the given index in the model.
bool percentMode () const
Returns whether this diagram is drawn in percent mode.
PieAttributes pieAttributes () const
PieAttributes pieAttributes (int column) const
PieAttributes pieAttributes (const QModelIndex &index) const
const PolarCoordinatePlane * polarCoordinatePlane () const
bool relativeThickness () const
virtual void resize (const QSizeF &area)
[reimplemented]
RingDiagram (QWidget *parent=0, PolarCoordinatePlane *plane=0)
int rowCount () const
virtual void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
[reimplemented]
void setAllowOverlappingDataValueTexts (bool allow)
Set whether data value labels are allowed to overlap.
void setAntiAliasing (bool enabled)
Set whether anti-aliasing is to be used while rendering this diagram.
virtual void setAttributesModel (AttributesModel *model)
Associate an AttributesModel with this diagram.
void setAutoRotateLabels (bool autoRotate)
If this property is set, and if a pie's TextAttributes have no rotation set, its labels will automatically be rotated according to the pie's angle.
void setBrush (const QModelIndex &index, const QBrush &brush)
Set the brush to be used, for painting the datapoint at the given index.
void setBrush (int dataset, const QBrush &brush)
Set the brush to be used, for painting the given dataset.
void setBrush (const QBrush &brush)
Set the brush to be used, for painting all datasets in the model.
virtual void setCoordinatePlane (AbstractCoordinatePlane *plane)
Set the coordinate plane associated with the diagram.
void setDatasetDimension (int dimension)
void setDataValueAttributes (const QModelIndex &index, const DataValueAttributes &a)
Set the DataValueAttributes for the given index.
void setDataValueAttributes (int dataset, const DataValueAttributes &a)
Set the DataValueAttributes for the given dataset.
void setDataValueAttributes (const DataValueAttributes &a)
Set the DataValueAttributes for all datapoints in the model.
virtual void setExpandWhenExploded (bool expand)
void setGranularity (qreal value)
Set the granularity: the smaller the granularity the more your diagram segments will show facettes instead of rounded segments.
void setHidden (const QModelIndex &index, bool hidden)
Hide (or unhide, resp.) a data cell.
void setHidden (int dataset, bool hidden)
Hide (or unhide, resp.) a dataset.
void setHidden (bool hidden)
Hide (or unhide, resp.) all datapoints in the model.
virtual void setModel (QAbstractItemModel *model)
Associate a model with the diagram.
void setPen (const QModelIndex &index, const QPen &pen)
Set the pen to be used, for painting the datapoint at the given index.
void setPen (int dataset, const QPen &pen)
Set the pen to be used, for painting the given dataset.
void setPen (const QPen &pen)
Set the pen to be used, for painting all datasets in the model.
void setPercentMode (bool percent)
Deprecated method that turns the percent mode of this diagram on or off.
void setPieAttributes (const PieAttributes &a)
void setPieAttributes (int column, const PieAttributes &a)
void setPieAttributes (const QModelIndex &index, const PieAttributes &a)
void setRelativeThickness (bool relativeThickness)
virtual void setRootIndex (const QModelIndex &idx)
Set the root index in the model, where the diagram starts referencing data for display.
virtual void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
[reimplemented]
virtual void setSelectionModel (QItemSelectionModel *selectionModel)
Associate a seleection model with the diagrom.
void setStartPosition (int degrees)
void setThreeDPieAttributes (const ThreeDPieAttributes &a)
void setThreeDPieAttributes (int column, const ThreeDPieAttributes &a)
void setThreeDPieAttributes (const QModelIndex &index, const ThreeDPieAttributes &a)
void setUnitPrefix (const QString &prefix, int column, Qt::Orientation orientation)
Set the unit prefix to be used on axes for one specific column.
void setUnitPrefix (const QString &prefix, Qt::Orientation orientation)
Set the unit prefix to be used on axes for all columns.
void setUnitSuffix (const QString &suffix, int column, Qt::Orientation orientation)
Set the unit prefix to be used on axes for one specific column.
void setUnitSuffix (const QString &suffix, Qt::Orientation orientation)
Set the unit prefix to be used on axes for all columns.
int startPosition () const
ThreeDPieAttributes threeDPieAttributes () const
ThreeDPieAttributes threeDPieAttributes (int column) const
ThreeDPieAttributes threeDPieAttributes (const QModelIndex &index) const
QString unitPrefix (int column, Qt::Orientation orientation, bool fallback=false) const
Retrieves the axis unit prefix for a specific column.
QString unitPrefix (Qt::Orientation orientation) const
Retrieves the axis unit prefix.
QString unitSuffix (int column, Qt::Orientation orientation, bool fallback=false) const
Retrieves the axis unit suffix for a specific column.
QString unitSuffix (Qt::Orientation orientation) const
Retrieves the axis unit suffix.
void update () const
void useDefaultColors ()
Set the palette to be used, for painting datasets to the default palette.
void useRainbowColors ()
Set the palette to be used, for painting datasets to the rainbow palette.
virtual bool usesExternalAttributesModel () const
Returns whether the diagram is using its own built-in attributes model or an attributes model that was set via setAttributesModel.
void useSubduedColors ()
Set the palette to be used, for painting datasets to the subdued palette.
virtual qreal valueTotals () const
[reimplemented]
qreal valueTotals (int dataset) const
virtual int verticalOffset () const
[reimplemented]
virtual QRect visualRect (const QModelIndex &index) const
[reimplemented]
virtual QRegion visualRegion (const QModelIndex &index) const
virtual QRegion visualRegionForSelection (const QItemSelection &selection) const
[reimplemented]
virtual ~RingDiagram ()
Protected Slots
void setDataBoundariesDirty () const
Protected Member Functions
QModelIndex attributesModelRootIndex () const
virtual const QPair< QPointF, QPointF > calculateDataBoundaries () const
[reimplemented]
virtual bool checkInvariants (bool justReturnTheStatus=false) const
virtual void paint (PaintContext *paintContext)
[reimplemented]
virtual void paintDataValueTexts (QPainter *painter)
void paintEvent (QPaintEvent *)
virtual void paintMarkers (QPainter *painter)
void resizeEvent (QResizeEvent *)
void setAttributesModelRootIndex (const QModelIndex &)
void setDatasetDimensionInternal (int dimension)
qreal valueForCell (int row, int column) const
Helper method, retrieving the data value (DisplayRole) for a given row and column.
Detailed Description
RingDiagram defines a common ring diagram.
Definition at line 33 of file KDChartRingDiagram.h.
Constructor & Destructor Documentation
RingDiagram()
RingDiagram::RingDiagram (QWidget * parent = 0, PolarCoordinatePlane * plane = 0) explicit
Definition at line 50 of file KDChartRingDiagram.cpp.
Referenced by clone().
~RingDiagram()
RingDiagram::~RingDiagram () virtual
Definition at line 56 of file KDChartRingDiagram.cpp.
Member Function Documentation
aboutToBeDestroyed
void KDChart::AbstractDiagram::aboutToBeDestroyed () signal inherited
This signal is emitted when this diagram is being destroyed, but before all the data, i.e.
the attributes model, is invalidated.
Referenced by KDChart::AbstractDiagram::~AbstractDiagram().
allowOverlappingDataValueTexts()
bool AbstractDiagram::allowOverlappingDataValueTexts () const inherited
Returns
Whether data value labels are allowed to overlap.
Definition at line 372 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare().
antiAliasing()
bool AbstractDiagram::antiAliasing () const inherited
Returns
Whether anti-aliasing is to be used for rendering this diagram.
Definition at line 383 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), and KDChart::PaintingHelpers::paintThreeDLines().
attributesModel()
AttributesModel * AbstractDiagram::attributesModel () const virtual inherited
Returns the AttributesModel, that is used by this diagram.
By default each diagram owns its own AttributesModel, which should never be deleted. Only if a user-supplied AttributesModel has been set does the pointer returned here not belong to the diagram.
Returns
The AttributesModel associated with the diagram.
See also
setAttributesModel
Definition at line 198 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::brush(), KDChart::AbstractDiagram::compare(), KDChart::Plotter::connectAttributesModel(), KDChart::AbstractDiagram::dataValueAttributes(), KDChart::AbstractDiagram::isHidden(), KDChart::AbstractDiagram::itemRowLabels(), KDChart::AbstractDiagram::pen(), KDChart::AbstractCartesianDiagram::setAttributesModel(), KDChart::BarDiagram::setBarAttributes(), KDChart::AbstractDiagram::setBrush(), KDChart::AbstractDiagram::setPen(), KDChart::AbstractCartesianDiagram::setRootIndex(), KDChart::Plotter::setUseDataCompression(), and KDChart::TernaryLineDiagram::TernaryLineDiagram().
attributesModelAboutToChange
void KDChart::AbstractDiagram::attributesModelAboutToChange (AttributesModel * newModel, AttributesModel * oldModel) signal inherited
This signal is emitted just before the new attributes model is connected internally.
It gives you a chance to connect to its signals first or perform other setup work.
attributesModelRootIndex()
QModelIndex AbstractDiagram::attributesModelRootIndex () const protected inherited
returns a QModelIndex pointing into the AttributesModel that corresponds to the root index of the diagram.
Definition at line 226 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::itemRowLabels(), KDChart::BarDiagram::numberOfAbscissaSegments(), KDChart::Plotter::numberOfAbscissaSegments(), KDChart::LineDiagram::numberOfAbscissaSegments(), KDChart::BarDiagram::numberOfOrdinateSegments(), KDChart::Plotter::numberOfOrdinateSegments(), KDChart::LineDiagram::numberOfOrdinateSegments(), and KDChart::AbstractDiagram::valueForCell().
autoRotateLabels()
bool AbstractPieDiagram::autoRotateLabels () const inherited
See also
setAutoRotateLabels(bool autoRotate)
Definition at line 115 of file KDChartAbstractPieDiagram.cpp.
References d.
boundariesChanged
void KDChart::AbstractDiagram::boundariesChanged () signal inherited
Emitted upon change of a data boundary.
Referenced by KDChart::Plotter::connectAttributesModel(), and KDChart::Plotter::setType().
brush() [1/3]
QBrush AbstractDiagram::brush () const inherited
Retrieve the brush to be used for painting datapoints globally.
This will fall back automatically to the default settings, if there are no specific settings.
Returns
The brush to use for painting.
Definition at line 709 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetBrushRole.
Referenced by KDChart::AbstractDiagram::brush(), KDChart::AbstractDiagram::datasetBrushes(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), KDChart::AbstractDiagram::paintMarker(), KDChart::PaintingHelpers::paintThreeDLines(), and KDChart::AbstractDiagram::setBrush().
brush() [2/3]
QBrush AbstractDiagram::brush (int dataset) const inherited
Retrieve the brush to be used for the given dataset.
This will fall back automatically to what was set at model level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the brush for.
Returns
The brush to use for painting.
Definition at line 714 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), d, and KDChart::DatasetBrushRole.
brush() [3/3]
QBrush AbstractDiagram::brush (const QModelIndex & index) const inherited
Retrieve the brush to be used, for painting the datapoint at the given index in the model.
Parameters
index The index of the datapoint in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
Returns
The brush to use for painting.
Definition at line 722 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetBrushRole.
calculateDataBoundaries()
const QPair< QPointF, QPointF > RingDiagram::calculateDataBoundaries () const protected virtual
[reimplemented]
Implements KDChart::AbstractDiagram.
Definition at line 105 of file KDChartRingDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractPolarDiagram::columnCount(), d, KDChart::PieAttributes::explodeFactor(), KDChart::AbstractPieDiagram::pieAttributes(), and KDChart::AbstractPolarDiagram::rowCount().
checkInvariants()
bool AbstractDiagram::checkInvariants (bool justReturnTheStatus = false) const protected virtual inherited
Definition at line 949 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::coordinatePlane().
Referenced by calculateDataBoundaries(), KDChart::PieDiagram::calculateDataBoundaries(), KDChart::RadarDiagram::calculateDataBoundaries(), KDChart::PolarDiagram::calculateDataBoundaries(), KDChart::BarDiagram::calculateDataBoundaries(), KDChart::Plotter::calculateDataBoundaries(), KDChart::LineDiagram::calculateDataBoundaries(), paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::BarDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::Plotter::paint(), KDChart::LineDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), KDChart::AbstractDiagram::paintMarker(), and KDChart::AbstractDiagram::paintMarkers().
clone()
RingDiagram * RingDiagram::clone () const virtual
Creates an exact copy of this diagram.
Definition at line 67 of file KDChartRingDiagram.cpp.
References d, and RingDiagram().
columnCount()
int AbstractPolarDiagram::columnCount () const inherited
Definition at line 57 of file KDChartAbstractPolarDiagram.cpp.
References KDChart::AbstractPolarDiagram::numberOfValuesPerDataset().
Referenced by calculateDataBoundaries(), KDChart::PieDiagram::calculateDataBoundaries(), paint(), valueTotals(), and KDChart::PieDiagram::valueTotals().
compare() [1/3]
bool AbstractPieDiagram::compare (const AbstractPieDiagram * other) const inherited
Returns true if both diagrams have the same settings.
Definition at line 61 of file KDChartAbstractPieDiagram.cpp.
References KDChart::AbstractPieDiagram::granularity(), and KDChart::AbstractPieDiagram::startPosition().
compare() [2/3]
bool RingDiagram::compare (const RingDiagram * other) const
Returns true if both diagrams have the same settings.
Definition at line 72 of file KDChartRingDiagram.cpp.
References expandWhenExploded(), and relativeThickness().
compare() [3/3]
bool AbstractDiagram::compare (const AbstractDiagram * other) const inherited
Returns true if both diagrams have the same settings.
Definition at line 69 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::allowOverlappingDataValueTexts(), KDChart::AbstractDiagram::antiAliasing(), KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::compare(), KDChart::AbstractDiagram::datasetDimension(), and KDChart::AbstractDiagram::percentMode().
coordinatePlane()
AbstractCoordinatePlane * AbstractDiagram::coordinatePlane () const inherited
The coordinate plane associated with the diagram.
This determines how coordinates in value space are mapped into pixel space. By default this is a CartesianCoordinatePlane.
Returns
The coordinate plane associated with the diagram.
Definition at line 113 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Plotter::calcMergeRadius(), KDChart::BarDiagram::calculateDataBoundaries(), KDChart::LineDiagram::calculateDataBoundaries(), KDChart::AbstractDiagram::checkInvariants(), KDChart::Plotter::connectAttributesModel(), KDChart::LeveyJenningsDiagram::iconRect(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), KDChart::AbstractDiagram::paintMarkers(), KDChart::AbstractPolarDiagram::polarCoordinatePlane(), KDChart::BarDiagram::resize(), KDChart::Plotter::resize(), and KDChart::LineDiagram::resize().
dataBoundaries()
const QPair< QPointF, QPointF > AbstractDiagram::dataBoundaries () const inherited
Return the bottom left and top right data point, that the diagram will display (unless the grid adjusts these values).
This method returns a cached result of calculations done by calculateDataBoundaries. Classes derived from AbstractDiagram must implement the calculateDataBoundaries function, to specify their own way of calculating the data boundaries. If derived classes want to force recalculation of the data boundaries, they can call setDataBoundariesDirty()
Returned value is in diagram coordinates.
Definition at line 118 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::calculateDataBoundaries(), and d.
Referenced by KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::RadarDiagram::paint(), KDChart::BarDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::Plotter::paint(), and KDChart::LineDiagram::paint().
dataChanged()
void AbstractDiagram::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) virtual inherited
[reimplemented]
Definition at line 248 of file KDChartAbstractDiagram.cpp.
Referenced by KDChart::LeveyJenningsDiagram::setModel().
dataHidden
void KDChart::AbstractDiagram::dataHidden () signal inherited
This signal is emitted, when the hidden status of at least one data cell was (un)set.
Referenced by KDChart::AbstractDiagram::setHidden().
datasetBrushes()
QList< QBrush > AbstractDiagram::datasetBrushes () const inherited
The set of dataset brushes currently used, for use in legends, etc.
Note
Cell-level override brushes, if set, take precedence over the dataset values, so you might need to check these too, in order to find the brush, that is used for a single cell.
Returns
The current set of dataset brushes.
Definition at line 910 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), and d.
Referenced by KDChart::Legend::datasetCount(), KDChart::Legend::removeDiagram(), and KDChart::Legend::setBrushesFromDiagram().
datasetDimension()
int AbstractDiagram::datasetDimension () const inherited
The dataset dimension of a diagram determines how many value dimensions it expects each datapoint to have.
For each dimension and data series it will expect one column of values in the model. If the dimension is 1, automatic values will be used for X.
For example, a diagram with the default dimension of 1 will have one column per data series (the Y values) and will use automatic values for X (1, 2, 3, ... n). If the dimension is 2, the diagram will use the first, (and the third, fifth, etc) columns as X values, and the second, (and the fourth, sixth, etc) column as Y values.
Returns
The dataset dimension of the diagram.
Definition at line 961 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare(), KDChart::CartesianCoordinatePlane::getDataDimensionsList(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), KDChart::AbstractDiagram::paintMarkers(), KDChart::Plotter::setType(), and KDChart::LineDiagram::setType().
datasetLabels()
QStringList AbstractDiagram::datasetLabels () const inherited
The set of dataset labels currently displayed, for use in legends, etc.
Returns
The set of dataset labels currently displayed.
Definition at line 897 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Legend::datasetCount().
datasetMarkers()
QList< MarkerAttributes > AbstractDiagram::datasetMarkers () const inherited
The set of dataset markers currently used, for use in legends, etc.
Note
Cell-level override markers, if set, take precedence over the dataset values, so you might need to check these too, in order to find the marker, that is shown for a single cell.
Returns
The current set of dataset brushes.
Definition at line 936 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::DataValueAttributes::markerAttributes().
datasetPens()
QList< QPen > AbstractDiagram::datasetPens () const inherited
The set of dataset pens currently used, for use in legends, etc.
Note
Cell-level override pens, if set, take precedence over the dataset values, so you might need to check these too, in order to find the pens, that is used for a single cell.
Returns
The current set of dataset pens.
Definition at line 923 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::pen().
Referenced by KDChart::Legend::removeDiagram().
dataValueAttributes() [1/3]
DataValueAttributes AbstractDiagram::dataValueAttributes () const inherited
Retrieve the DataValueAttributes specified globally.
This will fall back automatically to the default settings, if there are no specific settings.
Returns
The global DataValueAttributes.
Definition at line 325 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DataValueLabelAttributesRole, and KDChart::AttributesModel::modelData().
Referenced by KDChart::AbstractDiagram::datasetMarkers(), KDChart::AbstractDiagram::dataValueAttributes(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::AbstractDiagram::paintMarker(), KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts(), and KDChart::TernaryLineDiagram::TernaryLineDiagram().
dataValueAttributes() [2/3]
DataValueAttributes AbstractDiagram::dataValueAttributes (int dataset) const inherited
Retrieve the DataValueAttributes for the given dataset.
This will fall back automatically to what was set at model level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the attributes for.
Returns
The DataValueAttributes for the given dataset.
Definition at line 330 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::DataValueLabelAttributesRole.
dataValueAttributes() [3/3]
DataValueAttributes AbstractDiagram::dataValueAttributes (const QModelIndex & index) const inherited
Retrieve the DataValueAttributes for the given index.
This will fall back automatically to what was set at dataset or model level, if there are no datapoint specific settings.
Parameters
index The datapoint to retrieve the attributes for. With a dataset dimension of two, this is the index of the key of each key/value pair.
Returns
The DataValueAttributes for the given index.
Definition at line 350 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DataValueLabelAttributesRole.
doItemsLayout()
void AbstractDiagram::doItemsLayout () virtual inherited
[reimplemented]
Definition at line 238 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
expandWhenExploded()
bool RingDiagram::expandWhenExploded () const virtual
Definition at line 100 of file KDChartRingDiagram.cpp.
References d.
Referenced by compare().
granularity()
qreal AbstractPieDiagram::granularity () const inherited
Returns
the granularity.
Definition at line 90 of file KDChartAbstractPieDiagram.cpp.
References d.
Referenced by KDChart::AbstractPieDiagram::compare(), and paint().
horizontalOffset()
int AbstractDiagram::horizontalOffset () const virtual inherited
[reimplemented]
Definition at line 830 of file KDChartAbstractDiagram.cpp.
indexAt()
QModelIndex AbstractDiagram::indexAt (const QPoint & point) const virtual inherited
[reimplemented]
Definition at line 1002 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Chart::event().
indexesAt()
QModelIndexList AbstractDiagram::indexesAt (const QPoint & point) const inherited
This method is added alongside with indexAt from QAIM, since in kdchart multiple indexes can be displayed at the same spot.
Definition at line 1007 of file KDChartAbstractDiagram.cpp.
References d.
indexesIn()
QModelIndexList AbstractDiagram::indexesIn (const QRect & rect) const inherited
Definition at line 1012 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Chart::event().
isHidden() [1/3]
bool AbstractDiagram::isHidden () const inherited
Retrieve the hidden status specified globally.
This will fall back automatically to the default settings (= not hidden), if there are no specific settings.
Returns
The global hidden status.
Definition at line 285 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DataHiddenRole, and KDChart::AttributesModel::modelData().
Referenced by KDChart::AbstractDiagram::isHidden().
isHidden() [2/3]
bool AbstractDiagram::isHidden (int dataset) const inherited
Retrieve the hidden status for the given dataset.
This will fall back automatically to what was set at diagram level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the hidden status for.
Returns
The hidden status for the given dataset.
Definition at line 290 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataHiddenRole, and KDChart::AbstractDiagram::isHidden().
isHidden() [3/3]
bool AbstractDiagram::isHidden (const QModelIndex & index) const inherited
Retrieve the hidden status for the given index.
This will fall back automatically to what was set at dataset or diagram level, if there are no datapoint specific settings.
Parameters
index The datapoint to retrieve the hidden status for.
Returns
The hidden status for the given index.
Definition at line 298 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), d, KDChart::DataHiddenRole, and KDChart::AbstractDiagram::isHidden().
isIndexHidden()
bool AbstractDiagram::isIndexHidden (const QModelIndex & index) const virtual inherited
[reimplemented]
Definition at line 836 of file KDChartAbstractDiagram.cpp.
itemRowLabels()
QStringList AbstractDiagram::itemRowLabels () const inherited
The set of item row labels currently displayed, for use in Abscissa axes, etc.
Returns
The set of item row labels currently displayed.
Definition at line 881 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AbstractDiagram::attributesModelRootIndex(), KDChart::AttributesModel::headerData(), KDChart::AttributesModel::rowCount(), KDChart::AbstractDiagram::unitPrefix(), and KDChart::AbstractDiagram::unitSuffix().
layoutChanged
void KDChart::AbstractDiagram::layoutChanged (AbstractDiagram *) signal inherited
Diagrams are supposed to emit this signal, when the layout of one of their element changes.
Layouts can change, for example, when axes are added or removed, or when the configuration was changed in a way that the axes or the diagram itself are displayed in a different geometry. Changes in the diagrams coordinate system also result in the layoutChanged() signal being emitted.
Referenced by KDChart::LineDiagram::setCenterDataPoints(), KDChart::AbstractDiagram::setDatasetDimensionInternal(), KDChart::LeveyJenningsDiagram::setModel(), KDChart::AbstractPieDiagram::setPieAttributes(), KDChart::BarDiagram::setThreeDBarAttributes(), KDChart::AbstractPieDiagram::setThreeDPieAttributes(), KDChart::Plotter::setType(), and KDChart::LineDiagram::setType().
modelDataChanged
void KDChart::AbstractDiagram::modelDataChanged () signal inherited
This signal is emitted, when the model data is changed.
modelsChanged
void KDChart::AbstractDiagram::modelsChanged () signal inherited
This signal is emitted when either the model or the AttributesModel is replaced.
Referenced by KDChart::AbstractDiagram::setAttributesModel(), KDChart::AbstractDiagram::setModel(), and KDChart::AbstractDiagram::setSelectionModel().
moveCursor()
QModelIndex AbstractDiagram::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) virtual inherited
[reimplemented]
Definition at line 827 of file KDChartAbstractDiagram.cpp.
numberOfDatasets()
qreal RingDiagram::numberOfDatasets () const virtual
Reimplemented from KDChart::AbstractPolarDiagram.
Definition at line 483 of file KDChartRingDiagram.cpp.
numberOfGridRings()
qreal RingDiagram::numberOfGridRings () const virtual
[reimplemented]
Implements KDChart::AbstractPolarDiagram.
Definition at line 489 of file KDChartRingDiagram.cpp.
numberOfValuesPerDataset()
qreal RingDiagram::numberOfValuesPerDataset () const virtual
[reimplemented]
Implements KDChart::AbstractPolarDiagram.
Definition at line 478 of file KDChartRingDiagram.cpp.
paint()
void RingDiagram::paint (PaintContext * paintContext) protected virtual
[reimplemented]
Implements KDChart::AbstractDiagram.
Definition at line 153 of file KDChartRingDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractPolarDiagram::columnCount(), d, KDChart::PieAttributes::explode(), KDChart::PieAttributes::explodeFactor(), KDChart::PieAttributes::gapFactor(), KDChart::AbstractPieDiagram::granularity(), KDChart::PaintContext::painter(), KDChart::AbstractPieDiagram::pieAttributes(), KDChart::AbstractPolarDiagram::polarCoordinatePlane(), KDChart::PaintContext::rectangle(), KDChart::AbstractPolarDiagram::rowCount(), KDChart::PolarCoordinatePlane::startPosition(), and valueTotals().
Referenced by paintEvent().
paintDataValueText()
void AbstractDiagram::paintDataValueText (QPainter * painter, const QModelIndex & index, const QPointF & pos, qreal value) inherited
Definition at line 400 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::paintDataValueTexts().
paintDataValueTexts()
void AbstractDiagram::paintDataValueTexts (QPainter * painter) protected virtual inherited
Deprecated:
This method is deprecated and provided for backward-compatibility only.
Your own diagram classes should call d->paintDataValueTextsAndMarkers() instead which also is taking care for showing your cell-specific comments, if any,
Definition at line 409 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractDiagram::coordinatePlane(), d, KDChart::AbstractDiagram::datasetDimension(), KDChart::AbstractDiagram::paintDataValueText(), and translate().
paintEvent()
void RingDiagram::paintEvent (QPaintEvent *) protected
Definition at line 140 of file KDChartRingDiagram.cpp.
References paint(), KDChart::PaintContext::setPainter(), and KDChart::PaintContext::setRectangle().
paintMarker() [1/3]
void AbstractDiagram::paintMarker (QPainter * painter, const MarkerAttributes & markerAttributes, const QBrush & brush, const QPen & pen, const QPointF & point, const QSizeF & size) virtual inherited
Definition at line 472 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), KDChart::MarkerAttributes::customMarkerPath(), KDChart::MarkerAttributes::Marker1Pixel, KDChart::MarkerAttributes::Marker4Pixels, KDChart::MarkerAttributes::MarkerCircle, KDChart::MarkerAttributes::MarkerCross, KDChart::MarkerAttributes::MarkerDiamond, KDChart::MarkerAttributes::MarkerFastCross, KDChart::MarkerAttributes::MarkerRing, KDChart::MarkerAttributes::MarkerSquare, KDChart::MarkerAttributes::markerStyle(), KDChart::MarkerAttributes::NoMarker, KDChart::MarkerAttributes::PainterPathMarker, KDChart::AbstractDiagram::pen(), KDChart::PrintingParameters::scalePen(), and KDChart::MarkerAttributes::threeD().
Referenced by KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::MarkerLayoutItem::paintIntoRect(), KDChart::AbstractDiagram::paintMarker(), and KDChart::AbstractDiagram::paintMarkers().
paintMarker() [2/3]
void AbstractDiagram::paintMarker (QPainter * painter, const DataValueAttributes & a, const QModelIndex & index, const QPointF & pos) inherited
Definition at line 436 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), KDChart::AbstractDiagram::checkInvariants(), d, KDChart::MarkerAttributes::isVisible(), KDChart::DataValueAttributes::isVisible(), KDChart::DataValueAttributes::markerAttributes(), KDChart::MarkerAttributes::markerColor(), KDChart::MarkerAttributes::markerSize(), KDChart::AbstractDiagram::paintMarker(), and KDChart::MarkerAttributes::pen().
paintMarker() [3/3]
void AbstractDiagram::paintMarker (QPainter * painter, const QModelIndex & index, const QPointF & pos) inherited
Definition at line 464 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::AbstractDiagram::paintMarker().
paintMarkers()
void AbstractDiagram::paintMarkers (QPainter * painter) protected virtual inherited
Deprecated:
This method is deprecated and provided for backward-compatibility only.
Your own diagram classes should call d->paintDataValueTextsAndMarkers() instead which also is taking care for showing your cell-specific comments, if any,
Definition at line 621 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractDiagram::coordinatePlane(), KDChart::AbstractDiagram::datasetDimension(), KDChart::AbstractDiagram::paintMarker(), and translate().
pen() [1/3]
QPen AbstractDiagram::pen () const inherited
Retrieve the pen to be used for painting datapoints globally.
This will fall back automatically to the default settings, if there are no specific settings.
Returns
The pen to use for painting.
Definition at line 668 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetPenRole.
Referenced by KDChart::AbstractDiagram::datasetPens(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), KDChart::AbstractDiagram::paintMarker(), KDChart::PaintingHelpers::paintThreeDLines(), KDChart::AbstractDiagram::pen(), KDChart::AbstractDiagram::setPen(), and KDChart::LeveyJenningsDiagram::setScanLinePen().
pen() [2/3]
QPen AbstractDiagram::pen (int dataset) const inherited
Retrieve the pen to be used for the given dataset.
This will fall back automatically to what was set at model level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the pen for.
Returns
The pen to use for painting.
Definition at line 673 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DatasetPenRole, and KDChart::AbstractDiagram::pen().
pen() [3/3]
QPen AbstractDiagram::pen (const QModelIndex & index) const inherited
Retrieve the pen to be used, for painting the datapoint at the given index in the model.
Parameters
index The index of the datapoint in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
Returns
The pen to use for painting.
Definition at line 681 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetPenRole.
percentMode()
bool AbstractDiagram::percentMode () const inherited
Returns whether this diagram is drawn in percent mode.
If true, all data points in the same column of a diagram will be be drawn at the same X coordinate and stacked up so that the distance from the last data point (or the zero line) to a data point P is always the ratio of (Y-Value of P)/ (sum of all Y-Values in same column as P) relative to the diagrams height (or width, if abscissa and ordinate are swapped).
Note that this property is not applicable to all diagram types.
Definition at line 394 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare().
pieAttributes() [1/3]
PieAttributes AbstractPieDiagram::pieAttributes () const inherited
Definition at line 138 of file KDChartAbstractPieDiagram.cpp.
References d, and KDChart::PieAttributesRole.
Referenced by calculateDataBoundaries(), KDChart::PieDiagram::calculateDataBoundaries(), paint(), and KDChart::AbstractPieDiagram::pieAttributes().
pieAttributes() [2/3]
PieAttributes AbstractPieDiagram::pieAttributes (int column) const inherited
Definition at line 143 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractPieDiagram::pieAttributes(), and KDChart::PieAttributesRole.
pieAttributes() [3/3]
PieAttributes AbstractPieDiagram::pieAttributes (const QModelIndex & index) const inherited
Definition at line 151 of file KDChartAbstractPieDiagram.cpp.
References d, and KDChart::PieAttributesRole.
polarCoordinatePlane()
const PolarCoordinatePlane * AbstractPolarDiagram::polarCoordinatePlane () const inherited
Definition at line 52 of file KDChartAbstractPolarDiagram.cpp.
References KDChart::AbstractDiagram::coordinatePlane().
Referenced by paint().
propertiesChanged
void KDChart::AbstractDiagram::propertiesChanged () signal inherited
Emitted upon change of a property of the Diagram.
Referenced by KDChart::Plotter::resetLineAttributes(), KDChart::LineDiagram::resetLineAttributes(), KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts(), KDChart::AbstractDiagram::setAntiAliasing(), KDChart::BarDiagram::setBarAttributes(), KDChart::AbstractDiagram::setBrush(), KDChart::LineDiagram::setCenterDataPoints(), KDChart::AbstractDiagram::setDataValueAttributes(), KDChart::Plotter::setLineAttributes(), KDChart::LineDiagram::setLineAttributes(), KDChart::AbstractDiagram::setPen(), KDChart::AbstractDiagram::setPercentMode(), KDChart::BarDiagram::setThreeDBarAttributes(), KDChart::Plotter::setThreeDLineAttributes(), KDChart::LineDiagram::setThreeDLineAttributes(), KDChart::Plotter::setType(), KDChart::LineDiagram::setType(), KDChart::Plotter::setValueTrackerAttributes(), and KDChart::LineDiagram::setValueTrackerAttributes().
relativeThickness()
bool RingDiagram::relativeThickness () const
Definition at line 90 of file KDChartRingDiagram.cpp.
References d.
Referenced by compare(), and setRelativeThickness().
resize()
void RingDiagram::resize (const QSizeF & area) virtual
[reimplemented]
Implements KDChart::AbstractDiagram.
Definition at line 264 of file KDChartRingDiagram.cpp.
resizeEvent()
void RingDiagram::resizeEvent (QResizeEvent *) protected
Definition at line 149 of file KDChartRingDiagram.cpp.
rowCount()
int AbstractPolarDiagram::rowCount () const inherited
Definition at line 62 of file KDChartAbstractPolarDiagram.cpp.
References KDChart::AbstractPolarDiagram::numberOfDatasets().
Referenced by calculateDataBoundaries(), KDChart::PieDiagram::calculateDataBoundaries(), KDChart::RadarDiagram::calculateDataBoundaries(), KDChart::PolarDiagram::calculateDataBoundaries(), paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), valueTotals(), and KDChart::PieDiagram::valueTotals().
scrollTo()
void AbstractDiagram::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) virtual inherited
[reimplemented]
Definition at line 822 of file KDChartAbstractDiagram.cpp.
setAllowOverlappingDataValueTexts()
void AbstractDiagram::setAllowOverlappingDataValueTexts (bool allow) inherited
Set whether data value labels are allowed to overlap.
Parameters
allow True means that overlapping labels are allowed.
Definition at line 363 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataValueAttributes(), KDChart::AbstractDiagram::propertiesChanged(), KDChart::AbstractDiagram::setDataValueAttributes(), and KDChart::DataValueAttributes::setShowOverlappingDataLabels().
setAntiAliasing()
void AbstractDiagram::setAntiAliasing (bool enabled) inherited
Set whether anti-aliasing is to be used while rendering this diagram.
Parameters
enabled True means that AA is enabled.
Definition at line 377 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::propertiesChanged().
setAttributesModel()
void AbstractDiagram::setAttributesModel (AttributesModel * amodel) virtual inherited
Associate an AttributesModel with this diagram.
Note that the diagram does not take ownership of the AttributesModel. This should thus only be used with AttributesModels that have been explicitly created by the user, and are owned by her. Setting an AttributesModel that is internal to another diagram is an error.
Correct:
AttributesModel *am = new AttributesModel(model, 0);
diagram1->setAttributesModel(am);
diagram2->setAttributesModel(am);
Wrong:
diagram1->setAttributesModel(diagram2->attributesModel());
Parameters
model The AttributesModel to use for this diagram.
See also
AttributesModel, usesExternalAttributesModel
Sets an external AttributesModel on this diagram. By default, a diagram has it's own internal set of attributes, but an external one can be set. This can be used to share attributes between several diagrams. The diagram does not take ownership of the attributesmodel.
Parameters
amodel The AttributesModel to use for this diagram.
Reimplemented in KDChart::AbstractCartesianDiagram.
Definition at line 173 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::modelsChanged(), and KDChart::AbstractDiagram::setDataBoundariesDirty().
Referenced by KDChart::AbstractCartesianDiagram::setAttributesModel().
setAttributesModelRootIndex()
void AbstractDiagram::setAttributesModelRootIndex (const QModelIndex & idx) protected inherited
Definition at line 217 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::setDataBoundariesDirty().
Referenced by KDChart::AbstractDiagram::setRootIndex().
setAutoRotateLabels()
void AbstractPieDiagram::setAutoRotateLabels (bool autoRotate) inherited
If this property is set, and if a pie's TextAttributes have no rotation set, its labels will automatically be rotated according to the pie's angle.
Definition at line 110 of file KDChartAbstractPieDiagram.cpp.
References d.
setBrush() [1/3]
void AbstractDiagram::setBrush (const QModelIndex & index, const QBrush & brush) inherited
Set the brush to be used, for painting the datapoint at the given index.
Parameters
index The datapoint's index in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
brush The brush to use.
Definition at line 688 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AbstractDiagram::brush(), KDChart::DatasetBrushRole, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setData().
setBrush() [2/3]
void AbstractDiagram::setBrush (int dataset, const QBrush & brush) inherited
Set the brush to be used, for painting the given dataset.
Parameters
dataset The dataset to set the brush for.
brush The brush to use.
Definition at line 703 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), d, KDChart::DatasetBrushRole, and KDChart::AbstractDiagram::propertiesChanged().
setBrush() [3/3]
void AbstractDiagram::setBrush (const QBrush & brush) inherited
Set the brush to be used, for painting all datasets in the model.
Parameters
brush The brush to use.
Definition at line 696 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AbstractDiagram::brush(), KDChart::DatasetBrushRole, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setModelData().
setCoordinatePlane()
void AbstractDiagram::setCoordinatePlane (AbstractCoordinatePlane * plane) virtual inherited
Set the coordinate plane associated with the diagram.
This determines how coordinates in value space are mapped into pixel space. The chart takes ownership.
Returns
The coordinate plane associated with the diagram.
Reimplemented in KDChart::AbstractCartesianDiagram.
Definition at line 233 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::AbstractCartesianDiagram::setCoordinatePlane(), and KDChart::AbstractCoordinatePlane::takeDiagram().
setDataBoundariesDirty
void AbstractDiagram::setDataBoundariesDirty () const protected slot inherited
Definition at line 127 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
Referenced by KDChart::BarDiagram::resize(), KDChart::LineDiagram::resize(), KDChart::AbstractDiagram::setAttributesModel(), KDChart::AbstractDiagram::setAttributesModelRootIndex(), KDChart::LineDiagram::setCenterDataPoints(), KDChart::Plotter::setDataBoundariesDirty(), KDChart::AbstractDiagram::setDatasetDimensionInternal(), KDChart::AbstractDiagram::setModel(), KDChart::BarDiagram::setThreeDBarAttributes(), KDChart::LineDiagram::setThreeDLineAttributes(), and KDChart::LineDiagram::setType().
setDatasetDimension()
void AbstractDiagram::setDatasetDimension (int dimension) inherited
Deprecated:
Sets the dataset dimension of the diagram. Using this method is deprecated. Use the specific diagram types instead.
Definition at line 966 of file KDChartAbstractDiagram.cpp.
setDatasetDimensionInternal()
void AbstractDiagram::setDatasetDimensionInternal (int dimension) protected inherited
Definition at line 973 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::AbstractDiagram::setDataBoundariesDirty().
Referenced by KDChart::TernaryLineDiagram::TernaryLineDiagram(), and KDChart::TernaryPointDiagram::TernaryPointDiagram().
setDataValueAttributes() [1/3]
void AbstractDiagram::setDataValueAttributes (const QModelIndex & index, const DataValueAttributes & a) inherited
Set the DataValueAttributes for the given index.
Parameters
index The datapoint to set the attributes for. With a dataset dimension of two, this is the index of the key of each key/value pair.
a The attributes to set.
Definition at line 310 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataValueLabelAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
Referenced by KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts().
setDataValueAttributes() [2/3]
void AbstractDiagram::setDataValueAttributes (int dataset, const DataValueAttributes & a) inherited
Set the DataValueAttributes for the given dataset.
Parameters
dataset The dataset to set the attributes for.
a The attributes to set.
Definition at line 319 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataValueLabelAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
setDataValueAttributes() [3/3]
void AbstractDiagram::setDataValueAttributes (const DataValueAttributes & a) inherited
Set the DataValueAttributes for all datapoints in the model.
Parameters
a The attributes to set.
Definition at line 357 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataValueLabelAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
setExpandWhenExploded()
void RingDiagram::setExpandWhenExploded (bool expand) virtual
Definition at line 95 of file KDChartRingDiagram.cpp.
References d.
setGranularity()
void AbstractPieDiagram::setGranularity (qreal value) inherited
Set the granularity: the smaller the granularity the more your diagram segments will show facettes instead of rounded segments.
Parameters
value the granularity value between 0.05 (one twentieth of a degree) and 36.0 (one tenth of a full circle), other values will be interpreted as 1.0.
Definition at line 85 of file KDChartAbstractPieDiagram.cpp.
References d.
setHidden() [1/3]
void AbstractDiagram::setHidden (const QModelIndex & index, bool hidden) inherited
Hide (or unhide, resp.) a data cell.
Note
Hidden data are still taken into account by the coordinate plane, so neither the grid nor your axes' ranges will change, when you hide data. For totally removing data from KD Chart's view you can use another approach: e.g. you could define a proxy model on top of your data model, and register the proxy model calling setModel() instead of registering your real data model.
Parameters
index The datapoint to set the hidden status for. With a dataset dimension of two, this is the index of the key of each key/value pair.
hidden The hidden status to set.
Definition at line 264 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataHidden(), and KDChart::DataHiddenRole.
setHidden() [2/3]
void AbstractDiagram::setHidden (int dataset, bool hidden) inherited
Hide (or unhide, resp.) a dataset.
Note
Hidden data are still taken into account by the coordinate plane, so neither the grid nor your axes' ranges will change, when you hide data. For totally removing data from KD Chart's view you can use another approach: e.g. you could define a proxy model on top of your data model, and register the proxy model calling setModel() instead of registering your real data model.
Parameters
dataset The dataset to set the hidden status for.
hidden The hidden status to set.
Definition at line 273 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataHidden(), and KDChart::DataHiddenRole.
setHidden() [3/3]
void AbstractDiagram::setHidden (bool hidden) inherited
Hide (or unhide, resp.) all datapoints in the model.
Note
Hidden data are still taken into account by the coordinate plane, so neither the grid nor your axes' ranges will change, when you hide data. For totally removing data from KD Chart's view you can use another approach: e.g. you could define a proxy model on top of your data model, and register the proxy model calling setModel() instead of registering your real data model.
Parameters
hidden The hidden status to set.
Definition at line 279 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataHidden(), and KDChart::DataHiddenRole.
setModel()
void AbstractDiagram::setModel (QAbstractItemModel * model) virtual inherited
Associate a model with the diagram.
Reimplemented in KDChart::AbstractCartesianDiagram, and KDChart::LeveyJenningsDiagram.
Definition at line 133 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AttributesModel::initFrom(), KDChart::AbstractDiagram::modelsChanged(), and KDChart::AbstractDiagram::setDataBoundariesDirty().
Referenced by KDChart::AbstractCartesianDiagram::setModel(), and KDChart::Widget::setType().
setPen() [1/3]
void AbstractDiagram::setPen (const QModelIndex & index, const QPen & pen) inherited
Set the pen to be used, for painting the datapoint at the given index.
Parameters
index The datapoint's index in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
pen The pen to use.
Definition at line 647 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DatasetPenRole, KDChart::AbstractDiagram::pen(), KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setData().
setPen() [2/3]
void AbstractDiagram::setPen (int dataset, const QPen & pen) inherited
Set the pen to be used, for painting the given dataset.
Parameters
dataset The dataset to set the pen for.
pen The pen to use.
Definition at line 662 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DatasetPenRole, KDChart::AbstractDiagram::pen(), and KDChart::AbstractDiagram::propertiesChanged().
setPen() [3/3]
void AbstractDiagram::setPen (const QPen & pen) inherited
Set the pen to be used, for painting all datasets in the model.
Parameters
pen The pen to use.
Definition at line 655 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DatasetPenRole, KDChart::AbstractDiagram::pen(), KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setModelData().
setPercentMode()
void AbstractDiagram::setPercentMode (bool percent) inherited
Deprecated method that turns the percent mode of this diagram on or off.
Deprecated:
This method is deprecated. Use the setType() method of a supporting diagram implementation instead, e.g. BarDiagram::setType().
See also
percentMode
Definition at line 388 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::propertiesChanged().
Referenced by KDChart::LineDiagram::setType().
setPieAttributes() [1/3]
void AbstractPieDiagram::setPieAttributes (const PieAttributes & a) inherited
Definition at line 120 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::PieAttributesRole.
setPieAttributes() [2/3]
void AbstractPieDiagram::setPieAttributes (int column, const PieAttributes & a) inherited
Definition at line 126 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::PieAttributesRole.
setPieAttributes() [3/3]
void AbstractPieDiagram::setPieAttributes (const QModelIndex & index, const PieAttributes & a) inherited
Definition at line 132 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::PieAttributesRole.
setRelativeThickness()
void RingDiagram::setRelativeThickness (bool relativeThickness)
Definition at line 85 of file KDChartRingDiagram.cpp.
References d, and relativeThickness().
setRootIndex()
void AbstractDiagram::setRootIndex (const QModelIndex & idx) virtual inherited
Set the root index in the model, where the diagram starts referencing data for display.
[reimplemented]
Reimplemented in KDChart::AbstractCartesianDiagram.
Definition at line 210 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::setAttributesModelRootIndex().
Referenced by KDChart::AbstractCartesianDiagram::setRootIndex().
setSelection()
void AbstractDiagram::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags command) virtual inherited
[reimplemented]
Definition at line 839 of file KDChartAbstractDiagram.cpp.
References d.
setSelectionModel()
void AbstractDiagram::setSelectionModel (QItemSelectionModel * selectionModel) virtual inherited
Associate a seleection model with the diagrom.
Definition at line 150 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::modelsChanged().
setStartPosition()
void AbstractPieDiagram::setStartPosition (int degrees) inherited
Deprecated:
Use PolarCoordinatePlane::setStartPosition(qreal degrees) instead.
Definition at line 98 of file KDChartAbstractPieDiagram.cpp.
setThreeDPieAttributes() [1/3]
void AbstractPieDiagram::setThreeDPieAttributes (const ThreeDPieAttributes & a) inherited
Definition at line 159 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::ThreeDPieAttributesRole.
setThreeDPieAttributes() [2/3]
void AbstractPieDiagram::setThreeDPieAttributes (int column, const ThreeDPieAttributes & a) inherited
Definition at line 165 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::ThreeDPieAttributesRole.
setThreeDPieAttributes() [3/3]
void AbstractPieDiagram::setThreeDPieAttributes (const QModelIndex & index, const ThreeDPieAttributes & a) inherited
Definition at line 171 of file KDChartAbstractPieDiagram.cpp.
References KDChart::AbstractDiagram::layoutChanged(), and KDChart::ThreeDPieAttributesRole.
setUnitPrefix() [1/2]
void AbstractDiagram::setUnitPrefix (const QString & prefix, int column, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for one specific column.
Sets the unit prefix for one value.
Parameters
prefix The prefix to be used.
column The column which should be set.
orientation The orientation of the axis to use.
prefix the prefix to be set
column the value using that prefix
orientation the orientantion of the axis to set
Definition at line 734 of file KDChartAbstractDiagram.cpp.
References d.
setUnitPrefix() [2/2]
void AbstractDiagram::setUnitPrefix (const QString & prefix, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for all columns.
Sets the unit prefix for all values.
Parameters
prefix The prefix to be used.
orientation The orientation of the axis to use.
prefix the prefix to be set
orientation the orientantion of the axis to set
Definition at line 744 of file KDChartAbstractDiagram.cpp.
References d.
setUnitSuffix() [1/2]
void AbstractDiagram::setUnitSuffix (const QString & suffix, int column, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for one specific column.
Sets the unit suffix for one value.
Parameters
suffix The suffix to be used.
column The column which should be set.
orientation The orientation of the axis to use.
suffix the suffix to be set
column the value using that suffix
orientation the orientantion of the axis to set
Definition at line 755 of file KDChartAbstractDiagram.cpp.
References d.
setUnitSuffix() [2/2]
void AbstractDiagram::setUnitSuffix (const QString & suffix, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for all columns.
Sets the unit suffix for all values.
Parameters
suffix The suffix to be used.
orientation The orientation of the axis to use.
suffix the suffix to be set
orientation the orientantion of the axis to set
Definition at line 765 of file KDChartAbstractDiagram.cpp.
References d.
startPosition()
int AbstractPieDiagram::startPosition () const inherited
Deprecated:
Use qreal PolarCoordinatePlane::startPosition instead.
Definition at line 104 of file KDChartAbstractPieDiagram.cpp.
Referenced by KDChart::AbstractPieDiagram::compare().
threeDPieAttributes() [1/3]
ThreeDPieAttributes AbstractPieDiagram::threeDPieAttributes () const inherited
Definition at line 177 of file KDChartAbstractPieDiagram.cpp.
References d, and KDChart::ThreeDPieAttributesRole.
Referenced by KDChart::AbstractPieDiagram::threeDPieAttributes().
threeDPieAttributes() [2/3]
ThreeDPieAttributes AbstractPieDiagram::threeDPieAttributes (int column) const inherited
Definition at line 182 of file KDChartAbstractPieDiagram.cpp.
References d, KDChart::AbstractPieDiagram::threeDPieAttributes(), and KDChart::ThreeDPieAttributesRole.
threeDPieAttributes() [3/3]
ThreeDPieAttributes AbstractPieDiagram::threeDPieAttributes (const QModelIndex & index) const inherited
Definition at line 190 of file KDChartAbstractPieDiagram.cpp.
References d, and KDChart::ThreeDPieAttributesRole.
unitPrefix() [1/2]
QString AbstractDiagram::unitPrefix (int column, Qt::Orientation orientation, bool fallback = false) const inherited
Retrieves the axis unit prefix for a specific column.
Returns the unit prefix for a special value.
Parameters
column The column whose prefix should be retrieved.
orientation The orientation of the axis.
fallback If true, the prefix for all columns is returned, when none is set for the selected column.
Returns
The axis unit prefix.
Parameters
column the value which's prefix is requested
orientation the orientation of the axis
fallback if true, the global prefix is return when no specific one is set for that value
Returns
the unit prefix
Definition at line 777 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::itemRowLabels().
unitPrefix() [2/2]
QString AbstractDiagram::unitPrefix (Qt::Orientation orientation) const inherited
Retrieves the axis unit prefix.
Returns the global unit prefix.
Parameters
orientation The orientation of the axis.
Returns
The axis unit prefix.
Parameters
orientation the orientation of the axis
Returns
the unit prefix
Definition at line 788 of file KDChartAbstractDiagram.cpp.
References d.
unitSuffix() [1/2]
QString AbstractDiagram::unitSuffix (int column, Qt::Orientation orientation, bool fallback = false) const inherited
Retrieves the axis unit suffix for a specific column.
Returns the unit suffix for a special value.
Parameters
column The column whose prefix should be retrieved.
orientation The orientation of the axis.
fallback If true, the suffix for all columns is returned, when none is set for the selected column.
Returns
The axis unit suffix.
Parameters
column the value which's suffix is requested
orientation the orientation of the axis
fallback if true, the global suffix is return when no specific one is set for that value
Returns
the unit suffix
Definition at line 800 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::itemRowLabels().
unitSuffix() [2/2]
QString AbstractDiagram::unitSuffix (Qt::Orientation orientation) const inherited
Retrieves the axis unit suffix.
Returns the global unit suffix.
Parameters
orientation The orientation of the axis.
Returns
The axis unit suffix.
Parameters
orientation the orientation of the axis
Returns
the unit siffix
Definition at line 811 of file KDChartAbstractDiagram.cpp.
References d.
update()
void AbstractDiagram::update () const inherited
Definition at line 995 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::doItemsLayout(), KDChart::AbstractDiagram::setDataBoundariesDirty(), KDChart::LeveyJenningsDiagram::setExpectedMeanValue(), KDChart::LeveyJenningsDiagram::setExpectedStandardDeviation(), KDChart::LeveyJenningsDiagram::setFluidicsPackChangedSymbolPosition(), KDChart::LeveyJenningsDiagram::setFluidicsPackChanges(), KDChart::LeveyJenningsDiagram::setLotChangedSymbolPosition(), KDChart::LeveyJenningsDiagram::setScanLinePen(), KDChart::LeveyJenningsDiagram::setSensorChangedSymbolPosition(), KDChart::LeveyJenningsDiagram::setSensorChanges(), KDChart::LeveyJenningsDiagram::setSymbol(), and KDChart::LeveyJenningsDiagram::setTimeRange().
useDefaultColors()
void KDChart::AbstractDiagram::useDefaultColors () inherited
Set the palette to be used, for painting datasets to the default palette.
See also
KDChart::Palette. FIXME: fold into one usePalette (KDChart::Palette&) method
Definition at line 866 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AttributesModel::PaletteTypeDefault.
useRainbowColors()
void KDChart::AbstractDiagram::useRainbowColors () inherited
Set the palette to be used, for painting datasets to the rainbow palette.
See also
KDChart::Palette.
Definition at line 876 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AttributesModel::PaletteTypeRainbow.
usesExternalAttributesModel()
bool AbstractDiagram::usesExternalAttributesModel () const virtual inherited
Returns whether the diagram is using its own built-in attributes model or an attributes model that was set via setAttributesModel.
See also
setAttributesModel
Definition at line 193 of file KDChartAbstractDiagram.cpp.
References d.
useSubduedColors()
void KDChart::AbstractDiagram::useSubduedColors () inherited
Set the palette to be used, for painting datasets to the subdued palette.
See also
KDChart::Palette.
Definition at line 871 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AttributesModel::PaletteTypeSubdued.
valueForCell()
qreal AbstractDiagram::valueForCell (int row, int column) const protected inherited
Helper method, retrieving the data value (DisplayRole) for a given row and column.
Parameters
row The row to query.
column The column to query.
Returns
The value of the display role at the given row and column as a qreal.
Deprecated:
Definition at line 985 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModelRootIndex(), and d.
valueTotals() [1/2]
qreal RingDiagram::valueTotals () const virtual
[reimplemented]
Implements KDChart::AbstractPolarDiagram.
Definition at line 453 of file KDChartRingDiagram.cpp.
References KDChart::AbstractPolarDiagram::columnCount(), and KDChart::AbstractPolarDiagram::rowCount().
Referenced by paint().
valueTotals() [2/2]
qreal RingDiagram::valueTotals (int dataset) const
Definition at line 466 of file KDChartRingDiagram.cpp.
References KDChart::AbstractPolarDiagram::columnCount(), and KDChart::AbstractPolarDiagram::rowCount().
verticalOffset()
int AbstractDiagram::verticalOffset () const virtual inherited
[reimplemented]
Definition at line 833 of file KDChartAbstractDiagram.cpp.
viewportCoordinateSystemChanged
void KDChart::AbstractDiagram::viewportCoordinateSystemChanged () signal inherited
Emitted upon change of the view coordinate system.
visualRect()
QRect AbstractDiagram::visualRect (const QModelIndex & index) const virtual inherited
[reimplemented]
Definition at line 817 of file KDChartAbstractDiagram.cpp.
References d.
visualRegion()
QRegion AbstractDiagram::visualRegion (const QModelIndex & index) const virtual inherited
Definition at line 860 of file KDChartAbstractDiagram.cpp.
References d.
visualRegionForSelection()
QRegion AbstractDiagram::visualRegionForSelection (const QItemSelection & selection) const virtual inherited
[reimplemented]
Definition at line 850 of file KDChartAbstractDiagram.cpp.
References d.
The documentation for this class was generated from the following files:
KDChartRingDiagram.h
KDChartRingDiagram.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/