KD Chart 2: KDChart::BackgroundAttributes Class Reference
KDChart::BackgroundAttributes Class Reference
Set of attributes usable for background pixmaps.
#include <KDChartBackgroundAttributes.h>
Public Types
enum BackgroundPixmapMode {
BackgroundPixmapModeNone,
BackgroundPixmapModeCentered,
BackgroundPixmapModeScaled,
BackgroundPixmapModeStretched
}
Public Member Functions
BackgroundAttributes ()
BackgroundAttributes (const BackgroundAttributes &)
QBrush brush () const
bool isEqualTo (const BackgroundAttributes &other, bool ignorePixmap=false) const
bool isVisible () const
bool operator!= (const BackgroundAttributes &other) const
BackgroundAttributes & operator= (const BackgroundAttributes &)
bool operator== (const BackgroundAttributes &) const
QPixmap pixmap () const
BackgroundPixmapMode pixmapMode () const
void setBrush (const QBrush &brush)
void setPixmap (const QPixmap &backPixmap)
void setPixmapMode (BackgroundPixmapMode mode)
void setVisible (bool visible)
~BackgroundAttributes ()
Detailed Description
Set of attributes usable for background pixmaps.
Definition at line 36 of file KDChartBackgroundAttributes.h.
Member Enumeration Documentation
BackgroundPixmapMode
enum KDChart::BackgroundAttributes::BackgroundPixmapMode
Enumerator
BackgroundPixmapModeNone
BackgroundPixmapModeCentered
BackgroundPixmapModeScaled
BackgroundPixmapModeStretched
Definition at line 45 of file KDChartBackgroundAttributes.h.
Constructor & Destructor Documentation
BackgroundAttributes() [1/2]
BackgroundAttributes::BackgroundAttributes ()
Definition at line 52 of file KDChartBackgroundAttributes.cpp.
BackgroundAttributes() [2/2]
BackgroundAttributes::BackgroundAttributes (const BackgroundAttributes & r)
Definition at line 57 of file KDChartBackgroundAttributes.cpp.
~BackgroundAttributes()
BackgroundAttributes::~BackgroundAttributes ()
Definition at line 97 of file KDChartBackgroundAttributes.cpp.
Member Function Documentation
brush()
QBrush BackgroundAttributes::brush () const
Definition at line 121 of file KDChartBackgroundAttributes.cpp.
References d.
Referenced by isEqualTo(), operator<<(), KDChart::AbstractAreaBase::paintBackgroundAttributes(), setBrush(), and updateCommonBrush().
isEqualTo()
bool BackgroundAttributes::isEqualTo (const BackgroundAttributes & other, bool ignorePixmap = false) const
Definition at line 78 of file KDChartBackgroundAttributes.cpp.
References brush(), isVisible(), pixmap(), and pixmapMode().
Referenced by operator==().
isVisible()
bool BackgroundAttributes::isVisible () const
Definition at line 111 of file KDChartBackgroundAttributes.cpp.
References d.
Referenced by isEqualTo(), operator<<(), and KDChart::AbstractAreaBase::paintBackgroundAttributes().
operator!=()
bool KDChart::BackgroundAttributes::operator!= (const BackgroundAttributes & other) const
Definition at line 63 of file KDChartBackgroundAttributes.h.
References KDGantt::operator==().
operator=()
BackgroundAttributes & BackgroundAttributes::operator= (const BackgroundAttributes & r)
Definition at line 62 of file KDChartBackgroundAttributes.cpp.
References d.
operator==()
bool BackgroundAttributes::operator== (const BackgroundAttributes & r) const
Definition at line 72 of file KDChartBackgroundAttributes.cpp.
References isEqualTo().
pixmap()
QPixmap BackgroundAttributes::pixmap () const
Definition at line 141 of file KDChartBackgroundAttributes.cpp.
References d.
Referenced by isEqualTo(), operator<<(), and KDChart::AbstractAreaBase::paintBackgroundAttributes().
pixmapMode()
BackgroundAttributes::BackgroundPixmapMode BackgroundAttributes::pixmapMode () const
Definition at line 131 of file KDChartBackgroundAttributes.cpp.
References d.
Referenced by isEqualTo(), operator<<(), and KDChart::AbstractAreaBase::paintBackgroundAttributes().
setBrush()
void BackgroundAttributes::setBrush (const QBrush & brush)
Definition at line 116 of file KDChartBackgroundAttributes.cpp.
References brush(), and d.
setPixmap()
void BackgroundAttributes::setPixmap (const QPixmap & backPixmap)
Definition at line 136 of file KDChartBackgroundAttributes.cpp.
References d.
setPixmapMode()
void BackgroundAttributes::setPixmapMode (BackgroundPixmapMode mode)
Definition at line 126 of file KDChartBackgroundAttributes.cpp.
References d.
setVisible()
void BackgroundAttributes::setVisible (bool visible)
Definition at line 105 of file KDChartBackgroundAttributes.cpp.
References d.
The documentation for this class was generated from the following files:
KDChartBackgroundAttributes.h
KDChartBackgroundAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/