KD Chart 2: KDChart::DataValueAttributes Class Reference
KDChart::DataValueAttributes Class Reference
Diagram attributes dealing with data value labels.
#include <KDChartDataValueAttributes>
Public Member Functions
BackgroundAttributes backgroundAttributes () const
QString dataLabel () const
Returns the string displayed instead of the data value label.
DataValueAttributes ()
DataValueAttributes (const DataValueAttributes &)
int decimalDigits () const
FrameAttributes frameAttributes () const
bool isVisible () const
MarkerAttributes markerAttributes () const
bool mirrorNegativeValueTextRotation () const
If true, rotation of negative value labels is negated, so that negative values are rotated in opposite direction of textAttributes().rotation(), and in this sense appear "mirrored" to positive value labels, though the text itself is not mirrored, only its rotation.
const RelativePosition negativePosition () const
Return the relative positioning of the data value labels.
bool operator!= (const DataValueAttributes &other) const
DataValueAttributes & operator= (const DataValueAttributes &)
bool operator== (const DataValueAttributes &) const
const RelativePosition position (bool positive) const
const RelativePosition positivePosition () const
Return the relative positioning of the data value labels.
QString prefix () const
Returns the string used as a prefix to the data value text.
void setBackgroundAttributes (const BackgroundAttributes &a)
Set the background attributes to use for the data value labels area.
void setDataLabel (const QString label)
display a string label instead of the original data value label Supports HTML code.
void setDecimalDigits (int digits)
Set how many decimal digits to display when rendering the data value labels.
void setFrameAttributes (const FrameAttributes &a)
Set the frame attributes to use for the data value labels area.
void setMarkerAttributes (const MarkerAttributes &a)
Set the marker attributes to use for the data values.
void setMirrorNegativeValueTextRotation (bool enable)
void setNegativePosition (const RelativePosition &relPosition)
Defines the relative positioning of the data value labels for negative values.
void setPositivePosition (const RelativePosition &relPosition)
Defines the relative position of the data value labels for positive values.
void setPrefix (const QString prefix)
Prepend a prefix string to the data value label.
void setShowOverlappingDataLabels (bool showOverlappingDataLabels)
Set whether data value texts overlapping other data value texts of the same diagram should be drawn.
void setShowRepetitiveDataLabels (bool showRepetitiveDataLabels)
Set whether data value labels not different from their predecessors should be drawn.
void setSuffix (const QString suffix)
Append a suffix string to the data value label.
void setTextAttributes (const TextAttributes &a)
Set the text attributes to use for the data value labels.
void setUsePercentage (bool enable)
Specify whether to use percentages instead of actual data point values when no specific label is set.
void setVisible (bool visible)
Set whether data value labels should be displayed.
bool showOverlappingDataLabels () const
bool showRepetitiveDataLabels () const
QString suffix () const
Returns the string used as a suffix to the data value text.
TextAttributes textAttributes () const
bool usePercentage () const
~DataValueAttributes ()
Static Public Member Functions
static const DataValueAttributes & defaultAttributes ()
static const QVariant & defaultAttributesAsVariant ()
Detailed Description
Diagram attributes dealing with data value labels.
The DataValueAttributes group all properties that can be set wrt data value labels and if and how they are displayed. This includes things like the text attributes (font, color), what markers are used, how many decimal digits are displayed, etc.
Definition at line 55 of file KDChartDataValueAttributes.h.
Constructor & Destructor Documentation
DataValueAttributes() [1/2]
DataValueAttributes::DataValueAttributes ()
Definition at line 97 of file KDChartDataValueAttributes.cpp.
DataValueAttributes() [2/2]
DataValueAttributes::DataValueAttributes (const DataValueAttributes & r)
Definition at line 102 of file KDChartDataValueAttributes.cpp.
~DataValueAttributes()
DataValueAttributes::~DataValueAttributes ()
Definition at line 117 of file KDChartDataValueAttributes.cpp.
Member Function Documentation
backgroundAttributes()
BackgroundAttributes DataValueAttributes::backgroundAttributes () const
Returns
The background attributes used for painting the data value labels area.
See also
BackgroundAttributes
Definition at line 194 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
dataLabel()
QString DataValueAttributes::dataLabel () const
Returns the string displayed instead of the data value label.
See also
setDataLabel
Definition at line 264 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator==().
decimalDigits()
int DataValueAttributes::decimalDigits () const
Returns
The number of decimal digits displayed.
Definition at line 234 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
defaultAttributes()
const DataValueAttributes & DataValueAttributes::defaultAttributes () static
Definition at line 145 of file KDChartDataValueAttributes.cpp.
Referenced by defaultAttributesAsVariant().
defaultAttributesAsVariant()
const QVariant & DataValueAttributes::defaultAttributesAsVariant () static
Definition at line 152 of file KDChartDataValueAttributes.cpp.
References defaultAttributes().
Referenced by KDChart::AttributesModel::AttributesModel().
frameAttributes()
FrameAttributes DataValueAttributes::frameAttributes () const
Returns
The frame attributes used for painting the data value labels area.
See also
FrameAttributes
Definition at line 184 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
isVisible()
bool DataValueAttributes::isVisible () const
Returns
Whether data value labels should be displayed.
Definition at line 164 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::AbstractDiagram::paintMarker().
markerAttributes()
MarkerAttributes DataValueAttributes::markerAttributes () const
Returns
The marker attributes used for decorating the data values.
See also
MarkerAttributes
Definition at line 204 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by KDChart::AbstractDiagram::datasetMarkers(), operator==(), and KDChart::AbstractDiagram::paintMarker().
mirrorNegativeValueTextRotation()
bool DataValueAttributes::mirrorNegativeValueTextRotation () const
If true, rotation of negative value labels is negated, so that negative values are rotated in opposite direction of textAttributes().rotation(), and in this sense appear "mirrored" to positive value labels, though the text itself is not mirrored, only its rotation.
Definition at line 214 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator==().
negativePosition()
const RelativePosition DataValueAttributes::negativePosition () const
Return the relative positioning of the data value labels.
See also
setNegativePosition
Definition at line 314 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
operator!=()
bool KDChart::DataValueAttributes::operator!= (const DataValueAttributes & other) const
Definition at line 62 of file KDChartDataValueAttributes.h.
References KDGantt::operator==().
operator=()
DataValueAttributes & DataValueAttributes::operator= (const DataValueAttributes & r)
Definition at line 107 of file KDChartDataValueAttributes.cpp.
References d.
operator==()
bool DataValueAttributes::operator== (const DataValueAttributes & r) const
Definition at line 123 of file KDChartDataValueAttributes.cpp.
References backgroundAttributes(), dataLabel(), decimalDigits(), frameAttributes(), isVisible(), markerAttributes(), mirrorNegativeValueTextRotation(), negativePosition(), positivePosition(), prefix(), showOverlappingDataLabels(), showRepetitiveDataLabels(), suffix(), textAttributes(), and usePercentage().
position()
const RelativePosition KDChart::DataValueAttributes::position (bool positive) const
Definition at line 303 of file KDChartDataValueAttributes.h.
positivePosition()
const RelativePosition DataValueAttributes::positivePosition () const
Return the relative positioning of the data value labels.
See also
setPositivePosition
Definition at line 324 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
prefix()
QString DataValueAttributes::prefix () const
Returns the string used as a prefix to the data value text.
See also
setPrefix
Definition at line 244 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator==().
setBackgroundAttributes()
void DataValueAttributes::setBackgroundAttributes (const BackgroundAttributes & a)
Set the background attributes to use for the data value labels area.
Parameters
a The background attributes to set.
See also
BackgroundAttributes
Definition at line 189 of file KDChartDataValueAttributes.cpp.
References d.
setDataLabel()
void DataValueAttributes::setDataLabel (const QString label)
display a string label instead of the original data value label Supports HTML code.
See also
dataLabel
Definition at line 259 of file KDChartDataValueAttributes.cpp.
References d.
setDecimalDigits()
void DataValueAttributes::setDecimalDigits (int digits)
Set how many decimal digits to display when rendering the data value labels.
If there are no decimal digits it will not be displayed.
Parameters
digits The number of decimal digits to use.
Definition at line 229 of file KDChartDataValueAttributes.cpp.
References d.
setFrameAttributes()
void DataValueAttributes::setFrameAttributes (const FrameAttributes & a)
Set the frame attributes to use for the data value labels area.
Parameters
a The frame attributes to set.
See also
FrameAttributes
Definition at line 179 of file KDChartDataValueAttributes.cpp.
References d.
setMarkerAttributes()
void DataValueAttributes::setMarkerAttributes (const MarkerAttributes & a)
Set the marker attributes to use for the data values.
This includes the marker type.
Parameters
a The marker attributes to set.
See also
MarkerAttributes
Definition at line 199 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by KDChart::TernaryLineDiagram::TernaryLineDiagram().
setMirrorNegativeValueTextRotation()
void DataValueAttributes::setMirrorNegativeValueTextRotation (bool enable)
See also
mirrorNegativeValueTextRotation()
Definition at line 209 of file KDChartDataValueAttributes.cpp.
References d.
setNegativePosition()
void DataValueAttributes::setNegativePosition (const RelativePosition & relPosition)
Defines the relative positioning of the data value labels for negative values.
The position is specified in relation to the respective data value point, or in relation to the respective data representation area, that's one area segment in a LineDiagram showing areas, or one bar in a BarDiagram, one pie slice ...
See detailed description of KDChart::Position for an illustration of the different possible reference positions.
See also
negativePosition
Definition at line 309 of file KDChartDataValueAttributes.cpp.
References d.
setPositivePosition()
void DataValueAttributes::setPositivePosition (const RelativePosition & relPosition)
Defines the relative position of the data value labels for positive values.
The position is specified in relation to the respective data value point, or in relation to the respective data representation area, that's one area segment in a LineDiagram showing areas, or one bar in a BarDiagram, one pie slice ...
See detailed description of KDChart::Position for an illustration of the different possible reference positions.
See also
positivePosition
Definition at line 319 of file KDChartDataValueAttributes.cpp.
References d.
setPrefix()
void DataValueAttributes::setPrefix (const QString prefix)
Prepend a prefix string to the data value label.
See also
prefix
Definition at line 239 of file KDChartDataValueAttributes.cpp.
References d.
setShowOverlappingDataLabels()
void DataValueAttributes::setShowOverlappingDataLabels (bool showOverlappingDataLabels)
Set whether data value texts overlapping other data value texts of the same diagram should be drawn.
Parameters
showOverlappingDataLabels Whether data texts overlapping other data value texts of the same diagram are drawn.
Definition at line 284 of file KDChartDataValueAttributes.cpp.
References d, and showOverlappingDataLabels().
Referenced by KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts().
setShowRepetitiveDataLabels()
void DataValueAttributes::setShowRepetitiveDataLabels (bool showRepetitiveDataLabels)
Set whether data value labels not different from their predecessors should be drawn.
Parameters
showRepetitiveDataLabels Whether data value not different from their predecessors are drawn.
Definition at line 274 of file KDChartDataValueAttributes.cpp.
References d, and showRepetitiveDataLabels().
setSuffix()
void DataValueAttributes::setSuffix (const QString suffix)
Append a suffix string to the data value label.
See also
suffix
Definition at line 249 of file KDChartDataValueAttributes.cpp.
References d.
setTextAttributes()
void DataValueAttributes::setTextAttributes (const TextAttributes & a)
Set the text attributes to use for the data value labels.
Parameters
a The text attributes to set.
See also
TextAttributes
Definition at line 169 of file KDChartDataValueAttributes.cpp.
References d.
setUsePercentage()
void DataValueAttributes::setUsePercentage (bool enable)
Specify whether to use percentages instead of actual data point values when no specific label is set.
In a bar or cartesian diagram, this means that the value will be shown in % in relation to the sum of all values in the same category, in a polar diagram in relation to the sum of all values in a data set.
When this is turned on, the value will not automatically have the '' postfix.
Parameters
enable Whether to enable percentage values
Definition at line 219 of file KDChartDataValueAttributes.cpp.
References d.
setVisible()
void DataValueAttributes::setVisible (bool visible)
Set whether data value labels should be displayed.
Parameters
visible Whether data value labels should be displayed.
Definition at line 159 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by KDChart::TernaryLineDiagram::TernaryLineDiagram().
showOverlappingDataLabels()
bool DataValueAttributes::showOverlappingDataLabels () const
Returns
Whether data value texts overlapping other data value texts of the same diagram are drawn.
Definition at line 279 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and setShowOverlappingDataLabels().
showRepetitiveDataLabels()
bool DataValueAttributes::showRepetitiveDataLabels () const
Returns
Whether data values not different from their predecessors are drawn.
Definition at line 269 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and setShowRepetitiveDataLabels().
suffix()
QString DataValueAttributes::suffix () const
Returns the string used as a suffix to the data value text.
See also
setSuffix
Definition at line 254 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator==().
textAttributes()
TextAttributes DataValueAttributes::textAttributes () const
Returns
The text attributes used for painting data value labels.
Definition at line 174 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
usePercentage()
bool DataValueAttributes::usePercentage () const
Returns
Whether to use percentage values
See also
setUsePercentage
Definition at line 224 of file KDChartDataValueAttributes.cpp.
References d.
Referenced by operator==().
The documentation for this class was generated from the following files:
KDChartDataValueAttributes.h
KDChartDataValueAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/