KD Chart 2: KDChart::ThreeDBarAttributes Class Reference
KDChart::ThreeDBarAttributes Class Reference
A set of 3D bar attributes.
#include <KDChartThreeDBarAttributes.h>
Public Member Functions
uint angle () const
qreal depth () const
bool isEnabled () const
bool isThreeDBrushEnabled () const
bool operator!= (const ThreeDBarAttributes &other) const
bool operator!= (const AbstractThreeDAttributes &other) const
ThreeDBarAttributes & operator= (const ThreeDBarAttributes &)
bool operator== (const ThreeDBarAttributes &) const
bool operator== (const AbstractThreeDAttributes &) const
void setAngle (uint threeDAngle)
void setDepth (qreal depth)
void setEnabled (bool enabled)
void setThreeDBrushEnabled (bool enabled)
void setUseShadowColors (bool useShadowColors)
ThreeDBarAttributes ()
ThreeDBarAttributes (const ThreeDBarAttributes &)
virtual QBrush threeDBrush (const QBrush &brush, const QRectF &rect) const
bool useShadowColors () const
qreal validDepth () const
~ThreeDBarAttributes ()
Detailed Description
A set of 3D bar attributes.
Definition at line 35 of file KDChartThreeDBarAttributes.h.
Constructor & Destructor Documentation
ThreeDBarAttributes() [1/2]
ThreeDBarAttributes::ThreeDBarAttributes ()
Definition at line 41 of file KDChartThreeDBarAttributes.cpp.
ThreeDBarAttributes() [2/2]
ThreeDBarAttributes::ThreeDBarAttributes (const ThreeDBarAttributes & r)
Definition at line 47 of file KDChartThreeDBarAttributes.cpp.
~ThreeDBarAttributes()
ThreeDBarAttributes::~ThreeDBarAttributes ()
Definition at line 62 of file KDChartThreeDBarAttributes.cpp.
Member Function Documentation
angle()
uint ThreeDBarAttributes::angle () const
Definition at line 95 of file KDChartThreeDBarAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
depth()
qreal AbstractThreeDAttributes::depth () const inherited
Definition at line 99 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), KDChart::AbstractThreeDAttributes::operator==(), KDChart::PaintingHelpers::project(), and KDChart::AbstractThreeDAttributes::setDepth().
isEnabled()
bool AbstractThreeDAttributes::isEnabled () const inherited
Definition at line 88 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), KDChart::AbstractThreeDAttributes::operator==(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), and KDChart::AbstractThreeDAttributes::validDepth().
isThreeDBrushEnabled()
bool AbstractThreeDAttributes::isThreeDBrushEnabled () const inherited
Definition at line 110 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by KDChart::AbstractThreeDAttributes::operator==(), and KDChart::AbstractThreeDAttributes::threeDBrush().
operator!=() [1/2]
bool KDChart::ThreeDBarAttributes::operator!= (const ThreeDBarAttributes & other) const
Definition at line 53 of file KDChartThreeDBarAttributes.h.
References KDGantt::operator==().
operator!=() [2/2]
bool KDChart::AbstractThreeDAttributes::operator!= (const AbstractThreeDAttributes & other) const inherited
Definition at line 57 of file KDChartAbstractThreeDAttributes.h.
References KDGantt::operator==().
operator=()
ThreeDBarAttributes & ThreeDBarAttributes::operator= (const ThreeDBarAttributes & r)
Definition at line 52 of file KDChartThreeDBarAttributes.cpp.
References d.
operator==() [1/2]
bool ThreeDBarAttributes::operator== (const ThreeDBarAttributes & r) const
Definition at line 71 of file KDChartThreeDBarAttributes.cpp.
References angle(), KDChart::AbstractThreeDAttributes::operator==(), and useShadowColors().
operator==() [2/2]
bool AbstractThreeDAttributes::operator== (const AbstractThreeDAttributes & r) const inherited
Definition at line 70 of file KDChartAbstractThreeDAttributes.cpp.
References KDChart::AbstractThreeDAttributes::depth(), KDChart::AbstractThreeDAttributes::isEnabled(), and KDChart::AbstractThreeDAttributes::isThreeDBrushEnabled().
Referenced by KDChart::ThreeDPieAttributes::operator==(), KDChart::ThreeDLineAttributes::operator==(), and operator==().
setAngle()
void ThreeDBarAttributes::setAngle (uint threeDAngle)
Definition at line 90 of file KDChartThreeDBarAttributes.cpp.
References d.
setDepth()
void AbstractThreeDAttributes::setDepth (qreal depth) inherited
Definition at line 93 of file KDChartAbstractThreeDAttributes.cpp.
References d, and KDChart::AbstractThreeDAttributes::depth().
setEnabled()
void AbstractThreeDAttributes::setEnabled (bool enabled) inherited
Definition at line 83 of file KDChartAbstractThreeDAttributes.cpp.
References d.
setThreeDBrushEnabled()
void AbstractThreeDAttributes::setThreeDBrushEnabled (bool enabled) inherited
Definition at line 115 of file KDChartAbstractThreeDAttributes.cpp.
References d.
setUseShadowColors()
void ThreeDBarAttributes::setUseShadowColors (bool useShadowColors)
Definition at line 80 of file KDChartThreeDBarAttributes.cpp.
References d.
threeDBrush()
QBrush AbstractThreeDAttributes::threeDBrush (const QBrush & brush, const QRectF & rect) const virtual inherited
Definition at line 120 of file KDChartAbstractThreeDAttributes.cpp.
References KDChart::AbstractThreeDAttributes::isThreeDBrushEnabled().
Referenced by KDChart::PaintingHelpers::paintAreas(), and KDChart::PaintingHelpers::paintThreeDLines().
useShadowColors()
bool ThreeDBarAttributes::useShadowColors () const
Definition at line 85 of file KDChartThreeDBarAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
validDepth()
qreal AbstractThreeDAttributes::validDepth () const inherited
Definition at line 105 of file KDChartAbstractThreeDAttributes.cpp.
References d, and KDChart::AbstractThreeDAttributes::isEnabled().
Referenced by KDChart::BarDiagram::threeDItemDepth(), KDChart::Plotter::threeDItemDepth(), and KDChart::LineDiagram::threeDItemDepth().
The documentation for this class was generated from the following files:
KDChartThreeDBarAttributes.h
KDChartThreeDBarAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/