KD Chart 2: KDChart::LeveyJenningsGridAttributes Class Reference
KDChart::LeveyJenningsGridAttributes Class Reference
A set of attributes controlling the appearance of grids.
#include <KDChartLeveyJenningsGridAttributes.h>
Public Types
enum GridType {
Expected,
Calculated
}
enum Range {
NormalRange,
CriticalRange,
OutOfRange
}
Public Member Functions
QPen gridPen (GridType type) const
bool isGridVisible (GridType type) const
LeveyJenningsGridAttributes ()
LeveyJenningsGridAttributes (const LeveyJenningsGridAttributes &)
bool operator!= (const LeveyJenningsGridAttributes &other) const
LeveyJenningsGridAttributes & operator= (const LeveyJenningsGridAttributes &)
bool operator== (const LeveyJenningsGridAttributes &) const
QBrush rangeBrush (Range range) const
void setGridPen (GridType type, const QPen &pen)
void setGridVisible (GridType type, bool visible)
void setRangeBrush (Range range, const QBrush &brush)
~LeveyJenningsGridAttributes ()
Detailed Description
A set of attributes controlling the appearance of grids.
Definition at line 39 of file KDChartLeveyJenningsGridAttributes.h.
Member Enumeration Documentation
GridType
enum KDChart::LeveyJenningsGridAttributes::GridType
Enumerator
Expected
Calculated
Definition at line 48 of file KDChartLeveyJenningsGridAttributes.h.
Range
enum KDChart::LeveyJenningsGridAttributes::Range
Enumerator
NormalRange
CriticalRange
OutOfRange
Definition at line 54 of file KDChartLeveyJenningsGridAttributes.h.
Constructor & Destructor Documentation
LeveyJenningsGridAttributes() [1/2]
LeveyJenningsGridAttributes::LeveyJenningsGridAttributes ()
Definition at line 61 of file KDChartLeveyJenningsGridAttributes.cpp.
LeveyJenningsGridAttributes() [2/2]
LeveyJenningsGridAttributes::LeveyJenningsGridAttributes (const LeveyJenningsGridAttributes & r)
Definition at line 67 of file KDChartLeveyJenningsGridAttributes.cpp.
~LeveyJenningsGridAttributes()
LeveyJenningsGridAttributes::~LeveyJenningsGridAttributes ()
Definition at line 82 of file KDChartLeveyJenningsGridAttributes.cpp.
Member Function Documentation
gridPen()
QPen LeveyJenningsGridAttributes::gridPen (GridType type) const
Definition at line 123 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
Referenced by operator==().
isGridVisible()
bool LeveyJenningsGridAttributes::isGridVisible (GridType type) const
Definition at line 112 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
Referenced by operator==().
operator!=()
bool KDChart::LeveyJenningsGridAttributes::operator!= (const LeveyJenningsGridAttributes & other) const
Definition at line 71 of file KDChartLeveyJenningsGridAttributes.h.
References KDGantt::operator==().
operator=()
LeveyJenningsGridAttributes & LeveyJenningsGridAttributes::operator= (const LeveyJenningsGridAttributes & r)
Definition at line 72 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
operator==()
bool LeveyJenningsGridAttributes::operator== (const LeveyJenningsGridAttributes & r) const
Definition at line 88 of file KDChartLeveyJenningsGridAttributes.cpp.
References Calculated, Expected, gridPen(), and isGridVisible().
rangeBrush()
QBrush LeveyJenningsGridAttributes::rangeBrush (Range range) const
Definition at line 101 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
setGridPen()
void LeveyJenningsGridAttributes::setGridPen (GridType type, const QPen & pen)
Definition at line 117 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
setGridVisible()
void LeveyJenningsGridAttributes::setGridVisible (GridType type, bool visible)
Definition at line 107 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
setRangeBrush()
void LeveyJenningsGridAttributes::setRangeBrush (Range range, const QBrush & brush)
Definition at line 96 of file KDChartLeveyJenningsGridAttributes.cpp.
References d.
The documentation for this class was generated from the following files:
KDChartLeveyJenningsGridAttributes.h
KDChartLeveyJenningsGridAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/