KD Chart 2: KDChart::TextAttributes Class Reference
KDChart::TextAttributes Class Reference
A set of text attributes.
#include <KDChartTextAttributes.h>
Public Member Functions
bool autoRotate () const
bool autoShrink () const
const QFont calculatedFont (const QObject *autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation) const
Returns the font in the size that is used at drawing time.
qreal calculatedFontSize (const QSizeF &referenceSize, KDChartEnums::MeasureOrientation autoReferenceOrientation) const
Returns the font size that is used at drawing time.
const qreal calculatedFontSize (const QObject *autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation) const
Returns the font size that is used at drawing time.
QFont font () const
Measure fontSize () const
bool hasAbsoluteFontSize () const
bool hasRotation () const
bool isVisible () const
Measure minimalFontSize () const
bool operator!= (const TextAttributes &other) const
TextAttributes & operator= (const TextAttributes &)
bool operator== (const TextAttributes &) const
QPen pen () const
void resetRotation ()
int rotation () const
void setAutoRotate (bool autoRotate)
Set whether the text should be automatically rotated as needed when space is tight.
void setAutoShrink (bool autoShrink)
Set whether the text should automatically be shrunk if space is tight.
void setFont (const QFont &font)
Set the font to be used for rendering the text.
void setFontSize (const Measure &measure)
Set the size of the font used for rendering text.
void setMinimalFontSize (const Measure &measure)
Set the minimal size of the font used for rendering text.
void setPen (const QPen &pen)
Set the pen to use for rendering the text.
void setRotation (int rotation)
Set the rotation angle to use for the text.
void setTextDocument (QTextDocument *layout)
Sets the document to use for the text.
void setVisible (bool visible)
Set whether the text is to be rendered at all.
TextAttributes ()
TextAttributes (const TextAttributes &)
QTextDocument * textDocument () const
~TextAttributes ()
Detailed Description
A set of text attributes.
TextAttributes encapsulates settings that have to do with text. This includes font, fontsize, color, whether the text is rotated, etc
Definition at line 46 of file KDChartTextAttributes.h.
Constructor & Destructor Documentation
TextAttributes() [1/2]
TextAttributes::TextAttributes ()
Definition at line 72 of file KDChartTextAttributes.cpp.
TextAttributes() [2/2]
TextAttributes::TextAttributes (const TextAttributes & r)
Definition at line 77 of file KDChartTextAttributes.cpp.
~TextAttributes()
TextAttributes::~TextAttributes ()
Definition at line 93 of file KDChartTextAttributes.cpp.
Member Function Documentation
autoRotate()
bool TextAttributes::autoRotate () const
Returns
Whether text is automatically rotated when space is tight.
Definition at line 219 of file KDChartTextAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::CartesianAxis::paintCtx(), and setAutoRotate().
autoShrink()
bool TextAttributes::autoShrink () const
Returns
Whether text is automatically shrunk if space is tight.
Definition at line 229 of file KDChartTextAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and setAutoShrink().
calculatedFont()
const QFont TextAttributes::calculatedFont (const QObject * autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation) const
Returns the font in the size that is used at drawing time.
This method is called at drawing time. It returns the font as it is used for rendering text, taking into account any measures that were set via setFontSize and/or setMinimalFontSize.
Definition at line 185 of file KDChartTextAttributes.cpp.
References calculatedFontSize(), d, and KDChart::CartesianCoordinatePlane::hasFixedDataCoordinateSpaceRelation().
Referenced by KDChart::LeveyJenningsDiagram::iconRect().
calculatedFontSize() [1/2]
qreal TextAttributes::calculatedFontSize (const QSizeF & referenceSize, KDChartEnums::MeasureOrientation autoReferenceOrientation) const
Returns the font size that is used at drawing time.
This method is called at drawing time. It returns the font size as it is used for rendering text, taking into account any measures that were set via setFontSize and/or setMinimalFontSize.
Definition at line 166 of file KDChartTextAttributes.cpp.
References KDChart::Measure::calculatedValue(), fontSize(), and minimalFontSize().
Referenced by calculatedFont().
calculatedFontSize() [2/2]
const qreal TextAttributes::calculatedFontSize (const QObject * autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation) const
Returns the font size that is used at drawing time.
This method is called at drawing time. It returns the font size as it is used for rendering text, taking into account any measures that were set via setFontSize and/or setMinimalFontSize.
Definition at line 177 of file KDChartTextAttributes.cpp.
References KDChart::Measure::calculatedValue(), fontSize(), and minimalFontSize().
font()
QFont TextAttributes::font () const
Returns
The font that is used for rendering text.
Definition at line 135 of file KDChartTextAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::RadarDiagram::paint(), setFont(), and KDChart::TextLayoutItem::setTextAttributes().
fontSize()
Measure TextAttributes::fontSize () const
Returns
The measure used for the font size.
Definition at line 145 of file KDChartTextAttributes.cpp.
References d.
Referenced by calculatedFontSize(), operator<<(), operator==(), and KDChart::CartesianAxis::titleTextAttributes().
hasAbsoluteFontSize()
bool TextAttributes::hasAbsoluteFontSize () const
Returns
Whether the text has an absolute font size set.
Definition at line 160 of file KDChartTextAttributes.cpp.
References d, and KDChartEnums::MeasureCalculationModeAbsolute.
hasRotation()
bool TextAttributes::hasRotation () const
Definition at line 251 of file KDChartTextAttributes.cpp.
References d.
isVisible()
bool TextAttributes::isVisible () const
Returns
Whether the text is visible.
Definition at line 123 of file KDChartTextAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::RadarDiagram::paint(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), and KDChart::CartesianAxis::paintCtx().
minimalFontSize()
Measure TextAttributes::minimalFontSize () const
Returns
The measure used for the minimal font size.
Definition at line 155 of file KDChartTextAttributes.cpp.
References d.
Referenced by calculatedFontSize(), operator<<(), and operator==().
operator!=()
bool KDChart::TextAttributes::operator!= (const TextAttributes & other) const
Definition at line 53 of file KDChartTextAttributes.h.
References KDGantt::operator==().
operator=()
TextAttributes & TextAttributes::operator= (const TextAttributes & r)
Definition at line 83 of file KDChartTextAttributes.cpp.
References d.
operator==()
bool TextAttributes::operator== (const TextAttributes & r) const
Definition at line 99 of file KDChartTextAttributes.cpp.
References autoRotate(), autoShrink(), font(), fontSize(), isVisible(), minimalFontSize(), pen(), rotation(), and textDocument().
pen()
QPen TextAttributes::pen () const
Returns
The pen used for rendering the text.
Definition at line 261 of file KDChartTextAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::RadarDiagram::paint(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), setPen(), and KDChart::LeveyJenningsAxis::setType().
resetRotation()
void TextAttributes::resetRotation ()
Definition at line 245 of file KDChartTextAttributes.cpp.
References d.
rotation()
int TextAttributes::rotation () const
Returns
The rotation angle used for rendering the text.
Definition at line 240 of file KDChartTextAttributes.cpp.
References d.
Referenced by fitFontSizeToGeometry(), operator<<(), operator==(), KDChart::CartesianAxis::paintCtx(), and setRotation().
setAutoRotate()
void TextAttributes::setAutoRotate (bool autoRotate)
Set whether the text should be automatically rotated as needed when space is tight.
Parameters
autoRotate Whether text should be automatically rotated.
Definition at line 214 of file KDChartTextAttributes.cpp.
References autoRotate(), and d.
setAutoShrink()
void TextAttributes::setAutoShrink (bool autoShrink)
Set whether the text should automatically be shrunk if space is tight.
Parameters
autoShrink Whether text should be auto-shrunk.
Definition at line 224 of file KDChartTextAttributes.cpp.
References autoShrink(), and d.
setFont()
void TextAttributes::setFont (const QFont & font)
Set the font to be used for rendering the text.
Note
All of the font's attributes will be used - except of its size! To specify the size please use setFontSize (or setMinimalFontSize, resp.)
Parameters
font The font to use.
See also
setFontSize, setMinimalFontSize
Definition at line 128 of file KDChartTextAttributes.cpp.
References d, and font().
setFontSize()
void TextAttributes::setFontSize (const Measure & measure)
Set the size of the font used for rendering text.
Parameters
measure The measure to use.
See also
Measure
Definition at line 140 of file KDChartTextAttributes.cpp.
References d.
Referenced by KDChart::LeveyJenningsDiagram::iconRect(), and KDChart::CartesianAxis::titleTextAttributes().
setMinimalFontSize()
void TextAttributes::setMinimalFontSize (const Measure & measure)
Set the minimal size of the font used for rendering text.
Parameters
measure The measure to use.
See also
Measure
Definition at line 150 of file KDChartTextAttributes.cpp.
References d.
setPen()
void TextAttributes::setPen (const QPen & pen)
Set the pen to use for rendering the text.
Parameters
pen The pen to use.
Definition at line 256 of file KDChartTextAttributes.cpp.
References d, and pen().
Referenced by KDChart::LeveyJenningsAxis::setType().
setRotation()
void TextAttributes::setRotation (int rotation)
Set the rotation angle to use for the text.
Note
For axis titles the rotation angle can be set to one of the following angles: 0, 90, 180, 270 Any other values specified will be replaced by the next smaller one of the allowed values, so no matter what you set the rotation will always be one of these four values.
Parameters
rotation The rotation angle.
Definition at line 234 of file KDChartTextAttributes.cpp.
References d, and rotation().
Referenced by KDChart::CartesianAxis::paintCtx().
setTextDocument()
void TextAttributes::setTextDocument (QTextDocument * layout)
Sets the document to use for the text.
The previous document is deleted.
Definition at line 271 of file KDChartTextAttributes.cpp.
References d.
setVisible()
void TextAttributes::setVisible (bool visible)
Set whether the text is to be rendered at all.
Parameters
visible Whether the text is visible.
Definition at line 118 of file KDChartTextAttributes.cpp.
References d.
textDocument()
QTextDocument * TextAttributes::textDocument () const
Returns
The document used for the drawing the text or NULL if the default document is used.
Definition at line 266 of file KDChartTextAttributes.cpp.
References d.
Referenced by operator==().
The documentation for this class was generated from the following files:
KDChartTextAttributes.h
KDChartTextAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/