KD Chart 2: KDAB::UnitTest::Runner Class Reference
KDAB::UnitTest::Runner Class Reference
#include <testregistry.h>
Public Member Functions
unsigned int run (const char *group=0) const
~Runner ()
Detailed Description
Definition at line 63 of file testregistry.h.
Constructor & Destructor Documentation
~Runner()
KDAB::UnitTest::Runner::~Runner ()
Definition at line 99 of file testregistry.cpp.
References KDAB::UnitTest::TestRegistry::deleteInstance().
Member Function Documentation
run()
unsigned int KDAB::UnitTest::Runner::run (const char * group = 0) const
Definition at line 104 of file testregistry.cpp.
References KDAB::UnitTest::TestRegistry::instance(), and KDAB::UnitTest::TestRegistry::run().
The documentation for this class was generated from the following files:
testregistry.h
testregistry.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/