KD Chart 2: TernaryPoint Class Reference
TernaryPoint Class Reference
TernaryPoint defines a point within a ternary coordinate plane.
#include <TernaryPoint.h>
Public Member Functions
qreal a () const
qreal b () const
qreal c () const
bool isValid () const
void set (qreal a, qreal b)
TernaryPoint ()
TernaryPoint (qreal a, qreal b)
Detailed Description
TernaryPoint defines a point within a ternary coordinate plane.
Definition at line 33 of file TernaryPoint.h.
Constructor & Destructor Documentation
TernaryPoint() [1/2]
TernaryPoint::TernaryPoint ()
Definition at line 31 of file TernaryPoint.cpp.
References isValid().
TernaryPoint() [2/2]
TernaryPoint::TernaryPoint (qreal a, qreal b)
Definition at line 38 of file TernaryPoint.cpp.
References a(), and b().
Member Function Documentation
a()
qreal TernaryPoint::a () const
Definition at line 39 of file TernaryPoint.h.
Referenced by operator<<(), set(), TernaryPoint(), and translate().
b()
qreal TernaryPoint::b () const
Definition at line 40 of file TernaryPoint.h.
Referenced by operator<<(), set(), TernaryPoint(), and translate().
c()
qreal TernaryPoint::c () const
Definition at line 41 of file TernaryPoint.h.
Referenced by operator<<().
isValid()
bool TernaryPoint::isValid () const
Definition at line 60 of file TernaryPoint.cpp.
Referenced by operator<<(), set(), TernaryPoint(), and translate().
set()
void TernaryPoint::set (qreal a, qreal b)
Definition at line 45 of file TernaryPoint.cpp.
References a(), b(), and isValid().
The documentation for this class was generated from the following files:
TernaryPoint.h
TernaryPoint.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/