KD Chart 2: KDChart::ChartGraphicsItem Class Reference
KDChart::ChartGraphicsItem Class Reference
Graphics item used inside of the ReverseMapper.
#include <ChartGraphicsItem.h>
Public Types
enum { Type = UserType + 1 }
Public Member Functions
ChartGraphicsItem ()
ChartGraphicsItem (int row, int column)
int column () const
int row () const
int type () const
Detailed Description
Graphics item used inside of the ReverseMapper.
Definition at line 34 of file ChartGraphicsItem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 37 of file ChartGraphicsItem.h.
Constructor & Destructor Documentation
ChartGraphicsItem() [1/2]
ChartGraphicsItem::ChartGraphicsItem ()
Definition at line 27 of file ChartGraphicsItem.cpp.
ChartGraphicsItem() [2/2]
ChartGraphicsItem::ChartGraphicsItem (int row, int column)
Definition at line 34 of file ChartGraphicsItem.cpp.
Member Function Documentation
column()
int KDChart::ChartGraphicsItem::column () const
Definition at line 44 of file ChartGraphicsItem.h.
Referenced by KDChart::ReverseMapper::addItem(), KDChart::ReverseMapper::indexesAt(), and KDChart::ReverseMapper::indexesIn().
row()
int KDChart::ChartGraphicsItem::row () const
Definition at line 43 of file ChartGraphicsItem.h.
Referenced by KDChart::ReverseMapper::addItem(), KDChart::ReverseMapper::indexesAt(), and KDChart::ReverseMapper::indexesIn().
type()
int KDChart::ChartGraphicsItem::type () const
Definition at line 45 of file ChartGraphicsItem.h.
References Type.
The documentation for this class was generated from the following files:
ChartGraphicsItem.h
ChartGraphicsItem.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/