KD Chart 2: KDGantt::Span Class Reference
KDGantt::Span Class Reference
A class representing a start point and a length.
#include <KDGanttGlobal>
Public Member Functions
qreal end () const
bool equals (const Span &other) const
Span expandedTo (const Span &other) const
bool isValid () const
qreal length () const
Span & operator= (const Span &other)
void setEnd (qreal end)
void setLength (qreal length)
void setStart (qreal start)
Span ()
Span (qreal start, qreal length)
Span (const Span &other)
qreal start () const
Detailed Description
A class representing a start point and a length.
Definition at line 234 of file kdganttglobal.h.
Constructor & Destructor Documentation
KDGantt::Span::Span ()
Definition at line 238 of file kdganttglobal.h.
KDGantt::Span::Span (qreal start, qreal length)
Definition at line 239 of file kdganttglobal.h.
KDGantt::Span::Span (const Span & other)
Definition at line 240 of file kdganttglobal.h.
Member Function Documentation
qreal KDGantt::Span::end () const
Definition at line 247 of file kdganttglobal.h.
Referenced by expandedTo(), and KDGantt::AbstractGrid::isSatisfiedConstraint().
bool KDGantt::Span::equals (const Span & other) const
Definition at line 254 of file kdganttglobal.h.
Referenced by KDGantt::operator!=(), and KDGantt::operator==().
Span KDGantt::Span::expandedTo (const Span & other) const
Definition at line 257 of file kdganttglobal.h.
References end(), and start().
bool KDGantt::Span::isValid () const
Definition at line 252 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
qreal KDGantt::Span::length () const
Definition at line 250 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE(), KDGantt::DateTimeGrid::mapFromChart(), operator<<(), KDGantt::DateTimeGrid::paintGrid(), and KDGantt::GraphicsItem::updateItem().
Span& KDGantt::Span::operator= (const Span & other)
Definition at line 242 of file kdganttglobal.h.
void KDGantt::Span::setEnd (qreal end)
Definition at line 246 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
void KDGantt::Span::setLength (qreal length)
Definition at line 249 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
void KDGantt::Span::setStart (qreal start)
Definition at line 244 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
qreal KDGantt::Span::start () const
Definition at line 245 of file kdganttglobal.h.
Referenced by expandedTo(), KDAB_SCOPED_UNITTEST_SIMPLE(), KDGantt::DateTimeGrid::mapFromChart(), operator<<(), KDGantt::DateTimeGrid::paintGrid(), and KDGantt::GraphicsItem::updateItem().
The documentation for this class was generated from the following file:
kdganttglobal.h
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/