KD Chart 2: KDGantt::DateTimeGrid Class Reference
KDGantt::DateTimeGrid Class Reference
#include <kdganttdatetimegrid.h>
Public Types
enum Scale {
ScaleAuto,
ScaleHour,
ScaleDay,
ScaleWeek,
ScaleMonth,
ScaleUserDefined
}
Public Slots
virtual void setModel (QAbstractItemModel *model)
virtual void setRootIndex (const QModelIndex &idx)
Signals
void gridChanged ()
Public Member Functions
DateTimeGrid ()
qreal dayWidth () const
QSet< Qt::DayOfWeek > freeDays () const
QBrush freeDaysBrush () const
bool isSatisfiedConstraint (const Constraint &c) const
bool mapFromChart (const Span &span, const QModelIndex &idx, const QList< Constraint > &constraints=QList< Constraint >()) const
QVariant mapFromChart (qreal x) const
qreal mapFromDateTime (const QDateTime &dt) const
Span mapToChart (const QModelIndex &idx) const
qreal mapToChart (const QVariant &value) const
QDateTime mapToDateTime (qreal x) const
QAbstractItemModel * model () const
QBrush noInformationBrush () const
void paintGrid (QPainter *painter, const QRectF &sceneRect, const QRectF &exposedRect, AbstractRowController *rowController=0, QWidget *widget=0)
void paintHeader (QPainter *painter, const QRectF &headerRect, const QRectF &exposedRect, qreal offset, QWidget *widget=0)
QModelIndex rootIndex () const
bool rowSeparators () const
Scale scale () const
void setDayWidth (qreal)
void setFreeDays (const QSet< Qt::DayOfWeek > &fd)
void setFreeDaysBrush (const QBrush brush)
void setNoInformationBrush (const QBrush &brush)
void setRowSeparators (bool enable)
void setScale (Scale s)
void setStartDateTime (const QDateTime &dt)
void setUserDefinedLowerScale (DateTimeScaleFormatter *lower)
void setUserDefinedUpperScale (DateTimeScaleFormatter *upper)
void setWeekStart (Qt::DayOfWeek)
QDateTime startDateTime () const
DateTimeScaleFormatter * userDefinedLowerScale () const
DateTimeScaleFormatter * userDefinedUpperScale () const
Qt::DayOfWeek weekStart () const
virtual ~DateTimeGrid ()
Protected Member Functions
QRectF computeRect (const QDateTime &from, const QDateTime &to, const QRectF &rect) const
Return the rectangle that represents the date-range.
QPair< QDateTime, QDateTime > dateTimeRange (const QRectF &rect) const
Return a date-range represented by the rectangle.
void drawBackground (QPainter *paint, const QRectF &rect)
virtual void drawDayBackground (QPainter *painter, const QRectF &rect, const QDate &date)
virtual void drawDayForeground (QPainter *painter, const QRectF &rect, const QDate &date)
void drawForeground (QPainter *paint, const QRectF &rect)
virtual void paintDayScaleHeader (QPainter *painter, const QRectF &headerRect, const QRectF &exposedRect, qreal offset, QWidget *widget=0)
virtual void paintHourScaleHeader (QPainter *painter, const QRectF &headerRect, const QRectF &exposedRect, qreal offset, QWidget *widget=0)
virtual void paintMonthScaleHeader (QPainter *painter, const QRectF &headerRect, const QRectF &exposedRect, qreal offset, QWidget *widget=0)
virtual void paintUserDefinedHeader (QPainter *painter, const QRectF &headerRect, const QRectF &exposedRect, qreal offset, const DateTimeScaleFormatter *formatter, QWidget *widget=0)
virtual void paintWeekScaleHeader (QPainter *painter, const QRectF &headerRect, const QRectF &exposedRect, qreal offset, QWidget *widget=0)
Detailed Description
This implementation of AbstractGrid works with QDateTime and shows days and week numbers in the header
Definition at line 35 of file kdganttdatetimegrid.h.
Member Enumeration Documentation
enum KDGantt::DateTimeGrid::Scale
Enumerator
ScaleAuto
ScaleHour
ScaleDay
ScaleWeek
ScaleMonth
ScaleUserDefined
Definition at line 40 of file kdganttdatetimegrid.h.
Constructor & Destructor Documentation
DateTimeGrid::DateTimeGrid ()
Definition at line 288 of file kdganttdatetimegrid.cpp.
DateTimeGrid::~DateTimeGrid () virtual
Definition at line 292 of file kdganttdatetimegrid.cpp.
Member Function Documentation
QRectF DateTimeGrid::computeRect (const QDateTime & from, const QDateTime & to, const QRectF & rect) const protected
Return the rectangle that represents the date-range.
Definition at line 1182 of file kdganttdatetimegrid.cpp.
References d.
QPair< QDateTime, QDateTime > DateTimeGrid::dateTimeRange (const QRectF & rect) const protected
Return a date-range represented by the rectangle.
Definition at line 1192 of file kdganttdatetimegrid.cpp.
References d.
qreal DateTimeGrid::dayWidth () const
Returns
The width in pixels for each day in the grid.
The default is 100 pixels.
Definition at line 320 of file kdganttdatetimegrid.cpp.
References d.
Referenced by drawBackground(), drawForeground(), paintDayScaleHeader(), paintGrid(), paintHourScaleHeader(), paintMonthScaleHeader(), and paintWeekScaleHeader().
void DateTimeGrid::drawBackground (QPainter * paint, const QRectF & rect) protected virtual
Todo:
document this function
Reimplemented from KDGantt::AbstractGrid.
Definition at line 1203 of file kdganttdatetimegrid.cpp.
References d, dayWidth(), and drawDayBackground().
void DateTimeGrid::drawDayBackground (QPainter * painter, const QRectF & rect, const QDate & date) protected virtual
Draw the background for a day.
Definition at line 1164 of file kdganttdatetimegrid.cpp.
Referenced by drawBackground().
void DateTimeGrid::drawDayForeground (QPainter * painter, const QRectF & rect, const QDate & date) protected virtual
Draw the foreground for a day.
Definition at line 1173 of file kdganttdatetimegrid.cpp.
Referenced by drawForeground().
void DateTimeGrid::drawForeground (QPainter * paint, const QRectF & rect) protected virtual
Todo:
document this function
Reimplemented from KDGantt::AbstractGrid.
Definition at line 1246 of file kdganttdatetimegrid.cpp.
References d, dayWidth(), and drawDayForeground().
QSet< Qt::DayOfWeek > DateTimeGrid::freeDays () const
Returns
The days marked as free in the grid.
Definition at line 453 of file kdganttdatetimegrid.cpp.
References d.
QBrush DateTimeGrid::freeDaysBrush () const
Returns
The brush used to paint free days.
Definition at line 468 of file kdganttdatetimegrid.cpp.
References d.
void KDGantt::AbstractGrid::gridChanged () signal inherited
Referenced by setDayWidth(), setFreeDays(), setNoInformationBrush(), setScale(), setStartDateTime(), setUserDefinedLowerScale(), setUserDefinedUpperScale(), and setWeekStart().
bool AbstractGrid::isSatisfiedConstraint (const Constraint & c) const inherited
Returns
true if the startpoint is before the endpoint of the constraint c.
Definition at line 86 of file kdganttabstractgrid.cpp.
References KDGantt::Span::end(), KDGantt::Constraint::endIndex(), KDGantt::AbstractGrid::mapToChart(), and KDGantt::Constraint::startIndex().
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE(), and mapFromChart().
bool DateTimeGrid::mapFromChart (const Span & span, const QModelIndex & idx, const QList< Constraint > & constraints = QList<Constraint>()) const virtual
Maps the supplied Span to QDateTimes, and puts them as start time and end time for the supplied index.
Parameters
span The span used to map from.
idx The index used for setting the start time and end time in the model.
constraints A list of hard constraints to match against the start time and end time mapped from the span.
Returns
true if the start time and time was successfully added to the model, or false if unsucessful. Also returns false if any of the constraints isn't satisfied. That is, if the start time of the constrained index is before the end time of the dependency index, or the end time of the constrained index is before the start time of the dependency index.
Implements KDGantt::AbstractGrid.
Definition at line 586 of file kdganttdatetimegrid.cpp.
References d, KDGantt::Constraint::endIndex(), KDGantt::EndTimeRole, KDGantt::AbstractGrid::isSatisfiedConstraint(), KDGantt::Span::length(), KDGantt::AbstractGrid::model(), KDGantt::Span::start(), KDGantt::Constraint::startIndex(), KDGantt::StartTimeRole, KDGantt::Constraint::type(), and KDGantt::Constraint::TypeHard.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
QVariant DateTimeGrid::mapFromChart (qreal x) const virtual
Parameters
x The x value get the datetime for.
Returns
The datetime corresponding to x or an invalid datetime if x cannot be mapped.
Reimplemented from KDGantt::AbstractGrid.
Definition at line 519 of file kdganttdatetimegrid.cpp.
References d.
qreal DateTimeGrid::mapFromDateTime (const QDateTime & dt) const
Maps a given point in time dt to an X value in the scene.
Definition at line 327 of file kdganttdatetimegrid.cpp.
References d.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
Span DateTimeGrid::mapToChart (const QModelIndex & idx) const virtual
Parameters
idx The index to get the Span for.
Returns
The start and end pixels, in a Span, of the specified index.
Implements KDGantt::AbstractGrid.
Definition at line 527 of file kdganttdatetimegrid.cpp.
References d, KDGantt::EndTimeRole, KDGantt::AbstractGrid::model(), and KDGantt::StartTimeRole.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
qreal DateTimeGrid::mapToChart (const QVariant & value) const virtual
Parameters
value The datetime to get the x value for.
Returns
The x value corresponding to value or -1.0 if value is not a datetime variant.
Reimplemented from KDGantt::AbstractGrid.
Definition at line 505 of file kdganttdatetimegrid.cpp.
References d.
QDateTime DateTimeGrid::mapToDateTime (qreal x) const
Maps a given X value x in scene coordinates to a point in time.
Definition at line 334 of file kdganttdatetimegrid.cpp.
References d.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
QAbstractItemModel * AbstractGrid::model () const inherited
Returns
The QAbstractItemModel used by this grid
Definition at line 64 of file kdganttabstractgrid.cpp.
References d.
Referenced by mapFromChart(), mapToChart(), and KDGantt::AbstractGrid::setModel().
QBrush DateTimeGrid::noInformationBrush () const
Returns
the brush used to mark rows with no information.
Definition at line 496 of file kdganttdatetimegrid.cpp.
References d.
void DateTimeGrid::paintDayScaleHeader (QPainter * painter, const QRectF & headerRect, const QRectF & exposedRect, qreal offset, QWidget * widget = 0) protected virtual
Paints the day scale header.
See also
paintHeader()
Definition at line 1049 of file kdganttdatetimegrid.cpp.
References d, and dayWidth().
Referenced by paintHeader().
void DateTimeGrid::paintGrid (QPainter * painter, const QRectF & sceneRect, const QRectF & exposedRect, AbstractRowController * rowController = 0, QWidget * widget = 0) virtual
Implement this to paint the background of the view – typically with some grid lines.
Parameters
painter – the QPainter to paint with.
sceneRect – the total bounding rectangle of the scene.
exposedRect – the rectangle that needs to be painted.
rowController – the row controller used by the view – may be 0.
widget – the widget used by the view – may be 0.
Implements KDGantt::AbstractGrid.
Definition at line 772 of file kdganttdatetimegrid.cpp.
References d, dayWidth(), KDGantt::AbstractRowController::indexAbove(), KDGantt::AbstractRowController::indexAt(), KDGantt::AbstractRowController::indexBelow(), KDGantt::ItemTypeRole, KDGantt::Span::length(), KDGantt::AbstractRowController::rowGeometry(), scale(), ScaleAuto, ScaleDay, ScaleHour, ScaleMonth, ScaleUserDefined, ScaleWeek, and KDGantt::Span::start().
void DateTimeGrid::paintHeader (QPainter * painter, const QRectF & headerRect, const QRectF & exposedRect, qreal offset, QWidget * widget = 0) virtual
Implement this to paint the header part of the view.
Parameters
painter – the QPainter to paint with.
headerRect – the total rectangle occupied by the header.
exposedRect – the rectangle that needs to be painted.
offset – the horizontal scroll offset of the view.
widget – the widget used by the view – may be 0.
Implements KDGantt::AbstractGrid.
Definition at line 873 of file kdganttdatetimegrid.cpp.
References d, paintDayScaleHeader(), paintHourScaleHeader(), paintMonthScaleHeader(), paintUserDefinedHeader(), paintWeekScaleHeader(), scale(), ScaleAuto, ScaleDay, ScaleHour, ScaleMonth, ScaleUserDefined, ScaleWeek, startDateTime(), and KDGantt::DateTimeScaleFormatter::text().
void DateTimeGrid::paintHourScaleHeader (QPainter * painter, const QRectF & headerRect, const QRectF & exposedRect, qreal offset, QWidget * widget = 0) protected virtual
Paints the hour scale header.
See also
paintHeader()
Definition at line 1008 of file kdganttdatetimegrid.cpp.
References d, and dayWidth().
Referenced by paintHeader().
void DateTimeGrid::paintMonthScaleHeader (QPainter * painter, const QRectF & headerRect, const QRectF & exposedRect, qreal offset, QWidget * widget = 0) protected virtual
Paints the week scale header.
See also
paintHeader()
Definition at line 1128 of file kdganttdatetimegrid.cpp.
References d, and dayWidth().
Referenced by paintHeader().
void DateTimeGrid::paintUserDefinedHeader (QPainter * painter, const QRectF & headerRect, const QRectF & exposedRect, qreal offset, const DateTimeScaleFormatter * formatter, QWidget * widget = 0) protected virtual
Definition at line 926 of file kdganttdatetimegrid.cpp.
References KDGantt::DateTimeScaleFormatter::alignment(), KDGantt::DateTimeScaleFormatter::currentRangeBegin(), d, KDGantt::DateTimeScaleFormatter::nextRangeBegin(), and KDGantt::DateTimeScaleFormatter::text().
Referenced by paintHeader().
void DateTimeGrid::paintWeekScaleHeader (QPainter * painter, const QRectF & headerRect, const QRectF & exposedRect, qreal offset, QWidget * widget = 0) protected virtual
Paints the week scale header.
See also
paintHeader()
Definition at line 1089 of file kdganttdatetimegrid.cpp.
References d, and dayWidth().
Referenced by paintHeader().
QModelIndex AbstractGrid::rootIndex () const inherited
Returns
the current root index for this grid
Definition at line 78 of file kdganttabstractgrid.cpp.
References d.
bool DateTimeGrid::rowSeparators () const
Returns
true if row separators are used.
Definition at line 474 of file kdganttdatetimegrid.cpp.
References d.
DateTimeGrid::Scale DateTimeGrid::scale () const
Returns
The scale used to paint the grid.
The default is ScaleAuto, which means the day scale will be used as long as the day width is less or equal to 500.
See also
Scale
Definition at line 376 of file kdganttdatetimegrid.cpp.
References d.
Referenced by paintGrid(), and paintHeader().
void DateTimeGrid::setDayWidth (qreal w)
Parameters
w The width in pixels for each day in the grid.
The signal gridChanged() is emitted after the day width is changed.
Definition at line 343 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
void DateTimeGrid::setFreeDays (const QSet< Qt::DayOfWeek > & fd)
Parameters
fd A set of days to mark as free in the grid.
Free days are filled with the alternate base brush of the palette used by the view. The signal gridChanged() is emitted after the free days are changed.
Definition at line 446 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
void DateTimeGrid::setFreeDaysBrush (const QBrush brush)
Sets the brush to use to paint free days.
Definition at line 460 of file kdganttdatetimegrid.cpp.
References d.
void AbstractGrid::setModel (QAbstractItemModel * model) virtual slot inherited
Sets the QAbstractItemModel used by this grid implementation. This is called by the view, you should never need to call this from client code.
Definition at line 58 of file kdganttabstractgrid.cpp.
References d, and KDGantt::AbstractGrid::model().
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
void DateTimeGrid::setNoInformationBrush (const QBrush & brush)
Sets the brush used to display rows where no data is found. Default is a red pattern. If set to QBrush() rows with no information will not be marked.
Definition at line 488 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
void AbstractGrid::setRootIndex (const QModelIndex & idx) virtual slot inherited
Sets the root index used by this grid implementation. This is called by the view, you should never need to call this from client code.
Definition at line 72 of file kdganttabstractgrid.cpp.
References d.
void DateTimeGrid::setRowSeparators (bool enable)
Parameters
enable Whether to use row separators or not.
Definition at line 479 of file kdganttdatetimegrid.cpp.
References d.
void DateTimeGrid::setScale (Scale s)
Parameters
s The scale to be used to paint the grid.
The signal gridChanged() is emitted after the scale has changed.
See also
Scale
Following example demonstrates how to change the format of the header to use a date-scaling with the header-label displayed with the ISO date-notation.
DateTimeScaleFormatter* formatter = new DateTimeScaleFormatter(DateTimeScaleFormatter::Day, QString::fromLatin1("yyyy-MMMM-dddd"));
grid->setUserDefinedUpperScale(formatter);
grid->setUserDefinedLowerScale(formatter);
grid->setScale(DateTimeGrid::ScaleUserDefined);
Definition at line 364 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
void DateTimeGrid::setStartDateTime (const QDateTime & dt)
Parameters
dt The start date of the grid. It is used as the beginning of the horizontal scrollbar in the view.
Emits gridChanged() after the start date has changed.
Definition at line 310 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
void DateTimeGrid::setUserDefinedLowerScale (DateTimeScaleFormatter * lower)
Sets the scale formatter for the lower part of the header to the user defined formatter to lower. The DateTimeGrid object takes ownership of the formatter, which has to be allocated with new.
You have to set the scale to ScaleUserDefined for this setting to take effect.
See also
DateTimeScaleFormatter
Definition at line 388 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
void DateTimeGrid::setUserDefinedUpperScale (DateTimeScaleFormatter * upper)
Sets the scale formatter for the upper part of the header to the user defined formatter to upper. The DateTimeGrid object takes ownership of the formatter, which has to be allocated with new.
You have to set the scale to ScaleUserDefined for this setting to take effect.
See also
DateTimeScaleFormatter
Definition at line 402 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
void DateTimeGrid::setWeekStart (Qt::DayOfWeek ws)
Parameters
ws The start day of the week.
A solid line is drawn on the grid to mark the beginning of a new week. Emits gridChanged() after the start day has changed.
Definition at line 428 of file kdganttdatetimegrid.cpp.
References d, and KDGantt::AbstractGrid::gridChanged().
QDateTime DateTimeGrid::startDateTime () const
Returns
The QDateTime used as start date for the grid.
The default is three days before the current date.
Definition at line 300 of file kdganttdatetimegrid.cpp.
References d.
Referenced by paintHeader().
DateTimeScaleFormatter * DateTimeGrid::userDefinedLowerScale () const
Returns
The DateTimeScaleFormatter being used to render the lower scale.
Definition at line 411 of file kdganttdatetimegrid.cpp.
References d.
DateTimeScaleFormatter * DateTimeGrid::userDefinedUpperScale () const
Returns
The DateTimeScaleFormatter being used to render the upper scale.
Definition at line 418 of file kdganttdatetimegrid.cpp.
References d.
Qt::DayOfWeek DateTimeGrid::weekStart () const
Returns
The start day of the week
Definition at line 435 of file kdganttdatetimegrid.cpp.
References d.
The documentation for this class was generated from the following files:
kdganttdatetimegrid.h
kdganttdatetimegrid.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/