KD Chart 2: KDChart::BarAttributes Class Reference
KDChart::BarAttributes Class Reference
Set of attributes for changing the appearance of bar charts.
#include <KDChartBarAttributes.h>
Public Member Functions
BarAttributes ()
BarAttributes (const BarAttributes &)
qreal barGapFactor () const
bool drawSolidExcessArrows () const
qreal fixedBarWidth () const
qreal fixedDataValueGap () const
qreal fixedValueBlockGap () const
qreal groupGapFactor () const
bool operator!= (const BarAttributes &other) const
BarAttributes & operator= (const BarAttributes &)
bool operator== (const BarAttributes &) const
void setBarGapFactor (qreal gapFactor)
void setDrawSolidExcessArrows (bool solidArrows)
void setFixedBarWidth (qreal width)
void setFixedDataValueGap (qreal gap)
void setFixedValueBlockGap (qreal gap)
void setGroupGapFactor (qreal gapFactor)
void setUseFixedBarWidth (bool useFixedBarWidth)
void setUseFixedDataValueGap (bool gapIsFixed)
void setUseFixedValueBlockGap (bool gapIsFixed)
bool useFixedBarWidth () const
bool useFixedDataValueGap () const
bool useFixedValueBlockGap () const
~BarAttributes ()
Detailed Description
Set of attributes for changing the appearance of bar charts.
Definition at line 34 of file KDChartBarAttributes.h.
Constructor & Destructor Documentation
BarAttributes() [1/2]
BarAttributes::BarAttributes ()
Definition at line 66 of file KDChartBarAttributes.cpp.
BarAttributes() [2/2]
BarAttributes::BarAttributes (const BarAttributes & r)
Definition at line 71 of file KDChartBarAttributes.cpp.
~BarAttributes()
BarAttributes::~BarAttributes ()
Definition at line 86 of file KDChartBarAttributes.cpp.
Member Function Documentation
barGapFactor()
qreal BarAttributes::barGapFactor () const
Definition at line 185 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
drawSolidExcessArrows()
bool BarAttributes::drawSolidExcessArrows () const
Definition at line 195 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
fixedBarWidth()
qreal BarAttributes::fixedBarWidth () const
Definition at line 154 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
fixedDataValueGap()
qreal BarAttributes::fixedDataValueGap () const
Definition at line 114 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
fixedValueBlockGap()
qreal BarAttributes::fixedValueBlockGap () const
Definition at line 134 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
groupGapFactor()
qreal BarAttributes::groupGapFactor () const
Definition at line 175 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
operator!=()
bool KDChart::BarAttributes::operator!= (const BarAttributes & other) const
Definition at line 71 of file KDChartBarAttributes.h.
References KDGantt::operator==().
operator=()
BarAttributes & BarAttributes::operator= (const BarAttributes & r)
Definition at line 76 of file KDChartBarAttributes.cpp.
References d.
operator==()
bool BarAttributes::operator== (const BarAttributes & r) const
Definition at line 92 of file KDChartBarAttributes.cpp.
References barGapFactor(), drawSolidExcessArrows(), fixedBarWidth(), fixedDataValueGap(), fixedValueBlockGap(), groupGapFactor(), useFixedBarWidth(), useFixedDataValueGap(), and useFixedValueBlockGap().
setBarGapFactor()
void BarAttributes::setBarGapFactor (qreal gapFactor)
Definition at line 180 of file KDChartBarAttributes.cpp.
References d.
setDrawSolidExcessArrows()
void BarAttributes::setDrawSolidExcessArrows (bool solidArrows)
Definition at line 190 of file KDChartBarAttributes.cpp.
References d.
setFixedBarWidth()
void BarAttributes::setFixedBarWidth (qreal width)
Definition at line 149 of file KDChartBarAttributes.cpp.
References d.
setFixedDataValueGap()
void BarAttributes::setFixedDataValueGap (qreal gap)
Definition at line 109 of file KDChartBarAttributes.cpp.
References d.
setFixedValueBlockGap()
void BarAttributes::setFixedValueBlockGap (qreal gap)
Definition at line 129 of file KDChartBarAttributes.cpp.
References d.
setGroupGapFactor()
void BarAttributes::setGroupGapFactor (qreal gapFactor)
Definition at line 170 of file KDChartBarAttributes.cpp.
References d.
setUseFixedBarWidth()
void BarAttributes::setUseFixedBarWidth (bool useFixedBarWidth)
Definition at line 160 of file KDChartBarAttributes.cpp.
References d, and useFixedBarWidth().
setUseFixedDataValueGap()
void BarAttributes::setUseFixedDataValueGap (bool gapIsFixed)
Definition at line 119 of file KDChartBarAttributes.cpp.
References d.
setUseFixedValueBlockGap()
void BarAttributes::setUseFixedValueBlockGap (bool gapIsFixed)
Definition at line 139 of file KDChartBarAttributes.cpp.
References d.
useFixedBarWidth()
bool BarAttributes::useFixedBarWidth () const
Definition at line 165 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==(), and setUseFixedBarWidth().
useFixedDataValueGap()
bool BarAttributes::useFixedDataValueGap () const
Definition at line 124 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
useFixedValueBlockGap()
bool BarAttributes::useFixedValueBlockGap () const
Definition at line 144 of file KDChartBarAttributes.cpp.
References d.
Referenced by operator==().
The documentation for this class was generated from the following files:
KDChartBarAttributes.h
KDChartBarAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/