KD Chart 2: KDChart::ReverseMapper Class Reference
KDChart::ReverseMapper Class Reference
The ReverseMapper stores information about objects on a chart and their respective model indexes.
#include <ReverseMapper.h>
Public Member Functions
void addCircle (int row, int column, const QPointF &location, const QSizeF &diameter)
void addItem (ChartGraphicsItem *item)
void addLine (int row, int column, const QPointF &from, const QPointF &to)
void addPolygon (int row, int column, const QPolygonF &polygon)
void addRect (int row, int column, const QRectF &rect)
QRectF boundingRect (int row, int column) const
void clear ()
QModelIndexList indexesAt (const QPointF &point) const
QModelIndexList indexesIn (const QRect &rect) const
QPolygonF polygon (int row, int column) const
ReverseMapper ()
ReverseMapper (AbstractDiagram *diagram)
void setDiagram (AbstractDiagram *diagram)
~ReverseMapper ()
Detailed Description
The ReverseMapper stores information about objects on a chart and their respective model indexes.
Definition at line 44 of file ReverseMapper.h.
Constructor & Destructor Documentation
ReverseMapper() [1/2]
ReverseMapper::ReverseMapper ()
Definition at line 38 of file ReverseMapper.cpp.
ReverseMapper() [2/2]
ReverseMapper::ReverseMapper (AbstractDiagram * diagram) explicit
Definition at line 44 of file ReverseMapper.cpp.
~ReverseMapper()
ReverseMapper::~ReverseMapper ()
Definition at line 50 of file ReverseMapper.cpp.
Member Function Documentation
addCircle()
void ReverseMapper::addCircle (int row, int column, const QPointF & location, const QSizeF & diameter)
Definition at line 142 of file ReverseMapper.cpp.
References addPolygon().
Referenced by addLine().
addItem()
void ReverseMapper::addItem (ChartGraphicsItem * item)
Definition at line 123 of file ReverseMapper.cpp.
References KDChart::ChartGraphicsItem::column(), and KDChart::ChartGraphicsItem::row().
Referenced by addPolygon().
addLine()
void ReverseMapper::addLine (int row, int column, const QPointF & from, const QPointF & to)
Definition at line 150 of file ReverseMapper.cpp.
References addCircle(), and addPolygon().
addPolygon()
void ReverseMapper::addPolygon (int row, int column, const QPolygonF & polygon)
Definition at line 135 of file ReverseMapper.cpp.
References addItem(), and polygon().
Referenced by addCircle(), addLine(), addRect(), and KDChart::PaintingHelpers::paintThreeDLines().
addRect()
void ReverseMapper::addRect (int row, int column, const QRectF & rect)
Definition at line 130 of file ReverseMapper.cpp.
References addPolygon().
boundingRect()
QRectF ReverseMapper::boundingRect (int row, int column) const
Definition at line 115 of file ReverseMapper.cpp.
clear()
void ReverseMapper::clear ()
Definition at line 61 of file ReverseMapper.cpp.
indexesAt()
QModelIndexList ReverseMapper::indexesAt (const QPointF & point) const
Definition at line 87 of file ReverseMapper.cpp.
References KDChart::ChartGraphicsItem::column(), and KDChart::ChartGraphicsItem::row().
indexesIn()
QModelIndexList ReverseMapper::indexesIn (const QRect & rect) const
Definition at line 68 of file ReverseMapper.cpp.
References KDChart::ChartGraphicsItem::column(), and KDChart::ChartGraphicsItem::row().
polygon()
QPolygonF ReverseMapper::polygon (int row, int column) const
Definition at line 107 of file ReverseMapper.cpp.
Referenced by addPolygon().
setDiagram()
void ReverseMapper::setDiagram (AbstractDiagram * diagram)
Definition at line 55 of file ReverseMapper.cpp.
The documentation for this class was generated from the following files:
ReverseMapper.h
ReverseMapper.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/