KD Chart 2: KDGantt::GraphicsItem Class Reference
KDGantt::GraphicsItem Class Reference
#include <kdganttgraphicsitem.h>
Public Types
enum { Type = UserType + 42 }
Public Member Functions
void addEndConstraint (ConstraintGraphicsItem *)
void addStartConstraint (ConstraintGraphicsItem *)
QRectF boundingRect () const
QList< ConstraintGraphicsItem * > endConstraints () const
virtual QString ganttToolTip () const
GraphicsItem (QGraphicsItem *parent=0, GraphicsScene *scene=0)
GraphicsItem (const QModelIndex &idx, QGraphicsItem *parent=0, GraphicsScene *scene=0)
const QPersistentModelIndex & index () const
bool isEditable () const
bool isUpdating () const
QVariant itemChange (GraphicsItemChange, const QVariant &value)
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
QRectF rect () const
void removeEndConstraint (ConstraintGraphicsItem *)
void removeStartConstraint (ConstraintGraphicsItem *)
GraphicsScene * scene () const
void setBoundingRect (const QRectF &r)
void setIndex (const QPersistentModelIndex &idx)
void setRect (const QRectF &r)
QList< ConstraintGraphicsItem * > startConstraints () const
int type () const
void updateItem (const Span &rowgeometry, const QPersistentModelIndex &idx)
virtual ~GraphicsItem ()
Protected Member Functions
void focusInEvent (QFocusEvent *event)
void hoverLeaveEvent (QGraphicsSceneHoverEvent *)
void hoverMoveEvent (QGraphicsSceneHoverEvent *)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *)
void mouseMoveEvent (QGraphicsSceneMouseEvent *)
void mousePressEvent (QGraphicsSceneMouseEvent *)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *)
Detailed Description
Definition at line 42 of file kdganttgraphicsitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 44 of file kdganttgraphicsitem.h.
Constructor & Destructor Documentation
GraphicsItem() [1/2]
GraphicsItem::GraphicsItem (QGraphicsItem * parent = 0, GraphicsScene * scene = 0) explicit
Definition at line 69 of file kdganttgraphicsitem.cpp.
GraphicsItem() [2/2]
GraphicsItem::GraphicsItem (const QModelIndex & idx, QGraphicsItem * parent = 0, GraphicsScene * scene = 0) explicit
Definition at line 75 of file kdganttgraphicsitem.cpp.
~GraphicsItem()
GraphicsItem::~GraphicsItem () virtual
Definition at line 101 of file kdganttgraphicsitem.cpp.
Member Function Documentation
addEndConstraint()
void GraphicsItem::addEndConstraint (ConstraintGraphicsItem * item)
Definition at line 264 of file kdganttgraphicsitem.cpp.
References KDGantt::ConstraintGraphicsItem::setEnd().
Referenced by KDGantt::GraphicsScene::insertItem().
addStartConstraint()
void GraphicsItem::addStartConstraint (ConstraintGraphicsItem * item)
Definition at line 256 of file kdganttgraphicsitem.cpp.
References KDGantt::ConstraintGraphicsItem::setStart().
Referenced by KDGantt::GraphicsScene::insertItem().
boundingRect()
QRectF GraphicsItem::boundingRect () const
Definition at line 218 of file kdganttgraphicsitem.cpp.
Referenced by mouseReleaseEvent(), and paint().
endConstraints()
QList<ConstraintGraphicsItem*> KDGantt::GraphicsItem::endConstraints () const
Definition at line 77 of file kdganttgraphicsitem.h.
Referenced by KDGantt::GraphicsScene::removeItem().
focusInEvent()
void GraphicsItem::focusInEvent (QFocusEvent * event) protected
Definition at line 364 of file kdganttgraphicsitem.cpp.
References index(), scene(), and KDGantt::GraphicsScene::selectionModel().
ganttToolTip()
QString GraphicsItem::ganttToolTip () const virtual
Definition at line 213 of file kdganttgraphicsitem.cpp.
References index(), KDGantt::GraphicsScene::itemDelegate(), scene(), and KDGantt::ItemDelegate::toolTip().
hoverLeaveEvent()
void GraphicsItem::hoverLeaveEvent (QGraphicsSceneHoverEvent *) protected
Definition at line 433 of file kdganttgraphicsitem.cpp.
hoverMoveEvent()
void GraphicsItem::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected
Definition at line 401 of file kdganttgraphicsitem.cpp.
References index(), KDGantt::ItemDelegate::interactionStateFor(), isEditable(), KDGantt::GraphicsScene::itemDelegate(), KDGantt::GraphicsScene::itemEntered(), scene(), KDGantt::ItemDelegate::State_ExtendLeft, KDGantt::ItemDelegate::State_ExtendRight, and KDGantt::ItemDelegate::State_Move.
index()
const QPersistentModelIndex& KDGantt::GraphicsItem::index () const
Definition at line 66 of file kdganttgraphicsitem.h.
Referenced by focusInEvent(), ganttToolTip(), hoverMoveEvent(), itemChange(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), and updateItem().
isEditable()
bool GraphicsItem::isEditable () const
Definition at line 190 of file kdganttgraphicsitem.cpp.
References KDGantt::GraphicsScene::isReadOnly(), and scene().
Referenced by hoverMoveEvent(), itemChange(), mouseMoveEvent(), and mouseReleaseEvent().
isUpdating()
bool KDGantt::GraphicsItem::isUpdating () const
Definition at line 70 of file kdganttgraphicsitem.h.
Referenced by itemChange().
itemChange()
QVariant GraphicsItem::itemChange (GraphicsItemChange change, const QVariant & value)
Definition at line 338 of file kdganttgraphicsitem.cpp.
References index(), isEditable(), isUpdating(), scene(), and KDGantt::GraphicsScene::selectionModel().
mouseDoubleClickEvent()
void GraphicsItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 526 of file kdganttgraphicsitem.cpp.
References index(), KDGantt::ItemDelegate::interactionStateFor(), KDGantt::GraphicsScene::itemDelegate(), KDGantt::GraphicsScene::itemDoubleClicked(), KDGantt::ItemTypeRole, scene(), KDGantt::ItemDelegate::State_None, and KDGantt::TypeSummary.
mouseMoveEvent()
void GraphicsItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 568 of file kdganttgraphicsitem.cpp.
References index(), isEditable(), rect(), scene(), KDGantt::GraphicsScene::selectionModel(), KDGantt::GraphicsScene::setDragSource(), KDGantt::ItemDelegate::State_DragConstraint, KDGantt::ItemDelegate::State_ExtendLeft, KDGantt::ItemDelegate::State_ExtendRight, and KDGantt::ItemDelegate::State_Move.
mousePressEvent()
void GraphicsItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 440 of file kdganttgraphicsitem.cpp.
References index(), KDGantt::ItemDelegate::interactionStateFor(), KDGantt::GraphicsScene::itemDelegate(), KDGantt::GraphicsScene::itemPressed(), scene(), KDGantt::ItemDelegate::State_ExtendLeft, KDGantt::ItemDelegate::State_ExtendRight, and KDGantt::ItemDelegate::State_None.
mouseReleaseEvent()
void GraphicsItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 466 of file kdganttgraphicsitem.cpp.
References KDGantt::GraphicsView::addConstraint(), boundingRect(), KDGantt::GraphicsScene::dragSource(), index(), isEditable(), KDGantt::GraphicsScene::itemClicked(), KDGantt::ItemTypeRole, rect(), scene(), KDGantt::GraphicsScene::setDragSource(), and KDGantt::TypeEvent.
paint()
void GraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
Definition at line 195 of file kdganttgraphicsitem.cpp.
References boundingRect(), index(), KDGantt::GraphicsScene::itemDelegate(), KDGantt::ItemDelegate::paintGanttItem(), and scene().
rect()
QRectF KDGantt::GraphicsItem::rect () const
Definition at line 60 of file kdganttgraphicsitem.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), updateItem(), and KDGantt::GraphicsScene::updateItems().
removeEndConstraint()
void GraphicsItem::removeEndConstraint (ConstraintGraphicsItem * item)
Definition at line 279 of file kdganttgraphicsitem.cpp.
removeStartConstraint()
void GraphicsItem::removeStartConstraint (ConstraintGraphicsItem * item)
Definition at line 272 of file kdganttgraphicsitem.cpp.
scene()
GraphicsScene * GraphicsItem::scene () const
Definition at line 163 of file kdganttgraphicsitem.cpp.
Referenced by focusInEvent(), ganttToolTip(), hoverMoveEvent(), isEditable(), itemChange(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paint(), and updateItem().
setBoundingRect()
void GraphicsItem::setBoundingRect (const QRectF & r)
Definition at line 183 of file kdganttgraphicsitem.cpp.
Referenced by updateItem().
setIndex()
void GraphicsItem::setIndex (const QPersistentModelIndex & idx)
Definition at line 207 of file kdganttgraphicsitem.cpp.
Referenced by updateItem(), and KDGantt::GraphicsScene::updateRow().
setRect()
void GraphicsItem::setRect (const QRectF & r)
Definition at line 168 of file kdganttgraphicsitem.cpp.
Referenced by updateItem().
startConstraints()
QList<ConstraintGraphicsItem*> KDGantt::GraphicsItem::startConstraints () const
Definition at line 76 of file kdganttgraphicsitem.h.
Referenced by KDGantt::GraphicsScene::removeItem().
type()
int GraphicsItem::type () const
Definition at line 121 of file kdganttgraphicsitem.cpp.
References Type.
updateItem()
void GraphicsItem::updateItem (const Span & rowgeometry, const QPersistentModelIndex & idx)
Definition at line 300 of file kdganttgraphicsitem.cpp.
References KDGantt::GraphicsScene::grid(), index(), KDGantt::ItemDelegate::itemBoundingSpan(), KDGantt::GraphicsScene::itemDelegate(), KDGantt::ItemTypeRole, KDGantt::Span::length(), KDGantt::AbstractRowController::maximumItemHeight(), rect(), KDGantt::GraphicsScene::rowController(), scene(), setBoundingRect(), setIndex(), setRect(), KDGantt::Span::start(), and KDGantt::TypeMulti.
Referenced by KDGantt::GraphicsScene::updateItems(), and KDGantt::GraphicsScene::updateRow().
The documentation for this class was generated from the following files:
kdganttgraphicsitem.h
kdganttgraphicsitem.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/