KD Chart 2: KDChart::LeveyJenningsDiagram Class Reference
KDChart::LeveyJenningsDiagram Class Reference
LeveyDiagram defines a Levey Jennings chart.
#include <KDChartLeveyJenningsDiagram.h>
Public Types
enum LineType {
Normal = 0,
Stacked = 1,
Percent = 2
}
enum Symbol {
OkDataPoint,
NotOkDataPoint,
LotChanged,
SensorChanged,
FluidicsPackChanged
}
Signals
void aboutToBeDestroyed ()
This signal is emitted when this diagram is being destroyed, but before all the data, i.e.
void attributesModelAboutToChange (AttributesModel *newModel, AttributesModel *oldModel)
This signal is emitted just before the new attributes model is connected internally.
void boundariesChanged ()
Emitted upon change of a data boundary.
void dataHidden ()
This signal is emitted, when the hidden status of at least one data cell was (un)set.
void layoutChanged (AbstractDiagram *)
Diagrams are supposed to emit this signal, when the layout of one of their element changes.
void modelDataChanged ()
This signal is emitted, when the model data is changed.
void modelsChanged ()
This signal is emitted when either the model or the AttributesModel is replaced.
void propertiesChanged ()
Emitted upon change of a property of the Diagram.
void viewportCoordinateSystemChanged ()
Emitted upon change of the view coordinate system.
Public Member Functions
virtual void addAxis (CartesianAxis *axis)
Add the axis to the diagram.
bool allowOverlappingDataValueTexts () const
bool antiAliasing () const
virtual AttributesModel * attributesModel () const
Returns the AttributesModel, that is used by this diagram.
virtual KDChart::CartesianAxisList axes () const
QBrush brush () const
Retrieve the brush to be used for painting datapoints globally.
QBrush brush (int dataset) const
Retrieve the brush to be used for the given dataset.
QBrush brush (const QModelIndex &index) const
Retrieve the brush to be used, for painting the datapoint at the given index in the model.
float calculatedMeanValue () const
Returns the calculated mean values over all QC values.
float calculatedStandardDeviation () const
Returns the calculated standard deviation over all QC values.
bool centerDataPoints () const
virtual LineDiagram * clone () const
Creates an exact copy of this diagram.
bool compare (const AbstractCartesianDiagram *other) const
Returns true if both diagrams have the same settings.
bool compare (const LineDiagram *other) const
Returns true if both diagrams have the same settings.
bool compare (const LeveyJenningsDiagram *other) const
Returns true if both diagrams have the same settings.
bool compare (const AbstractDiagram *other) const
Returns true if both diagrams have the same settings.
AbstractCoordinatePlane * coordinatePlane () const
The coordinate plane associated with the diagram.
const QPair< QPointF, QPointF > dataBoundaries () const
Return the bottom left and top right data point, that the diagram will display (unless the grid adjusts these values).
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
[reimplemented]
QList< QBrush > datasetBrushes () const
The set of dataset brushes currently used, for use in legends, etc.
int datasetDimension () const
The dataset dimension of a diagram determines how many value dimensions it expects each datapoint to have.
QStringList datasetLabels () const
The set of dataset labels currently displayed, for use in legends, etc.
QList< MarkerAttributes > datasetMarkers () const
The set of dataset markers currently used, for use in legends, etc.
QList< QPen > datasetPens () const
The set of dataset pens currently used, for use in legends, etc.
DataValueAttributes dataValueAttributes () const
Retrieve the DataValueAttributes specified globally.
DataValueAttributes dataValueAttributes (int dataset) const
Retrieve the DataValueAttributes for the given dataset.
DataValueAttributes dataValueAttributes (const QModelIndex &index) const
Retrieve the DataValueAttributes for the given index.
virtual void doItemsLayout ()
[reimplemented]
float expectedMeanValue () const
Returns the expected mean values over all QC values.
float expectedStandardDeviation () const
Returns the expected standard deviation over all QC values.
Qt::Alignment fluidicsPackChangedSymbolPosition () const
Returns the position of the fluidics pack changed symbol.
QVector< QDateTime > fluidicsPackChanges () const
Returns the list of all fluidics pack changes.
virtual int horizontalOffset () const
[reimplemented]
virtual QModelIndex indexAt (const QPoint &point) const
[reimplemented]
QModelIndexList indexesAt (const QPoint &point) const
This method is added alongside with indexAt from QAIM, since in kdchart multiple indexes can be displayed at the same spot.
QModelIndexList indexesIn (const QRect &rect) const
bool isHidden () const
Retrieve the hidden status specified globally.
bool isHidden (int dataset) const
Retrieve the hidden status for the given dataset.
bool isHidden (const QModelIndex &index) const
Retrieve the hidden status for the given index.
virtual bool isIndexHidden (const QModelIndex &index) const
[reimplemented]
QStringList itemRowLabels () const
The set of item row labels currently displayed, for use in Abscissa axes, etc.
virtual void layoutPlanes ()
Triggers layouting of all coordinate planes on the current chart.
LeveyJenningsDiagram (QWidget *parent=0, LeveyJenningsCoordinatePlane *plane=0)
LineAttributes lineAttributes () const
LineAttributes lineAttributes (int column) const
LineAttributes lineAttributes (const QModelIndex &index) const
Qt::Alignment lotChangedSymbolPosition () const
Returns the position of the lot change symbol.
virtual QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
[reimplemented]
const int numberOfAbscissaSegments () const
const int numberOfOrdinateSegments () const
void paintDataValueText (QPainter *painter, const QModelIndex &index, const QPointF &pos, qreal value)
virtual void paintMarker (QPainter *painter, const MarkerAttributes &markerAttributes, const QBrush &brush, const QPen &, const QPointF &point, const QSizeF &size)
void paintMarker (QPainter *painter, const DataValueAttributes &a, const QModelIndex &index, const QPointF &pos)
void paintMarker (QPainter *painter, const QModelIndex &index, const QPointF &pos)
QPen pen () const
Retrieve the pen to be used for painting datapoints globally.
QPen pen (int dataset) const
Retrieve the pen to be used for the given dataset.
QPen pen (const QModelIndex &index) const
Retrieve the pen to be used, for painting the datapoint at the given index in the model.
bool percentMode () const
Returns whether this diagram is drawn in percent mode.
virtual AbstractCartesianDiagram * referenceDiagram () const
virtual QPointF referenceDiagramOffset () const
void resetLineAttributes (int column)
Resets the line attributes of data set column.
void resetLineAttributes (const QModelIndex &index)
Remove any explicit line attributes settings that might have been specified before.
void resize (const QSizeF &area)
Called by the widget's sizeEvent.
bool reverseDatasetOrder () const
QPen scanLinePen () const
Returns the pen being used for drawing the scan line.
virtual void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
[reimplemented]
Qt::Alignment sensorChangedSymbolPosition () const
Returns the position of the sensor changed symbol.
QVector< QDateTime > sensorChanges () const
Returns the list of all sensor changes.
void setAllowOverlappingDataValueTexts (bool allow)
Set whether data value labels are allowed to overlap.
void setAntiAliasing (bool enabled)
Set whether anti-aliasing is to be used while rendering this diagram.
void setAttributesModel (AttributesModel *model)
Associate an AttributesModel with this diagram.
void setBrush (const QModelIndex &index, const QBrush &brush)
Set the brush to be used, for painting the datapoint at the given index.
void setBrush (int dataset, const QBrush &brush)
Set the brush to be used, for painting the given dataset.
void setBrush (const QBrush &brush)
Set the brush to be used, for painting all datasets in the model.
void setCenterDataPoints (bool center)
If centerDataPoints() is true, all data points are moved by an offset of 0.5 to the right.
virtual void setCoordinatePlane (AbstractCoordinatePlane *plane)
[reimplemented]
void setDatasetDimension (int dimension)
void setDataValueAttributes (const QModelIndex &index, const DataValueAttributes &a)
Set the DataValueAttributes for the given index.
void setDataValueAttributes (int dataset, const DataValueAttributes &a)
Set the DataValueAttributes for the given dataset.
void setDataValueAttributes (const DataValueAttributes &a)
Set the DataValueAttributes for all datapoints in the model.
void setExpectedMeanValue (float meanValue)
Sets the expected mean value over all QC values to meanValue.
void setExpectedStandardDeviation (float sd)
Sets the expected standard deviaction over all QC values to sd.
void setFluidicsPackChangedSymbolPosition (Qt::Alignment pos)
Sets the position of the fluidics pack changed symbol to pos.
void setFluidicsPackChanges (const QVector< QDateTime > &changes)
Sets the date/time of all fluidics pack changes to changes.
void setHidden (const QModelIndex &index, bool hidden)
Hide (or unhide, resp.) a data cell.
void setHidden (int dataset, bool hidden)
Hide (or unhide, resp.) a dataset.
void setHidden (bool hidden)
Hide (or unhide, resp.) all datapoints in the model.
void setLineAttributes (const LineAttributes &a)
Sets the global line attributes to la.
void setLineAttributes (int column, const LineAttributes &a)
Sets the line attributes of data set column to la.
void setLineAttributes (const QModelIndex &index, const LineAttributes &a)
Sets the line attributes for the model index index to la.
void setLotChangedSymbolPosition (Qt::Alignment pos)
Sets the position of the lot change symbol to pos.
void setModel (QAbstractItemModel *model)
Associate a model with the diagram.
void setPen (const QModelIndex &index, const QPen &pen)
Set the pen to be used, for painting the datapoint at the given index.
void setPen (int dataset, const QPen &pen)
Set the pen to be used, for painting the given dataset.
void setPen (const QPen &pen)
Set the pen to be used, for painting all datasets in the model.
void setPercentMode (bool percent)
Deprecated method that turns the percent mode of this diagram on or off.
virtual void setReferenceDiagram (AbstractCartesianDiagram *diagram, const QPointF &offset=QPointF())
Makes this diagram use another diagram diagram as reference diagram with relative offset offset.
void setReverseDatasetOrder (bool reverse)
With this property set to true, data sets in a normal line diagram are drawn in reversed order.
void setRootIndex (const QModelIndex &index)
Set the root index in the model, where the diagram starts referencing data for display.
void setScanLinePen (const QPen &pen)
Sets the pen used for drawing the scan line to pen.
virtual void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
[reimplemented]
virtual void setSelectionModel (QItemSelectionModel *selectionModel)
Associate a seleection model with the diagrom.
void setSensorChangedSymbolPosition (Qt::Alignment pos)
Sets the position of the sensor changed symbol to pos.
void setSensorChanges (const QVector< QDateTime > &changes)
Sets the date/time of all sensor changes to changes.
void setSymbol (Symbol symbol, const QString &filename)
Sets the symbol being used for symbol to a SVG file filename.
void setThreeDLineAttributes (const ThreeDLineAttributes &a)
Sets the global 3D line attributes to la.
void setThreeDLineAttributes (int column, const ThreeDLineAttributes &a)
Sets the 3D line attributes of data set column to ta.
void setThreeDLineAttributes (const QModelIndex &index, const ThreeDLineAttributes &a)
Sets the 3D line attributes of model index index to la.
void setTimeRange (const QPair< QDateTime, QDateTime > &timeRange)
Sets the timeRange visible on the x axis.
void setType (const LineType type)
Sets the line diagram's type to type.
void setUnitPrefix (const QString &prefix, int column, Qt::Orientation orientation)
Set the unit prefix to be used on axes for one specific column.
void setUnitPrefix (const QString &prefix, Qt::Orientation orientation)
Set the unit prefix to be used on axes for all columns.
void setUnitSuffix (const QString &suffix, int column, Qt::Orientation orientation)
Set the unit prefix to be used on axes for one specific column.
void setUnitSuffix (const QString &suffix, Qt::Orientation orientation)
Set the unit prefix to be used on axes for all columns.
void setValueTrackerAttributes (const QModelIndex &index, const ValueTrackerAttributes &a)
Sets the value tracker attributes of the model index index to va.
QString symbol (Symbol symbol) const
Returns the SVG file name usef for symbol.
virtual void takeAxis (CartesianAxis *axis)
Removes the axis from the diagram, without deleting it.
ThreeDLineAttributes threeDLineAttributes () const
ThreeDLineAttributes threeDLineAttributes (int column) const
ThreeDLineAttributes threeDLineAttributes (const QModelIndex &index) const
QPair< QDateTime, QDateTime > timeRange () const
Returns the timerange of the diagram's data.
LineType type () const
QString unitPrefix (int column, Qt::Orientation orientation, bool fallback=false) const
Retrieves the axis unit prefix for a specific column.
QString unitPrefix (Qt::Orientation orientation) const
Retrieves the axis unit prefix.
QString unitSuffix (int column, Qt::Orientation orientation, bool fallback=false) const
Retrieves the axis unit suffix for a specific column.
QString unitSuffix (Qt::Orientation orientation) const
Retrieves the axis unit suffix.
void update () const
void useDefaultColors ()
Set the palette to be used, for painting datasets to the default palette.
void useRainbowColors ()
Set the palette to be used, for painting datasets to the rainbow palette.
virtual bool usesExternalAttributesModel () const
Returns whether the diagram is using its own built-in attributes model or an attributes model that was set via setAttributesModel.
void useSubduedColors ()
Set the palette to be used, for painting datasets to the subdued palette.
ValueTrackerAttributes valueTrackerAttributes (const QModelIndex &index) const
Returns the value tracker attributes of the model index index.
virtual int verticalOffset () const
[reimplemented]
virtual QRect visualRect (const QModelIndex &index) const
[reimplemented]
virtual QRegion visualRegion (const QModelIndex &index) const
virtual QRegion visualRegionForSelection (const QItemSelection &selection) const
[reimplemented]
virtual ~LeveyJenningsDiagram ()
Protected Slots
void calculateMeanAndStandardDeviation () const
void connectAttributesModel (AttributesModel *)
void setDataBoundariesDirty () const
Protected Member Functions
QModelIndex attributesModelRootIndex () const
const QPair< QPointF, QPointF > calculateDataBoundaries () const
[reimplemented]
virtual bool checkInvariants (bool justReturnTheStatus=false) const
void drawChanges (PaintContext *paintContext)
Draws the fluidics pack and sensor changed symbols.
virtual void drawDataPointSymbol (PaintContext *paintContext, const QPointF &pos, bool ok)
Draws a data point symbol for the data point at pos.
virtual void drawFluidicsPackChangedSymbol (PaintContext *paintContext, const QPointF &pos)
Draws a fluidics pack changed symbol for the data point at pos.
virtual void drawLotChangeSymbol (PaintContext *paintContext, const QPointF &pos)
Draws a lot changed symbol for the data point at pos.
virtual void drawSensorChangedSymbol (PaintContext *paintContext, const QPointF &pos)
Draws a sensor changed symbol for the data point at pos.
virtual QRectF iconRect () const
Returns the rectangle being used for drawing the icons.
QSvgRenderer * iconRenderer (Symbol symbol)
Returns the SVG icon renderer for symbol.
void paint (PaintContext *paintContext)
[reimplemented]
virtual void paintDataValueTexts (QPainter *painter)
void paintEvent (QPaintEvent *)
virtual void paintMarkers (QPainter *painter)
void resizeEvent (QResizeEvent *)
void setAttributesModelRootIndex (const QModelIndex &)
void setDatasetDimensionInternal (int dimension)
virtual qreal threeDItemDepth (const QModelIndex &index) const
virtual qreal threeDItemDepth (int column) const
qreal valueForCell (int row, int column) const
Helper method, retrieving the data value (DisplayRole) for a given row and column.
Detailed Description
LeveyDiagram defines a Levey Jennings chart.
It provides different subtypes which are set using setType.
Definition at line 44 of file KDChartLeveyJenningsDiagram.h.
Member Enumeration Documentation
enum KDChart::LineDiagram::LineType inherited
Enumerator
Normal
Stacked
Percent
Definition at line 68 of file KDChartLineDiagram.h.
enum KDChart::LeveyJenningsDiagram::Symbol
Enumerator
OkDataPoint
NotOkDataPoint
LotChanged
SensorChanged
FluidicsPackChanged
Definition at line 60 of file KDChartLeveyJenningsDiagram.h.
Constructor & Destructor Documentation
LeveyJenningsDiagram::LeveyJenningsDiagram (QWidget * parent = 0, LeveyJenningsCoordinatePlane * plane = 0) explicit
Definition at line 52 of file KDChartLeveyJenningsDiagram.cpp.
Referenced by clone().
LeveyJenningsDiagram::~LeveyJenningsDiagram () virtual
Definition at line 81 of file KDChartLeveyJenningsDiagram.cpp.
Member Function Documentation
void KDChart::AbstractDiagram::aboutToBeDestroyed () signal inherited
This signal is emitted when this diagram is being destroyed, but before all the data, i.e.
the attributes model, is invalidated.
Referenced by KDChart::AbstractDiagram::~AbstractDiagram().
void AbstractCartesianDiagram::addAxis (CartesianAxis * axis) virtual inherited
Add the axis to the diagram.
The diagram takes ownership of the axis and will delete it.
To gain back ownership (e.g. for assigning the axis to another diagram) use the takeAxis method, before calling addAxis on the other diagram.
See also
takeAxis
Definition at line 84 of file KDChartAbstractCartesianDiagram.cpp.
References KDChart::AbstractAxis::createObserver(), d, and KDChart::AbstractCartesianDiagram::layoutPlanes().
bool AbstractDiagram::allowOverlappingDataValueTexts () const inherited
Returns
Whether data value labels are allowed to overlap.
Definition at line 372 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare().
bool AbstractDiagram::antiAliasing () const inherited
Returns
Whether anti-aliasing is to be used for rendering this diagram.
Definition at line 383 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), and KDChart::PaintingHelpers::paintThreeDLines().
AttributesModel * AbstractDiagram::attributesModel () const virtual inherited
Returns the AttributesModel, that is used by this diagram.
By default each diagram owns its own AttributesModel, which should never be deleted. Only if a user-supplied AttributesModel has been set does the pointer returned here not belong to the diagram.
Returns
The AttributesModel associated with the diagram.
See also
setAttributesModel
Definition at line 198 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::brush(), KDChart::AbstractDiagram::compare(), KDChart::Plotter::connectAttributesModel(), KDChart::AbstractDiagram::dataValueAttributes(), KDChart::AbstractDiagram::isHidden(), KDChart::AbstractDiagram::itemRowLabels(), KDChart::AbstractDiagram::pen(), KDChart::AbstractCartesianDiagram::setAttributesModel(), KDChart::BarDiagram::setBarAttributes(), KDChart::AbstractDiagram::setBrush(), KDChart::AbstractDiagram::setPen(), KDChart::AbstractCartesianDiagram::setRootIndex(), KDChart::Plotter::setUseDataCompression(), and KDChart::TernaryLineDiagram::TernaryLineDiagram().
void KDChart::AbstractDiagram::attributesModelAboutToChange (AttributesModel * newModel, AttributesModel * oldModel) signal inherited
This signal is emitted just before the new attributes model is connected internally.
It gives you a chance to connect to its signals first or perform other setup work.
QModelIndex AbstractDiagram::attributesModelRootIndex () const protected inherited
returns a QModelIndex pointing into the AttributesModel that corresponds to the root index of the diagram.
Definition at line 226 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::itemRowLabels(), KDChart::BarDiagram::numberOfAbscissaSegments(), KDChart::Plotter::numberOfAbscissaSegments(), KDChart::LineDiagram::numberOfAbscissaSegments(), KDChart::BarDiagram::numberOfOrdinateSegments(), KDChart::Plotter::numberOfOrdinateSegments(), KDChart::LineDiagram::numberOfOrdinateSegments(), and KDChart::AbstractDiagram::valueForCell().
KDChart::CartesianAxisList AbstractCartesianDiagram::axes () const virtual inherited
Returns
a list of all axes added to the diagram
Definition at line 103 of file KDChartAbstractCartesianDiagram.cpp.
References d.
Referenced by allAxisAnnotations(), checkExistingAxes(), findSharingAxisDiagrams(), KDChart::Widget::setType(), and KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
void KDChart::AbstractDiagram::boundariesChanged () signal inherited
Emitted upon change of a data boundary.
Referenced by KDChart::Plotter::connectAttributesModel(), and KDChart::Plotter::setType().
QBrush AbstractDiagram::brush () const inherited
Retrieve the brush to be used for painting datapoints globally.
This will fall back automatically to the default settings, if there are no specific settings.
Returns
The brush to use for painting.
Definition at line 709 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetBrushRole.
Referenced by KDChart::AbstractDiagram::brush(), KDChart::AbstractDiagram::datasetBrushes(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), KDChart::AbstractDiagram::paintMarker(), and KDChart::PaintingHelpers::paintThreeDLines().
QBrush AbstractDiagram::brush (int dataset) const inherited
Retrieve the brush to be used for the given dataset.
This will fall back automatically to what was set at model level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the brush for.
Returns
The brush to use for painting.
Definition at line 714 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), d, and KDChart::DatasetBrushRole.
QBrush AbstractDiagram::brush (const QModelIndex & index) const inherited
Retrieve the brush to be used, for painting the datapoint at the given index in the model.
Parameters
index The index of the datapoint in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
Returns
The brush to use for painting.
Definition at line 722 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetBrushRole.
const QPair< QPointF, QPointF > LeveyJenningsDiagram::calculateDataBoundaries () const protected virtual
[reimplemented]
Reimplemented from KDChart::LineDiagram.
Definition at line 424 of file KDChartLeveyJenningsDiagram.cpp.
References d, and timeRange().
float LeveyJenningsDiagram::calculatedMeanValue () const
Returns the calculated mean values over all QC values.
Definition at line 301 of file KDChartLeveyJenningsDiagram.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate().
float LeveyJenningsDiagram::calculatedStandardDeviation () const
Returns the calculated standard deviation over all QC values.
Definition at line 309 of file KDChartLeveyJenningsDiagram.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate().
void LeveyJenningsDiagram::calculateMeanAndStandardDeviation () const protected slot
Definition at line 357 of file KDChartLeveyJenningsDiagram.cpp.
References d.
Referenced by setModel().
bool LineDiagram::centerDataPoints () const inherited
Returns
option set by setCenterDataPoints()
Definition at line 164 of file KDChartLineDiagram.cpp.
References d.
Referenced by KDChart::LineDiagram::compare(), and referenceDiagramNeedsCenteredAbscissaTicks().
bool AbstractDiagram::checkInvariants (bool justReturnTheStatus = false) const protected virtual inherited
Definition at line 949 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::coordinatePlane().
Referenced by KDChart::RingDiagram::calculateDataBoundaries(), KDChart::PieDiagram::calculateDataBoundaries(), KDChart::RadarDiagram::calculateDataBoundaries(), KDChart::PolarDiagram::calculateDataBoundaries(), KDChart::BarDiagram::calculateDataBoundaries(), KDChart::Plotter::calculateDataBoundaries(), KDChart::LineDiagram::calculateDataBoundaries(), KDChart::RingDiagram::paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::BarDiagram::paint(), paint(), KDChart::Plotter::paint(), KDChart::LineDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), KDChart::AbstractDiagram::paintMarker(), and KDChart::AbstractDiagram::paintMarkers().
LineDiagram * LeveyJenningsDiagram::clone () const virtual
Creates an exact copy of this diagram.
Reimplemented from KDChart::LineDiagram.
Definition at line 88 of file KDChartLeveyJenningsDiagram.cpp.
References d, and LeveyJenningsDiagram().
bool AbstractCartesianDiagram::compare (const AbstractCartesianDiagram * other) const inherited
Returns true if both diagrams have the same settings.
Definition at line 40 of file KDChartAbstractCartesianDiagram.cpp.
References KDChart::AbstractCartesianDiagram::referenceDiagram(), and KDChart::AbstractCartesianDiagram::referenceDiagramOffset().
bool LineDiagram::compare (const LineDiagram * other) const inherited
Returns true if both diagrams have the same settings.
Definition at line 91 of file KDChartLineDiagram.cpp.
References KDChart::LineDiagram::centerDataPoints(), KDChart::LineDiagram::reverseDatasetOrder(), and KDChart::LineDiagram::type().
bool LeveyJenningsDiagram::compare (const LeveyJenningsDiagram * other) const
Returns true if both diagrams have the same settings.
Definition at line 94 of file KDChartLeveyJenningsDiagram.cpp.
bool AbstractDiagram::compare (const AbstractDiagram * other) const inherited
Returns true if both diagrams have the same settings.
Definition at line 69 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::allowOverlappingDataValueTexts(), KDChart::AbstractDiagram::antiAliasing(), KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::compare(), KDChart::AbstractDiagram::datasetDimension(), and KDChart::AbstractDiagram::percentMode().
void AbstractCartesianDiagram::connectAttributesModel (AttributesModel * newModel) protected slot inherited
Definition at line 185 of file KDChartAbstractCartesianDiagram.cpp.
References d.
Referenced by KDChart::Plotter::connectAttributesModel().
AbstractCoordinatePlane * AbstractDiagram::coordinatePlane () const inherited
The coordinate plane associated with the diagram.
This determines how coordinates in value space are mapped into pixel space. By default this is a CartesianCoordinatePlane.
Returns
The coordinate plane associated with the diagram.
Definition at line 113 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Plotter::calcMergeRadius(), KDChart::BarDiagram::calculateDataBoundaries(), KDChart::LineDiagram::calculateDataBoundaries(), KDChart::AbstractDiagram::checkInvariants(), KDChart::Plotter::connectAttributesModel(), iconRect(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), KDChart::AbstractDiagram::paintMarkers(), KDChart::AbstractPolarDiagram::polarCoordinatePlane(), KDChart::BarDiagram::resize(), KDChart::Plotter::resize(), and KDChart::LineDiagram::resize().
const QPair< QPointF, QPointF > AbstractDiagram::dataBoundaries () const inherited
Return the bottom left and top right data point, that the diagram will display (unless the grid adjusts these values).
This method returns a cached result of calculations done by calculateDataBoundaries. Classes derived from AbstractDiagram must implement the calculateDataBoundaries function, to specify their own way of calculating the data boundaries. If derived classes want to force recalculation of the data boundaries, they can call setDataBoundariesDirty()
Returned value is in diagram coordinates.
Definition at line 118 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::calculateDataBoundaries(), and d.
Referenced by KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::RadarDiagram::paint(), KDChart::BarDiagram::paint(), paint(), KDChart::Plotter::paint(), and KDChart::LineDiagram::paint().
void AbstractDiagram::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) virtual inherited
[reimplemented]
Definition at line 248 of file KDChartAbstractDiagram.cpp.
Referenced by setModel().
void KDChart::AbstractDiagram::dataHidden () signal inherited
This signal is emitted, when the hidden status of at least one data cell was (un)set.
Referenced by KDChart::AbstractDiagram::setHidden().
QList< QBrush > AbstractDiagram::datasetBrushes () const inherited
The set of dataset brushes currently used, for use in legends, etc.
Note
Cell-level override brushes, if set, take precedence over the dataset values, so you might need to check these too, in order to find the brush, that is used for a single cell.
Returns
The current set of dataset brushes.
Definition at line 910 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), and d.
Referenced by KDChart::Legend::datasetCount(), KDChart::Legend::removeDiagram(), and KDChart::Legend::setBrushesFromDiagram().
int AbstractDiagram::datasetDimension () const inherited
The dataset dimension of a diagram determines how many value dimensions it expects each datapoint to have.
For each dimension and data series it will expect one column of values in the model. If the dimension is 1, automatic values will be used for X.
For example, a diagram with the default dimension of 1 will have one column per data series (the Y values) and will use automatic values for X (1, 2, 3, ... n). If the dimension is 2, the diagram will use the first, (and the third, fifth, etc) columns as X values, and the second, (and the fourth, sixth, etc) column as Y values.
Returns
The dataset dimension of the diagram.
Definition at line 961 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare(), KDChart::CartesianCoordinatePlane::getDataDimensionsList(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::AbstractDiagram::paintDataValueTexts(), KDChart::AbstractDiagram::paintMarkers(), KDChart::Plotter::setType(), and KDChart::LineDiagram::setType().
QStringList AbstractDiagram::datasetLabels () const inherited
The set of dataset labels currently displayed, for use in legends, etc.
Returns
The set of dataset labels currently displayed.
Definition at line 897 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Legend::datasetCount().
QList< MarkerAttributes > AbstractDiagram::datasetMarkers () const inherited
The set of dataset markers currently used, for use in legends, etc.
Note
Cell-level override markers, if set, take precedence over the dataset values, so you might need to check these too, in order to find the marker, that is shown for a single cell.
Returns
The current set of dataset brushes.
Definition at line 936 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::DataValueAttributes::markerAttributes().
QList< QPen > AbstractDiagram::datasetPens () const inherited
The set of dataset pens currently used, for use in legends, etc.
Note
Cell-level override pens, if set, take precedence over the dataset values, so you might need to check these too, in order to find the pens, that is used for a single cell.
Returns
The current set of dataset pens.
Definition at line 923 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::pen().
Referenced by KDChart::Legend::removeDiagram().
DataValueAttributes AbstractDiagram::dataValueAttributes () const inherited
Retrieve the DataValueAttributes specified globally.
This will fall back automatically to the default settings, if there are no specific settings.
Returns
The global DataValueAttributes.
Definition at line 325 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DataValueLabelAttributesRole, and KDChart::AttributesModel::modelData().
Referenced by KDChart::AbstractDiagram::datasetMarkers(), KDChart::AbstractDiagram::dataValueAttributes(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::AbstractDiagram::paintMarker(), KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts(), and KDChart::TernaryLineDiagram::TernaryLineDiagram().
DataValueAttributes AbstractDiagram::dataValueAttributes (int dataset) const inherited
Retrieve the DataValueAttributes for the given dataset.
This will fall back automatically to what was set at model level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the attributes for.
Returns
The DataValueAttributes for the given dataset.
Definition at line 330 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::DataValueLabelAttributesRole.
DataValueAttributes AbstractDiagram::dataValueAttributes (const QModelIndex & index) const inherited
Retrieve the DataValueAttributes for the given index.
This will fall back automatically to what was set at dataset or model level, if there are no datapoint specific settings.
Parameters
index The datapoint to retrieve the attributes for. With a dataset dimension of two, this is the index of the key of each key/value pair.
Returns
The DataValueAttributes for the given index.
Definition at line 350 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DataValueLabelAttributesRole.
void AbstractDiagram::doItemsLayout () virtual inherited
[reimplemented]
Definition at line 238 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::drawChanges (PaintContext * paintContext) protected
Draws the fluidics pack and sensor changed symbols.
Definition at line 494 of file KDChartLeveyJenningsDiagram.cpp.
References d, drawFluidicsPackChangedSymbol(), drawSensorChangedSymbol(), and timeRange().
Referenced by paint().
void LeveyJenningsDiagram::drawDataPointSymbol (PaintContext * ctx, const QPointF & pos, bool ok) protected virtual
Draws a data point symbol for the data point at pos.
Parameters
ok True, when the data point is ok, false otherwise (different symbol)
ctx The PaintContext being used
Definition at line 641 of file KDChartLeveyJenningsDiagram.cpp.
References KDChart::PaintContext::coordinatePlane(), iconRect(), iconRenderer(), NotOkDataPoint, OkDataPoint, KDChart::PaintContext::painter(), KDChart::AbstractCoordinatePlane::translate(), and KDChart::LineDiagram::type().
Referenced by paint().
void LeveyJenningsDiagram::drawFluidicsPackChangedSymbol (PaintContext * ctx, const QPointF & pos) protected virtual
Draws a fluidics pack changed symbol for the data point at pos.
Parameters
ctx The PaintContext being used
See also
fluidicsPackChangedSymbolPosition
Definition at line 700 of file KDChartLeveyJenningsDiagram.cpp.
References KDChart::PaintContext::coordinatePlane(), d, FluidicsPackChanged, iconRect(), iconRenderer(), KDChart::PaintContext::painter(), and KDChart::AbstractCoordinatePlane::translate().
Referenced by drawChanges().
void LeveyJenningsDiagram::drawLotChangeSymbol (PaintContext * ctx, const QPointF & pos) protected virtual
Draws a lot changed symbol for the data point at pos.
Parameters
ctx The PaintContext being used
See also
lotChangedSymbolPosition
Definition at line 659 of file KDChartLeveyJenningsDiagram.cpp.
References KDChart::PaintContext::coordinatePlane(), d, iconRect(), iconRenderer(), LotChanged, KDChart::PaintContext::painter(), and KDChart::AbstractCoordinatePlane::translate().
Referenced by paint().
void LeveyJenningsDiagram::drawSensorChangedSymbol (PaintContext * ctx, const QPointF & pos) protected virtual
Draws a sensor changed symbol for the data point at pos.
Parameters
ctx The PaintContext being used
See also
sensorChangedSymbolPosition
Definition at line 680 of file KDChartLeveyJenningsDiagram.cpp.
References KDChart::PaintContext::coordinatePlane(), d, iconRect(), iconRenderer(), KDChart::PaintContext::painter(), SensorChanged, and KDChart::AbstractCoordinatePlane::translate().
Referenced by drawChanges().
float LeveyJenningsDiagram::expectedMeanValue () const
Returns the expected mean values over all QC values.
Definition at line 272 of file KDChartLeveyJenningsDiagram.cpp.
References d.
Referenced by paint(), and KDChart::LeveyJenningsAxis::paintAsOrdinate().
float LeveyJenningsDiagram::expectedStandardDeviation () const
Returns the expected standard deviation over all QC values.
Definition at line 293 of file KDChartLeveyJenningsDiagram.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate().
Qt::Alignment LeveyJenningsDiagram::fluidicsPackChangedSymbolPosition () const
Returns the position of the fluidics pack changed symbol.
Definition at line 146 of file KDChartLeveyJenningsDiagram.cpp.
References d.
QVector< QDateTime > LeveyJenningsDiagram::fluidicsPackChanges () const
Returns the list of all fluidics pack changes.
Definition at line 187 of file KDChartLeveyJenningsDiagram.cpp.
References d.
int AbstractDiagram::horizontalOffset () const virtual inherited
[reimplemented]
Definition at line 830 of file KDChartAbstractDiagram.cpp.
QRectF LeveyJenningsDiagram::iconRect () const protected virtual
Returns the rectangle being used for drawing the icons.
Definition at line 718 of file KDChartLeveyJenningsDiagram.cpp.
References KDChart::TextAttributes::calculatedFont(), KDChart::AbstractDiagram::coordinatePlane(), KDChartEnums::MeasureCalculationModeAuto, KDChartEnums::MeasureOrientationAuto, and KDChart::TextAttributes::setFontSize().
Referenced by drawDataPointSymbol(), drawFluidicsPackChangedSymbol(), drawLotChangeSymbol(), drawSensorChangedSymbol(), and paint().
QSvgRenderer * LeveyJenningsDiagram::iconRenderer (Symbol symbol) protected
Returns the SVG icon renderer for symbol.
Definition at line 731 of file KDChartLeveyJenningsDiagram.cpp.
References d, and symbol().
Referenced by drawDataPointSymbol(), drawFluidicsPackChangedSymbol(), drawLotChangeSymbol(), and drawSensorChangedSymbol().
QModelIndex AbstractDiagram::indexAt (const QPoint & point) const virtual inherited
[reimplemented]
Definition at line 1002 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::Chart::event().
QModelIndexList AbstractDiagram::indexesAt (const QPoint & point) const inherited
This method is added alongside with indexAt from QAIM, since in kdchart multiple indexes can be displayed at the same spot.
Definition at line 1007 of file KDChartAbstractDiagram.cpp.
References d.
QModelIndexList AbstractDiagram::indexesIn (const QRect & rect) const inherited
Definition at line 1012 of file KDChartAbstractDiagram.cpp.
References d.
bool AbstractDiagram::isHidden () const inherited
Retrieve the hidden status specified globally.
This will fall back automatically to the default settings (= not hidden), if there are no specific settings.
Returns
The global hidden status.
Definition at line 285 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DataHiddenRole, and KDChart::AttributesModel::modelData().
Referenced by KDChart::AbstractDiagram::isHidden().
bool AbstractDiagram::isHidden (int dataset) const inherited
Retrieve the hidden status for the given dataset.
This will fall back automatically to what was set at diagram level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the hidden status for.
Returns
The hidden status for the given dataset.
Definition at line 290 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataHiddenRole, and KDChart::AbstractDiagram::isHidden().
bool AbstractDiagram::isHidden (const QModelIndex & index) const inherited
Retrieve the hidden status for the given index.
This will fall back automatically to what was set at dataset or diagram level, if there are no datapoint specific settings.
Parameters
index The datapoint to retrieve the hidden status for.
Returns
The hidden status for the given index.
Definition at line 298 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), d, KDChart::DataHiddenRole, and KDChart::AbstractDiagram::isHidden().
bool AbstractDiagram::isIndexHidden (const QModelIndex & index) const virtual inherited
[reimplemented]
Definition at line 836 of file KDChartAbstractDiagram.cpp.
QStringList AbstractDiagram::itemRowLabels () const inherited
The set of item row labels currently displayed, for use in Abscissa axes, etc.
Returns
The set of item row labels currently displayed.
Definition at line 881 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AbstractDiagram::attributesModelRootIndex(), KDChart::AttributesModel::headerData(), KDChart::AttributesModel::rowCount(), KDChart::AbstractDiagram::unitPrefix(), and KDChart::AbstractDiagram::unitSuffix().
void KDChart::AbstractDiagram::layoutChanged (AbstractDiagram *) signal inherited
Diagrams are supposed to emit this signal, when the layout of one of their element changes.
Layouts can change, for example, when axes are added or removed, or when the configuration was changed in a way that the axes or the diagram itself are displayed in a different geometry. Changes in the diagrams coordinate system also result in the layoutChanged() signal being emitted.
Referenced by KDChart::LineDiagram::setCenterDataPoints(), KDChart::AbstractDiagram::setDatasetDimensionInternal(), setModel(), KDChart::AbstractPieDiagram::setPieAttributes(), KDChart::BarDiagram::setThreeDBarAttributes(), KDChart::AbstractPieDiagram::setThreeDPieAttributes(), KDChart::Plotter::setType(), and KDChart::LineDiagram::setType().
void KDChart::AbstractCartesianDiagram::layoutPlanes () virtual inherited
Triggers layouting of all coordinate planes on the current chart.
Normally you don't need to call this method. It's handled automatically for you.
Definition at line 108 of file KDChartAbstractCartesianDiagram.cpp.
References KDChart::AbstractCoordinatePlane::layoutPlanes().
Referenced by KDChart::AbstractCartesianDiagram::addAxis(), and KDChart::AbstractCartesianDiagram::takeAxis().
LineAttributes LineDiagram::lineAttributes () const inherited
Returns
the global line attribute set
Definition at line 237 of file KDChartLineDiagram.cpp.
References d, and KDChart::LineAttributesRole.
Referenced by KDChart::LineDiagram::lineAttributes().
LineAttributes LineDiagram::lineAttributes (int column) const inherited
Returns
the line attribute set of data set column
Definition at line 245 of file KDChartLineDiagram.cpp.
References d, KDChart::LineDiagram::lineAttributes(), and KDChart::LineAttributesRole.
LineAttributes LineDiagram::lineAttributes (const QModelIndex & index) const inherited
Returns
the line attribute set of the model index index
Definition at line 256 of file KDChartLineDiagram.cpp.
References d, and KDChart::LineAttributesRole.
Qt::Alignment LeveyJenningsDiagram::lotChangedSymbolPosition () const
Returns the position of the lot change symbol.
Definition at line 125 of file KDChartLeveyJenningsDiagram.cpp.
References d.
void KDChart::AbstractDiagram::modelDataChanged () signal inherited
This signal is emitted, when the model data is changed.
void KDChart::AbstractDiagram::modelsChanged () signal inherited
This signal is emitted when either the model or the AttributesModel is replaced.
Referenced by KDChart::AbstractDiagram::setAttributesModel(), KDChart::AbstractDiagram::setModel(), and KDChart::AbstractDiagram::setSelectionModel().
QModelIndex AbstractDiagram::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) virtual inherited
[reimplemented]
Definition at line 827 of file KDChartAbstractDiagram.cpp.
const int LineDiagram::numberOfAbscissaSegments () const virtual inherited
Implements KDChart::AbstractCartesianDiagram.
Definition at line 426 of file KDChartLineDiagram.cpp.
References KDChart::AbstractDiagram::attributesModelRootIndex(), and d.
const int LineDiagram::numberOfOrdinateSegments () const virtual inherited
Implements KDChart::AbstractCartesianDiagram.
Definition at line 434 of file KDChartLineDiagram.cpp.
References KDChart::AbstractDiagram::attributesModelRootIndex(), and d.
void LeveyJenningsDiagram::paint (PaintContext * paintContext) protected virtual
[reimplemented]
Implements KDChart::AbstractDiagram.
Definition at line 514 of file KDChartLeveyJenningsDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::PaintContext::coordinatePlane(), d, KDChart::AbstractDiagram::dataBoundaries(), drawChanges(), drawDataPointSymbol(), drawLotChangeSymbol(), expectedMeanValue(), iconRect(), KDChart::PaintContext::painter(), KDChart::AbstractDiagram::pen(), KDChart::PaintContext::setCoordinatePlane(), KDChart::AbstractCoordinatePlane::sharedAxisMasterPlane(), timeRange(), and KDChart::AbstractCoordinatePlane::translate().
void AbstractDiagram::paintDataValueText (QPainter * painter, const QModelIndex & index, const QPointF & pos, qreal value) inherited
Definition at line 400 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::paintDataValueTexts().
void AbstractDiagram::paintDataValueTexts (QPainter * painter) protected virtual inherited
Deprecated:
This method is deprecated and provided for backward-compatibility only. Your own diagram classes should call d->paintDataValueTextsAndMarkers() instead which also is taking care for showing your cell-specific comments, if any,
Definition at line 409 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractDiagram::coordinatePlane(), d, KDChart::AbstractDiagram::datasetDimension(), KDChart::AbstractDiagram::paintDataValueText(), and translate().
void LineDiagram::paintEvent (QPaintEvent *) protected inherited
Definition at line 386 of file KDChartLineDiagram.cpp.
References KDChart::LineDiagram::paint(), KDChart::PaintContext::setPainter(), and KDChart::PaintContext::setRectangle().
void AbstractDiagram::paintMarker (QPainter * painter, const MarkerAttributes & markerAttributes, const QBrush & brush, const QPen & pen, const QPointF & point, const QSizeF & size) virtual inherited
Definition at line 472 of file KDChartAbstractDiagram.cpp.
References KDChart::MarkerAttributes::customMarkerPath(), KDChart::MarkerAttributes::Marker1Pixel, KDChart::MarkerAttributes::Marker4Pixels, KDChart::MarkerAttributes::MarkerCircle, KDChart::MarkerAttributes::MarkerCross, KDChart::MarkerAttributes::MarkerDiamond, KDChart::MarkerAttributes::MarkerFastCross, KDChart::MarkerAttributes::MarkerRing, KDChart::MarkerAttributes::MarkerSquare, KDChart::MarkerAttributes::markerStyle(), KDChart::MarkerAttributes::NoMarker, KDChart::MarkerAttributes::PainterPathMarker, KDChart::PrintingParameters::scalePen(), and KDChart::MarkerAttributes::threeD().
Referenced by KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::MarkerLayoutItem::paintIntoRect(), KDChart::AbstractDiagram::paintMarker(), and KDChart::AbstractDiagram::paintMarkers().
void AbstractDiagram::paintMarker (QPainter * painter, const DataValueAttributes & a, const QModelIndex & index, const QPointF & pos) inherited
Definition at line 436 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::brush(), KDChart::AbstractDiagram::checkInvariants(), d, KDChart::MarkerAttributes::isVisible(), KDChart::DataValueAttributes::isVisible(), KDChart::DataValueAttributes::markerAttributes(), KDChart::MarkerAttributes::markerColor(), KDChart::MarkerAttributes::markerSize(), KDChart::AbstractDiagram::paintMarker(), and KDChart::MarkerAttributes::pen().
void AbstractDiagram::paintMarker (QPainter * painter, const QModelIndex & index, const QPointF & pos) inherited
Definition at line 464 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractDiagram::dataValueAttributes(), and KDChart::AbstractDiagram::paintMarker().
void AbstractDiagram::paintMarkers (QPainter * painter) protected virtual inherited
Deprecated:
This method is deprecated and provided for backward-compatibility only. Your own diagram classes should call d->paintDataValueTextsAndMarkers() instead which also is taking care for showing your cell-specific comments, if any,
Definition at line 621 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::checkInvariants(), KDChart::AbstractDiagram::coordinatePlane(), KDChart::AbstractDiagram::datasetDimension(), KDChart::AbstractDiagram::paintMarker(), and translate().
QPen AbstractDiagram::pen () const inherited
Retrieve the pen to be used for painting datapoints globally.
This will fall back automatically to the default settings, if there are no specific settings.
Returns
The pen to use for painting.
Definition at line 668 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetPenRole.
Referenced by KDChart::AbstractDiagram::datasetPens(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), paint(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), KDChart::PaintingHelpers::paintThreeDLines(), KDChart::AbstractDiagram::pen(), and setScanLinePen().
QPen AbstractDiagram::pen (int dataset) const inherited
Retrieve the pen to be used for the given dataset.
This will fall back automatically to what was set at model level, if there are no dataset specific settings.
Parameters
dataset The dataset to retrieve the pen for.
Returns
The pen to use for painting.
Definition at line 673 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DatasetPenRole, and KDChart::AbstractDiagram::pen().
QPen AbstractDiagram::pen (const QModelIndex & index) const inherited
Retrieve the pen to be used, for painting the datapoint at the given index in the model.
Parameters
index The index of the datapoint in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
Returns
The pen to use for painting.
Definition at line 681 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::AttributesModel::data(), and KDChart::DatasetPenRole.
bool AbstractDiagram::percentMode () const inherited
Returns whether this diagram is drawn in percent mode.
If true, all data points in the same column of a diagram will be be drawn at the same X coordinate and stacked up so that the distance from the last data point (or the zero line) to a data point P is always the ratio of (Y-Value of P)/ (sum of all Y-Values in same column as P) relative to the diagrams height (or width, if abscissa and ordinate are swapped).
Note that this property is not applicable to all diagram types.
Definition at line 394 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::compare().
void KDChart::AbstractDiagram::propertiesChanged () signal inherited
Emitted upon change of a property of the Diagram.
Referenced by KDChart::Plotter::resetLineAttributes(), KDChart::LineDiagram::resetLineAttributes(), KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts(), KDChart::AbstractDiagram::setAntiAliasing(), KDChart::BarDiagram::setBarAttributes(), KDChart::AbstractDiagram::setBrush(), KDChart::LineDiagram::setCenterDataPoints(), KDChart::AbstractDiagram::setDataValueAttributes(), KDChart::Plotter::setLineAttributes(), KDChart::LineDiagram::setLineAttributes(), KDChart::AbstractDiagram::setPen(), KDChart::AbstractDiagram::setPercentMode(), KDChart::BarDiagram::setThreeDBarAttributes(), KDChart::Plotter::setThreeDLineAttributes(), KDChart::LineDiagram::setThreeDLineAttributes(), KDChart::Plotter::setType(), KDChart::LineDiagram::setType(), KDChart::Plotter::setValueTrackerAttributes(), and KDChart::LineDiagram::setValueTrackerAttributes().
AbstractCartesianDiagram * AbstractCartesianDiagram::referenceDiagram () const virtual inherited
Returns
this diagram's reference diagram
See also
setReferenceDiagram
Definition at line 153 of file KDChartAbstractCartesianDiagram.cpp.
References d.
Referenced by KDChart::AbstractCartesianDiagram::compare(), KDChart::CartesianCoordinatePlane::getDataDimensionsList(), referenceDiagramIsBarDiagram(), and referenceDiagramNeedsCenteredAbscissaTicks().
QPointF AbstractCartesianDiagram::referenceDiagramOffset () const virtual inherited
Returns
the relative offset of this diagram's reference diagram
See also
setReferenceDiagram
Definition at line 158 of file KDChartAbstractCartesianDiagram.cpp.
References d.
Referenced by KDChart::AbstractCartesianDiagram::compare().
void LineDiagram::resetLineAttributes (int column) inherited
Resets the line attributes of data set column.
Definition at line 204 of file KDChartLineDiagram.cpp.
References d, KDChart::LineAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void LineDiagram::resetLineAttributes (const QModelIndex & index) inherited
Remove any explicit line attributes settings that might have been specified before.
Definition at line 227 of file KDChartLineDiagram.cpp.
References d, KDChart::LineAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void LineDiagram::resize (const QSizeF & area) virtual inherited
Called by the widget's sizeEvent.
Adjust all internal structures, that are calculated, dependending on the size of the widget.
Parameters
area
Implements KDChart::AbstractDiagram.
Definition at line 415 of file KDChartLineDiagram.cpp.
References KDChart::AbstractDiagram::coordinatePlane(), d, KDChart::AbstractDiagram::setDataBoundariesDirty(), KDChart::AbstractCoordinatePlane::zoomFactorX(), and KDChart::AbstractCoordinatePlane::zoomFactorY().
void LineDiagram::resizeEvent (QResizeEvent *) protected inherited
Definition at line 366 of file KDChartLineDiagram.cpp.
bool LineDiagram::reverseDatasetOrder () const inherited
See also
setReverseDatasetOrder
Definition at line 174 of file KDChartLineDiagram.cpp.
References d.
Referenced by KDChart::LineDiagram::compare().
QPen LeveyJenningsDiagram::scanLinePen () const
Returns the pen being used for drawing the scan line.
Definition at line 219 of file KDChartLeveyJenningsDiagram.cpp.
References d.
void AbstractDiagram::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) virtual inherited
[reimplemented]
Definition at line 822 of file KDChartAbstractDiagram.cpp.
Qt::Alignment LeveyJenningsDiagram::sensorChangedSymbolPosition () const
Returns the position of the sensor changed symbol.
Definition at line 167 of file KDChartLeveyJenningsDiagram.cpp.
References d.
QVector< QDateTime > LeveyJenningsDiagram::sensorChanges () const
Returns the list of all sensor changes.
Definition at line 251 of file KDChartLeveyJenningsDiagram.cpp.
References d.
void AbstractDiagram::setAllowOverlappingDataValueTexts (bool allow) inherited
Set whether data value labels are allowed to overlap.
Parameters
allow True means that overlapping labels are allowed.
Definition at line 363 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataValueAttributes(), KDChart::AbstractDiagram::propertiesChanged(), KDChart::AbstractDiagram::setDataValueAttributes(), and KDChart::DataValueAttributes::setShowOverlappingDataLabels().
void AbstractDiagram::setAntiAliasing (bool enabled) inherited
Set whether anti-aliasing is to be used while rendering this diagram.
Parameters
enabled True means that AA is enabled.
Definition at line 377 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::propertiesChanged().
void AbstractCartesianDiagram::setAttributesModel (AttributesModel * amodel) virtual inherited
Associate an AttributesModel with this diagram.
Note that the diagram does not take ownership of the AttributesModel. This should thus only be used with AttributesModels that have been explicitly created by the user, and are owned by her. Setting an AttributesModel that is internal to another diagram is an error.
Correct:
AttributesModel *am = new AttributesModel(model, 0);
diagram1->setAttributesModel(am);
diagram2->setAttributesModel(am);
Wrong:
diagram1->setAttributesModel(diagram2->attributesModel());
Parameters
model The AttributesModel to use for this diagram.
See also
AttributesModel, usesExternalAttributesModel
Sets an external AttributesModel on this diagram. By default, a diagram has it's own internal set of attributes, but an external one can be set. This can be used to share attributes between several diagrams. The diagram does not take ownership of the attributesmodel.
Parameters
amodel The AttributesModel to use for this diagram.
Reimplemented from KDChart::AbstractDiagram.
Definition at line 177 of file KDChartAbstractCartesianDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), and KDChart::AbstractDiagram::setAttributesModel().
void AbstractDiagram::setAttributesModelRootIndex (const QModelIndex & idx) protected inherited
Definition at line 217 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::setDataBoundariesDirty().
Referenced by KDChart::AbstractDiagram::setRootIndex().
void AbstractDiagram::setBrush (const QModelIndex & index, const QBrush & brush) inherited
Set the brush to be used, for painting the datapoint at the given index.
Parameters
index The datapoint's index in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
brush The brush to use.
Definition at line 688 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DatasetBrushRole, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setData().
void AbstractDiagram::setBrush (int dataset, const QBrush & brush) inherited
Set the brush to be used, for painting the given dataset.
Parameters
dataset The dataset to set the brush for.
brush The brush to use.
Definition at line 703 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DatasetBrushRole, and KDChart::AbstractDiagram::propertiesChanged().
void AbstractDiagram::setBrush (const QBrush & brush) inherited
Set the brush to be used, for painting all datasets in the model.
Parameters
brush The brush to use.
Definition at line 696 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DatasetBrushRole, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setModelData().
void LineDiagram::setCenterDataPoints (bool center) inherited
If centerDataPoints() is true, all data points are moved by an offset of 0.5 to the right.
This is useful in conjunction with bar diagrams, since data points are then centered just like bars.
See also
centerDataPoints()
Definition at line 149 of file KDChartLineDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AbstractDiagram::setDataBoundariesDirty().
void KDChart::AbstractCartesianDiagram::setCoordinatePlane (AbstractCoordinatePlane * plane) virtual inherited
[reimplemented]
Reimplemented from KDChart::AbstractDiagram.
Definition at line 116 of file KDChartAbstractCartesianDiagram.cpp.
References KDChart::AbstractDiagram::setCoordinatePlane().
void AbstractDiagram::setDataBoundariesDirty () const protected slot inherited
Definition at line 127 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
Referenced by KDChart::BarDiagram::resize(), KDChart::LineDiagram::resize(), KDChart::AbstractDiagram::setAttributesModel(), KDChart::AbstractDiagram::setAttributesModelRootIndex(), KDChart::LineDiagram::setCenterDataPoints(), KDChart::Plotter::setDataBoundariesDirty(), KDChart::AbstractDiagram::setDatasetDimensionInternal(), KDChart::AbstractDiagram::setModel(), KDChart::BarDiagram::setThreeDBarAttributes(), KDChart::LineDiagram::setThreeDLineAttributes(), and KDChart::LineDiagram::setType().
void AbstractDiagram::setDatasetDimension (int dimension) inherited
Deprecated:
Sets the dataset dimension of the diagram. Using this method is deprecated. Use the specific diagram types instead.
Definition at line 966 of file KDChartAbstractDiagram.cpp.
void AbstractDiagram::setDatasetDimensionInternal (int dimension) protected inherited
Definition at line 973 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::layoutChanged(), and KDChart::AbstractDiagram::setDataBoundariesDirty().
Referenced by KDChart::TernaryLineDiagram::TernaryLineDiagram(), and KDChart::TernaryPointDiagram::TernaryPointDiagram().
void AbstractDiagram::setDataValueAttributes (const QModelIndex & index, const DataValueAttributes & a) inherited
Set the DataValueAttributes for the given index.
Parameters
index The datapoint to set the attributes for. With a dataset dimension of two, this is the index of the key of each key/value pair.
a The attributes to set.
Definition at line 310 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataValueLabelAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
Referenced by KDChart::AbstractDiagram::setAllowOverlappingDataValueTexts().
void AbstractDiagram::setDataValueAttributes (int dataset, const DataValueAttributes & a) inherited
Set the DataValueAttributes for the given dataset.
Parameters
dataset The dataset to set the attributes for.
a The attributes to set.
Definition at line 319 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataValueLabelAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void AbstractDiagram::setDataValueAttributes (const DataValueAttributes & a) inherited
Set the DataValueAttributes for all datapoints in the model.
Parameters
a The attributes to set.
Definition at line 357 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DataValueLabelAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void LeveyJenningsDiagram::setExpectedMeanValue (float meanValue)
Sets the expected mean value over all QC values to meanValue.
Definition at line 259 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::setExpectedStandardDeviation (float sd)
Sets the expected standard deviaction over all QC values to sd.
Definition at line 280 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::setFluidicsPackChangedSymbolPosition (Qt::Alignment pos)
Sets the position of the fluidics pack changed symbol to pos.
Valid values are: Qt::AlignBottom (default), Qt::AlignTop.
Definition at line 134 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::setFluidicsPackChanges (const QVector< QDateTime > & changes)
Sets the date/time of all fluidics pack changes to changes.
Definition at line 175 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void AbstractDiagram::setHidden (const QModelIndex & index, bool hidden) inherited
Hide (or unhide, resp.) a data cell.
Note
Hidden data are still taken into account by the coordinate plane, so neither the grid nor your axes' ranges will change, when you hide data. For totally removing data from KD Chart's view you can use another approach: e.g. you could define a proxy model on top of your data model, and register the proxy model calling setModel() instead of registering your real data model.
Parameters
index The datapoint to set the hidden status for. With a dataset dimension of two, this is the index of the key of each key/value pair.
hidden The hidden status to set.
Definition at line 264 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataHidden(), and KDChart::DataHiddenRole.
void AbstractDiagram::setHidden (int dataset, bool hidden) inherited
Hide (or unhide, resp.) a dataset.
Note
Hidden data are still taken into account by the coordinate plane, so neither the grid nor your axes' ranges will change, when you hide data. For totally removing data from KD Chart's view you can use another approach: e.g. you could define a proxy model on top of your data model, and register the proxy model calling setModel() instead of registering your real data model.
Parameters
dataset The dataset to set the hidden status for.
hidden The hidden status to set.
Definition at line 273 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataHidden(), and KDChart::DataHiddenRole.
void AbstractDiagram::setHidden (bool hidden) inherited
Hide (or unhide, resp.) all datapoints in the model.
Note
Hidden data are still taken into account by the coordinate plane, so neither the grid nor your axes' ranges will change, when you hide data. For totally removing data from KD Chart's view you can use another approach: e.g. you could define a proxy model on top of your data model, and register the proxy model calling setModel() instead of registering your real data model.
Parameters
hidden The hidden status to set.
Definition at line 279 of file KDChartAbstractDiagram.cpp.
References d, KDChart::AbstractDiagram::dataHidden(), and KDChart::DataHiddenRole.
void LineDiagram::setLineAttributes (const LineAttributes & a) inherited
Sets the global line attributes to la.
Definition at line 182 of file KDChartLineDiagram.cpp.
References d, KDChart::LineAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void LineDiagram::setLineAttributes (int column, const LineAttributes & a) inherited
Sets the line attributes of data set column to la.
Definition at line 193 of file KDChartLineDiagram.cpp.
References d, KDChart::LineAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void LineDiagram::setLineAttributes (const QModelIndex & index, const LineAttributes & a) inherited
Sets the line attributes for the model index index to la.
Definition at line 213 of file KDChartLineDiagram.cpp.
References d, KDChart::LineAttributesRole, and KDChart::AbstractDiagram::propertiesChanged().
void LeveyJenningsDiagram::setLotChangedSymbolPosition (Qt::Alignment pos)
Sets the position of the lot change symbol to pos.
Valid values are: Qt::AlignTop (default), Qt::AlignBottom.
Definition at line 113 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::setModel (QAbstractItemModel * model) virtual
Associate a model with the diagram.
Reimplemented from KDChart::AbstractCartesianDiagram.
Definition at line 314 of file KDChartLeveyJenningsDiagram.cpp.
References calculateMeanAndStandardDeviation(), KDChart::AbstractDiagram::dataChanged(), KDChart::AbstractDiagram::layoutChanged(), and KDChart::AbstractCartesianDiagram::setModel().
void AbstractDiagram::setPen (const QModelIndex & index, const QPen & pen) inherited
Set the pen to be used, for painting the datapoint at the given index.
Parameters
index The datapoint's index in the model. With a dataset dimension of two, this is the index of the key of each key/value pair.
pen The pen to use.
Definition at line 647 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DatasetPenRole, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setData().
void AbstractDiagram::setPen (int dataset, const QPen & pen) inherited
Set the pen to be used, for painting the given dataset.
Parameters
dataset The dataset to set the pen for.
pen The pen to use.
Definition at line 662 of file KDChartAbstractDiagram.cpp.
References d, KDChart::DatasetPenRole, and KDChart::AbstractDiagram::propertiesChanged().
void AbstractDiagram::setPen (const QPen & pen) inherited
Set the pen to be used, for painting all datasets in the model.
Parameters
pen The pen to use.
Definition at line 655 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), KDChart::DatasetPenRole, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::AttributesModel::setModelData().
void AbstractDiagram::setPercentMode (bool percent) inherited
Deprecated method that turns the percent mode of this diagram on or off.
Deprecated:
This method is deprecated. Use the setType() method of a supporting diagram implementation instead, e.g. BarDiagram::setType().
See also
percentMode
Definition at line 388 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AbstractDiagram::propertiesChanged().
Referenced by KDChart::LineDiagram::setType().
void AbstractCartesianDiagram::setReferenceDiagram (AbstractCartesianDiagram * diagram, const QPointF & offset = QPointF()) virtual inherited
Makes this diagram use another diagram diagram as reference diagram with relative offset offset.
To share cartesian axes between different diagrams there might be cases when you need that. Normally you don't.
See also
examples/SharedAbscissa
Definition at line 147 of file KDChartAbstractCartesianDiagram.cpp.
References d.
void LineDiagram::setReverseDatasetOrder (bool reverse) inherited
With this property set to true, data sets in a normal line diagram are drawn in reversed order.
More clearly, the first (top-most) data set in the source model will then appear in front. This is mostly due to historical reasons.
Definition at line 169 of file KDChartLineDiagram.cpp.
References d.
void AbstractCartesianDiagram::setRootIndex (const QModelIndex & idx) virtual inherited
Set the root index in the model, where the diagram starts referencing data for display.
[reimplemented]
Reimplemented from KDChart::AbstractDiagram.
Definition at line 163 of file KDChartAbstractCartesianDiagram.cpp.
References KDChart::AbstractDiagram::attributesModel(), d, and KDChart::AbstractDiagram::setRootIndex().
void LeveyJenningsDiagram::setScanLinePen (const QPen & pen)
Sets the pen used for drawing the scan line to pen.
Definition at line 207 of file KDChartLeveyJenningsDiagram.cpp.
References d, KDChart::AbstractDiagram::pen(), and KDChart::AbstractDiagram::update().
void AbstractDiagram::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags command) virtual inherited
[reimplemented]
Definition at line 839 of file KDChartAbstractDiagram.cpp.
References d.
void AbstractDiagram::setSelectionModel (QItemSelectionModel * selectionModel) virtual inherited
Associate a seleection model with the diagrom.
Definition at line 150 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::modelsChanged().
void LeveyJenningsDiagram::setSensorChangedSymbolPosition (Qt::Alignment pos)
Sets the position of the sensor changed symbol to pos.
Valid values are: Qt::AlignBottom (default), Qt::AlignTop.
Definition at line 155 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::setSensorChanges (const QVector< QDateTime > & changes)
Sets the date/time of all sensor changes to changes.
Definition at line 195 of file KDChartLeveyJenningsDiagram.cpp.
References d, and KDChart::AbstractDiagram::update().
void LeveyJenningsDiagram::setSymbol (Symbol symbol, const QString & filename)
Sets the symbol being used for symbol to a SVG file filename.
Definition at line 235 of file KDChartLeveyJenningsDiagram.cpp.
References d, symbol(), and KDChart::AbstractDiagram::update().
void LineDiagram::setThreeDLineAttributes (const ThreeDLineAttributes & a) inherited
Sets the global 3D line attributes to la.
Definition at line 267 of file KDChartLineDiagram.cpp.
References d, KDChart::AbstractDiagram::propertiesChanged(), KDChart::AbstractDiagram::setDataBoundariesDirty(), and KDChart::ThreeDLineAttributesRole.
void LineDiagram::setThreeDLineAttributes (int column, const ThreeDLineAttributes & a) inherited
Sets the 3D line attributes of data set column to ta.
Definition at line 280 of file KDChartLineDiagram.cpp.
References d, KDChart::AbstractDiagram::propertiesChanged(), KDChart::AbstractDiagram::setDataBoundariesDirty(), and KDChart::ThreeDLineAttributesRole.
void LineDiagram::setThreeDLineAttributes (const QModelIndex & index, const ThreeDLineAttributes & a) inherited
Sets the 3D line attributes of model index index to la.
Definition at line 292 of file KDChartLineDiagram.cpp.
References d, KDChart::AbstractDiagram::propertiesChanged(), KDChart::AbstractDiagram::setDataBoundariesDirty(), and KDChart::ThreeDLineAttributesRole.
void LeveyJenningsDiagram::setTimeRange (const QPair< QDateTime, QDateTime > & timeRange)
Sets the timeRange visible on the x axis.
Set it to QPair< QDateTime, QDateTime >() to use the default auto calculation.
Definition at line 482 of file KDChartLeveyJenningsDiagram.cpp.
References d, timeRange(), and KDChart::AbstractDiagram::update().
void LineDiagram::setType (const LineType type) inherited
Sets the line diagram's type to type.
See also
LineDiagram::LineType
Definition at line 109 of file KDChartLineDiagram.cpp.
References d, KDChart::AbstractDiagram::datasetDimension(), KDChart::AbstractDiagram::layoutChanged(), KDChart::LineDiagram::Normal, KDChart::LineDiagram::Percent, KDChart::AbstractDiagram::propertiesChanged(), KDChart::AbstractDiagram::setDataBoundariesDirty(), KDChart::AbstractDiagram::setPercentMode(), KDChart::LineDiagram::Stacked, and KDChart::LineDiagram::type().
Referenced by KDChart::LineDiagram::clone().
void AbstractDiagram::setUnitPrefix (const QString & prefix, int column, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for one specific column.
Sets the unit prefix for one value.
Parameters
prefix The prefix to be used.
column The column which should be set.
orientation The orientation of the axis to use.
prefix the prefix to be set
column the value using that prefix
orientation the orientantion of the axis to set
Definition at line 734 of file KDChartAbstractDiagram.cpp.
References d.
void AbstractDiagram::setUnitPrefix (const QString & prefix, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for all columns.
Sets the unit prefix for all values.
Parameters
prefix The prefix to be used.
orientation The orientation of the axis to use.
prefix the prefix to be set
orientation the orientantion of the axis to set
Definition at line 744 of file KDChartAbstractDiagram.cpp.
References d.
void AbstractDiagram::setUnitSuffix (const QString & suffix, int column, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for one specific column.
Sets the unit suffix for one value.
Parameters
suffix The suffix to be used.
column The column which should be set.
orientation The orientation of the axis to use.
suffix the suffix to be set
column the value using that suffix
orientation the orientantion of the axis to set
Definition at line 755 of file KDChartAbstractDiagram.cpp.
References d.
void AbstractDiagram::setUnitSuffix (const QString & suffix, Qt::Orientation orientation) inherited
Set the unit prefix to be used on axes for all columns.
Sets the unit suffix for all values.
Parameters
suffix The suffix to be used.
orientation The orientation of the axis to use.
suffix the suffix to be set
orientation the orientantion of the axis to set
Definition at line 765 of file KDChartAbstractDiagram.cpp.
References d.
void LineDiagram::setValueTrackerAttributes (const QModelIndex & index, const ValueTrackerAttributes & a) inherited
Sets the value tracker attributes of the model index index to va.
Definition at line 346 of file KDChartLineDiagram.cpp.
References d, KDChart::AbstractDiagram::propertiesChanged(), and KDChart::ValueTrackerAttributesRole.
QString LeveyJenningsDiagram::symbol (Symbol symbol) const
Returns the SVG file name usef for symbol.
Definition at line 227 of file KDChartLeveyJenningsDiagram.cpp.
References d.
Referenced by iconRenderer(), and setSymbol().
void AbstractCartesianDiagram::takeAxis (CartesianAxis * axis) virtual inherited
Removes the axis from the diagram, without deleting it.
The diagram no longer owns the axis, so it is the caller's responsibility to delete the axis.
See also
addAxis
Definition at line 93 of file KDChartAbstractCartesianDiagram.cpp.
References d, KDChart::AbstractAxis::deleteObserver(), KDChart::AbstractCartesianDiagram::layoutPlanes(), and KDChart::AbstractLayoutItem::setParentWidget().
Referenced by KDChart::Widget::setType(), KDChart::CartesianAxis::~CartesianAxis(), and KDChart::LeveyJenningsAxis::~LeveyJenningsAxis().
qreal LineDiagram::threeDItemDepth (const QModelIndex & index) const protected virtual inherited
Returns
the 3D item depth of the model index index
Implements KDChart::AbstractCartesianDiagram.
Definition at line 333 of file KDChartLineDiagram.cpp.
References KDChart::LineDiagram::threeDLineAttributes(), and KDChart::AbstractThreeDAttributes::validDepth().
qreal LineDiagram::threeDItemDepth (int column) const protected virtual inherited
Returns
the 3D item depth of the data set column
Implements KDChart::AbstractCartesianDiagram.
Definition at line 338 of file KDChartLineDiagram.cpp.
References KDChart::LineDiagram::threeDLineAttributes(), and KDChart::AbstractThreeDAttributes::validDepth().
ThreeDLineAttributes LineDiagram::threeDLineAttributes () const inherited
Returns
the global 3D line attributes
Definition at line 307 of file KDChartLineDiagram.cpp.
References d, and KDChart::ThreeDLineAttributesRole.
Referenced by KDChart::LineDiagram::threeDItemDepth(), and KDChart::LineDiagram::threeDLineAttributes().
ThreeDLineAttributes LineDiagram::threeDLineAttributes (int column) const inherited
Returns
the 3D line attributes of data set column
Definition at line 315 of file KDChartLineDiagram.cpp.
References d, KDChart::LineDiagram::threeDLineAttributes(), and KDChart::ThreeDLineAttributesRole.
ThreeDLineAttributes LineDiagram::threeDLineAttributes (const QModelIndex & index) const inherited
Returns
the 3D line attributes of the model index index
Definition at line 326 of file KDChartLineDiagram.cpp.
References d, and KDChart::ThreeDLineAttributesRole.
QPair< QDateTime, QDateTime > LeveyJenningsDiagram::timeRange () const
Returns the timerange of the diagram's data.
Definition at line 448 of file KDChartLeveyJenningsDiagram.cpp.
References ceilDay(), ceilHour(), d, floorDay(), and floorHour().
Referenced by calculateDataBoundaries(), drawChanges(), paint(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), and setTimeRange().
LineDiagram::LineType LineDiagram::type () const inherited
Returns
the type of the line diagram
Definition at line 144 of file KDChartLineDiagram.cpp.
References d.
Referenced by KDChart::LineDiagram::clone(), KDChart::LineDiagram::compare(), drawDataPointSymbol(), and KDChart::LineDiagram::setType().
QString AbstractDiagram::unitPrefix (int column, Qt::Orientation orientation, bool fallback = false) const inherited
Retrieves the axis unit prefix for a specific column.
Returns the unit prefix for a special value.
Parameters
column The column whose prefix should be retrieved.
orientation The orientation of the axis.
fallback If true, the prefix for all columns is returned, when none is set for the selected column.
Returns
The axis unit prefix.
Parameters
column the value which's prefix is requested
orientation the orientation of the axis
fallback if true, the global prefix is return when no specific one is set for that value
Returns
the unit prefix
Definition at line 777 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::itemRowLabels().
QString AbstractDiagram::unitPrefix (Qt::Orientation orientation) const inherited
Retrieves the axis unit prefix.
Returns the global unit prefix.
Parameters
orientation The orientation of the axis.
Returns
The axis unit prefix.
Parameters
orientation the orientation of the axis
Returns
the unit prefix
Definition at line 788 of file KDChartAbstractDiagram.cpp.
References d.
QString AbstractDiagram::unitSuffix (int column, Qt::Orientation orientation, bool fallback = false) const inherited
Retrieves the axis unit suffix for a specific column.
Returns the unit suffix for a special value.
Parameters
column The column whose prefix should be retrieved.
orientation The orientation of the axis.
fallback If true, the suffix for all columns is returned, when none is set for the selected column.
Returns
The axis unit suffix.
Parameters
column the value which's suffix is requested
orientation the orientation of the axis
fallback if true, the global suffix is return when no specific one is set for that value
Returns
the unit suffix
Definition at line 800 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::itemRowLabels().
QString AbstractDiagram::unitSuffix (Qt::Orientation orientation) const inherited
Retrieves the axis unit suffix.
Returns the global unit suffix.
Parameters
orientation The orientation of the axis.
Returns
The axis unit suffix.
Parameters
orientation the orientation of the axis
Returns
the unit siffix
Definition at line 811 of file KDChartAbstractDiagram.cpp.
References d.
void AbstractDiagram::update () const inherited
Definition at line 995 of file KDChartAbstractDiagram.cpp.
References d.
Referenced by KDChart::AbstractDiagram::doItemsLayout(), KDChart::AbstractDiagram::setDataBoundariesDirty(), setExpectedMeanValue(), setExpectedStandardDeviation(), setFluidicsPackChangedSymbolPosition(), setFluidicsPackChanges(), setLotChangedSymbolPosition(), setScanLinePen(), setSensorChangedSymbolPosition(), setSensorChanges(), setSymbol(), and setTimeRange().
void KDChart::AbstractDiagram::useDefaultColors () inherited
Set the palette to be used, for painting datasets to the default palette.
See also
KDChart::Palette. FIXME: fold into one usePalette (KDChart::Palette&) method
Definition at line 866 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AttributesModel::PaletteTypeDefault.
void KDChart::AbstractDiagram::useRainbowColors () inherited
Set the palette to be used, for painting datasets to the rainbow palette.
See also
KDChart::Palette.
Definition at line 876 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AttributesModel::PaletteTypeRainbow.
bool AbstractDiagram::usesExternalAttributesModel () const virtual inherited
Returns whether the diagram is using its own built-in attributes model or an attributes model that was set via setAttributesModel.
See also
setAttributesModel
Definition at line 193 of file KDChartAbstractDiagram.cpp.
References d.
void KDChart::AbstractDiagram::useSubduedColors () inherited
Set the palette to be used, for painting datasets to the subdued palette.
See also
KDChart::Palette.
Definition at line 871 of file KDChartAbstractDiagram.cpp.
References d, and KDChart::AttributesModel::PaletteTypeSubdued.
qreal AbstractDiagram::valueForCell (int row, int column) const protected inherited
Helper method, retrieving the data value (DisplayRole) for a given row and column.
Parameters
row The row to query.
column The column to query.
Returns
The value of the display role at the given row and column as a qreal.
Deprecated:
Definition at line 985 of file KDChartAbstractDiagram.cpp.
References KDChart::AbstractDiagram::attributesModelRootIndex(), and d.
ValueTrackerAttributes LineDiagram::valueTrackerAttributes (const QModelIndex & index) const inherited
Returns the value tracker attributes of the model index index.
Definition at line 358 of file KDChartLineDiagram.cpp.
References d, and KDChart::ValueTrackerAttributesRole.
int AbstractDiagram::verticalOffset () const virtual inherited
[reimplemented]
Definition at line 833 of file KDChartAbstractDiagram.cpp.
void KDChart::AbstractDiagram::viewportCoordinateSystemChanged () signal inherited
Emitted upon change of the view coordinate system.
QRect AbstractDiagram::visualRect (const QModelIndex & index) const virtual inherited
[reimplemented]
Definition at line 817 of file KDChartAbstractDiagram.cpp.
References d.
QRegion AbstractDiagram::visualRegion (const QModelIndex & index) const virtual inherited
Definition at line 860 of file KDChartAbstractDiagram.cpp.
References d.
QRegion AbstractDiagram::visualRegionForSelection (const QItemSelection & selection) const virtual inherited
[reimplemented]
Definition at line 850 of file KDChartAbstractDiagram.cpp.
References d.
The documentation for this class was generated from the following files:
KDChartLeveyJenningsDiagram.h
KDChartLeveyJenningsDiagram.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/