KD Chart 2: PrerenderedElement Class Reference
PrerenderedElement Class Reference abstract
base class for prerendered elements like labels, pixmaps, markers, etc.
#include <KDChartTextLabelCache.h>
Public Member Functions
virtual const QPixmap & pixmap () const =0
Returns the rendered element.
const QPointF & position () const
Get the position of the element.
PrerenderedElement ()
KDChartEnums::PositionValue referencePoint () const
Get the reference point of the element.
virtual QPointF referencePointLocation (KDChartEnums::PositionValue) const =0
Return the location of the reference point relatively to the pixmap's origin.
void setPosition (const QPointF &position)
Set the position of the element.
void setReferencePoint (KDChartEnums::PositionValue)
Set the reference point of the element.
virtual ~PrerenderedElement ()
Protected Member Functions
virtual void invalidate () const =0
invalidate() needs to be called if any of the properties that determine the visual appearance of the prerendered element change.
Detailed Description
base class for prerendered elements like labels, pixmaps, markers, etc.
Definition at line 36 of file KDChartTextLabelCache.h.
Constructor & Destructor Documentation
PrerenderedElement()
PrerenderedElement::PrerenderedElement ()
Definition at line 52 of file KDChartTextLabelCache.cpp.
~PrerenderedElement()
virtual PrerenderedElement::~PrerenderedElement () virtual
Definition at line 39 of file KDChartTextLabelCache.h.
Member Function Documentation
invalidate()
virtual void PrerenderedElement::invalidate () const protected pure virtual
invalidate() needs to be called if any of the properties that determine the visual appearance of the prerendered element change.
It can be called for a const object, as objects may need to force recalculation of the pixmap.
Implemented in PrerenderedLabel.
pixmap()
virtual const QPixmap& PrerenderedElement::pixmap () const pure virtual
Returns the rendered element.
If any of the properties have change, the element will be regenerated.
Implemented in PrerenderedLabel.
position()
const QPointF & PrerenderedElement::position () const
Get the position of the element.
Definition at line 62 of file KDChartTextLabelCache.cpp.
Referenced by KDChart::TernaryAxis::paintCtx(), PrerenderedLabel::referencePointLocation(), and setPosition().
referencePoint()
KDChartEnums::PositionValue PrerenderedElement::referencePoint () const
Get the reference point of the element.
Definition at line 72 of file KDChartTextLabelCache.cpp.
Referenced by PrerenderedLabel::referencePointLocation().
referencePointLocation()
virtual QPointF PrerenderedElement::referencePointLocation (KDChartEnums::PositionValue) const pure virtual
Return the location of the reference point relatively to the pixmap's origin.
Implemented in PrerenderedLabel.
setPosition()
void PrerenderedElement::setPosition (const QPointF & position)
Set the position of the element.
Definition at line 57 of file KDChartTextLabelCache.cpp.
References position().
setReferencePoint()
void PrerenderedElement::setReferencePoint (KDChartEnums::PositionValue point)
Set the reference point of the element.
Every element has nine possible reference points (all compass directions, plus the center.
Definition at line 67 of file KDChartTextLabelCache.cpp.
The documentation for this class was generated from the following files:
KDChartTextLabelCache.h
KDChartTextLabelCache.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/