KD Chart 2: KDChart::Chart Class Reference
KDChart::Chart Class Reference
A chart with one or more diagrams.
#include <KDChartChart>
Signals
void finishedDrawing ()
void propertiesChanged ()
Emitted upon change of a property of the Chart or any of its components.
Public Member Functions
void addCoordinatePlane (AbstractCoordinatePlane *plane)
Adds a coordinate plane to the chart.
void addHeaderFooter (HeaderFooter *headerFooter)
Adds a header or a footer to the chart.
void addLegend (Legend *legend)
Add the given legend to the chart.
BackgroundAttributes backgroundAttributes () const
Chart (QWidget *parent=0)
AbstractCoordinatePlane * coordinatePlane ()
Each chart must have at least one coordinate plane.
QLayout * coordinatePlaneLayout ()
CoordinatePlaneList coordinatePlanes ()
The list of coordinate planes.
FrameAttributes frameAttributes () const
int globalLeadingBottom () const
The padding between the start of the widget and the start of the area that is used for drawing at the bottom.
int globalLeadingLeft () const
The padding between the start of the widget and the start of the area that is used for drawing on the left.
int globalLeadingRight () const
The padding between the start of the widget and the start of the area that is used for drawing on the right.
int globalLeadingTop () const
The padding between the start of the widget and the start of the area that is used for drawing at the top.
HeaderFooter * headerFooter ()
The first header or footer of the chart.
HeaderFooterList headerFooters ()
The list of headers and footers associated with the chart.
void insertCoordinatePlane (int index, AbstractCoordinatePlane *plane)
Inserts a coordinate plane to the chart at index index.
Legend * legend ()
The first legend of the chart or 0 if there was none added to the chart.
LegendList legends ()
The list of all legends associated with the chart.
void paint (QPainter *painter, const QRect &target)
Paints all the contents of the chart.
void reLayoutFloatingLegends ()
void replaceCoordinatePlane (AbstractCoordinatePlane *plane, AbstractCoordinatePlane *oldPlane=0)
Replaces the old coordinate plane, or appends the plane, it there is none yet.
void replaceHeaderFooter (HeaderFooter *headerFooter, HeaderFooter *oldHeaderFooter=0)
Replaces the old header (or footer, resp.), or appends the new header or footer, it there is none yet.
void replaceLegend (Legend *legend, Legend *oldLegend=0)
Replaces the old legend, or appends the new legend, it there is none yet.
void setBackgroundAttributes (const BackgroundAttributes &a)
Specify the background attributes to be used, by default there is no background.
void setCoordinatePlaneLayout (QLayout *layout)
Set the coordinate plane layout that should be used as model for the internal used layout.
void setFrameAttributes (const FrameAttributes &a)
Specify the frame attributes to be used, by default is it a thin black line.
void setGlobalLeading (int left, int top, int right, int bottom)
Set the padding between the margin of the widget and the area that the contents are drawn into.
void setGlobalLeadingBottom (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing on the bottom.
void setGlobalLeadingLeft (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing on the left.
void setGlobalLeadingRight (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing on the right.
void setGlobalLeadingTop (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing at the top.
void setUseNewLayoutSystem (bool value)
void takeCoordinatePlane (AbstractCoordinatePlane *plane)
Removes the coordinate plane from the chart, without deleting it.
void takeHeaderFooter (HeaderFooter *headerFooter)
Removes the header (or footer, resp.) from the chart, without deleting it.
void takeLegend (Legend *legend)
Removes the legend from the chart, without deleting it.
bool useNewLayoutSystem () const
useNewLayoutSystem Be very careful activating the new layout system, its still experimental and works only if the user knows what he is doing.
~Chart ()
Protected Member Functions
bool event (QEvent *event)
reimp
void mouseDoubleClickEvent (QMouseEvent *event)
reimp
void mouseMoveEvent (QMouseEvent *event)
reimp
void mousePressEvent (QMouseEvent *event)
reimp
void mouseReleaseEvent (QMouseEvent *event)
reimp
void paintEvent (QPaintEvent *event)
Draws the background and frame, then calls paint().
void resizeEvent (QResizeEvent *event)
Adjusts the internal layout when the chart is resized.
Properties
int globalLeadingBottom
int globalLeadingLeft
int globalLeadingRight
int globalLeadingTop
bool useNewLayoutSystem
Detailed Description
A chart with one or more diagrams.
The Chart class represents a drawing consisting of one or more diagrams and various optional elements such as legends, axes, text boxes, headers or footers. It takes ownership of all these elements when they are assigned to it. Each diagram is associated with a coordinate plane, of which the chart can have more than one. The coordinate planes (and thus the associated diagrams) can be laid out in various ways.
The Chart class makes heavy use of the Qt Interview framework for model/view programming, and thus requires data to be presented to it in a QAbstractItemModel compatible way. For many simple charts, especially if the visualized data is static, KDChart::Widget provides an abstracted interface, that hides the complexity of Interview to a large extent.
Definition at line 98 of file KDChartChart.h.
Constructor & Destructor Documentation
Chart()
Chart::Chart (QWidget * parent = 0) explicit
Definition at line 1141 of file KDChartChart.cpp.
References addCoordinatePlane(), d, setFrameAttributes(), KDChart::FrameAttributes::setPadding(), and KDChart::FrameAttributes::setPen().
~Chart()
Chart::~Chart ()
Definition at line 1161 of file KDChartChart.cpp.
References d.
Member Function Documentation
addCoordinatePlane()
void Chart::addCoordinatePlane (AbstractCoordinatePlane * plane)
Adds a coordinate plane to the chart.
The chart takes ownership.
Parameters
plane The coordinate plane to add.
See also
replaceCoordinatePlane, takeCoordinatePlane
Definition at line 1223 of file KDChartChart.cpp.
References d, and insertCoordinatePlane().
Referenced by Chart(), and replaceCoordinatePlane().
addHeaderFooter()
void Chart::addHeaderFooter (HeaderFooter * headerFooter)
Adds a header or a footer to the chart.
The chart takes ownership.
Parameters
headerFooter The header (or footer, resp.) to add.
See also
replaceHeaderFooter, takeHeaderFooter
Definition at line 1445 of file KDChartChart.cpp.
References d, KDChart::HeaderFooter::Footer, getRowAndColumnForPosition(), KDChart::HeaderFooter::Header, KDChartEnums::MeasureOrientationMinimum, KDChart::HeaderFooter::position(), s_gridAlignments, KDChart::AbstractLayoutItem::setParentLayout(), KDChart::Measure::setRelativeMode(), KDChart::TextLayoutItem::setTextAttributes(), KDChart::TextLayoutItem::textAttributes(), KDChart::HeaderFooter::type(), and KDChart::Position::value().
Referenced by replaceHeaderFooter().
addLegend()
void Chart::addLegend (Legend * legend)
Add the given legend to the chart.
The chart takes ownership.
Parameters
legend The legend to add.
See also
replaceLegend, takeLegend
Definition at line 1547 of file KDChartChart.cpp.
References legend(), and propertiesChanged().
Referenced by replaceLegend().
backgroundAttributes()
BackgroundAttributes Chart::backgroundAttributes () const
Definition at line 1181 of file KDChartChart.cpp.
References d.
coordinatePlane()
AbstractCoordinatePlane * Chart::coordinatePlane ()
Each chart must have at least one coordinate plane.
Initially a default CartesianCoordinatePlane is created. Use replaceCoordinatePlane() to replace it with a different one, such as a PolarCoordinatePlane.
Returns
The first coordinate plane of the chart.
Definition at line 1208 of file KDChartChart.cpp.
References d.
coordinatePlaneLayout()
QLayout * Chart::coordinatePlaneLayout ()
Definition at line 1203 of file KDChartChart.cpp.
References d.
coordinatePlanes()
CoordinatePlaneList Chart::coordinatePlanes ()
The list of coordinate planes.
Returns
The list of coordinate planes.
Definition at line 1218 of file KDChartChart.cpp.
References d.
event()
bool Chart::event (QEvent * event) protected
reimp
Definition at line 1760 of file KDChartChart.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), KDChart::AbstractDiagram::indexAt(), and KDChart::AbstractDiagram::indexesIn().
Referenced by mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and resizeEvent().
finishedDrawing
void KDChart::Chart::finishedDrawing () signal
Referenced by paintEvent().
frameAttributes()
FrameAttributes Chart::frameAttributes () const
Definition at line 1171 of file KDChartChart.cpp.
References d.
globalLeadingBottom()
int KDChart::Chart::globalLeadingBottom () const
The padding between the start of the widget and the start of the area that is used for drawing at the bottom.
Returns
The padding between the start of the widget and the start of the area that is used for drawing at the bottom.
See also
setGlobalLeading
globalLeadingLeft()
int KDChart::Chart::globalLeadingLeft () const
The padding between the start of the widget and the start of the area that is used for drawing on the left.
Returns
The padding between the start of the widget and the start of the area that is used for drawing on the left.
See also
setGlobalLeading
globalLeadingRight()
int KDChart::Chart::globalLeadingRight () const
The padding between the start of the widget and the start of the area that is used for drawing on the right.
Returns
The padding between the start of the widget and the start of the area that is used for drawing on the right.
See also
setGlobalLeading
globalLeadingTop()
int KDChart::Chart::globalLeadingTop () const
The padding between the start of the widget and the start of the area that is used for drawing at the top.
Returns
The padding between the start of the widget and the start of the area that is used for drawing at the top.
See also
setGlobalLeading
headerFooter()
HeaderFooter * Chart::headerFooter ()
The first header or footer of the chart.
By default there is none.
Returns
The first header or footer of the chart or 0 if there was none added to the chart.
Definition at line 1525 of file KDChartChart.cpp.
References d.
Referenced by replaceHeaderFooter(), and takeHeaderFooter().
headerFooters()
HeaderFooterList Chart::headerFooters ()
The list of headers and footers associated with the chart.
Returns
The list of headers and footers associated with the chart.
Definition at line 1534 of file KDChartChart.cpp.
References d.
insertCoordinatePlane()
void Chart::insertCoordinatePlane (int index, AbstractCoordinatePlane * plane)
Inserts a coordinate plane to the chart at index index.
The chart takes ownership.
Parameters
index The index where to add the plane
plane The coordinate plane to add.
See also
replaceCoordinatePlane, takeCoordinatePlane
Definition at line 1229 of file KDChartChart.cpp.
References d, propertiesChanged(), and KDChart::AbstractCoordinatePlane::setParent().
Referenced by addCoordinatePlane().
legend()
Legend * Chart::legend ()
The first legend of the chart or 0 if there was none added to the chart.
Returns
The first legend of the chart or 0 if none exists.
Definition at line 1683 of file KDChartChart.cpp.
References d.
Referenced by addLegend(), reLayoutFloatingLegends(), replaceLegend(), and takeLegend().
legends()
LegendList Chart::legends ()
The list of all legends associated with the chart.
Returns
The list of all legends associated with the chart.
Definition at line 1688 of file KDChartChart.cpp.
References d.
mouseDoubleClickEvent()
void Chart::mouseDoubleClickEvent (QMouseEvent * event) protected
reimp
Definition at line 1707 of file KDChartChart.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), event(), KDChart::AbstractCoordinatePlane::geometry(), and KDChart::AbstractCoordinatePlane::mouseDoubleClickEvent().
mouseMoveEvent()
void Chart::mouseMoveEvent (QMouseEvent * event) protected
reimp
Definition at line 1720 of file KDChartChart.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), event(), KDChart::AbstractCoordinatePlane::geometry(), and KDChart::AbstractCoordinatePlane::mouseMoveEvent().
mousePressEvent()
void Chart::mousePressEvent (QMouseEvent * event) protected
reimp
Definition at line 1693 of file KDChartChart.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), event(), KDChart::AbstractCoordinatePlane::geometry(), and KDChart::AbstractCoordinatePlane::mousePressEvent().
mouseReleaseEvent()
void Chart::mouseReleaseEvent (QMouseEvent * event) protected
reimp
Definition at line 1739 of file KDChartChart.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), event(), KDChart::AbstractCoordinatePlane::geometry(), and KDChart::AbstractCoordinatePlane::mouseReleaseEvent().
paint()
void Chart::paint (QPainter * painter, const QRect & target)
Paints all the contents of the chart.
Use this method to make KDChart draw into your QPainter.
Note
Any global leading settings will be used by the paint method too, so make sure to set them to zero, if you want the drawing to have the exact size of the target rectangle.
Parameters
painter The painter to be drawn into.
target The rectangle to be filled by the Chart's drawing.
See also
setGlobalLeading
Definition at line 1337 of file KDChartChart.cpp.
References d, KDChart::GlobalMeasureScaling::instance(), invalidateLayoutTree(), KDChart::GlobalMeasureScaling::paintDevice(), KDChart::GlobalMeasureScaling::resetFactors(), KDChart::PrintingParameters::resetScaleFactor(), KDChart::GlobalMeasureScaling::setFactors(), KDChart::GlobalMeasureScaling::setPaintDevice(), and KDChart::PrintingParameters::setScaleFactor().
paintEvent()
void Chart::paintEvent (QPaintEvent * event) protected
Draws the background and frame, then calls paint().
In most cases there is no need to override this method in a derived class, but if you do, do not forget to call paint().
See also
paint
Definition at line 1438 of file KDChartChart.cpp.
References d, and finishedDrawing().
propertiesChanged
void KDChart::Chart::propertiesChanged () signal
Emitted upon change of a property of the Chart or any of its components.
Referenced by addLegend(), insertCoordinatePlane(), takeCoordinatePlane(), and takeLegend().
reLayoutFloatingLegends()
void Chart::reLayoutFloatingLegends ()
Definition at line 1406 of file KDChartChart.cpp.
References d, KDChart::Legend::floatingPosition(), KDChart::Position::isFloating(), legend(), KDChart::Legend::position(), and KDChart::Legend::sizeHint().
replaceCoordinatePlane()
void Chart::replaceCoordinatePlane (AbstractCoordinatePlane * plane, AbstractCoordinatePlane * oldPlane = 0)
Replaces the old coordinate plane, or appends the plane, it there is none yet.
Parameters
plane The coordinate plane to be used instead of the old plane. This parameter must not be zero, or the method will do nothing.
oldPlane The coordinate plane to be removed by the new plane. This plane will be deleted automatically. If the parameter is omitted, the very first coordinate plane will be replaced. In case, there was no plane yet, the new plane will just be added.
Note
If you want to re-use the old coordinate plane, call takeCoordinatePlane and addCoordinatePlane, instead of using replaceCoordinatePlane.
See also
addCoordinatePlane, takeCoordinatePlane
Definition at line 1246 of file KDChartChart.cpp.
References addCoordinatePlane(), d, and takeCoordinatePlane().
replaceHeaderFooter()
void Chart::replaceHeaderFooter (HeaderFooter * headerFooter, HeaderFooter * oldHeaderFooter = 0)
Replaces the old header (or footer, resp.), or appends the new header or footer, it there is none yet.
Parameters
headerFooter The header or footer to be used instead of the old one. This parameter must not be zero, or the method will do nothing.
oldHeaderFooter The header or footer to be removed by the new one. This header or footer will be deleted automatically. If the parameter is omitted, the very first header or footer will be replaced. In case, there was no header and no footer yet, the new header or footer will just be added.
Note
If you want to re-use the old header or footer, call takeHeaderFooter and addHeaderFooter, instead of using replaceHeaderFooter.
See also
addHeaderFooter, takeHeaderFooter
Definition at line 1484 of file KDChartChart.cpp.
References addHeaderFooter(), d, headerFooter(), and takeHeaderFooter().
replaceLegend()
void Chart::replaceLegend (Legend * legend, Legend * oldLegend = 0)
Replaces the old legend, or appends the new legend, it there is none yet.
Parameters
legend The legend to be used instead of the old one. This parameter must not be zero, or the method will do nothing.
oldLegend The legend to be removed by the new one. This legend will be deleted automatically. If the parameter is omitted, the very first legend will be replaced. In case, there was no legend yet, the new legend will just be added.
If you want to re-use the old legend, call takeLegend and addLegend, instead of using replaceLegend.
Note
Whenever addLegend is called the font sizes used by the Legend are set to relative and they get coupled to the Chart's size, with their relative values being 20 for the item texts and 24 to the title text. So if you want to use custom font sizes for the Legend make sure to set them after calling addLegend.
See also
addLegend, takeLegend
Definition at line 1649 of file KDChartChart.cpp.
References addLegend(), d, legend(), and takeLegend().
resizeEvent()
void Chart::resizeEvent (QResizeEvent * event) protected
Adjusts the internal layout when the chart is resized.
Definition at line 1399 of file KDChartChart.cpp.
References d, and event().
setBackgroundAttributes()
void Chart::setBackgroundAttributes (const BackgroundAttributes & a)
Specify the background attributes to be used, by default there is no background.
To set a light blue background, you could do something like this:
KDChart::BackgroundAttributes backgroundAttrs(my_chart->backgroundAttributes());
backgroundAttrs.setVisible(true);
backgroundAttrs.setBrush(QColor(0xd0,0xd0,0xff));
my_chart->setBackgroundAttributes(backgroundAttrs);
See also
setFrameAttributes
Definition at line 1176 of file KDChartChart.cpp.
References d.
setCoordinatePlaneLayout()
void Chart::setCoordinatePlaneLayout (QLayout * layout)
Set the coordinate plane layout that should be used as model for the internal used layout.
The layout needs to be an instance of QHBoxLayout or QVBoxLayout.
Definition at line 1187 of file KDChartChart.cpp.
References d.
setFrameAttributes()
void Chart::setFrameAttributes (const FrameAttributes & a)
Specify the frame attributes to be used, by default is it a thin black line.
To hide the frame line, you could do something like this:
KDChart::FrameAttributes frameAttrs(my_chart->frameAttributes());
frameAttrs.setVisible(false);
my_chart->setFrameAttributes(frameAttrs);
See also
setBackgroundAttributes
Definition at line 1166 of file KDChartChart.cpp.
References d.
Referenced by Chart().
setGlobalLeading()
void Chart::setGlobalLeading (int left, int top, int right, int bottom)
Set the padding between the margin of the widget and the area that the contents are drawn into.
Parameters
left The padding on the left side.
top The padding at the top.
right The padding on the left hand side.
bottom The padding on the bottom.
Note
Using previous versions of KD Chart you might have called setGlobalLeading() to make room for long Abscissa labels (or for an overlapping top label of an Ordinate axis, resp.) that would not fit into the normal axis area. This is no longer needed because KD Chart now is using hidden auto-spacer items reserving as much free space as is needed for axes with overlaping content at the respective sides.
See also
setGlobalLeadingTop, setGlobalLeadingBottom, setGlobalLeadingLeft, setGlobalLeadingRight
globalLeadingTop, globalLeadingBottom, globalLeadingLeft, globalLeadingRight
Definition at line 1281 of file KDChartChart.cpp.
References setGlobalLeadingBottom(), setGlobalLeadingLeft(), setGlobalLeadingRight(), and setGlobalLeadingTop().
setGlobalLeadingBottom()
void Chart::setGlobalLeadingBottom (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing on the bottom.
Parameters
leading The padding value.
See also
setGlobalLeading
Definition at line 1325 of file KDChartChart.cpp.
References d.
Referenced by setGlobalLeading().
setGlobalLeadingLeft()
void Chart::setGlobalLeadingLeft (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing on the left.
Parameters
leading The padding value.
See also
setGlobalLeading
Definition at line 1289 of file KDChartChart.cpp.
References d.
Referenced by setGlobalLeading().
setGlobalLeadingRight()
void Chart::setGlobalLeadingRight (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing on the right.
Parameters
leading The padding value.
See also
setGlobalLeading
Definition at line 1313 of file KDChartChart.cpp.
References d.
Referenced by setGlobalLeading().
setGlobalLeadingTop()
void Chart::setGlobalLeadingTop (int leading)
Set the padding between the start of the widget and the start of the area that is used for drawing at the top.
Parameters
leading The padding value.
See also
setGlobalLeading
Definition at line 1301 of file KDChartChart.cpp.
References d.
Referenced by setGlobalLeading().
setUseNewLayoutSystem()
void Chart::setUseNewLayoutSystem (bool value)
Definition at line 1797 of file KDChartChart.cpp.
References useNewLayoutSystem().
takeCoordinatePlane()
void Chart::takeCoordinatePlane (AbstractCoordinatePlane * plane)
Removes the coordinate plane from the chart, without deleting it.
The chart no longer owns the plane, so it is the caller's responsibility to delete the plane.
See also
addCoordinatePlane, takeCoordinatePlane
Definition at line 1264 of file KDChartChart.cpp.
References d, propertiesChanged(), KDChart::AbstractLayoutItem::removeFromParentLayout(), and KDChart::AbstractCoordinatePlane::setParent().
Referenced by replaceCoordinatePlane().
takeHeaderFooter()
void Chart::takeHeaderFooter (HeaderFooter * headerFooter)
Removes the header (or footer, resp.) from the chart, without deleting it.
The chart no longer owns the header or footer, so it is the caller's responsibility to delete the header or footer.
See also
addHeaderFooter, replaceHeaderFooter
Definition at line 1502 of file KDChartChart.cpp.
References d, headerFooter(), KDChart::AbstractLayoutItem::removeFromParentLayout(), and KDChart::AbstractLayoutItem::setParentLayout().
Referenced by replaceHeaderFooter().
takeLegend()
void Chart::takeLegend (Legend * legend)
Removes the legend from the chart, without deleting it.
The chart no longer owns the legend, so it is the caller's responsibility to delete the legend.
See also
addLegend, takeLegend
Definition at line 1666 of file KDChartChart.cpp.
References d, legend(), and propertiesChanged().
Referenced by replaceLegend().
useNewLayoutSystem()
bool KDChart::Chart::useNewLayoutSystem () const
useNewLayoutSystem Be very careful activating the new layout system, its still experimental and works only if the user knows what he is doing.
The reason is that the system does not prevent the user from creating sharing graphs that are not layoutable in a plane and still needs assistance from the user.
Referenced by setUseNewLayoutSystem().
Property Documentation
globalLeadingBottom
int Chart::globalLeadingBottom read write
Definition at line 103 of file KDChartChart.h.
globalLeadingLeft
int Chart::globalLeadingLeft read write
Definition at line 104 of file KDChartChart.h.
globalLeadingRight
int Chart::globalLeadingRight read write
Definition at line 105 of file KDChartChart.h.
globalLeadingTop
int Chart::globalLeadingTop read write
Definition at line 102 of file KDChartChart.h.
useNewLayoutSystem
bool Chart::useNewLayoutSystem read write
Definition at line 106 of file KDChartChart.h.
The documentation for this class was generated from the following files:
KDChartChart.h
KDChartChart.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/