KD Chart 2: KDChart::TextLayoutItem Class Reference
KDChart::TextLayoutItem Class Reference
Layout item showing a text.
#include <KDChartLayoutItems.h>
Public Member Functions
const QObject * autoReferenceArea () const
QPolygon boundingPolygon () const
virtual Qt::Orientations expandingDirections () const
pure virtual in QLayoutItem
virtual QRect geometry () const
pure virtual in QLayoutItem
virtual bool intersects (const TextLayoutItem &other, const QPointF &myPos, const QPointF &otherPos) const
virtual bool intersects (const TextLayoutItem &other, const QPoint &myPos, const QPoint &otherPos) const
virtual bool isEmpty () const
pure virtual in QLayoutItem
virtual int marginWidth () const
virtual QSize maximumSize () const
pure virtual in QLayoutItem
virtual QSize minimumSize () const
pure virtual in QLayoutItem
virtual void paint (QPainter *)
virtual void paintAll (QPainter &painter)
Default impl: just call paint.
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
QLayout * parentLayout ()
virtual QFont realFont () const
virtual qreal realFontSize () const
void removeFromParentLayout ()
void setAutoReferenceArea (const QObject *area)
virtual void setGeometry (const QRect &r)
pure virtual in QLayoutItem
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
void setText (const QString &text)
void setTextAlignment (Qt::Alignment)
void setTextAttributes (const TextAttributes &a)
Use this to specify the text attributes to be used for this item.
virtual QSize sizeHint () const
pure virtual in QLayoutItem
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
virtual QSize sizeHintUnrotated () const
QString text () const
Qt::Alignment textAlignment () const
TextAttributes textAttributes () const
Returns the text attributes to be used for this item.
TextLayoutItem ()
TextLayoutItem (const QString &text, const TextAttributes &attributes, const QObject *autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation, Qt::Alignment alignment=0)
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
Layout item showing a text.
Definition at line 100 of file KDChartLayoutItems.h.
Constructor & Destructor Documentation
TextLayoutItem() [1/2]
KDChart::TextLayoutItem::TextLayoutItem ()
Definition at line 218 of file KDChartLayoutItems.cpp.
TextLayoutItem() [2/2]
KDChart::TextLayoutItem::TextLayoutItem (const QString & text, const TextAttributes & attributes, const QObject * autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation, Qt::Alignment alignment = 0)
Definition at line 201 of file KDChartLayoutItems.cpp.
Member Function Documentation
autoReferenceArea()
const QObject * KDChart::TextLayoutItem::autoReferenceArea () const
Definition at line 239 of file KDChartLayoutItems.cpp.
Referenced by KDChart::HeaderFooter::compare(), and KDChart::HeaderFooter::setParent().
boundingPolygon()
QPolygon KDChart::TextLayoutItem::boundingPolygon () const
Definition at line 392 of file KDChartLayoutItems.cpp.
Referenced by intersects(), and KDChart::CartesianAxis::paintCtx().
expandingDirections()
Qt::Orientations KDChart::TextLayoutItem::expandingDirections () const virtual
pure virtual in QLayoutItem
Definition at line 298 of file KDChartLayoutItems.cpp.
geometry()
QRect KDChart::TextLayoutItem::geometry () const virtual
pure virtual in QLayoutItem
Definition at line 303 of file KDChartLayoutItems.cpp.
Referenced by KDChart::TextArea::areaGeometry(), KDChart::TextArea::paintAll(), and KDChart::TextArea::paintIntoRect().
intersects() [1/2]
bool KDChart::TextLayoutItem::intersects (const TextLayoutItem & other, const QPointF & myPos, const QPointF & otherPos) const virtual
Definition at line 398 of file KDChartLayoutItems.cpp.
Referenced by KDChart::CartesianAxis::paintCtx().
intersects() [2/2]
bool KDChart::TextLayoutItem::intersects (const TextLayoutItem & other, const QPoint & myPos, const QPoint & otherPos) const virtual
Definition at line 403 of file KDChartLayoutItems.cpp.
References boundingPolygon().
isEmpty()
bool KDChart::TextLayoutItem::isEmpty () const virtual
pure virtual in QLayoutItem
Definition at line 308 of file KDChartLayoutItems.cpp.
marginWidth()
int KDChart::TextLayoutItem::marginWidth () const virtual
Definition at line 447 of file KDChartLayoutItems.cpp.
Referenced by KDChart::CartesianAxis::paintCtx().
maximumSize()
QSize KDChart::TextLayoutItem::maximumSize () const virtual
pure virtual in QLayoutItem
Definition at line 313 of file KDChartLayoutItems.cpp.
minimumSize()
QSize KDChart::TextLayoutItem::minimumSize () const virtual
pure virtual in QLayoutItem
Definition at line 318 of file KDChartLayoutItems.cpp.
paint()
void KDChart::TextLayoutItem::paint (QPainter * painter) virtual
Implements KDChart::AbstractLayoutItem.
Definition at line 490 of file KDChartLayoutItems.cpp.
References fitFontSizeToGeometry(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::TextArea::paintAll(), and KDChart::CartesianAxis::paintCtx().
paintAll()
void KDChart::AbstractLayoutItem::paintAll (QPainter & painter) virtual inherited
Default impl: just call paint.
Derived classes like KDChart::AbstractArea are providing additional action here.
Reimplemented in KDChart::AbstractArea, KDChart::TextArea, and KDChart::TernaryAxis.
Definition at line 64 of file KDChartLayoutItems.cpp.
paintCtx()
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual inherited
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
realFont()
QFont KDChart::TextLayoutItem::realFont () const virtual
Definition at line 386 of file KDChartLayoutItems.cpp.
Referenced by KDChart::CartesianAxis::paintCtx().
realFontSize()
qreal KDChart::TextLayoutItem::realFontSize () const virtual
Definition at line 369 of file KDChartLayoutItems.cpp.
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
setAutoReferenceArea()
void KDChart::TextLayoutItem::setAutoReferenceArea (const QObject * area)
Definition at line 232 of file KDChartLayoutItems.cpp.
Referenced by KDChart::HeaderFooter::setParent().
setGeometry()
void KDChart::TextLayoutItem::setGeometry (const QRect & r) virtual
pure virtual in QLayoutItem
Definition at line 323 of file KDChartLayoutItems.cpp.
Referenced by KDChart::TextArea::paintAll(), KDChart::CartesianAxis::paintCtx(), and KDChart::TextArea::paintIntoRect().
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
setText()
void KDChart::TextLayoutItem::setText (const QString & text)
Definition at line 244 of file KDChartLayoutItems.cpp.
Referenced by KDChart::Widget::addHeaderFooter(), KDChart::HeaderFooter::clone(), and KDChart::CartesianAxis::paintCtx().
setTextAlignment()
void KDChart::TextLayoutItem::setTextAlignment (Qt::Alignment alignment)
Definition at line 258 of file KDChartLayoutItems.cpp.
setTextAttributes()
void KDChart::TextLayoutItem::setTextAttributes (const TextAttributes & a)
Use this to specify the text attributes to be used for this item.
See also
textAttributes
Definition at line 277 of file KDChartLayoutItems.cpp.
References KDChart::TextAttributes::font().
Referenced by KDChart::Chart::addHeaderFooter(), KDChart::HeaderFooter::clone(), and KDChart::CartesianAxis::paintCtx().
sizeHint()
QSize KDChart::TextLayoutItem::sizeHint () const virtual
pure virtual in QLayoutItem
Definition at line 411 of file KDChartLayoutItems.cpp.
Referenced by KDChart::LeveyJenningsAxis::paintAsAbscissa(), and KDChart::CartesianAxis::paintCtx().
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
sizeHintUnrotated()
QSize KDChart::TextLayoutItem::sizeHintUnrotated () const virtual
Definition at line 425 of file KDChartLayoutItems.cpp.
text()
QString KDChart::TextLayoutItem::text () const
Definition at line 253 of file KDChartLayoutItems.cpp.
Referenced by KDChart::HeaderFooter::clone(), and KDChart::HeaderFooter::compare().
textAlignment()
Qt::Alignment KDChart::TextLayoutItem::textAlignment () const
Definition at line 267 of file KDChartLayoutItems.cpp.
textAttributes()
KDChart::TextAttributes KDChart::TextLayoutItem::textAttributes () const
Returns the text attributes to be used for this item.
See also
setTextAttributes
Definition at line 292 of file KDChartLayoutItems.cpp.
Referenced by KDChart::Chart::addHeaderFooter(), KDChart::HeaderFooter::clone(), and KDChart::HeaderFooter::compare().
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartLayoutItems.h
KDChartLayoutItems.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/