KD Chart 2: KDChart::TernaryAxis Class Reference
KDChart::TernaryAxis Class Reference
The class for ternary axes.
#include <KDChartTernaryAxis.h>
Public Slots
void update ()
Signals
void coordinateSystemChanged ()
void positionChanged (AbstractArea *)
Public Member Functions
void alignToReferencePoint (const RelativePosition &position)
BackgroundAttributes backgroundAttributes () const
virtual int bottomOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
bool compare (const AbstractAxis *other) const
Returns true if both axes have the same settings.
virtual void connectSignals ()
Wireing the signal/slot connections.
const AbstractCoordinatePlane * coordinatePlane () const
Convenience function, returns the coordinate plane, in which this axis is used.
void createObserver (AbstractDiagram *diagram)
virtual const QString customizedLabel (const QString &label) const
Reimplement this method if you want to adjust axis labels before they are printed.
void deleteObserver (AbstractDiagram *diagram)
const AbstractDiagram * diagram () const
virtual Qt::Orientations expandingDirections () const
FrameAttributes frameAttributes () const
virtual QRect geometry () const
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
bool hasDefaultTitleTextAttributes () const
virtual bool isEmpty () const
QStringList labels () const
Returns a list of strings, that are used as axis labels, as set via setLabels.
virtual int leftOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
virtual QSize maximumSize () const
virtual QSize minimumSize () const
bool observedBy (AbstractDiagram *diagram) const
virtual void paint (QPainter *)
virtual void paintAll (QPainter &)
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintCtx (PaintContext *)
Default impl: Paint the complete item using its layouted position and size.
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
virtual void paintIntoRect (QPainter &painter, const QRect &rect)
Draws the background and frame, then calls paint().
QLayout * parentLayout ()
virtual const Position position () const
void removeFromParentLayout ()
QPair< QSizeF, QSizeF > requiredMargins () const
void resetTitleTextAttributes ()
virtual int rightOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
RulerAttributes rulerAttributes () const
Returns the attributes to be used for painting the rulers.
void setBackgroundAttributes (const BackgroundAttributes &a)
void setFrameAttributes (const FrameAttributes &a)
virtual void setGeometry (const QRect &rect)
void setLabels (const QStringList &list)
Use this to specify your own set of strings, to be used as axis labels.
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
virtual void setPosition (Position p)
void setRulerAttributes (const RulerAttributes &a)
Use this to specify the attributes used to paint the axis ruler.
void setShortLabels (const QStringList &list)
Use this to specify your own set of strings, to be used as axis labels, in case the normal labels are too long.
void setTextAttributes (const TextAttributes &a)
Use this to specify the text attributes to be used for axis labels.
void setTitleText (const QString &text)
void setTitleTextAttributes (const TextAttributes &a)
QStringList shortLabels () const
Returns a list of strings, that are used as axis labels, as set via setShortLabels.
virtual QSize sizeHint () const
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
TernaryAxis (AbstractTernaryDiagram *diagram=0)
TextAttributes textAttributes () const
Returns the text attributes to be used for axis labels.
QString titleText () const
TextAttributes titleTextAttributes () const
virtual int topOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
~TernaryAxis ()
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Slots
virtual void delayedInit ()
called for initializing after the c'tor has completed
Protected Member Functions
virtual QRect areaGeometry () const
QRect innerRect () const
virtual void positionHasChanged ()
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
The class for ternary axes.
Definition at line 40 of file KDChartTernaryAxis.h.
Constructor & Destructor Documentation
TernaryAxis()
TernaryAxis::TernaryAxis (AbstractTernaryDiagram * diagram = 0) explicit
Definition at line 43 of file KDChartTernaryAxis.cpp.
References KDChart::AbstractAxis::diagram(), KDChartEnums::PositionSouth, resetTitleTextAttributes(), setPosition(), and PrerenderedLabel::setText().
~TernaryAxis()
TernaryAxis::~TernaryAxis ()
Definition at line 56 of file KDChartTernaryAxis.cpp.
Member Function Documentation
alignToReferencePoint()
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position) inherited
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
areaGeometry()
QRect AbstractArea::areaGeometry () const protected virtual inherited
Implements KDChart::AbstractAreaBase.
Definition at line 151 of file KDChartAbstractArea.cpp.
Referenced by KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::TernaryCoordinatePlane::paint(), KDChart::CartesianAxis::paint(), KDChart::AbstractArea::paintAll(), and KDChart::CartesianAxis::paintCtx().
backgroundAttributes()
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const inherited
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
bottomOverlap()
int AbstractArea::bottomOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the bottom edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 98 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
compare() [1/2]
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const inherited
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), and KDChart::AbstractAreaBase::frameAttributes().
Referenced by KDChart::Legend::compare().
compare() [2/2]
bool AbstractAxis::compare (const AbstractAxis * other) const inherited
Returns true if both axes have the same settings.
Definition at line 146 of file KDChartAbstractAxis.cpp.
References KDChart::AbstractAxis::labels(), KDChart::AbstractAxis::shortLabels(), and KDChart::AbstractAxis::textAttributes().
Referenced by KDChart::CartesianAxis::compare().
connectSignals()
void AbstractAxis::connectSignals () virtual inherited
Wireing the signal/slot connections.
This method gets called automatically, each time, when you assign the axis to a diagram, either by passing a diagram* to the c'tor, or by calling the diagram's setAxis method, resp.
If overwriting this method in derived classes, make sure to call this base method AbstractAxis::connectSignals(), so your axis gets connected to the diagram's built-in signals.
See also
AbstractCartesianDiagram::addAxis()
Definition at line 178 of file KDChartAbstractAxis.cpp.
References KDChart::AbstractAxis::coordinateSystemChanged(), and d.
coordinatePlane()
const AbstractCoordinatePlane * AbstractAxis::coordinatePlane () const inherited
Convenience function, returns the coordinate plane, in which this axis is used.
If the axis is not used in a coordinate plane, the return value is Zero.
Definition at line 242 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
coordinateSystemChanged
void KDChart::AbstractAxis::coordinateSystemChanged () signal inherited
Referenced by KDChart::AbstractAxis::connectSignals().
createObserver()
void AbstractAxis::createObserver (AbstractDiagram * diagram) inherited
Definition at line 168 of file KDChartAbstractAxis.cpp.
References d, and KDChart::AbstractAxis::diagram().
Referenced by KDChart::AbstractCartesianDiagram::addAxis().
customizedLabel()
const QString AbstractAxis::customizedLabel (const QString & label) const virtual inherited
Reimplement this method if you want to adjust axis labels before they are printed.
KD Chart is calling this method immediately before drawing the text, this means: What you return here will be drawn without further modifications.
Parameters
label The text of the label as KD Chart has calculated it automatically (or as it was taken from a QStringList provided by you, resp.)
Note
If you reimplement this method in a subclass of KDChartCartesianAxis, and your reimplementation's return value depends on data other than label (so KDChart will not know when it changes), you must manually ensure that layouts are adapted to any changed sizes of the axis labels. To do that, call KDChartCartesianAxis::layoutPlanes() from your reimplementation when you know that the external data changed and it will change label sizes - or when you cannot exclude that.
Returns
The text to be drawn. By default this is the same as label.
Definition at line 162 of file KDChartAbstractAxis.cpp.
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate(), and KDChart::CartesianAxis::paintCtx().
delayedInit
void AbstractAxis::delayedInit () protected virtual slot inherited
called for initializing after the c'tor has completed
Definition at line 138 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::AbstractAxis().
deleteObserver()
void AbstractAxis::deleteObserver (AbstractDiagram * diagram) inherited
Definition at line 173 of file KDChartAbstractAxis.cpp.
References d, and KDChart::AbstractAxis::diagram().
Referenced by KDChart::AbstractCartesianDiagram::takeAxis(), and KDChart::AbstractCartesianDiagram::~AbstractCartesianDiagram().
diagram()
const AbstractDiagram * KDChart::AbstractAxis::diagram () const inherited
Definition at line 249 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::createObserver(), KDChart::AbstractAxis::deleteObserver(), TernaryAxis(), KDChart::CartesianAxis::~CartesianAxis(), and KDChart::LeveyJenningsAxis::~LeveyJenningsAxis().
expandingDirections()
Qt::Orientations TernaryAxis::expandingDirections () const virtual
Definition at line 123 of file KDChartTernaryAxis.cpp.
frameAttributes()
FrameAttributes AbstractAreaBase::frameAttributes () const inherited
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::Legend::clone(), KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
geometry()
QRect TernaryAxis::geometry () const virtual
Implements KDChart::AbstractAxis.
Definition at line 97 of file KDChartTernaryAxis.cpp.
getFrameLeadings()
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const inherited
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::innerRect(), and KDChart::AbstractAreaWidget::paintAll().
hasDefaultTitleTextAttributes()
bool TernaryAxis::hasDefaultTitleTextAttributes () const
Definition at line 194 of file KDChartTernaryAxis.cpp.
innerRect()
QRect AbstractAreaBase::innerRect () const protected inherited
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::areaGeometry(), and KDChart::AbstractAreaBase::getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and KDChart::TextArea::paintAll().
isEmpty()
bool TernaryAxis::isEmpty () const virtual
Definition at line 91 of file KDChartTernaryAxis.cpp.
labels()
QStringList AbstractAxis::labels () const inherited
Returns a list of strings, that are used as axis labels, as set via setLabels.
See also
setLabels
Definition at line 223 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::compare(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), and paintCtx().
leftOverlap()
int AbstractArea::leftOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the left edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 74 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
maximumSize()
QSize TernaryAxis::maximumSize () const virtual
Definition at line 113 of file KDChartTernaryAxis.cpp.
minimumSize()
QSize TernaryAxis::minimumSize () const virtual
Definition at line 107 of file KDChartTernaryAxis.cpp.
observedBy()
bool KDChart::AbstractAxis::observedBy (AbstractDiagram * diagram) const inherited
Definition at line 254 of file KDChartAbstractAxis.cpp.
References d.
paint()
void TernaryAxis::paint (QPainter *) virtual
Implements KDChart::AbstractLayoutItem.
Definition at line 67 of file KDChartTernaryAxis.cpp.
paintAll()
void TernaryAxis::paintAll (QPainter & painter) virtual
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
Reimplemented from KDChart::AbstractArea.
Definition at line 62 of file KDChartTernaryAxis.cpp.
paintBackground()
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintBackgroundAttributes()
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static inherited
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by KDChart::AbstractAreaBase::paintBackground().
paintCtx()
void TernaryAxis::paintCtx (PaintContext * context) virtual
Default impl: Paint the complete item using its layouted position and size.
Reimplemented from KDChart::AbstractLayoutItem.
Definition at line 72 of file KDChartTernaryAxis.cpp.
References KDChart::PaintContext::coordinatePlane(), KDChart::AbstractAxis::labels(), KDChart::PaintContext::painter(), PrerenderedLabel::pixmap(), PrerenderedElement::position(), PrerenderedLabel::referencePointLocation(), and KDChart::TernaryCoordinatePlane::translate().
paintFrame()
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintFrameAttributes()
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static inherited
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::AbstractAreaBase::paintFrame().
paintIntoRect()
void AbstractArea::paintIntoRect (QPainter & painter, const QRect & rect) virtual inherited
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite AbstractLayoutItem::paint() instead.
Definition at line 108 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::paintAll().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
position()
const Position TernaryAxis::position () const virtual
Definition at line 128 of file KDChartTernaryAxis.cpp.
Referenced by requiredMargins(), and setPosition().
positionChanged
void KDChart::AbstractArea::positionChanged (AbstractArea *) signal inherited
Referenced by KDChart::AbstractArea::positionHasChanged().
positionHasChanged()
void AbstractArea::positionHasChanged () protected virtual inherited
Reimplemented from KDChart::AbstractAreaBase.
Definition at line 156 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::positionChanged().
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
requiredMargins()
QPair< QSizeF, QSizeF > TernaryAxis::requiredMargins () const
Definition at line 253 of file KDChartTernaryAxis.cpp.
References PrerenderedLabel::pixmap(), position(), KDChartEnums::PositionEast, KDChartEnums::PositionSouth, KDChartEnums::PositionWest, and PrerenderedLabel::referencePointLocation().
Referenced by KDChart::TernaryCoordinatePlane::layoutDiagrams().
resetTitleTextAttributes()
void TernaryAxis::resetTitleTextAttributes ()
Definition at line 187 of file KDChartTernaryAxis.cpp.
Referenced by TernaryAxis().
rightOverlap()
int AbstractArea::rightOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the right edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 82 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
rulerAttributes()
RulerAttributes AbstractAxis::rulerAttributes () const inherited
Returns the attributes to be used for painting the rulers.
See also
setRulerAttributes
Definition at line 209 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::CartesianAxis::paintCtx(), and KDChart::CartesianAxis::tickLength().
setBackgroundAttributes()
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a) inherited
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
setFrameAttributes()
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a) inherited
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
Referenced by KDChart::Legend::clone().
setGeometry()
void TernaryAxis::setGeometry (const QRect & rect) virtual
Implements KDChart::AbstractAxis.
Definition at line 102 of file KDChartTernaryAxis.cpp.
setLabels()
void AbstractAxis::setLabels (const QStringList & list) inherited
Use this to specify your own set of strings, to be used as axis labels.
Labels specified via setLabels take precedence: If a non-empty list is passed, KD Chart will use these strings as axis labels, instead of calculating them.
If you pass a smaller number of strings than the number of labels drawn at this axis, KD Chart will repeat the strings until all labels are drawn. As an example you could specify the seven days of the week as abscissa labels, which would be repeatedly used then.
By passing an empty QStringList you can reset the default behaviour.
See also
labels, setShortLabels
Definition at line 214 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsAbscissa().
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
setPosition()
void TernaryAxis::setPosition (Position p) virtual
Definition at line 133 of file KDChartTernaryAxis.cpp.
References position(), KDChartEnums::PositionEast, KDChartEnums::PositionSouth, KDChartEnums::PositionWest, PrerenderedLabel::setText(), and KDChart::Position::value().
Referenced by TernaryAxis().
setRulerAttributes()
void AbstractAxis::setRulerAttributes (const RulerAttributes & a) inherited
Use this to specify the attributes used to paint the axis ruler.
Every axis has a default set of ruler attributes that is exactly the same among them. Use this method to specify your own attributes.
See also
rulerAttributes
Definition at line 203 of file KDChartAbstractAxis.cpp.
References d.
setShortLabels()
void AbstractAxis::setShortLabels (const QStringList & list) inherited
Use this to specify your own set of strings, to be used as axis labels, in case the normal labels are too long.
Note
Setting done via setShortLabels will be ignored, if you did not pass a non-empty string list via setLabels too!
By passing an empty QStringList you can reset the default behaviour.
See also
shortLabels, setLabels
Definition at line 228 of file KDChartAbstractAxis.cpp.
References d.
setTextAttributes()
void AbstractAxis::setTextAttributes (const TextAttributes & a) inherited
Use this to specify the text attributes to be used for axis labels.
By default, the reference area will be set at painting time. It will be the then-valid coordinate plane's parent widget, so normally, it will be the KDChart::Chart. Thus the labels of all of your axes in all of your diagrams within that Chart will be drawn in same font size, by default.
See also
textAttributes, setLabels
Definition at line 188 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::setType().
setTitleText()
void TernaryAxis::setTitleText (const QString & text)
Definition at line 165 of file KDChartTernaryAxis.cpp.
References PrerenderedLabel::setText().
setTitleTextAttributes()
void TernaryAxis::setTitleTextAttributes (const TextAttributes & a)
Definition at line 176 of file KDChartTernaryAxis.cpp.
shortLabels()
QStringList AbstractAxis::shortLabels () const inherited
Returns a list of strings, that are used as axis labels, as set via setShortLabels.
Note
Setting done via setShortLabels will be ignored, if you did not pass a non-empty string list via setLabels too!
See also
setShortLabels
Definition at line 237 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::compare().
sizeHint()
QSize TernaryAxis::sizeHint () const virtual
Definition at line 118 of file KDChartTernaryAxis.cpp.
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
textAttributes()
TextAttributes AbstractAxis::textAttributes () const inherited
Returns the text attributes to be used for axis labels.
See also
setTextAttributes
Definition at line 197 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::compare(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), KDChart::CartesianAxis::paintCtx(), KDChart::LeveyJenningsAxis::setType(), and KDChart::CartesianAxis::titleTextAttributes().
titleText()
QString TernaryAxis::titleText () const
Definition at line 171 of file KDChartTernaryAxis.cpp.
References PrerenderedLabel::text().
titleTextAttributes()
TextAttributes TernaryAxis::titleTextAttributes () const
Definition at line 182 of file KDChartTernaryAxis.cpp.
topOverlap()
int AbstractArea::topOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the top edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 90 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
update
void KDChart::AbstractAxis::update () slot inherited
Definition at line 259 of file KDChartAbstractAxis.cpp.
References d.
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartTernaryAxis.h
KDChartTernaryAxis.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/