KD Chart 2: PrerenderedLabel Class Reference
PrerenderedLabel Class Reference
PrerenderedLabel is an internal KDChart class that simplifies creation and caching of cached text labels.
#include <KDChartTextLabelCache.h>
Public Member Functions
qreal angle () const
const QBrush & brush () const
const QFont & font () const
const QPen & pen () const
const QPixmap & pixmap () const
Returns the rendered element.
const QPointF & position () const
Get the position of the element.
PrerenderedLabel ()
KDChartEnums::PositionValue referencePoint () const
Get the reference point of the element.
QPointF referencePointLocation (KDChartEnums::PositionValue position) const
Return the location of the reference point relatively to the pixmap's origin.
QPointF referencePointLocation () const
void setAngle (qreal angle)
Sets the angle of the label to angle degrees.
void setBrush (const QBrush &brush)
Sets the label's brush to brush.
void setFont (const QFont &font)
Sets the label's font to font.
void setPen (const QPen &)
void setPosition (const QPointF &position)
Set the position of the element.
void setReferencePoint (KDChartEnums::PositionValue)
Set the reference point of the element.
void setText (const QString &text)
Sets the label's text to text.
const QString & text () const
~PrerenderedLabel ()
Protected Member Functions
void invalidate () const
Invalidates the preredendered data, forces re-rendering.
Detailed Description
PrerenderedLabel is an internal KDChart class that simplifies creation and caching of cached text labels.
It provides referenze points to anchor the text to other elements. Reference points use the positions defined in KDChartEnums.
Usage:
qreal angle = 90.0;
CachedLabel label;
label.paint(font, tr("Label"), angle);
Definition at line 97 of file KDChartTextLabelCache.h.
Constructor & Destructor Documentation
PrerenderedLabel()
PrerenderedLabel::PrerenderedLabel ()
Definition at line 77 of file KDChartTextLabelCache.cpp.
~PrerenderedLabel()
PrerenderedLabel::~PrerenderedLabel ()
Definition at line 87 of file KDChartTextLabelCache.cpp.
References DUMP_CACHE_STATS.
Member Function Documentation
angle()
qreal PrerenderedLabel::angle () const
Returns
the label's angle in degrees
Definition at line 163 of file KDChartTextLabelCache.cpp.
Referenced by setAngle().
brush()
const QBrush & PrerenderedLabel::brush () const
Returns
the label's brush
Definition at line 146 of file KDChartTextLabelCache.cpp.
Referenced by setBrush().
font()
const QFont & PrerenderedLabel::font () const
Returns
the label's font.
Definition at line 112 of file KDChartTextLabelCache.cpp.
Referenced by setFont().
invalidate()
void PrerenderedLabel::invalidate () const protected virtual
Invalidates the preredendered data, forces re-rendering.
Implements PrerenderedElement.
Definition at line 95 of file KDChartTextLabelCache.cpp.
Referenced by setAngle(), setBrush(), setFont(), and setText().
pen()
const QPen& PrerenderedLabel::pen () const
pixmap()
const QPixmap & PrerenderedLabel::pixmap () const virtual
Returns the rendered element.
If any of the properties have change, the element will be regenerated.
Implements PrerenderedElement.
Definition at line 168 of file KDChartTextLabelCache.cpp.
References INC_HIT_COUNT, and INC_MISS_COUNT.
Referenced by KDChart::TernaryAxis::paintCtx(), and KDChart::TernaryAxis::requiredMargins().
position()
const QPointF & PrerenderedElement::position () const inherited
Get the position of the element.
Definition at line 62 of file KDChartTextLabelCache.cpp.
Referenced by KDChart::TernaryAxis::paintCtx(), referencePointLocation(), and PrerenderedElement::setPosition().
referencePoint()
KDChartEnums::PositionValue PrerenderedElement::referencePoint () const inherited
Get the reference point of the element.
Definition at line 72 of file KDChartTextLabelCache.cpp.
Referenced by referencePointLocation().
referencePointLocation() [1/2]
QPointF PrerenderedLabel::referencePointLocation (KDChartEnums::PositionValue) const virtual
Return the location of the reference point relatively to the pixmap's origin.
Implements PrerenderedElement.
Definition at line 290 of file KDChartTextLabelCache.cpp.
References INC_HIT_COUNT, INC_MISS_COUNT, PrerenderedElement::position(), KDChartEnums::PositionCenter, KDChartEnums::PositionEast, KDChartEnums::PositionFloating, KDChartEnums::PositionNorth, KDChartEnums::PositionNorthEast, KDChartEnums::PositionNorthWest, KDChartEnums::PositionSouth, KDChartEnums::PositionSouthEast, KDChartEnums::PositionSouthWest, KDChartEnums::PositionUnknown, and KDChartEnums::PositionWest.
Referenced by KDChart::TernaryAxis::paintCtx(), and KDChart::TernaryAxis::requiredMargins().
referencePointLocation() [2/2]
QPointF PrerenderedLabel::referencePointLocation () const
Definition at line 285 of file KDChartTextLabelCache.cpp.
References PrerenderedElement::referencePoint().
setAngle()
void PrerenderedLabel::setAngle (qreal angle)
Sets the angle of the label to angle degrees.
Definition at line 154 of file KDChartTextLabelCache.cpp.
References angle(), and invalidate().
setBrush()
void PrerenderedLabel::setBrush (const QBrush & brush)
Sets the label's brush to brush.
Definition at line 137 of file KDChartTextLabelCache.cpp.
References brush(), and invalidate().
setFont()
void PrerenderedLabel::setFont (const QFont & font)
Sets the label's font to font.
Definition at line 103 of file KDChartTextLabelCache.cpp.
References font(), and invalidate().
setPen()
void PrerenderedLabel::setPen (const QPen &)
setPosition()
void PrerenderedElement::setPosition (const QPointF & position) inherited
Set the position of the element.
Definition at line 57 of file KDChartTextLabelCache.cpp.
References PrerenderedElement::position().
setReferencePoint()
void PrerenderedElement::setReferencePoint (KDChartEnums::PositionValue point) inherited
Set the reference point of the element.
Every element has nine possible reference points (all compass directions, plus the center.
Definition at line 67 of file KDChartTextLabelCache.cpp.
setText()
void PrerenderedLabel::setText (const QString & text)
Sets the label's text to text.
Definition at line 120 of file KDChartTextLabelCache.cpp.
References invalidate(), and text().
Referenced by KDChart::TernaryAxis::setPosition(), KDChart::TernaryAxis::setTitleText(), and KDChart::TernaryAxis::TernaryAxis().
text()
const QString & PrerenderedLabel::text () const
Returns
the label's text
Definition at line 129 of file KDChartTextLabelCache.cpp.
Referenced by setText(), and KDChart::TernaryAxis::titleText().
The documentation for this class was generated from the following files:
KDChartTextLabelCache.h
KDChartTextLabelCache.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/