KD Chart 2: KDChart::AbstractLayoutItem Class Reference
KDChart::AbstractLayoutItem Class Reference abstract
Base class for all layout items of KD Chart.
#include <KDChartLayoutItems.h>
Public Member Functions
AbstractLayoutItem (Qt::Alignment itemAlignment=0)
virtual void paint (QPainter *)=0
virtual void paintAll (QPainter &painter)
Default impl: just call paint.
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
QLayout * parentLayout ()
void removeFromParentLayout ()
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
Base class for all layout items of KD Chart.
Definition at line 52 of file KDChartLayoutItems.h.
Constructor & Destructor Documentation
AbstractLayoutItem()
KDChart::AbstractLayoutItem::AbstractLayoutItem (Qt::Alignment itemAlignment = 0)
Definition at line 55 of file KDChartLayoutItems.h.
Member Function Documentation
paint()
virtual void KDChart::AbstractLayoutItem::paint (QPainter *) pure virtual
Implemented in KDChart::AutoSpacerLayoutItem, KDChart::CartesianCoordinatePlane, KDChart::VerticalLineLayoutItem, KDChart::HorizontalLineLayoutItem, KDChart::LineWithMarkerLayoutItem, KDChart::LineLayoutItem, KDChart::MarkerLayoutItem, KDChart::TextBubbleLayoutItem, KDChart::PolarCoordinatePlane, KDChart::TextLayoutItem, KDChart::CartesianAxis, KDChart::TernaryAxis, and KDChart::TernaryCoordinatePlane.
Referenced by KDChart::Legend::paint(), and KDChart::AbstractArea::paintAll().
paintAll()
void KDChart::AbstractLayoutItem::paintAll (QPainter & painter) virtual
Default impl: just call paint.
Derived classes like KDChart::AbstractArea are providing additional action here.
Reimplemented in KDChart::AbstractArea, KDChart::TextArea, and KDChart::TernaryAxis.
Definition at line 64 of file KDChartLayoutItems.cpp.
paintCtx()
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout ()
Definition at line 78 of file KDChartLayoutItems.h.
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout ()
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay)
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartLayoutItems.h
KDChartLayoutItems.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/