KD Chart 2: KDChart::PieAttributes Class Reference
KDChart::PieAttributes Class Reference
A set of attributes controlling the appearance of pie charts.
#include <KDChartPieAttributes.h>
Public Member Functions
bool explode () const
qreal explodeFactor () const
qreal gapFactor (bool circular) const
bool operator!= (const PieAttributes &other) const
PieAttributes & operator= (const PieAttributes &)
bool operator== (const PieAttributes &) const
PieAttributes ()
PieAttributes (const PieAttributes &)
void setExplode (bool explode)
Enable or disable exploding the respective pie piece(s).
void setExplodeFactor (qreal factor)
Set the explode factor.
void setGapFactor (bool circular, qreal factor)
~PieAttributes ()
Detailed Description
A set of attributes controlling the appearance of pie charts.
Definition at line 35 of file KDChartPieAttributes.h.
Constructor & Destructor Documentation
PieAttributes() [1/2]
PieAttributes::PieAttributes ()
Definition at line 44 of file KDChartPieAttributes.cpp.
PieAttributes() [2/2]
PieAttributes::PieAttributes (const PieAttributes & r)
Definition at line 49 of file KDChartPieAttributes.cpp.
~PieAttributes()
PieAttributes::~PieAttributes ()
Definition at line 64 of file KDChartPieAttributes.cpp.
Member Function Documentation
explode()
bool PieAttributes::explode () const
Returns
whether the respective pie piece(s) will be exploded.
Definition at line 89 of file KDChartPieAttributes.cpp.
References d.
Referenced by KDChart::RingDiagram::paint().
explodeFactor()
qreal PieAttributes::explodeFactor () const
Returns
the explode factor set by setExplode or by setExplodeFactor.
Definition at line 99 of file KDChartPieAttributes.cpp.
References d.
Referenced by KDChart::RingDiagram::calculateDataBoundaries(), KDChart::PieDiagram::calculateDataBoundaries(), operator<<(), operator==(), and KDChart::RingDiagram::paint().
gapFactor()
qreal PieAttributes::gapFactor (bool circular) const
Definition at line 112 of file KDChartPieAttributes.cpp.
References d.
Referenced by operator==(), and KDChart::RingDiagram::paint().
operator!=()
bool KDChart::PieAttributes::operator!= (const PieAttributes & other) const
Definition at line 75 of file KDChartPieAttributes.h.
References KDGantt::operator==().
operator=()
PieAttributes & PieAttributes::operator= (const PieAttributes & r)
Definition at line 54 of file KDChartPieAttributes.cpp.
References d.
operator==()
bool PieAttributes::operator== (const PieAttributes & r) const
Definition at line 70 of file KDChartPieAttributes.cpp.
References explodeFactor(), and gapFactor().
setExplode()
void PieAttributes::setExplode (bool explode)
Enable or disable exploding the respective pie piece(s).
The default explode factor is 10 percent; use setExplodeFactor to specify a different factor.
Note
This is a convenience function: Calling setExplode(true) does the same as calling setExplodeFactor(0.1), and calling setExplode(false) does the same as calling setExplodeFactor(0.0).
See also
setExplodeFactor
Definition at line 84 of file KDChartPieAttributes.cpp.
References d.
setExplodeFactor()
void PieAttributes::setExplodeFactor (qreal factor)
Set the explode factor.
The explode factor is a qreal between 0 and 1, and is interpreted as a percentage of the total available radius of the pie.
See also
setExplode
Definition at line 94 of file KDChartPieAttributes.cpp.
References d.
setGapFactor()
void PieAttributes::setGapFactor (bool circular, qreal factor)
Definition at line 104 of file KDChartPieAttributes.cpp.
References d.
The documentation for this class was generated from the following files:
KDChartPieAttributes.h
KDChartPieAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/