KD Chart 2: KDGantt::ProxyModel Class Reference
KDGantt::ProxyModel Class Reference
#include <kdganttproxymodel.h>
Public Member Functions
int column (int ganttrole) const
int columnCount (const QModelIndex &idx) const
QVariant data (const QModelIndex &idx, int role=Qt::DisplayRole) const
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex mapFromSource (const QModelIndex &idx) const
QModelIndex mapToSource (const QModelIndex &proxyIdx) const
QMimeData * mimeData (const QModelIndexList &indexes) const
QStringList mimeTypes () const
QModelIndex parent (const QModelIndex &idx) const
ProxyModel (QObject *parent=0)
int role (int ganttrole) const
int rowCount (const QModelIndex &idx) const
void setColumn (int ganttrole, int col)
bool setData (const QModelIndex &idx, const QVariant &value, int role=Qt::EditRole)
void setRole (int ganttrole, int role)
void setSourceModel (QAbstractItemModel *model)
Qt::DropActions supportedDropActions () const
virtual ~ProxyModel ()
Protected Slots
virtual void sourceColumnsAboutToBeInserted (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsAboutToBeRemoved (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsInserted (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsRemoved (const QModelIndex &idx, int start, int end)
virtual void sourceDataChanged (const QModelIndex &from, const QModelIndex &to)
virtual void sourceLayoutAboutToBeChanged ()
virtual void sourceLayoutChanged ()
virtual void sourceModelAboutToBeReset ()
virtual void sourceModelReset ()
virtual void sourceRowsAboutToBeInserted (const QModelIndex &idx, int start, int end)
virtual void sourceRowsAboutToBeRemoved (const QModelIndex &, int start, int end)
virtual void sourceRowsInserted (const QModelIndex &idx, int start, int end)
virtual void sourceRowsRemoved (const QModelIndex &, int start, int end)
Detailed Description
Definition at line 29 of file kdganttproxymodel.h.
Constructor & Destructor Documentation
ProxyModel()
ProxyModel::ProxyModel (QObject * parent = 0) explicit
Definition at line 53 of file kdganttproxymodel.cpp.
~ProxyModel()
ProxyModel::~ProxyModel () virtual
Definition at line 59 of file kdganttproxymodel.cpp.
Member Function Documentation
column()
int ProxyModel::column (int ganttrole) const
Definition at line 112 of file kdganttproxymodel.cpp.
References d.
columnCount()
int ProxyModel::columnCount (const QModelIndex & idx) const
Definition at line 148 of file kdganttproxymodel.cpp.
References mapToSource().
data()
QVariant ProxyModel::data (const QModelIndex & idx, int role = Qt::DisplayRole) const
Definition at line 153 of file kdganttproxymodel.cpp.
References d, KDGantt::ForwardingProxyModel::index(), mapToSource(), and role().
dropMimeData()
bool ForwardingProxyModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) inherited
Definition at line 294 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::index(), KDGantt::ForwardingProxyModel::mapToSource(), KDGantt::ForwardingProxyModel::parent(), and KDGantt::ForwardingProxyModel::rowCount().
index()
QModelIndex ForwardingProxyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const inherited
See also
QAbstractItemModel::index
Definition at line 268 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource(), KDGantt::ForwardingProxyModel::mapToSource(), and KDGantt::ForwardingProxyModel::parent().
Referenced by data(), KDGantt::ForwardingProxyModel::dropMimeData(), KDAB_SCOPED_UNITTEST_SIMPLE(), KDGantt::SummaryHandlingProxyModel::setData(), and KDGantt::ForwardingProxyModel::setData().
mapFromSource()
QModelIndex ProxyModel::mapFromSource (const QModelIndex & idx) const
Definition at line 70 of file kdganttproxymodel.cpp.
mapToSource()
QModelIndex ProxyModel::mapToSource (const QModelIndex & proxyIdx) const
Definition at line 92 of file kdganttproxymodel.cpp.
Referenced by columnCount(), data(), and setData().
mimeData()
QMimeData * ForwardingProxyModel::mimeData (const QModelIndexList & indexes) const inherited
Definition at line 286 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapToSource().
mimeTypes()
QStringList ForwardingProxyModel::mimeTypes () const inherited
Definition at line 314 of file kdganttforwardingproxymodel.cpp.
parent()
QModelIndex ForwardingProxyModel::parent (const QModelIndex & idx) const inherited
See also
QAbstractItemModel::parent
Definition at line 274 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource(), and KDGantt::ForwardingProxyModel::mapToSource().
Referenced by KDGantt::ForwardingProxyModel::dropMimeData(), and KDGantt::ForwardingProxyModel::index().
role()
int ProxyModel::role (int ganttrole) const
Definition at line 122 of file kdganttproxymodel.cpp.
References d.
Referenced by data(), setData(), and setRole().
rowCount()
int ProxyModel::rowCount (const QModelIndex & idx) const
Definition at line 142 of file kdganttproxymodel.cpp.
setColumn()
void ProxyModel::setColumn (int ganttrole, int col)
Definition at line 107 of file kdganttproxymodel.cpp.
References d.
setData()
bool ProxyModel::setData (const QModelIndex & idx, const QVariant & value, int role = Qt::EditRole)
Definition at line 174 of file kdganttproxymodel.cpp.
References d, mapToSource(), and role().
setRole()
void ProxyModel::setRole (int ganttrole, int role)
Definition at line 117 of file kdganttproxymodel.cpp.
References d, and role().
setSourceModel()
void ForwardingProxyModel::setSourceModel (QAbstractItemModel * model) inherited
Sets the model to be used as the source model for this proxy. The proxy does not take ownership of the model.
See also
QAbstractProxyModel::setSourceModel
Definition at line 93 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::sourceColumnsAboutToBeInserted(), KDGantt::ForwardingProxyModel::sourceColumnsAboutToBeRemoved(), KDGantt::ForwardingProxyModel::sourceColumnsInserted(), KDGantt::ForwardingProxyModel::sourceColumnsRemoved(), KDGantt::ForwardingProxyModel::sourceDataChanged(), KDGantt::ForwardingProxyModel::sourceLayoutAboutToBeChanged(), KDGantt::ForwardingProxyModel::sourceLayoutChanged(), KDGantt::ForwardingProxyModel::sourceModelAboutToBeReset(), KDGantt::ForwardingProxyModel::sourceModelReset(), KDGantt::ForwardingProxyModel::sourceRowsAboutToBeInserted(), KDGantt::ForwardingProxyModel::sourceRowsAboutToBeRemoved(), KDGantt::ForwardingProxyModel::sourceRowsInserted(), and KDGantt::ForwardingProxyModel::sourceRowsRemoved().
sourceColumnsAboutToBeInserted
void ForwardingProxyModel::sourceColumnsAboutToBeInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called just before columns are inserted into the source model.
See also
QAbstractItemModel::columnsAboutToBeInserted()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 178 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource().
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceColumnsAboutToBeRemoved
void ForwardingProxyModel::sourceColumnsAboutToBeRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called just before columns are removed from the source model.
See also
QAbstractItemModel::columnsAboutToBeRemoved()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 199 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource().
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceColumnsInserted
void ForwardingProxyModel::sourceColumnsInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after columns have been inserted into the source model.
See also
QAbstractItemModel::columnsInserted()
Definition at line 188 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceColumnsRemoved
void ForwardingProxyModel::sourceColumnsRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after columns have been removed from the source model.
See also
QAbstractItemModel::columnsRemoved()
Definition at line 209 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceDataChanged
void ForwardingProxyModel::sourceDataChanged (const QModelIndex & from, const QModelIndex & to) protected virtual slot inherited
Called when the data in an existing item in the source model changes.
See also
QAbstractItemModel::dataChanged()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 169 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource().
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceLayoutAboutToBeChanged
void ForwardingProxyModel::sourceLayoutAboutToBeChanged () protected virtual slot inherited
Called just before the layout of the source model is changed.
See also
QAbstractItemModel::layoutAboutToBeChanged()
Definition at line 150 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceLayoutChanged
void ForwardingProxyModel::sourceLayoutChanged () protected virtual slot inherited
Called when the layout of the source model has changed.
See also
QAbstractItemModel::layoutChanged()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 159 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceModelAboutToBeReset
void ForwardingProxyModel::sourceModelAboutToBeReset () protected virtual slot inherited
Called when the source model is about to be reset.
See also
QAbstractItemModel::modelAboutToBeReset()
Definition at line 131 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceModelReset
void ForwardingProxyModel::sourceModelReset () protected virtual slot inherited
Called when the source model is reset
See also
QAbstractItemModel::modelReset()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 139 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceRowsAboutToBeInserted
void ForwardingProxyModel::sourceRowsAboutToBeInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called just before rows are inserted into the source model.
See also
QAbstractItemModel::rowsAboutToBeInserted()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 220 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource().
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceRowsAboutToBeRemoved
void ForwardingProxyModel::sourceRowsAboutToBeRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called just before rows are removed from the source model.
See also
QAbstractItemModel::rowsAboutToBeRemoved()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 239 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource().
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceRowsInserted
void ForwardingProxyModel::sourceRowsInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after rows have been inserted into the source model.
See also
QAbstractItemModel::rowsInserted()
Definition at line 228 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceRowsRemoved
void ForwardingProxyModel::sourceRowsRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after rows have been removed from the source model.
See also
QAbstractItemModel::rowsRemoved()
Definition at line 247 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
supportedDropActions()
Qt::DropActions ForwardingProxyModel::supportedDropActions () const inherited
Definition at line 319 of file kdganttforwardingproxymodel.cpp.
The documentation for this class was generated from the following files:
kdganttproxymodel.h
kdganttproxymodel.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/