KD Chart 2: KDChart::StockBarAttributes Class Reference
KDChart::StockBarAttributes Class Reference
Attributes to customize the appearance of a column in a stock chart.
#include <KDChartStockBarAttributes.h>
Public Member Functions
qreal candlestickWidth () const
bool operator!= (const StockBarAttributes &other) const
StockBarAttributes & operator= (const StockBarAttributes &)
bool operator== (const StockBarAttributes &) const
void setCandlestickWidth (qreal width)
Sets the width of a candlestick.
void setTickLength (qreal length)
Sets the tick length of both the open and close marker.
StockBarAttributes ()
StockBarAttributes (const StockBarAttributes &)
qreal tickLength () const
~StockBarAttributes ()
Detailed Description
Attributes to customize the appearance of a column in a stock chart.
Definition at line 34 of file KDChartStockBarAttributes.h.
Constructor & Destructor Documentation
StockBarAttributes() [1/2]
StockBarAttributes::StockBarAttributes ()
Definition at line 43 of file KDChartStockBarAttributes.cpp.
StockBarAttributes() [2/2]
StockBarAttributes::StockBarAttributes (const StockBarAttributes & r)
Definition at line 48 of file KDChartStockBarAttributes.cpp.
~StockBarAttributes()
StockBarAttributes::~StockBarAttributes ()
Definition at line 63 of file KDChartStockBarAttributes.cpp.
Member Function Documentation
candlestickWidth()
qreal StockBarAttributes::candlestickWidth () const
Returns
the width of a candlestick
Definition at line 80 of file KDChartStockBarAttributes.cpp.
References d.
Referenced by operator==().
operator!=()
bool KDChart::StockBarAttributes::operator!= (const StockBarAttributes & other) const
Definition at line 50 of file KDChartStockBarAttributes.h.
References KDGantt::operator==().
operator=()
StockBarAttributes & StockBarAttributes::operator= (const StockBarAttributes & r)
Definition at line 53 of file KDChartStockBarAttributes.cpp.
References d.
operator==()
bool StockBarAttributes::operator== (const StockBarAttributes & r) const
Definition at line 103 of file KDChartStockBarAttributes.cpp.
References candlestickWidth(), and tickLength().
setCandlestickWidth()
void StockBarAttributes::setCandlestickWidth (qreal width)
Sets the width of a candlestick.
Parameters
width The width of a candlestick
Definition at line 73 of file KDChartStockBarAttributes.cpp.
References d.
setTickLength()
void StockBarAttributes::setTickLength (qreal length)
Sets the tick length of both the open and close marker.
Parameters
length the tick length
Definition at line 90 of file KDChartStockBarAttributes.cpp.
References d.
tickLength()
qreal StockBarAttributes::tickLength () const
Returns
the tick length used for both the open and close marker
Definition at line 98 of file KDChartStockBarAttributes.cpp.
References d.
Referenced by operator==().
The documentation for this class was generated from the following files:
KDChartStockBarAttributes.h
KDChartStockBarAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/