KD Chart 2: KDChart::AbstractProxyModel Class Reference
KDChart::AbstractProxyModel Class Reference
Base class for all proxy models used inside KD Chart.
#include <KDChartAbstractProxyModel.h>
Public Member Functions
AbstractProxyModel (QObject *parent=0)
This is basically KDAbstractProxyModel, but only the bits that we really need from it.
QModelIndex index (int row, int col, const QModelIndex &index) const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
QModelIndex parent (const QModelIndex &index) const
Detailed Description
Base class for all proxy models used inside KD Chart.
Definition at line 36 of file KDChartAbstractProxyModel.h.
Constructor & Destructor Documentation
AbstractProxyModel()
KDChart::AbstractProxyModel::AbstractProxyModel (QObject * parent = 0) explicit
This is basically KDAbstractProxyModel, but only the bits that we really need from it.
Definition at line 41 of file KDChartAbstractProxyModel.cpp.
Member Function Documentation
index()
QModelIndex KDChart::AbstractProxyModel::index (int row, int col, const QModelIndex & index) const
[reimplemented]
Definition at line 87 of file KDChartAbstractProxyModel.cpp.
References mapFromSource(), and mapToSource().
Referenced by KDChart::AttributesModel::columnCount(), KDChart::AttributesModel::data(), parent(), KDChart::AttributesModel::resetData(), KDChart::AttributesModel::rowCount(), KDChart::AttributesModel::setData(), and KDChart::AttributesModel::setHeaderData().
mapFromSource()
QModelIndex KDChart::AbstractProxyModel::mapFromSource (const QModelIndex & sourceIndex) const
[reimplemented]
Definition at line 55 of file KDChartAbstractProxyModel.cpp.
Referenced by index(), and parent().
mapToSource()
QModelIndex KDChart::AbstractProxyModel::mapToSource (const QModelIndex & proxyIndex) const
[reimplemented]
Definition at line 68 of file KDChartAbstractProxyModel.cpp.
Referenced by KDChart::AttributesModel::columnCount(), KDChart::AttributesModel::data(), index(), parent(), KDChart::AttributesModel::rowCount(), and KDChart::AttributesModel::setData().
parent()
QModelIndex KDChart::AbstractProxyModel::parent (const QModelIndex & index) const
[reimplemented]
Definition at line 93 of file KDChartAbstractProxyModel.cpp.
References index(), mapFromSource(), and mapToSource().
The documentation for this class was generated from the following files:
KDChartAbstractProxyModel.h
KDChartAbstractProxyModel.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/