KD Chart 2: KDChart::TextArea Class Reference
KDChart::TextArea Class Reference
A text area in the chart with a background, a frame, etc.
#include <KDChartTextArea.h>
Signals
void positionChanged (TextArea *)
Public Member Functions
void alignToReferencePoint (const RelativePosition &position)
const QObject * autoReferenceArea () const
BackgroundAttributes backgroundAttributes () const
QPolygon boundingPolygon () const
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
virtual Qt::Orientations expandingDirections () const
pure virtual in QLayoutItem
FrameAttributes frameAttributes () const
virtual QRect geometry () const
pure virtual in QLayoutItem
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
virtual bool intersects (const TextLayoutItem &other, const QPointF &myPos, const QPointF &otherPos) const
virtual bool intersects (const TextLayoutItem &other, const QPoint &myPos, const QPoint &otherPos) const
virtual bool isEmpty () const
pure virtual in QLayoutItem
virtual int marginWidth () const
virtual QSize maximumSize () const
pure virtual in QLayoutItem
virtual QSize minimumSize () const
pure virtual in QLayoutItem
virtual void paint (QPainter *)
void paintAll (QPainter &painter)
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
virtual void paintIntoRect (QPainter &painter, const QRect &rect)
Draws the background and frame, then calls paint().
QLayout * parentLayout ()
virtual QFont realFont () const
virtual qreal realFontSize () const
void removeFromParentLayout ()
void setAutoReferenceArea (const QObject *area)
void setBackgroundAttributes (const BackgroundAttributes &a)
void setFrameAttributes (const FrameAttributes &a)
virtual void setGeometry (const QRect &r)
pure virtual in QLayoutItem
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
void setText (const QString &text)
void setTextAlignment (Qt::Alignment)
void setTextAttributes (const TextAttributes &a)
Use this to specify the text attributes to be used for this item.
virtual QSize sizeHint () const
pure virtual in QLayoutItem
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
virtual QSize sizeHintUnrotated () const
QString text () const
Qt::Alignment textAlignment () const
TextAttributes textAttributes () const
Returns the text attributes to be used for this item.
virtual ~TextArea ()
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Member Functions
virtual QRect areaGeometry () const
QRect innerRect () const
virtual void positionHasChanged ()
TextArea ()
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
A text area in the chart with a background, a frame, etc.
TextArea is the base class for all text containing non-widget chart elements that have a set of background attributes and frame attributes, such as headers or footers.
Note
This class inherits AbstractAreaBase, TextLayoutItem, and QObject. The reason for this triple inheritance is that neither AbstractAreaBase nor TextLayoutItem inherit QObject.
Definition at line 47 of file KDChartTextArea.h.
Constructor & Destructor Documentation
~TextArea()
TextArea::~TextArea () virtual
Definition at line 57 of file KDChartTextArea.cpp.
TextArea()
TextArea::TextArea () protected
Definition at line 49 of file KDChartTextArea.cpp.
Member Function Documentation
alignToReferencePoint()
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position) inherited
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
areaGeometry()
QRect TextArea::areaGeometry () const protected virtual
Implements KDChart::AbstractAreaBase.
Definition at line 102 of file KDChartTextArea.cpp.
References KDChart::TextLayoutItem::geometry().
Referenced by paintAll().
autoReferenceArea()
const QObject * KDChart::TextLayoutItem::autoReferenceArea () const inherited
Definition at line 239 of file KDChartLayoutItems.cpp.
Referenced by KDChart::HeaderFooter::compare(), and KDChart::HeaderFooter::setParent().
backgroundAttributes()
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const inherited
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
boundingPolygon()
QPolygon KDChart::TextLayoutItem::boundingPolygon () const inherited
Definition at line 392 of file KDChartLayoutItems.cpp.
Referenced by KDChart::TextLayoutItem::intersects(), and KDChart::CartesianAxis::paintCtx().
compare()
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const inherited
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), and KDChart::AbstractAreaBase::frameAttributes().
Referenced by KDChart::Legend::compare().
expandingDirections()
Qt::Orientations KDChart::TextLayoutItem::expandingDirections () const virtual inherited
pure virtual in QLayoutItem
Definition at line 298 of file KDChartLayoutItems.cpp.
frameAttributes()
FrameAttributes AbstractAreaBase::frameAttributes () const inherited
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::Legend::clone(), KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
geometry()
QRect KDChart::TextLayoutItem::geometry () const virtual inherited
pure virtual in QLayoutItem
Definition at line 303 of file KDChartLayoutItems.cpp.
Referenced by areaGeometry(), paintAll(), and paintIntoRect().
getFrameLeadings()
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const inherited
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::innerRect(), and KDChart::AbstractAreaWidget::paintAll().
innerRect()
QRect AbstractAreaBase::innerRect () const protected inherited
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::areaGeometry(), and KDChart::AbstractAreaBase::getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and paintAll().
intersects() [1/2]
bool KDChart::TextLayoutItem::intersects (const TextLayoutItem & other, const QPointF & myPos, const QPointF & otherPos) const virtual inherited
Definition at line 398 of file KDChartLayoutItems.cpp.
Referenced by KDChart::CartesianAxis::paintCtx().
intersects() [2/2]
bool KDChart::TextLayoutItem::intersects (const TextLayoutItem & other, const QPoint & myPos, const QPoint & otherPos) const virtual inherited
Definition at line 403 of file KDChartLayoutItems.cpp.
References KDChart::TextLayoutItem::boundingPolygon().
isEmpty()
bool KDChart::TextLayoutItem::isEmpty () const virtual inherited
pure virtual in QLayoutItem
Definition at line 308 of file KDChartLayoutItems.cpp.
marginWidth()
int KDChart::TextLayoutItem::marginWidth () const virtual inherited
Definition at line 447 of file KDChartLayoutItems.cpp.
Referenced by KDChart::CartesianAxis::paintCtx().
maximumSize()
QSize KDChart::TextLayoutItem::maximumSize () const virtual inherited
pure virtual in QLayoutItem
Definition at line 313 of file KDChartLayoutItems.cpp.
minimumSize()
QSize KDChart::TextLayoutItem::minimumSize () const virtual inherited
pure virtual in QLayoutItem
Definition at line 318 of file KDChartLayoutItems.cpp.
paint()
void KDChart::TextLayoutItem::paint (QPainter * painter) virtual inherited
Implements KDChart::AbstractLayoutItem.
Definition at line 490 of file KDChartLayoutItems.cpp.
References fitFontSizeToGeometry(), and KDChart::PrintingParameters::scalePen().
Referenced by paintAll(), and KDChart::CartesianAxis::paintCtx().
paintAll()
void TextArea::paintAll (QPainter & painter) virtual
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
Reimplemented from KDChart::AbstractLayoutItem.
Definition at line 80 of file KDChartTextArea.cpp.
References areaGeometry(), KDChart::TextLayoutItem::geometry(), KDChart::AbstractAreaBase::innerRect(), KDChart::TextLayoutItem::paint(), KDChart::AbstractAreaBase::paintBackground(), KDChart::AbstractAreaBase::paintFrame(), and KDChart::TextLayoutItem::setGeometry().
Referenced by paintIntoRect().
paintBackground()
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintBackgroundAttributes()
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static inherited
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by KDChart::AbstractAreaBase::paintBackground().
paintCtx()
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual inherited
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
paintFrame()
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintFrameAttributes()
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static inherited
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::AbstractAreaBase::paintFrame().
paintIntoRect()
void TextArea::paintIntoRect (QPainter & painter, const QRect & rect) virtual
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite TextLayoutItem::paint() instead.
Definition at line 68 of file KDChartTextArea.cpp.
References KDChart::TextLayoutItem::geometry(), paintAll(), and KDChart::TextLayoutItem::setGeometry().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
positionChanged
void KDChart::TextArea::positionChanged (TextArea *) signal
Referenced by positionHasChanged().
positionHasChanged()
void TextArea::positionHasChanged () protected virtual
Reimplemented from KDChart::AbstractAreaBase.
Definition at line 107 of file KDChartTextArea.cpp.
References positionChanged().
realFont()
QFont KDChart::TextLayoutItem::realFont () const virtual inherited
Definition at line 386 of file KDChartLayoutItems.cpp.
Referenced by KDChart::CartesianAxis::paintCtx().
realFontSize()
qreal KDChart::TextLayoutItem::realFontSize () const virtual inherited
Definition at line 369 of file KDChartLayoutItems.cpp.
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
setAutoReferenceArea()
void KDChart::TextLayoutItem::setAutoReferenceArea (const QObject * area) inherited
Definition at line 232 of file KDChartLayoutItems.cpp.
Referenced by KDChart::HeaderFooter::setParent().
setBackgroundAttributes()
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a) inherited
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
setFrameAttributes()
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a) inherited
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
Referenced by KDChart::Legend::clone().
setGeometry()
void KDChart::TextLayoutItem::setGeometry (const QRect & r) virtual inherited
pure virtual in QLayoutItem
Definition at line 323 of file KDChartLayoutItems.cpp.
Referenced by paintAll(), KDChart::CartesianAxis::paintCtx(), and paintIntoRect().
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
setText()
void KDChart::TextLayoutItem::setText (const QString & text) inherited
Definition at line 244 of file KDChartLayoutItems.cpp.
Referenced by KDChart::Widget::addHeaderFooter(), KDChart::HeaderFooter::clone(), and KDChart::CartesianAxis::paintCtx().
setTextAlignment()
void KDChart::TextLayoutItem::setTextAlignment (Qt::Alignment alignment) inherited
Definition at line 258 of file KDChartLayoutItems.cpp.
setTextAttributes()
void KDChart::TextLayoutItem::setTextAttributes (const TextAttributes & a) inherited
Use this to specify the text attributes to be used for this item.
See also
textAttributes
Definition at line 277 of file KDChartLayoutItems.cpp.
References KDChart::TextAttributes::font().
Referenced by KDChart::Chart::addHeaderFooter(), KDChart::HeaderFooter::clone(), and KDChart::CartesianAxis::paintCtx().
sizeHint()
QSize KDChart::TextLayoutItem::sizeHint () const virtual inherited
pure virtual in QLayoutItem
Definition at line 411 of file KDChartLayoutItems.cpp.
Referenced by KDChart::LeveyJenningsAxis::paintAsAbscissa(), and KDChart::CartesianAxis::paintCtx().
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
sizeHintUnrotated()
QSize KDChart::TextLayoutItem::sizeHintUnrotated () const virtual inherited
Definition at line 425 of file KDChartLayoutItems.cpp.
text()
QString KDChart::TextLayoutItem::text () const inherited
Definition at line 253 of file KDChartLayoutItems.cpp.
Referenced by KDChart::HeaderFooter::clone(), and KDChart::HeaderFooter::compare().
textAlignment()
Qt::Alignment KDChart::TextLayoutItem::textAlignment () const inherited
Definition at line 267 of file KDChartLayoutItems.cpp.
textAttributes()
KDChart::TextAttributes KDChart::TextLayoutItem::textAttributes () const inherited
Returns the text attributes to be used for this item.
See also
setTextAttributes
Definition at line 292 of file KDChartLayoutItems.cpp.
Referenced by KDChart::Chart::addHeaderFooter(), KDChart::HeaderFooter::clone(), and KDChart::HeaderFooter::compare().
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartTextArea.h
KDChartTextArea.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/