KD Chart 2: KDChart::Legend Class Reference
KDChart::Legend Class Reference
Legend defines the interface for the legend drawing class.
#include <KDChartLegend.h>
Public Types
enum LegendStyle {
MarkersOnly = 0,
LinesOnly = 1,
MarkersAndLines = 2
}
Signals
void destroyedLegend (Legend *)
void positionChanged (AbstractAreaWidget *)
void propertiesChanged ()
Emitted upon change of a property of the Legend or any of its components.
Public Member Functions
void addDiagram (KDChart::AbstractDiagram *newDiagram)
Add the given diagram to the legend.
Qt::Alignment alignment () const
Returns the alignment of a non-floating legend.
void alignToReferencePoint (const RelativePosition &position)
BackgroundAttributes backgroundAttributes () const
QBrush brush (uint dataset) const
const QMap< uint, QBrush > brushes () const
virtual Legend * clone () const
Creates an exact copy of this legend.
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
bool compare (const Legend *other) const
Returns true if both legends have the same settings.
ConstDiagramList constDiagrams () const
uint datasetCount () const
bool datasetIsHidden (uint dataset) const
uint dataSetOffset (KDChart::AbstractDiagram *diagram)
Returns the offset of the first dataset of diagram.
KDChart::AbstractDiagram * diagram () const
The first diagram of the legend or 0 if there was none added to the legend.
DiagramList diagrams () const
The list of all diagrams associated with the legend.
const RelativePosition floatingPosition () const
Returns the position of a floating legend.
virtual void forceRebuild ()
Call this to trigger an unconditional re-building of the widget's internals.
FrameAttributes frameAttributes () const
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
virtual bool hasHeightForWidth () const
virtual int heightForWidth (int width) const
const QList< uint > hiddenDatasets () const
Legend (QWidget *parent=0)
Legend (KDChart::AbstractDiagram *diagram, QWidget *parent=0)
LegendStyle legendStyle () const
Qt::Alignment legendSymbolAlignment () const
Returns the alignment used while drawing legend symbol(alignment of Legend::LinesOnly) within the legend.
MarkerAttributes markerAttributes (uint dataset) const
const QMap< uint, MarkerAttributes > markerAttributes () const
virtual QSize minimumSizeHint () const
virtual void needSizeHint ()
Call this to trigger an conditional re-building of the widget's internals.
Qt::Orientation orientation () const
virtual void paint (QPainter *painter)
Overwrite this to paint the inner contents of your widget.
void paintAll (QPainter &painter)
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintEvent (QPaintEvent *event)
Draws the background and frame, then calls paint().
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
virtual void paintIntoRect (QPainter &painter, const QRect &rect)
Draws the background and frame, then calls paint().
QPen pen (uint dataset) const
const QMap< uint, QPen > pens () const
Position position () const
Returns the position of a non-floating legend.
const QWidget * referenceArea () const
Returns the reference area, that is used for font size of title text, and for font size of the item texts, IF automatic area detection is set.
void removeDiagram (KDChart::AbstractDiagram *oldDiagram)
Removes the diagram from the legend's list of diagrams.
void removeDiagrams ()
Removes all diagrams from the legend's list of diagrams.
void replaceDiagram (KDChart::AbstractDiagram *newDiagram, KDChart::AbstractDiagram *oldDiagram=0)
Replaces the old diagram, or appends the new diagram, it there is none yet.
void resetTexts ()
Removes all legend texts that might have been set by setText.
virtual void resizeEvent (QResizeEvent *event)
virtual void resizeLayout (const QSize &size)
void setAlignment (Qt::Alignment)
Specify the alignment of a non-floating legend.
void setBackgroundAttributes (const BackgroundAttributes &a)
void setBrush (uint dataset, const QBrush &brush)
void setBrushesFromDiagram (KDChart::AbstractDiagram *diagram)
void setColor (uint dataset, const QColor &color)
Note: there is no color() getter method, since setColor just sets a QBrush with the respective color, so the brush() getter method is sufficient.
void setDatasetHidden (uint dataset, bool hidden)
void setDefaultColors ()
void setDiagram (KDChart::AbstractDiagram *newDiagram)
A convenience method doing the same as replaceDiagram(newDiagram, 0);.
void setFloatingPosition (const RelativePosition &relativePosition)
Specify the position and alignment of a floating legend.
void setFrameAttributes (const FrameAttributes &a)
void setHiddenDatasets (const QList< uint > hiddenDatasets)
Sets a list of datasets that are to be hidden in the legend.
void setLegendStyle (LegendStyle style)
void setLegendSymbolAlignment (Qt::Alignment)
Specify the alignment of the legend symbol(alignment of Legend::LinesOnly) within the legend.
void setMarkerAttributes (uint dataset, const MarkerAttributes &)
Note that any sizes specified via setMarkerAttributes are ignored, unless you disable the automatic size calculation, by saying setUseAutomaticMarkerSize(false)
void setOrientation (Qt::Orientation orientation)
void setPen (uint dataset, const QPen &pen)
void setPosition (Position position)
Specify the position of a non-floating legend.
void setRainbowColors ()
void setReferenceArea (const QWidget *area)
Specifies the reference area for font size of title text, and for font size of the item texts, IF automatic area detection is set.
void setShowLines (bool legendShowLines)
void setSortOrder (Qt::SortOrder order)
void setSpacing (uint space)
void setSubduedColors (bool ordered=false)
void setText (uint dataset, const QString &text)
void setTextAlignment (Qt::Alignment)
Specify the alignment of the text elements within the legend.
void setTextAttributes (const TextAttributes &a)
void setTitleText (const QString &text)
void setTitleTextAttributes (const TextAttributes &a)
void setUseAutomaticMarkerSize (bool useAutomaticMarkerSize)
This option is on by default, it means that Marker sizes in the Legend will be the same as the font height used for their respective label texts.
virtual void setVisible (bool visible)
bool showLines () const
virtual QSize sizeHint () const
Qt::SortOrder sortOrder () const
uint spacing () const
QString text (uint dataset) const
Qt::Alignment textAlignment () const
Returns the alignment used while rendering text elements within the legend.
TextAttributes textAttributes () const
const QMap< uint, QString > texts () const
QString titleText () const
TextAttributes titleTextAttributes () const
bool useAutomaticMarkerSize () const
virtual ~Legend ()
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Member Functions
virtual QRect areaGeometry () const
QRect innerRect () const
virtual void positionHasChanged ()
Detailed Description
Legend defines the interface for the legend drawing class.
Legend is the class for drawing legends for all kinds of diagrams ("chart types").
Legend is drawn on chart level, not per diagram, but you can have more than one legend per chart, using KDChart::Chart::addLegend().
Note
Legend is different from all other classes ofd KD Chart, since it can be displayed outside of the Chart's area. If you want to, you can embedd the legend into your own widget, or into another part of a bigger layout, into which you might have inserted the Chart.
On the other hand, please note that you MUST call Chart::addLegend to get your legend positioned into the correct place of your chart - if you want to have the legend shown inside of the chart (that's probably true for most cases).
Definition at line 55 of file KDChartLegend.h.
Member Enumeration Documentation
LegendStyle
enum KDChart::Legend::LegendStyle
Enumerator
MarkersOnly
LinesOnly
MarkersAndLines
Definition at line 68 of file KDChartLegend.h.
Constructor & Destructor Documentation
Legend() [1/2]
Legend::Legend (QWidget * parent = 0) explicit
Definition at line 81 of file KDChartLegend.cpp.
References d.
Referenced by clone().
Legend() [2/2]
Legend::Legend (KDChart::AbstractDiagram * diagram, QWidget * parent = 0) explicit
Definition at line 88 of file KDChartLegend.cpp.
References d, diagram(), and setDiagram().
~Legend()
Legend::~Legend () virtual
Definition at line 96 of file KDChartLegend.cpp.
References destroyedLegend().
Member Function Documentation
addDiagram()
void Legend::addDiagram (KDChart::AbstractDiagram * newDiagram)
Add the given diagram to the legend.
Parameters
newDiagram The diagram to add.
See also
diagram, diagrams, removeDiagram, removeDiagrams, replaceDiagram, setDiagram
Definition at line 319 of file KDChartLegend.cpp.
References d.
Referenced by replaceDiagram().
alignment()
Qt::Alignment Legend::alignment () const
Returns the alignment of a non-floating legend.
See also
setAlignment
Definition at line 474 of file KDChartLegend.cpp.
References d.
Referenced by clone(), compare(), setAlignment(), setLegendSymbolAlignment(), and setTextAlignment().
alignToReferencePoint()
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position) inherited
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
areaGeometry()
QRect AbstractAreaWidget::areaGeometry () const protected virtual inherited
Implements KDChart::AbstractAreaBase.
Definition at line 179 of file KDChartAbstractAreaWidget.cpp.
backgroundAttributes()
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const inherited
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
brush()
QBrush Legend::brush (uint dataset) const
Definition at line 633 of file KDChartLegend.cpp.
References d.
Referenced by setBrush().
brushes()
const QMap< uint, QBrush > Legend::brushes () const
Definition at line 642 of file KDChartLegend.cpp.
References d.
Referenced by compare().
clone()
Legend * Legend::clone () const virtual
Creates an exact copy of this legend.
Definition at line 200 of file KDChartLegend.cpp.
References alignment(), d, KDChart::AbstractAreaBase::frameAttributes(), Legend(), legendStyle(), position(), setAlignment(), KDChart::AbstractAreaBase::setFrameAttributes(), setLegendStyle(), setPosition(), setTextAlignment(), setTextAttributes(), setTitleTextAttributes(), setUseAutomaticMarkerSize(), textAlignment(), textAttributes(), titleTextAttributes(), and useAutomaticMarkerSize().
compare() [1/2]
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const inherited
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), and KDChart::AbstractAreaBase::frameAttributes().
Referenced by compare().
compare() [2/2]
bool Legend::compare (const Legend * other) const
Returns true if both legends have the same settings.
Definition at line 215 of file KDChartLegend.cpp.
References alignment(), brushes(), KDChart::AbstractAreaBase::compare(), floatingPosition(), legendStyle(), markerAttributes(), orientation(), pens(), position(), showLines(), spacing(), textAlignment(), textAttributes(), texts(), titleText(), titleTextAttributes(), and useAutomaticMarkerSize().
constDiagrams()
ConstDiagramList Legend::constDiagrams () const
Returns
The list of diagrams associated with this legend.
Definition at line 310 of file KDChartLegend.cpp.
References d.
datasetCount()
uint Legend::datasetCount () const
Definition at line 266 of file KDChartLegend.cpp.
References d, KDChart::AbstractDiagram::datasetBrushes(), KDChart::AbstractDiagram::datasetLabels(), KDChart::DiagramObserver::diagram(), and diagram().
datasetIsHidden()
bool Legend::datasetIsHidden (uint dataset) const
Definition at line 1251 of file KDChartLegend.cpp.
References d.
dataSetOffset()
uint Legend::dataSetOffset (KDChart::AbstractDiagram * diagram)
Returns the offset of the first dataset of diagram.
Definition at line 402 of file KDChartLegend.cpp.
References d, and diagram().
destroyedLegend
void KDChart::Legend::destroyedLegend (Legend *) signal
Referenced by ~Legend().
diagram()
AbstractDiagram * Legend::diagram () const
The first diagram of the legend or 0 if there was none added to the legend.
Returns
The first diagram of the legend or 0.
See also
diagrams, addDiagram, removeDiagram, removeDiagrams, replaceDiagram, setDiagram
Definition at line 293 of file KDChartLegend.cpp.
References d.
Referenced by datasetCount(), dataSetOffset(), Legend(), paint(), and setBrushesFromDiagram().
diagrams()
DiagramList Legend::diagrams () const
The list of all diagrams associated with the legend.
Returns
The list of all diagrams associated with the legend.
See also
diagram, addDiagram, removeDiagram, removeDiagrams, replaceDiagram, setDiagram
Definition at line 301 of file KDChartLegend.cpp.
References d.
Referenced by removeDiagram(), and removeDiagrams().
floatingPosition()
const RelativePosition Legend::floatingPosition () const
Returns the position of a floating legend.
See also
setFloatingPosition
Definition at line 516 of file KDChartLegend.cpp.
References d.
Referenced by compare(), and KDChart::Chart::reLayoutFloatingLegends().
forceRebuild()
void Legend::forceRebuild () virtual
Call this to trigger an unconditional re-building of the widget's internals.
Reimplemented from KDChart::AbstractAreaWidget.
Definition at line 759 of file KDChartLegend.cpp.
Referenced by resizeEvent().
frameAttributes()
FrameAttributes AbstractAreaBase::frameAttributes () const inherited
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by clone(), KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
getFrameLeadings()
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const inherited
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::innerRect(), and KDChart::AbstractAreaWidget::paintAll().
hasHeightForWidth()
bool Legend::hasHeightForWidth () const virtual
Definition at line 1168 of file KDChartLegend.cpp.
References d.
heightForWidth()
int Legend::heightForWidth (int width) const virtual
Definition at line 1176 of file KDChartLegend.cpp.
References d, showLines(), and spacing().
hiddenDatasets()
const QList< uint > Legend::hiddenDatasets () const
Definition at line 1237 of file KDChartLegend.cpp.
References d.
Referenced by setHiddenDatasets().
innerRect()
QRect AbstractAreaBase::innerRect () const protected inherited
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::areaGeometry(), and KDChart::AbstractAreaBase::getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and KDChart::TextArea::paintAll().
legendStyle()
Legend::LegendStyle Legend::legendStyle () const
Definition at line 192 of file KDChartLegend.cpp.
References d.
Referenced by clone(), and compare().
legendSymbolAlignment()
Qt::Alignment Legend::legendSymbolAlignment () const
Returns the alignment used while drawing legend symbol(alignment of Legend::LinesOnly) within the legend.
See also
setLegendSymbolAlignment()
Definition at line 502 of file KDChartLegend.cpp.
References d.
markerAttributes() [1/2]
MarkerAttributes Legend::markerAttributes (uint dataset) const
Definition at line 700 of file KDChartLegend.cpp.
References d.
Referenced by compare().
markerAttributes() [2/2]
const QMap< uint, MarkerAttributes > Legend::markerAttributes () const
Definition at line 711 of file KDChartLegend.cpp.
References d.
Referenced by compare(), and setMarkerAttributes().
minimumSizeHint()
QSize Legend::minimumSizeHint () const virtual
Definition at line 138 of file KDChartLegend.cpp.
References sizeHint().
needSizeHint()
void Legend::needSizeHint () virtual
Call this to trigger an conditional re-building of the widget's internals.
e.g. AbstractAreaWidget call this, before calling layout()->setGeometry()
Reimplemented from KDChart::AbstractAreaWidget.
Definition at line 156 of file KDChartLegend.cpp.
orientation()
Qt::Orientation Legend::orientation () const
Definition at line 531 of file KDChartLegend.cpp.
References d.
Referenced by compare(), and setOrientation().
paint()
void Legend::paint (QPainter * painter) virtual
Overwrite this to paint the inner contents of your widget.
Note
When overriding this method, please let your widget draw itself at the top/left corner of the painter. You should call rect() (or width(), height(), resp.) to find the drawable area's size: While the paint() method is being executed the frame of the widget is outside of its rect(), so you can use all of rect() for your custom drawing!
See also
paint, paintIntoRect
Implements KDChart::AbstractAreaWidget.
Definition at line 245 of file KDChartLegend.cpp.
References d, diagram(), and KDChart::AbstractLayoutItem::paint().
paintAll()
void AbstractAreaWidget::paintAll (QPainter & painter) inherited
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
Definition at line 140 of file KDChartAbstractAreaWidget.cpp.
References KDChart::AbstractAreaBase::getFrameLeadings(), KDChart::AbstractAreaWidget::paint(), KDChart::AbstractAreaBase::paintBackground(), and KDChart::AbstractAreaBase::paintFrame().
Referenced by KDChart::AbstractAreaWidget::paintEvent(), and KDChart::AbstractAreaWidget::paintIntoRect().
paintBackground()
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintBackgroundAttributes()
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static inherited
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by KDChart::AbstractAreaBase::paintBackground().
paintEvent()
void AbstractAreaWidget::paintEvent (QPaintEvent * event) virtual inherited
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite paint() instead.
See also
paint
Definition at line 95 of file KDChartAbstractAreaWidget.cpp.
References d, and KDChart::AbstractAreaWidget::paintAll().
paintFrame()
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintFrameAttributes()
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static inherited
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::AbstractAreaBase::paintFrame().
paintIntoRect()
void AbstractAreaWidget::paintIntoRect (QPainter & painter, const QRect & rect) virtual inherited
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite paint() instead.
Definition at line 105 of file KDChartAbstractAreaWidget.cpp.
References d, and KDChart::AbstractAreaWidget::paintAll().
pen()
QPen Legend::pen (uint dataset) const
Definition at line 675 of file KDChartLegend.cpp.
References d.
Referenced by setPen().
pens()
const QMap< uint, QPen > Legend::pens () const
Definition at line 684 of file KDChartLegend.cpp.
References d.
Referenced by compare().
position()
Position Legend::position () const
Returns the position of a non-floating legend.
See also
setPosition
Definition at line 460 of file KDChartLegend.cpp.
References d.
Referenced by clone(), compare(), KDChart::Chart::reLayoutFloatingLegends(), and setPosition().
positionChanged
void KDChart::AbstractAreaWidget::positionChanged (AbstractAreaWidget *) signal inherited
Referenced by KDChart::AbstractAreaWidget::positionHasChanged().
positionHasChanged()
void AbstractAreaWidget::positionHasChanged () protected virtual inherited
Reimplemented from KDChart::AbstractAreaBase.
Definition at line 184 of file KDChartAbstractAreaWidget.cpp.
References KDChart::AbstractAreaWidget::positionChanged().
propertiesChanged
void KDChart::Legend::propertiesChanged () signal
Emitted upon change of a property of the Legend or any of its components.
referenceArea()
const QWidget * Legend::referenceArea () const
Returns the reference area, that is used for font size of title text, and for font size of the item texts, IF automatic area detection is set.
See also
setReferenceArea
Definition at line 287 of file KDChartLegend.cpp.
References d.
removeDiagram()
void Legend::removeDiagram (KDChart::AbstractDiagram * oldDiagram)
Removes the diagram from the legend's list of diagrams.
See also
diagram, diagrams, addDiagram, removeDiagrams, replaceDiagram, setDiagram
Definition at line 343 of file KDChartLegend.cpp.
References d, KDChart::AbstractDiagram::datasetBrushes(), KDChart::AbstractDiagram::datasetPens(), and diagrams().
Referenced by removeDiagrams(), and replaceDiagram().
removeDiagrams()
void Legend::removeDiagrams ()
Removes all diagrams from the legend's list of diagrams.
See also
diagram, diagrams, addDiagram, removeDiagram, replaceDiagram, setDiagram
Definition at line 371 of file KDChartLegend.cpp.
References d, diagrams(), and removeDiagram().
replaceDiagram()
void Legend::replaceDiagram (KDChart::AbstractDiagram * newDiagram, KDChart::AbstractDiagram * oldDiagram = 0)
Replaces the old diagram, or appends the new diagram, it there is none yet.
Parameters
newDiagram The diagram to be used instead of the old one. If this parameter is zero, the first diagram will just be removed.
oldDiagram The diagram to be removed by the new one. This diagram will be deleted automatically. If the parameter is omitted, the very first diagram will be replaced. In case, there was no diagram yet, the new diagram will just be added.
See also
diagram, diagrams, addDiagram, removeDiagram, removeDiagrams, setDiagram
Definition at line 384 of file KDChartLegend.cpp.
References addDiagram(), d, and removeDiagram().
Referenced by setDiagram().
resetTexts()
void Legend::resetTexts ()
Removes all legend texts that might have been set by setText.
This resets the Legend to default behaviour: Texts are created automatically.
Definition at line 583 of file KDChartLegend.cpp.
References d.
resizeEvent()
void Legend::resizeEvent (QResizeEvent * event) virtual
Definition at line 821 of file KDChartLegend.cpp.
References forceRebuild(), and sizeHint().
resizeLayout()
void Legend::resizeLayout (const QSize & size) virtual
Reimplemented from KDChart::AbstractAreaWidget.
Definition at line 161 of file KDChartLegend.cpp.
References d.
setAlignment()
void Legend::setAlignment (Qt::Alignment alignment)
Specify the alignment of a non-floating legend.
Use setFloatingPosition to set position and alignment if your legend is floating.
See also
alignment, setPosition, setFloatingPosition
Definition at line 465 of file KDChartLegend.cpp.
References alignment(), and d.
Referenced by clone().
setBackgroundAttributes()
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a) inherited
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
setBrush()
void Legend::setBrush (uint dataset, const QBrush & brush)
Definition at line 624 of file KDChartLegend.cpp.
References brush(), and d.
Referenced by setDefaultColors(), setRainbowColors(), and setSubduedColors().
setBrushesFromDiagram()
void Legend::setBrushesFromDiagram (KDChart::AbstractDiagram * diagram)
Definition at line 648 of file KDChartLegend.cpp.
References d, KDChart::AbstractDiagram::datasetBrushes(), and diagram().
setColor()
void Legend::setColor (uint dataset, const QColor & color)
Note: there is no color() getter method, since setColor just sets a QBrush with the respective color, so the brush() getter method is sufficient.
Definition at line 615 of file KDChartLegend.cpp.
References d.
setDatasetHidden()
void Legend::setDatasetHidden (uint dataset, bool hidden)
Definition at line 1242 of file KDChartLegend.cpp.
References d.
setDefaultColors()
void Legend::setDefaultColors ()
Definition at line 785 of file KDChartLegend.cpp.
References KDChart::Palette::defaultPalette(), KDChart::Palette::getBrush(), setBrush(), and KDChart::Palette::size().
setDiagram()
void Legend::setDiagram (KDChart::AbstractDiagram * newDiagram)
A convenience method doing the same as replaceDiagram(newDiagram, 0);.
Replaces the first diagram by the given diagram. If the legend's list of diagram is empty the given diagram is added to the list.
See also
diagram, diagrams, addDiagram, removeDiagram, removeDiagrams, replaceDiagram
Definition at line 420 of file KDChartLegend.cpp.
References replaceDiagram().
Referenced by KDChart::Widget::addLegend(), Legend(), KDChart::Widget::replaceLegend(), and KDChart::Widget::setType().
setFloatingPosition()
void Legend::setFloatingPosition (const RelativePosition & relativePosition)
Specify the position and alignment of a floating legend.
Use setPosition and setAlignment to set position and alignment if your legend is non-floating.
Note
When setFloatingPosition is called, the Legend's position value is set to KDChart::Position::Floating automatically.
If your Chart is pointed to by m_chart, your could have the floating legend aligned exactly to the chart's coordinate plane's top-right corner with the following commands:
KDChart::RelativePosition relativePosition;
relativePosition.setReferenceArea(m_chart->coordinatePlane());
relativePosition.setReferencePosition(Position::NorthEast);
relativePosition.setAlignment(Qt::AlignTop | Qt::AlignRight);
relativePosition.setHorizontalPadding(
    KDChart::Measure( -1.0, KDChartEnums::MeasureCalculationModeAbsolute ) );
relativePosition.setVerticalPadding(
    KDChart::Measure( 0.0, KDChartEnums::MeasureCalculationModeAbsolute ) );
m_legend->setFloatingPosition(relativePosition);
   To have the legend positioned at a fixed point, measured from the QPainter's top left corner,
   you could use the following code code:
KDChart::RelativePosition relativePosition;
relativePosition.setReferencePoints(PositionPoints(QPointF(0.0, 0.0)));
relativePosition.setReferencePosition(Position::NorthWest);
relativePosition.setAlignment(Qt::AlignTop | Qt::AlignLeft);
relativePosition.setHorizontalPadding(
    KDChart::Measure( 4.0, KDChartEnums::MeasureCalculationModeAbsolute ) );
relativePosition.setVerticalPadding(
    KDChart::Measure( 4.0, KDChartEnums::MeasureCalculationModeAbsolute ) );
m_legend->setFloatingPosition(relativePosition);
Actually that's exactly the code KD Chart is using as default position for any floating legends, so if you just say setPosition(KDChart::Position::Floating) without calling setFloatingPosition your legend will be positioned at point 4/4.
See also
setPosition, setAlignment
Definition at line 507 of file KDChartLegend.cpp.
References d, and KDChart::Position::Floating.
setFrameAttributes()
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a) inherited
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
Referenced by clone().
setHiddenDatasets()
void Legend::setHiddenDatasets (const QList< uint > hiddenDatasets)
Sets a list of datasets that are to be hidden in the legend.
By passing an empty list, you show all datasets. All datasets are shown by default, which means that hiddenDatasets() returns an empty list.
Definition at line 1232 of file KDChartLegend.cpp.
References d, and hiddenDatasets().
setLegendStyle()
void Legend::setLegendStyle (LegendStyle style)
Definition at line 183 of file KDChartLegend.cpp.
References d.
Referenced by clone().
setLegendSymbolAlignment()
void Legend::setLegendSymbolAlignment (Qt::Alignment alignment)
Specify the alignment of the legend symbol(alignment of Legend::LinesOnly) within the legend.
See also
legendSymbolAlignment()
Definition at line 493 of file KDChartLegend.cpp.
References alignment(), and d.
setMarkerAttributes()
void Legend::setMarkerAttributes (uint dataset, const MarkerAttributes & markerAttributes)
Note that any sizes specified via setMarkerAttributes are ignored, unless you disable the automatic size calculation, by saying setUseAutomaticMarkerSize(false)
Definition at line 690 of file KDChartLegend.cpp.
References d, and markerAttributes().
setOrientation()
void Legend::setOrientation (Qt::Orientation orientation)
Definition at line 521 of file KDChartLegend.cpp.
References d, and orientation().
setPen()
void Legend::setPen (uint dataset, const QPen & pen)
Definition at line 665 of file KDChartLegend.cpp.
References d, and pen().
setPosition()
void Legend::setPosition (Position position)
Specify the position of a non-floating legend.
Use setFloatingPosition to set position and alignment if your legend is floating.
See also
setAlignment, setFloatingPosition
Definition at line 444 of file KDChartLegend.cpp.
References d, and position().
Referenced by KDChart::Widget::addLegend(), and clone().
setRainbowColors()
void Legend::setRainbowColors ()
Definition at line 793 of file KDChartLegend.cpp.
References KDChart::Palette::getBrush(), KDChart::Palette::rainbowPalette(), setBrush(), and KDChart::Palette::size().
setReferenceArea()
void Legend::setReferenceArea (const QWidget * area)
Specifies the reference area for font size of title text, and for font size of the item texts, IF automatic area detection is set.
Note
This parameter is ignored, if the Measure given for setTitleTextAttributes (or setTextAttributes, resp.) is not specifying automatic area detection.
If no reference area is specified, but automatic area detection is set, then the size of the legend's parent widget will be used.
See also
KDChart::Measure, KDChartEnums::MeasureCalculationMode
Definition at line 278 of file KDChartLegend.cpp.
References d.
setShowLines()
void Legend::setShowLines (bool legendShowLines)
Definition at line 551 of file KDChartLegend.cpp.
References d.
setSortOrder()
void Legend::setSortOrder (Qt::SortOrder order)
Definition at line 536 of file KDChartLegend.cpp.
References d.
setSpacing()
void Legend::setSpacing (uint space)
Definition at line 770 of file KDChartLegend.cpp.
References d.
setSubduedColors()
void Legend::setSubduedColors (bool ordered = false)
Definition at line 801 of file KDChartLegend.cpp.
References KDChart::Palette::getBrush(), setBrush(), KDChart::Palette::size(), and KDChart::Palette::subduedPalette().
setText()
void Legend::setText (uint dataset, const QString & text)
Definition at line 592 of file KDChartLegend.cpp.
References d, and text().
setTextAlignment()
void Legend::setTextAlignment (Qt::Alignment alignment)
Specify the alignment of the text elements within the legend.
See also
textAlignment()
Definition at line 479 of file KDChartLegend.cpp.
References alignment(), and d.
Referenced by clone().
setTextAttributes()
void Legend::setTextAttributes (const TextAttributes & a)
Definition at line 717 of file KDChartLegend.cpp.
References d.
Referenced by clone().
setTitleText()
void Legend::setTitleText (const QString & text)
Definition at line 731 of file KDChartLegend.cpp.
References d, and text().
setTitleTextAttributes()
void Legend::setTitleTextAttributes (const TextAttributes & a)
Definition at line 745 of file KDChartLegend.cpp.
References d.
Referenced by clone().
setUseAutomaticMarkerSize()
void Legend::setUseAutomaticMarkerSize (bool useAutomaticMarkerSize)
This option is on by default, it means that Marker sizes in the Legend will be the same as the font height used for their respective label texts.
Set this to false, if you want to specify the marker sizes via setMarkerAttributes or if you want the Legend to use the same marker sizes as they are used in the Diagrams.
Definition at line 566 of file KDChartLegend.cpp.
References d, and useAutomaticMarkerSize().
Referenced by clone().
setVisible()
void Legend::setVisible (bool visible) virtual
Definition at line 430 of file KDChartLegend.cpp.
showLines()
bool Legend::showLines () const
Definition at line 561 of file KDChartLegend.cpp.
References d.
Referenced by compare(), and heightForWidth().
sizeHint()
QSize Legend::sizeHint () const virtual
Definition at line 145 of file KDChartLegend.cpp.
References d.
Referenced by minimumSizeHint(), KDChart::Chart::reLayoutFloatingLegends(), and resizeEvent().
sortOrder()
Qt::SortOrder Legend::sortOrder () const
Definition at line 546 of file KDChartLegend.cpp.
References d.
spacing()
uint Legend::spacing () const
Definition at line 780 of file KDChartLegend.cpp.
References d.
Referenced by compare(), and heightForWidth().
text()
QString Legend::text (uint dataset) const
Definition at line 601 of file KDChartLegend.cpp.
References d.
Referenced by setText(), and setTitleText().
textAlignment()
Qt::Alignment Legend::textAlignment () const
Returns the alignment used while rendering text elements within the legend.
See also
setTextAlignment()
Definition at line 488 of file KDChartLegend.cpp.
References d.
Referenced by clone(), and compare().
textAttributes()
TextAttributes Legend::textAttributes () const
Definition at line 726 of file KDChartLegend.cpp.
References d.
Referenced by clone(), and compare().
texts()
const QMap< uint, QString > Legend::texts () const
Definition at line 610 of file KDChartLegend.cpp.
References d.
Referenced by compare().
titleText()
QString Legend::titleText () const
Definition at line 740 of file KDChartLegend.cpp.
References d.
Referenced by compare().
titleTextAttributes()
TextAttributes Legend::titleTextAttributes () const
Definition at line 754 of file KDChartLegend.cpp.
References d.
Referenced by clone(), and compare().
useAutomaticMarkerSize()
bool Legend::useAutomaticMarkerSize () const
Definition at line 573 of file KDChartLegend.cpp.
References d.
Referenced by clone(), compare(), and setUseAutomaticMarkerSize().
The documentation for this class was generated from the following files:
KDChartLegend.h
KDChartLegend.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/