KD Chart 2: KDGantt::GraphicsScene Class Reference
KDGantt::GraphicsScene Class Reference
#include <kdganttgraphicsscene.h>
Public Slots
void setConstraintModel (ConstraintModel *)
void setModel (QAbstractItemModel *)
void setReadOnly (bool)
void setRootIndex (const QModelIndex &idx)
void setSelectionModel (QItemSelectionModel *selectionmodel)
void setSummaryHandlingModel (QAbstractProxyModel *)
Signals
void clicked (const QModelIndex &index)
void entered (const QModelIndex &index)
void gridChanged ()
void pressed (const QModelIndex &index)
void qrealClicked (const QModelIndex &index)
Public Member Functions
void clearConstraintItems ()
void clearItems ()
ConstraintModel * constraintModel () const
GraphicsItem * createItem (ItemType type) const
void deleteSubtree (const QModelIndex &)
GraphicsItem * dragSource () const
ConstraintGraphicsItem * findConstraintItem (const Constraint &) const
GraphicsItem * findItem (const QModelIndex &) const
GraphicsItem * findItem (const QPersistentModelIndex &) const
GraphicsScene (QObject *parent=0)
AbstractGrid * grid () const
void insertItem (const QPersistentModelIndex &, GraphicsItem *)
bool isReadOnly () const
void itemClicked (const QModelIndex &)
ItemDelegate * itemDelegate () const
void itemDoubleClicked (const QModelIndex &)
void itemEntered (const QModelIndex &)
void itemPressed (const QModelIndex &)
QAbstractItemModel * model () const
void print (QPrinter *printer, bool drawRowLabels=true, bool drawColumnLabels=true)
void print (QPrinter *printer, qreal start, qreal end, bool drawRowLabels=true, bool drawColumnLabels=true)
void print (QPainter *painter, const QRectF &target=QRectF(), bool drawRowLabels=true, bool drawColumnLabels=true)
void print (QPainter *painter, qreal start, qreal end, const QRectF &target=QRectF(), bool drawRowLabels=true, bool drawColumnLabels=true)
void removeItem (const QModelIndex &)
QModelIndex rootIndex () const
AbstractRowController * rowController () const
QItemSelectionModel * selectionModel () const
void setDragSource (GraphicsItem *item)
void setGrid (AbstractGrid *grid)
void setItemDelegate (ItemDelegate *)
void setRowController (AbstractRowController *rc)
QAbstractProxyModel * summaryHandlingModel () const
void updateItems ()
void updateRow (const QModelIndex &idx)
virtual ~GraphicsScene ()
Static Public Member Functions
static QModelIndex dataIndex (const QModelIndex &idx)
static QModelIndex mainIndex (const QModelIndex &idx)
Protected Member Functions
void drawBackground (QPainter *painter, const QRectF &rect)
void drawForeground (QPainter *painter, const QRectF &rect)
void helpEvent (QGraphicsSceneHelpEvent *helpEvent)
Detailed Description
Definition at line 48 of file kdganttgraphicsscene.h.
Constructor & Destructor Documentation
GraphicsScene()
GraphicsScene::GraphicsScene (QObject * parent = 0) explicit
Definition at line 162 of file kdganttgraphicsscene.cpp.
~GraphicsScene()
GraphicsScene::~GraphicsScene () virtual
Definition at line 168 of file kdganttgraphicsscene.cpp.
References clearConstraintItems().
Member Function Documentation
clearConstraintItems()
void GraphicsScene::clearConstraintItems ()
Definition at line 542 of file kdganttgraphicsscene.cpp.
Referenced by ~GraphicsScene().
clearItems()
void GraphicsScene::clearItems ()
Definition at line 500 of file kdganttgraphicsscene.cpp.
References d.
clicked
void KDGantt::GraphicsScene::clicked (const QModelIndex & index) signal
Referenced by itemClicked().
constraintModel()
ConstraintModel * GraphicsScene::constraintModel () const
Definition at line 235 of file kdganttgraphicsscene.cpp.
References d.
createItem()
GraphicsItem * GraphicsScene::createItem (ItemType type) const
Creates a new item of type type. TODO: If the user should be allowed to override this in any way, it needs to be in View!
Definition at line 344 of file kdganttgraphicsscene.cpp.
References KDGantt::TypeEvent, KDGantt::TypeSummary, and KDGantt::TypeTask.
Referenced by updateRow().
dataIndex()
QModelIndex GraphicsScene::dataIndex (const QModelIndex & idx) static
Returns the index pointing to the last column in the same row as idx. This can be thought of as in "inverse" of mainIndex()
Definition at line 326 of file kdganttgraphicsscene.cpp.
References model().
Referenced by deleteSubtree().
deleteSubtree()
void GraphicsScene::deleteSubtree (const QModelIndex & _idx)
Definition at line 521 of file kdganttgraphicsscene.cpp.
References dataIndex(), removeItem(), and summaryHandlingModel().
dragSource()
GraphicsItem * GraphicsScene::dragSource () const
Definition at line 645 of file kdganttgraphicsscene.cpp.
References d.
Referenced by KDGantt::GraphicsItem::mouseReleaseEvent().
drawBackground()
void GraphicsScene::drawBackground (QPainter * painter, const QRectF & rect) protected
Definition at line 579 of file kdganttgraphicsscene.cpp.
References d.
drawForeground()
void GraphicsScene::drawForeground (QPainter * painter, const QRectF & rect) protected
Definition at line 615 of file kdganttgraphicsscene.cpp.
References d.
entered
void KDGantt::GraphicsScene::entered (const QModelIndex & index) signal
Referenced by itemEntered().
findConstraintItem()
ConstraintGraphicsItem * GraphicsScene::findConstraintItem (const Constraint & c) const
Definition at line 537 of file kdganttgraphicsscene.cpp.
References d.
findItem() [1/2]
GraphicsItem * GraphicsScene::findItem (const QModelIndex & idx) const
Definition at line 484 of file kdganttgraphicsscene.cpp.
References d, and summaryHandlingModel().
Referenced by KDGantt::View::ensureVisible(), and updateRow().
findItem() [2/2]
GraphicsItem * GraphicsScene::findItem (const QPersistentModelIndex & idx) const
Definition at line 492 of file kdganttgraphicsscene.cpp.
References d, and summaryHandlingModel().
grid()
AbstractGrid * GraphicsScene::grid () const
Definition at line 289 of file kdganttgraphicsscene.cpp.
References d.
Referenced by setGrid(), and KDGantt::GraphicsItem::updateItem().
gridChanged
void KDGantt::GraphicsScene::gridChanged () signal
Referenced by setGrid().
helpEvent()
void GraphicsScene::helpEvent (QGraphicsSceneHelpEvent * helpEvent) protected
Definition at line 565 of file kdganttgraphicsscene.cpp.
References KDGantt::ConstraintGraphicsItem::ganttToolTip().
insertItem()
void GraphicsScene::insertItem (const QPersistentModelIndex & idx, GraphicsItem * item)
Definition at line 428 of file kdganttgraphicsscene.cpp.
References KDGantt::GraphicsItem::addEndConstraint(), KDGantt::GraphicsItem::addStartConstraint(), d, KDGantt::Constraint::endIndex(), KDGantt::Constraint::startIndex(), and summaryHandlingModel().
Referenced by updateRow().
isReadOnly()
bool GraphicsScene::isReadOnly () const
Definition at line 299 of file kdganttgraphicsscene.cpp.
References d.
Referenced by KDGantt::GraphicsItem::isEditable().
itemClicked()
void GraphicsScene::itemClicked (const QModelIndex & idx)
Definition at line 630 of file kdganttgraphicsscene.cpp.
References clicked().
Referenced by KDGantt::GraphicsItem::mouseReleaseEvent().
itemDelegate()
ItemDelegate * GraphicsScene::itemDelegate () const
Definition at line 195 of file kdganttgraphicsscene.cpp.
References d.
Referenced by KDGantt::ConstraintGraphicsItem::boundingRect(), KDGantt::GraphicsItem::ganttToolTip(), KDGantt::GraphicsItem::hoverMoveEvent(), KDGantt::GraphicsItem::mouseDoubleClickEvent(), KDGantt::GraphicsItem::mousePressEvent(), KDGantt::ConstraintGraphicsItem::paint(), KDGantt::GraphicsItem::paint(), and KDGantt::GraphicsItem::updateItem().
itemDoubleClicked()
void GraphicsScene::itemDoubleClicked (const QModelIndex & idx)
Definition at line 635 of file kdganttgraphicsscene.cpp.
References qrealClicked().
Referenced by KDGantt::GraphicsItem::mouseDoubleClickEvent().
itemEntered()
void GraphicsScene::itemEntered (const QModelIndex & idx)
Definition at line 620 of file kdganttgraphicsscene.cpp.
References entered().
Referenced by KDGantt::GraphicsItem::hoverMoveEvent().
itemPressed()
void GraphicsScene::itemPressed (const QModelIndex & idx)
Definition at line 625 of file kdganttgraphicsscene.cpp.
References pressed().
Referenced by KDGantt::GraphicsItem::mousePressEvent().
mainIndex()
QModelIndex GraphicsScene::mainIndex (const QModelIndex & idx) static
Definition at line 309 of file kdganttgraphicsscene.cpp.
model()
QAbstractItemModel * GraphicsScene::model () const
Definition at line 200 of file kdganttgraphicsscene.cpp.
References d.
Referenced by dataIndex(), setGrid(), setModel(), setSummaryHandlingModel(), and updateRow().
pressed
void KDGantt::GraphicsScene::pressed (const QModelIndex & index) signal
Referenced by itemPressed().
print() [1/4]
void GraphicsScene::print (QPrinter * printer, bool drawRowLabels = true, bool drawColumnLabels = true)
Print the Gantt chart using printer. If drawRowLabels is true (the default), each row will have it's label printed on the left side. If drawColumnLabels is true (the default), each column will have it's label printed at the top side.
This version of print() will print multiple pages.
Definition at line 658 of file kdganttgraphicsscene.cpp.
print() [2/4]
void GraphicsScene::print (QPrinter * printer, qreal start, qreal end, bool drawRowLabels = true, bool drawColumnLabels = true)
Print part of the Gantt chart from start to end using printer. If drawRowLabels is true (the default), each row will have it's label printed on the left side. If drawColumnLabels is true (the default), each column will have it's label printed at the top side.
This version of print() will print multiple pages.
To print a certain range of a chart with a DateTimeGrid, use qreal DateTimeGrid::mapFromDateTime(const QDateTime& dt) const to figure out the values for start and end.
Definition at line 682 of file kdganttgraphicsscene.cpp.
print() [3/4]
void GraphicsScene::print (QPainter * painter, const QRectF & _targetRect = QRectF(), bool drawRowLabels = true, bool drawColumnLabels = true)
Render the GanttView inside the rectangle target using the painter painter. If drawRowLabels is true (the default), each row will have it's label printed on the left side. If drawColumnLabels is true (the default), each column will have it's label printed at the top side.
Definition at line 702 of file kdganttgraphicsscene.cpp.
print() [4/4]
void GraphicsScene::print (QPainter * painter, qreal start, qreal end, const QRectF & _targetRect = QRectF(), bool drawRowLabels = true, bool drawColumnLabels = true)
Render the GanttView inside the rectangle target using the painter painter. If drawRowLabels is true (the default), each row will have it's label printed on the left side. If drawColumnLabels is true (the default), each column will have it's label printed at the top side.
To print a certain range of a chart with a DateTimeGrid, use qreal DateTimeGrid::mapFromDateTime(const QDateTime& dt) const to figure out the values for start and end.
Definition at line 722 of file kdganttgraphicsscene.cpp.
qrealClicked
void KDGantt::GraphicsScene::qrealClicked (const QModelIndex & index) signal
Referenced by itemDoubleClicked().
removeItem()
void GraphicsScene::removeItem (const QModelIndex & idx)
Definition at line 461 of file kdganttgraphicsscene.cpp.
References d, KDGantt::GraphicsItem::endConstraints(), and KDGantt::GraphicsItem::startConstraints().
Referenced by deleteSubtree(), and updateRow().
rootIndex()
QModelIndex GraphicsScene::rootIndex () const
Definition at line 230 of file kdganttgraphicsscene.cpp.
References d.
rowController()
AbstractRowController * GraphicsScene::rowController () const
Definition at line 270 of file kdganttgraphicsscene.cpp.
References d.
Referenced by KDGantt::GraphicsItem::updateItem(), and updateRow().
selectionModel()
QItemSelectionModel * GraphicsScene::selectionModel () const
Definition at line 260 of file kdganttgraphicsscene.cpp.
References d.
Referenced by KDGantt::GraphicsItem::focusInEvent(), KDGantt::GraphicsItem::itemChange(), and KDGantt::GraphicsItem::mouseMoveEvent().
setConstraintModel
void GraphicsScene::setConstraintModel (ConstraintModel * cm) slot
Definition at line 240 of file kdganttgraphicsscene.cpp.
References d.
setDragSource()
void GraphicsScene::setDragSource (GraphicsItem * item)
Definition at line 640 of file kdganttgraphicsscene.cpp.
References d.
Referenced by KDGantt::GraphicsItem::mouseMoveEvent(), and KDGantt::GraphicsItem::mouseReleaseEvent().
setGrid()
void GraphicsScene::setGrid (AbstractGrid * grid)
Definition at line 275 of file kdganttgraphicsscene.cpp.
References d, grid(), gridChanged(), and model().
setItemDelegate()
void GraphicsScene::setItemDelegate (ItemDelegate * delegate)
Definition at line 188 of file kdganttgraphicsscene.cpp.
References d.
setModel
void GraphicsScene::setModel (QAbstractItemModel * model) slot
Definition at line 206 of file kdganttgraphicsscene.cpp.
References d, model(), and setSelectionModel().
setReadOnly
void GraphicsScene::setReadOnly (bool ro) slot
Definition at line 294 of file kdganttgraphicsscene.cpp.
References d.
setRootIndex
void GraphicsScene::setRootIndex (const QModelIndex & idx) slot
Definition at line 225 of file kdganttgraphicsscene.cpp.
References d.
setRowController()
void GraphicsScene::setRowController (AbstractRowController * rc)
Definition at line 265 of file kdganttgraphicsscene.cpp.
References d.
setSelectionModel
void GraphicsScene::setSelectionModel (QItemSelectionModel * selectionmodel) slot
Definition at line 254 of file kdganttgraphicsscene.cpp.
References d.
Referenced by setModel().
setSummaryHandlingModel
void GraphicsScene::setSummaryHandlingModel (QAbstractProxyModel * proxyModel) slot
Definition at line 219 of file kdganttgraphicsscene.cpp.
References d, and model().
summaryHandlingModel()
QAbstractProxyModel * GraphicsScene::summaryHandlingModel () const
Definition at line 214 of file kdganttgraphicsscene.cpp.
References d.
Referenced by deleteSubtree(), KDGantt::View::ensureVisible(), findItem(), insertItem(), KDGantt::ConstraintGraphicsItem::proxyConstraint(), and updateRow().
updateItems()
void GraphicsScene::updateItems ()
Definition at line 510 of file kdganttgraphicsscene.cpp.
References d, KDGantt::GraphicsItem::rect(), and KDGantt::GraphicsItem::updateItem().
updateRow()
void GraphicsScene::updateRow (const QModelIndex & idx)
Definition at line 378 of file kdganttgraphicsscene.cpp.
References createItem(), d, findItem(), insertItem(), KDGantt::AbstractRowController::isRowExpanded(), KDGantt::ItemTypeRole, model(), removeItem(), rowController(), KDGantt::AbstractRowController::rowGeometry(), KDGantt::GraphicsItem::setIndex(), summaryHandlingModel(), KDGantt::TypeMulti, KDGantt::TypeNone, and KDGantt::GraphicsItem::updateItem().
The documentation for this class was generated from the following files:
kdganttgraphicsscene.h
kdganttgraphicsscene.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/