KD Chart 2: KDChart::ThreeDPieAttributes Class Reference
KDChart::ThreeDPieAttributes Class Reference
A set of 3D pie attributes.
#include <KDChartThreeDPieAttributes.h>
Public Member Functions
qreal depth () const
bool isEnabled () const
bool isThreeDBrushEnabled () const
bool operator!= (const ThreeDPieAttributes &other) const
bool operator!= (const AbstractThreeDAttributes &other) const
ThreeDPieAttributes & operator= (const ThreeDPieAttributes &)
bool operator== (const ThreeDPieAttributes &) const
bool operator== (const AbstractThreeDAttributes &) const
void setDepth (qreal depth)
void setEnabled (bool enabled)
void setThreeDBrushEnabled (bool enabled)
void setUseShadowColors (bool useShadowColors)
virtual QBrush threeDBrush (const QBrush &brush, const QRectF &rect) const
ThreeDPieAttributes ()
ThreeDPieAttributes (const ThreeDPieAttributes &)
bool useShadowColors () const
qreal validDepth () const
~ThreeDPieAttributes ()
Detailed Description
A set of 3D pie attributes.
Definition at line 35 of file KDChartThreeDPieAttributes.h.
Constructor & Destructor Documentation
ThreeDPieAttributes() [1/2]
ThreeDPieAttributes::ThreeDPieAttributes ()
Definition at line 40 of file KDChartThreeDPieAttributes.cpp.
ThreeDPieAttributes() [2/2]
ThreeDPieAttributes::ThreeDPieAttributes (const ThreeDPieAttributes & r)
Definition at line 46 of file KDChartThreeDPieAttributes.cpp.
~ThreeDPieAttributes()
ThreeDPieAttributes::~ThreeDPieAttributes ()
Definition at line 61 of file KDChartThreeDPieAttributes.cpp.
Member Function Documentation
depth()
qreal AbstractThreeDAttributes::depth () const inherited
Definition at line 99 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), KDChart::AbstractThreeDAttributes::operator==(), KDChart::PaintingHelpers::project(), and KDChart::AbstractThreeDAttributes::setDepth().
isEnabled()
bool AbstractThreeDAttributes::isEnabled () const inherited
Definition at line 88 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), KDChart::AbstractThreeDAttributes::operator==(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), and KDChart::AbstractThreeDAttributes::validDepth().
isThreeDBrushEnabled()
bool AbstractThreeDAttributes::isThreeDBrushEnabled () const inherited
Definition at line 110 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by KDChart::AbstractThreeDAttributes::operator==(), and KDChart::AbstractThreeDAttributes::threeDBrush().
operator!=() [1/2]
bool KDChart::ThreeDPieAttributes::operator!= (const ThreeDPieAttributes & other) const
Definition at line 49 of file KDChartThreeDPieAttributes.h.
References KDGantt::operator==().
operator!=() [2/2]
bool KDChart::AbstractThreeDAttributes::operator!= (const AbstractThreeDAttributes & other) const inherited
Definition at line 57 of file KDChartAbstractThreeDAttributes.h.
References KDGantt::operator==().
operator=()
ThreeDPieAttributes & ThreeDPieAttributes::operator= (const ThreeDPieAttributes & r)
Definition at line 51 of file KDChartThreeDPieAttributes.cpp.
References d.
operator==() [1/2]
bool ThreeDPieAttributes::operator== (const ThreeDPieAttributes & r) const
Definition at line 71 of file KDChartThreeDPieAttributes.cpp.
References KDChart::AbstractThreeDAttributes::operator==(), and useShadowColors().
operator==() [2/2]
bool AbstractThreeDAttributes::operator== (const AbstractThreeDAttributes & r) const inherited
Definition at line 70 of file KDChartAbstractThreeDAttributes.cpp.
References KDChart::AbstractThreeDAttributes::depth(), KDChart::AbstractThreeDAttributes::isEnabled(), and KDChart::AbstractThreeDAttributes::isThreeDBrushEnabled().
Referenced by operator==(), KDChart::ThreeDLineAttributes::operator==(), and KDChart::ThreeDBarAttributes::operator==().
setDepth()
void AbstractThreeDAttributes::setDepth (qreal depth) inherited
Definition at line 93 of file KDChartAbstractThreeDAttributes.cpp.
References d, and KDChart::AbstractThreeDAttributes::depth().
setEnabled()
void AbstractThreeDAttributes::setEnabled (bool enabled) inherited
Definition at line 83 of file KDChartAbstractThreeDAttributes.cpp.
References d.
setThreeDBrushEnabled()
void AbstractThreeDAttributes::setThreeDBrushEnabled (bool enabled) inherited
Definition at line 115 of file KDChartAbstractThreeDAttributes.cpp.
References d.
setUseShadowColors()
void ThreeDPieAttributes::setUseShadowColors (bool useShadowColors)
Definition at line 77 of file KDChartThreeDPieAttributes.cpp.
References d.
threeDBrush()
QBrush AbstractThreeDAttributes::threeDBrush (const QBrush & brush, const QRectF & rect) const virtual inherited
Definition at line 120 of file KDChartAbstractThreeDAttributes.cpp.
References KDChart::AbstractThreeDAttributes::isThreeDBrushEnabled().
Referenced by KDChart::PaintingHelpers::paintAreas(), and KDChart::PaintingHelpers::paintThreeDLines().
useShadowColors()
bool ThreeDPieAttributes::useShadowColors () const
Definition at line 82 of file KDChartThreeDPieAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
validDepth()
qreal AbstractThreeDAttributes::validDepth () const inherited
Definition at line 105 of file KDChartAbstractThreeDAttributes.cpp.
References d, and KDChart::AbstractThreeDAttributes::isEnabled().
Referenced by KDChart::BarDiagram::threeDItemDepth(), KDChart::Plotter::threeDItemDepth(), and KDChart::LineDiagram::threeDItemDepth().
The documentation for this class was generated from the following files:
KDChartThreeDPieAttributes.h
KDChartThreeDPieAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/