KD Chart 2: KDChart::PrintingParameters Class Reference
KDChart::PrintingParameters Class Reference
PrintingParameters stores the scale factor which lines has to been scaled with when printing.
#include <KDChartPrintingParameters.h>
Static Public Member Functions
static void resetScaleFactor ()
static QPen scalePen (const QPen &pen)
static void setScaleFactor (const qreal scaleFactor)
Detailed Description
PrintingParameters stores the scale factor which lines has to been scaled with when printing.
It's essentially printer's logical DPI / widget's logical DPI
Definition at line 46 of file KDChartPrintingParameters.h.
Member Function Documentation
resetScaleFactor()
void PrintingParameters::resetScaleFactor () static
Definition at line 43 of file KDChartPrintingParameters.cpp.
Referenced by KDChart::Chart::paint().
scalePen()
QPen PrintingParameters::scalePen (const QPen & pen) static
Definition at line 48 of file KDChartPrintingParameters.cpp.
Referenced by KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::TextLayoutItem::paint(), KDChart::PaintingHelpers::paintAreas(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), KDChart::AbstractAreaBase::paintFrameAttributes(), KDChart::LineLayoutItem::paintIntoRect(), KDChart::AbstractDiagram::paintMarker(), KDChart::PaintingHelpers::paintPolyline(), KDChart::PaintingHelpers::paintThreeDLines(), and KDChart::PaintingHelpers::paintValueTracker().
setScaleFactor()
void PrintingParameters::setScaleFactor (const qreal scaleFactor) static
Definition at line 38 of file KDChartPrintingParameters.cpp.
Referenced by KDChart::Chart::paint().
The documentation for this class was generated from the following files:
KDChartPrintingParameters.h
KDChartPrintingParameters.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/