KD Chart 2: KDChart::ThreeDLineAttributes Class Reference
KDChart::ThreeDLineAttributes Class Reference
A set of 3D line attributes.
#include <KDChartThreeDLineAttributes.h>
Public Member Functions
qreal depth () const
bool isEnabled () const
bool isThreeDBrushEnabled () const
uint lineXRotation () const
uint lineYRotation () const
bool operator!= (const ThreeDLineAttributes &other) const
bool operator!= (const AbstractThreeDAttributes &other) const
ThreeDLineAttributes & operator= (const ThreeDLineAttributes &)
bool operator== (const ThreeDLineAttributes &) const
bool operator== (const AbstractThreeDAttributes &) const
void setDepth (qreal depth)
void setEnabled (bool enabled)
void setLineXRotation (const uint degrees)
void setLineYRotation (const uint degrees)
void setThreeDBrushEnabled (bool enabled)
virtual QBrush threeDBrush (const QBrush &brush, const QRectF &rect) const
ThreeDLineAttributes ()
ThreeDLineAttributes (const ThreeDLineAttributes &)
qreal validDepth () const
~ThreeDLineAttributes ()
Detailed Description
A set of 3D line attributes.
Definition at line 35 of file KDChartThreeDLineAttributes.h.
Constructor & Destructor Documentation
ThreeDLineAttributes() [1/2]
ThreeDLineAttributes::ThreeDLineAttributes ()
Definition at line 41 of file KDChartThreeDLineAttributes.cpp.
ThreeDLineAttributes() [2/2]
ThreeDLineAttributes::ThreeDLineAttributes (const ThreeDLineAttributes & r)
Definition at line 47 of file KDChartThreeDLineAttributes.cpp.
~ThreeDLineAttributes()
ThreeDLineAttributes::~ThreeDLineAttributes ()
Definition at line 62 of file KDChartThreeDLineAttributes.cpp.
Member Function Documentation
depth()
qreal AbstractThreeDAttributes::depth () const inherited
Definition at line 99 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), KDChart::AbstractThreeDAttributes::operator==(), KDChart::PaintingHelpers::project(), and KDChart::AbstractThreeDAttributes::setDepth().
isEnabled()
bool AbstractThreeDAttributes::isEnabled () const inherited
Definition at line 88 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), KDChart::AbstractThreeDAttributes::operator==(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), and KDChart::AbstractThreeDAttributes::validDepth().
isThreeDBrushEnabled()
bool AbstractThreeDAttributes::isThreeDBrushEnabled () const inherited
Definition at line 110 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by KDChart::AbstractThreeDAttributes::operator==(), and KDChart::AbstractThreeDAttributes::threeDBrush().
lineXRotation()
uint ThreeDLineAttributes::lineXRotation () const
Definition at line 85 of file KDChartThreeDLineAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::project().
lineYRotation()
uint ThreeDLineAttributes::lineYRotation () const
Definition at line 95 of file KDChartThreeDLineAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::project().
operator!=() [1/2]
bool KDChart::ThreeDLineAttributes::operator!= (const ThreeDLineAttributes & other) const
Definition at line 51 of file KDChartThreeDLineAttributes.h.
References KDGantt::operator==().
operator!=() [2/2]
bool KDChart::AbstractThreeDAttributes::operator!= (const AbstractThreeDAttributes & other) const inherited
Definition at line 57 of file KDChartAbstractThreeDAttributes.h.
References KDGantt::operator==().
operator=()
ThreeDLineAttributes & ThreeDLineAttributes::operator= (const ThreeDLineAttributes & r)
Definition at line 52 of file KDChartThreeDLineAttributes.cpp.
References d.
operator==() [1/2]
bool ThreeDLineAttributes::operator== (const ThreeDLineAttributes & r) const
Definition at line 71 of file KDChartThreeDLineAttributes.cpp.
References lineXRotation(), lineYRotation(), and KDChart::AbstractThreeDAttributes::operator==().
operator==() [2/2]
bool AbstractThreeDAttributes::operator== (const AbstractThreeDAttributes & r) const inherited
Definition at line 70 of file KDChartAbstractThreeDAttributes.cpp.
References KDChart::AbstractThreeDAttributes::depth(), KDChart::AbstractThreeDAttributes::isEnabled(), and KDChart::AbstractThreeDAttributes::isThreeDBrushEnabled().
Referenced by KDChart::ThreeDPieAttributes::operator==(), operator==(), and KDChart::ThreeDBarAttributes::operator==().
setDepth()
void AbstractThreeDAttributes::setDepth (qreal depth) inherited
Definition at line 93 of file KDChartAbstractThreeDAttributes.cpp.
References d, and KDChart::AbstractThreeDAttributes::depth().
setEnabled()
void AbstractThreeDAttributes::setEnabled (bool enabled) inherited
Definition at line 83 of file KDChartAbstractThreeDAttributes.cpp.
References d.
setLineXRotation()
void ThreeDLineAttributes::setLineXRotation (const uint degrees)
Definition at line 80 of file KDChartThreeDLineAttributes.cpp.
References d.
setLineYRotation()
void ThreeDLineAttributes::setLineYRotation (const uint degrees)
Definition at line 90 of file KDChartThreeDLineAttributes.cpp.
References d.
setThreeDBrushEnabled()
void AbstractThreeDAttributes::setThreeDBrushEnabled (bool enabled) inherited
Definition at line 115 of file KDChartAbstractThreeDAttributes.cpp.
References d.
threeDBrush()
QBrush AbstractThreeDAttributes::threeDBrush (const QBrush & brush, const QRectF & rect) const virtual inherited
Definition at line 120 of file KDChartAbstractThreeDAttributes.cpp.
References KDChart::AbstractThreeDAttributes::isThreeDBrushEnabled().
Referenced by KDChart::PaintingHelpers::paintAreas(), and KDChart::PaintingHelpers::paintThreeDLines().
validDepth()
qreal AbstractThreeDAttributes::validDepth () const inherited
Definition at line 105 of file KDChartAbstractThreeDAttributes.cpp.
References d, and KDChart::AbstractThreeDAttributes::isEnabled().
Referenced by KDChart::BarDiagram::threeDItemDepth(), KDChart::Plotter::threeDItemDepth(), and KDChart::LineDiagram::threeDItemDepth().
The documentation for this class was generated from the following files:
KDChartThreeDLineAttributes.h
KDChartThreeDLineAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/