KD Chart 2: KDChart::FrameAttributes Class Reference
KDChart::FrameAttributes Class Reference
A set of attributes for frames around items.
#include <KDChartFrameAttributes.h>
Public Member Functions
qreal cornerRadius () const
FrameAttributes ()
FrameAttributes (const FrameAttributes &)
bool isVisible () const
bool operator!= (const FrameAttributes &other) const
FrameAttributes & operator= (const FrameAttributes &)
bool operator== (const FrameAttributes &) const
int padding () const
QPen pen () const
void setCornerRadius (qreal radius)
void setPadding (int padding)
void setPen (const QPen &pen)
void setVisible (bool visible)
~FrameAttributes ()
Detailed Description
A set of attributes for frames around items.
Definition at line 36 of file KDChartFrameAttributes.h.
Constructor & Destructor Documentation
FrameAttributes() [1/2]
FrameAttributes::FrameAttributes ()
Definition at line 51 of file KDChartFrameAttributes.cpp.
FrameAttributes() [2/2]
FrameAttributes::FrameAttributes (const FrameAttributes & r)
Definition at line 56 of file KDChartFrameAttributes.cpp.
~FrameAttributes()
FrameAttributes::~FrameAttributes ()
Definition at line 71 of file KDChartFrameAttributes.cpp.
Member Function Documentation
cornerRadius()
qreal FrameAttributes::cornerRadius () const
Definition at line 113 of file KDChartFrameAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::AbstractAreaBase::paintFrameAttributes().
isVisible()
bool FrameAttributes::isVisible () const
Definition at line 93 of file KDChartFrameAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::AbstractAreaBase::paintFrameAttributes(), and updateCommonBrush().
operator!=()
bool KDChart::FrameAttributes::operator!= (const FrameAttributes & other) const
Definition at line 58 of file KDChartFrameAttributes.h.
References KDGantt::operator==().
operator=()
FrameAttributes & FrameAttributes::operator= (const FrameAttributes & r)
Definition at line 61 of file KDChartFrameAttributes.cpp.
References d.
operator==()
bool FrameAttributes::operator== (const FrameAttributes & r) const
Definition at line 77 of file KDChartFrameAttributes.cpp.
References cornerRadius(), isVisible(), padding(), and pen().
padding()
int FrameAttributes::padding () const
Definition at line 123 of file KDChartFrameAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and setPadding().
pen()
QPen FrameAttributes::pen () const
Definition at line 103 of file KDChartFrameAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::AbstractAreaBase::paintFrameAttributes(), and setPen().
setCornerRadius()
void FrameAttributes::setCornerRadius (qreal radius)
Definition at line 108 of file KDChartFrameAttributes.cpp.
References d.
setPadding()
void FrameAttributes::setPadding (int padding)
Definition at line 118 of file KDChartFrameAttributes.cpp.
References d, and padding().
Referenced by KDChart::Chart::Chart().
setPen()
void FrameAttributes::setPen (const QPen & pen)
Definition at line 98 of file KDChartFrameAttributes.cpp.
References d, and pen().
Referenced by KDChart::Chart::Chart().
setVisible()
void FrameAttributes::setVisible (bool visible)
Definition at line 88 of file KDChartFrameAttributes.cpp.
References d.
The documentation for this class was generated from the following files:
KDChartFrameAttributes.h
KDChartFrameAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/