KD Chart 2: KDChart::CartesianAxis Class Reference
KDChart::CartesianAxis Class Reference
The class for cartesian axes.
#include <KDChartCartesianAxis.h>
Public Types
enum Position {
Bottom,
Top,
Right,
Left
}
Public Slots
void setCachedSizeDirty () const
virtual int tickLength (bool subUnitTicks=false) const
void update ()
Signals
void positionChanged (AbstractArea *)
Public Member Functions
void alignToReferencePoint (const RelativePosition &position)
QMap< qreal, QString > annotations () const
Returns the currently set axis annotations.
BackgroundAttributes backgroundAttributes () const
virtual int bottomOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
CartesianAxis (AbstractCartesianDiagram *diagram=0)
C'tor of the class for cartesian axes.
bool compare (const CartesianAxis *other) const
Returns true if both axes have the same settings.
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
bool compare (const AbstractAxis *other) const
Returns true if both axes have the same settings.
virtual void connectSignals ()
Wireing the signal/slot connections.
const AbstractCoordinatePlane * coordinatePlane () const
Convenience function, returns the coordinate plane, in which this axis is used.
void createObserver (AbstractDiagram *diagram)
virtual const QString customizedLabel (const QString &label) const
Reimplement this method if you want to adjust axis labels before they are printed.
int customTickLength () const
Returns the length of custom ticks on the axis.
QList< qreal > customTicks () const
Returns the currently set custom ticks on the axis.
void deleteObserver (AbstractDiagram *diagram)
const AbstractDiagram * diagram () const
virtual Qt::Orientations expandingDirections () const
pure virtual in QLayoutItem
FrameAttributes frameAttributes () const
virtual QRect geometry () const
pure virtual in QLayoutItem
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
bool hasDefaultTitleTextAttributes () const
virtual bool isAbscissa () const
virtual bool isEmpty () const
pure virtual in QLayoutItem
virtual bool isOrdinate () const
QStringList labels () const
Returns a list of strings, that are used as axis labels, as set via setLabels.
virtual void layoutPlanes ()
virtual int leftOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
virtual QSize maximumSize () const
pure virtual in QLayoutItem
virtual QSize minimumSize () const
pure virtual in QLayoutItem
bool observedBy (AbstractDiagram *diagram) const
virtual void paint (QPainter *)
reimpl
virtual void paintAll (QPainter &painter)
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintCtx (PaintContext *)
reimpl
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
virtual void paintIntoRect (QPainter &painter, const QRect &rect)
Draws the background and frame, then calls paint().
QLayout * parentLayout ()
virtual const Position position () const
void removeFromParentLayout ()
void resetTitleTextAttributes ()
Reset the title text attributes to the built-in default:
virtual int rightOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
RulerAttributes rulerAttributes () const
Returns the attributes to be used for painting the rulers.
void setAnnotations (const QMap< qreal, QString > &annotations)
Sets the axis annotations to annotations.
void setBackgroundAttributes (const BackgroundAttributes &a)
void setCustomTickLength (int value)
Sets the length of custom ticks on the axis.
void setCustomTicks (const QList< qreal > &ticksPostions)
Sets custom ticks on the axis.
void setFrameAttributes (const FrameAttributes &a)
virtual void setGeometry (const QRect &r)
pure virtual in QLayoutItem
void setLabels (const QStringList &list)
Use this to specify your own set of strings, to be used as axis labels.
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
virtual void setPosition (Position p)
void setRulerAttributes (const RulerAttributes &a)
Use this to specify the attributes used to paint the axis ruler.
void setShortLabels (const QStringList &list)
Use this to specify your own set of strings, to be used as axis labels, in case the normal labels are too long.
void setTextAttributes (const TextAttributes &a)
Use this to specify the text attributes to be used for axis labels.
void setTitleSize (qreal value)
use setTitleTextAttributes() instead
void setTitleSpace (qreal value)
void setTitleText (const QString &text)
Sets the optional text displayed as chart title.
void setTitleTextAttributes (const TextAttributes &a)
QStringList shortLabels () const
Returns a list of strings, that are used as axis labels, as set via setShortLabels.
virtual QSize sizeHint () const
pure virtual in QLayoutItem
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
TextAttributes textAttributes () const
Returns the text attributes to be used for axis labels.
qreal titleSize () const
qreal titleSpace () const
QString titleText () const
TextAttributes titleTextAttributes () const
Returns the text attributes that will be used for displaying the title text.
virtual int topOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
~CartesianAxis ()
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Slots
virtual void delayedInit ()
called for initializing after the c'tor has completed
Protected Member Functions
virtual QRect areaGeometry () const
QRect innerRect () const
virtual void positionHasChanged ()
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
The class for cartesian axes.
For being useful, axes need to be assigned to a diagram, see AbstractCartesianDiagram::addAxis and AbstractCartesianDiagram::takeAxis.
See also
PolarAxis, AbstractCartesianDiagram
Definition at line 42 of file KDChartCartesianAxis.h.
Member Enumeration Documentation
Position
enum KDChart::CartesianAxis::Position
Enumerator
Bottom
Top
Right
Left
Definition at line 50 of file KDChartCartesianAxis.h.
Constructor & Destructor Documentation
CartesianAxis()
CartesianAxis::CartesianAxis (AbstractCartesianDiagram * diagram = 0) explicit
C'tor of the class for cartesian axes.
Note
If you pass a null parent to the constructor, you need to call your diagram's addAxis function to add your axis to the diagram. Otherwise there is no need to call addAxis, since the constructor does it already.
See also
AbstractCartesianDiagram::addAxis
Definition at line 381 of file KDChartCartesianAxis.cpp.
~CartesianAxis()
CartesianAxis::~CartesianAxis ()
Definition at line 387 of file KDChartCartesianAxis.cpp.
References d, KDChart::AbstractAxis::diagram(), and KDChart::AbstractCartesianDiagram::takeAxis().
Member Function Documentation
alignToReferencePoint()
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position) inherited
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
annotations()
QMap< qreal, QString > CartesianAxis::annotations () const
Returns the currently set axis annotations.
Definition at line 1129 of file KDChartCartesianAxis.cpp.
References d.
Referenced by setAnnotations().
areaGeometry()
QRect AbstractArea::areaGeometry () const protected virtual inherited
Implements KDChart::AbstractAreaBase.
Definition at line 151 of file KDChartAbstractArea.cpp.
Referenced by KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::TernaryCoordinatePlane::paint(), paint(), KDChart::AbstractArea::paintAll(), and paintCtx().
backgroundAttributes()
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const inherited
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
bottomOverlap()
int AbstractArea::bottomOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the bottom edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 98 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
compare() [1/3]
bool CartesianAxis::compare (const CartesianAxis * other) const
Returns true if both axes have the same settings.
Definition at line 410 of file KDChartCartesianAxis.cpp.
References KDChart::AbstractAxis::compare(), position(), titleText(), and titleTextAttributes().
compare() [2/3]
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const inherited
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), and KDChart::AbstractAreaBase::frameAttributes().
Referenced by KDChart::Legend::compare().
compare() [3/3]
bool AbstractAxis::compare (const AbstractAxis * other) const inherited
Returns true if both axes have the same settings.
Definition at line 146 of file KDChartAbstractAxis.cpp.
References KDChart::AbstractAxis::labels(), KDChart::AbstractAxis::shortLabels(), and KDChart::AbstractAxis::textAttributes().
Referenced by compare().
connectSignals()
void AbstractAxis::connectSignals () virtual inherited
Wireing the signal/slot connections.
This method gets called automatically, each time, when you assign the axis to a diagram, either by passing a diagram* to the c'tor, or by calling the diagram's setAxis method, resp.
If overwriting this method in derived classes, make sure to call this base method AbstractAxis::connectSignals(), so your axis gets connected to the diagram's built-in signals.
See also
AbstractCartesianDiagram::addAxis()
Definition at line 178 of file KDChartAbstractAxis.cpp.
References KDChart::AbstractAxis::coordinateSystemChanged(), and d.
coordinatePlane()
const AbstractCoordinatePlane * AbstractAxis::coordinatePlane () const inherited
Convenience function, returns the coordinate plane, in which this axis is used.
If the axis is not used in a coordinate plane, the return value is Zero.
Definition at line 242 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
createObserver()
void AbstractAxis::createObserver (AbstractDiagram * diagram) inherited
Definition at line 168 of file KDChartAbstractAxis.cpp.
References d, and KDChart::AbstractAxis::diagram().
Referenced by KDChart::AbstractCartesianDiagram::addAxis().
customizedLabel()
const QString AbstractAxis::customizedLabel (const QString & label) const virtual inherited
Reimplement this method if you want to adjust axis labels before they are printed.
KD Chart is calling this method immediately before drawing the text, this means: What you return here will be drawn without further modifications.
Parameters
label The text of the label as KD Chart has calculated it automatically (or as it was taken from a QStringList provided by you, resp.)
Note
If you reimplement this method in a subclass of KDChartCartesianAxis, and your reimplementation's return value depends on data other than label (so KDChart will not know when it changes), you must manually ensure that layouts are adapted to any changed sizes of the axis labels. To do that, call KDChartCartesianAxis::layoutPlanes() from your reimplementation when you know that the external data changed and it will change label sizes - or when you cannot exclude that.
Returns
The text to be drawn. By default this is the same as label.
Definition at line 162 of file KDChartAbstractAxis.cpp.
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate(), and paintCtx().
customTickLength()
int CartesianAxis::customTickLength () const
Returns the length of custom ticks on the axis.
Definition at line 1118 of file KDChartCartesianAxis.cpp.
References d.
customTicks()
QList< qreal > CartesianAxis::customTicks () const
Returns the currently set custom ticks on the axis.
Definition at line 1144 of file KDChartCartesianAxis.cpp.
References d.
delayedInit
void AbstractAxis::delayedInit () protected virtual slot inherited
called for initializing after the c'tor has completed
Definition at line 138 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::AbstractAxis().
deleteObserver()
void AbstractAxis::deleteObserver (AbstractDiagram * diagram) inherited
Definition at line 173 of file KDChartAbstractAxis.cpp.
References d, and KDChart::AbstractAxis::diagram().
Referenced by KDChart::AbstractCartesianDiagram::takeAxis(), and KDChart::AbstractCartesianDiagram::~AbstractCartesianDiagram().
diagram()
const AbstractDiagram * KDChart::AbstractAxis::diagram () const inherited
Definition at line 249 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::createObserver(), KDChart::AbstractAxis::deleteObserver(), KDChart::TernaryAxis::TernaryAxis(), ~CartesianAxis(), and KDChart::LeveyJenningsAxis::~LeveyJenningsAxis().
expandingDirections()
Qt::Orientations CartesianAxis::expandingDirections () const virtual
pure virtual in QLayoutItem
Definition at line 934 of file KDChartCartesianAxis.cpp.
References Bottom, Left, position(), Right, and Top.
frameAttributes()
FrameAttributes AbstractAreaBase::frameAttributes () const inherited
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::Legend::clone(), KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
geometry()
QRect CartesianAxis::geometry () const virtual
pure virtual in QLayoutItem
Implements KDChart::AbstractAxis.
Definition at line 1103 of file KDChartCartesianAxis.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), and paintCtx().
getFrameLeadings()
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const inherited
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::innerRect(), and KDChart::AbstractAreaWidget::paintAll().
hasDefaultTitleTextAttributes()
bool CartesianAxis::hasDefaultTitleTextAttributes () const
Definition at line 467 of file KDChartCartesianAxis.cpp.
References d.
Referenced by titleTextAttributes().
innerRect()
QRect AbstractAreaBase::innerRect () const protected inherited
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::areaGeometry(), and KDChart::AbstractAreaBase::getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and KDChart::TextArea::paintAll().
isAbscissa()
bool CartesianAxis::isAbscissa () const virtual
Definition at line 528 of file KDChartCartesianAxis.cpp.
References Bottom, d, Left, position(), referenceDiagramIsBarDiagram(), Right, and Top.
Referenced by isOrdinate(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), paintCtx(), and KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
isEmpty()
bool CartesianAxis::isEmpty () const virtual
pure virtual in QLayoutItem
Definition at line 928 of file KDChartCartesianAxis.cpp.
Referenced by paintCtx().
isOrdinate()
bool CartesianAxis::isOrdinate () const virtual
Definition at line 536 of file KDChartCartesianAxis.cpp.
References isAbscissa().
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate(), KDChart::LeveyJenningsAxis::paintCtx(), and KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
labels()
QStringList AbstractAxis::labels () const inherited
Returns a list of strings, that are used as axis labels, as set via setLabels.
See also
setLabels
Definition at line 223 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::compare(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), and KDChart::TernaryAxis::paintCtx().
layoutPlanes()
void CartesianAxis::layoutPlanes () virtual
Definition at line 493 of file KDChartCartesianAxis.cpp.
References d, and KDChart::AbstractCoordinatePlane::layoutPlanes().
Referenced by resetTitleTextAttributes(), setAnnotations(), setCustomTickLength(), setCustomTicks(), setPosition(), setTitleText(), and setTitleTextAttributes().
leftOverlap()
int AbstractArea::leftOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the left edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 74 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
maximumSize()
QSize CartesianAxis::maximumSize () const virtual
pure virtual in QLayoutItem
Definition at line 959 of file KDChartCartesianAxis.cpp.
References d.
Referenced by minimumSize(), and sizeHint().
minimumSize()
QSize CartesianAxis::minimumSize () const virtual
pure virtual in QLayoutItem
Definition at line 1082 of file KDChartCartesianAxis.cpp.
References maximumSize().
observedBy()
bool KDChart::AbstractAxis::observedBy (AbstractDiagram * diagram) const inherited
Definition at line 254 of file KDChartAbstractAxis.cpp.
References d.
paint()
void CartesianAxis::paint (QPainter * painter) virtual
reimpl
Implements KDChart::AbstractLayoutItem.
Definition at line 541 of file KDChartCartesianAxis.cpp.
References KDChart::AbstractArea::areaGeometry(), d, paintCtx(), KDChart::PaintContext::setCoordinatePlane(), KDChart::PaintContext::setPainter(), KDChart::PaintContext::setRectangle(), KDChart::AbstractCoordinatePlane::zoomFactorX(), and KDChart::AbstractCoordinatePlane::zoomFactorY().
paintAll()
void AbstractArea::paintAll (QPainter & painter) virtual inherited
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
Reimplemented from KDChart::AbstractLayoutItem.
Reimplemented in KDChart::TernaryAxis.
Definition at line 120 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::areaGeometry(), d, KDChart::AbstractAreaBase::innerRect(), KDChart::AbstractLayoutItem::paint(), KDChart::AbstractAreaBase::paintBackground(), and KDChart::AbstractAreaBase::paintFrame().
Referenced by KDChart::AbstractArea::paintIntoRect().
paintBackground()
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintBackgroundAttributes()
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static inherited
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by KDChart::AbstractAreaBase::paintBackground().
paintCtx()
void CartesianAxis::paintCtx (PaintContext * context) virtual
reimpl
Reimplemented from KDChart::AbstractLayoutItem.
Reimplemented in KDChart::LeveyJenningsAxis.
Definition at line 656 of file KDChartCartesianAxis.cpp.
References KDChart::AbstractArea::areaGeometry(), KDChart::TextAttributes::autoRotate(), Bottom, KDChart::TextLayoutItem::boundingPolygon(), KDChart::PaintContext::coordinatePlane(), KDChart::AbstractAxis::customizedLabel(), d, KDChart::DataDimension::end, geometry(), KDChart::RulerAttributes::hasTickMarkPenAt(), KDChart::TextLayoutItem::intersects(), isAbscissa(), isEmpty(), KDChart::TextAttributes::isVisible(), KDChart::RulerAttributes::labelMargin(), Left, KDChart::RulerAttributes::majorTickMarkPen(), KDChart::TextLayoutItem::marginWidth(), KDChartEnums::MeasureOrientationMinimum, KDChart::RulerAttributes::minorTickMarkPen(), KDChart::TextLayoutItem::paint(), KDChart::PaintContext::painter(), position(), KDChart::TextLayoutItem::realFont(), referenceDiagramNeedsCenteredAbscissaTicks(), Right, KDChart::TextAttributes::rotation(), KDChart::AbstractAxis::rulerAttributes(), KDChart::TextLayoutItem::setGeometry(), KDChart::TextAttributes::setRotation(), KDChart::TextLayoutItem::setText(), KDChart::TextLayoutItem::setTextAttributes(), KDChart::RulerAttributes::showFirstTick(), KDChart::RulerAttributes::showRulerLine(), KDChart::TextLayoutItem::sizeHint(), KDChart::DataDimension::start, KDChart::AbstractAxis::textAttributes(), tickLength(), KDChart::RulerAttributes::tickMarkPen(), titleText(), and Top.
Referenced by paint(), and KDChart::LeveyJenningsAxis::paintAsAbscissa().
paintFrame()
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintFrameAttributes()
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static inherited
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::AbstractAreaBase::paintFrame().
paintIntoRect()
void AbstractArea::paintIntoRect (QPainter & painter, const QRect & rect) virtual inherited
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite AbstractLayoutItem::paint() instead.
Definition at line 108 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::paintAll().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
position()
const CartesianAxis::Position CartesianAxis::position () const virtual
Definition at line 488 of file KDChartCartesianAxis.cpp.
References d.
Referenced by checkExistingAxes(), compare(), expandingDirections(), findSharingAxisDiagrams(), isAbscissa(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), and paintCtx().
positionChanged
void KDChart::AbstractArea::positionChanged (AbstractArea *) signal inherited
Referenced by KDChart::AbstractArea::positionHasChanged().
positionHasChanged()
void AbstractArea::positionHasChanged () protected virtual inherited
Reimplemented from KDChart::AbstractAreaBase.
Definition at line 156 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::positionChanged().
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
resetTitleTextAttributes()
void CartesianAxis::resetTitleTextAttributes ()
Reset the title text attributes to the built-in default:
Same font and pen as AbstractAxis::textAttributes() and 1.5 times their size.
Definition at line 460 of file KDChartCartesianAxis.cpp.
References d, layoutPlanes(), and setCachedSizeDirty().
rightOverlap()
int AbstractArea::rightOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the right edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 82 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
rulerAttributes()
RulerAttributes AbstractAxis::rulerAttributes () const inherited
Returns the attributes to be used for painting the rulers.
See also
setRulerAttributes
Definition at line 209 of file KDChartAbstractAxis.cpp.
References d.
Referenced by paintCtx(), and tickLength().
setAnnotations()
void CartesianAxis::setAnnotations (const QMap< qreal, QString > & annotations)
Sets the axis annotations to annotations.
Annotations are a QMap of qreals and QStrings defining special markers and their position. If you use annotations, the normal ticks and values will be invisible. To unset the annotations, pass an empty QMap.
Definition at line 1134 of file KDChartCartesianAxis.cpp.
References annotations(), d, layoutPlanes(), and setCachedSizeDirty().
setBackgroundAttributes()
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a) inherited
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
setCachedSizeDirty
void CartesianAxis::setCachedSizeDirty () const slot
Definition at line 953 of file KDChartCartesianAxis.cpp.
References d.
Referenced by resetTitleTextAttributes(), setAnnotations(), setCustomTickLength(), setCustomTicks(), setGeometry(), setPosition(), setTitleText(), and setTitleTextAttributes().
setCustomTickLength()
void CartesianAxis::setCustomTickLength (int value)
Sets the length of custom ticks on the axis.
Definition at line 1108 of file KDChartCartesianAxis.cpp.
References d, layoutPlanes(), and setCachedSizeDirty().
setCustomTicks()
void CartesianAxis::setCustomTicks (const QList< qreal > & ticksPostions)
Sets custom ticks on the axis.
Ticks are a QList of qreals defining their special position.
Definition at line 1149 of file KDChartCartesianAxis.cpp.
References d, layoutPlanes(), and setCachedSizeDirty().
setFrameAttributes()
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a) inherited
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
Referenced by KDChart::Legend::clone().
setGeometry()
void CartesianAxis::setGeometry (const QRect & r) virtual
pure virtual in QLayoutItem
Implements KDChart::AbstractAxis.
Definition at line 1094 of file KDChartCartesianAxis.cpp.
References d, and setCachedSizeDirty().
setLabels()
void AbstractAxis::setLabels (const QStringList & list) inherited
Use this to specify your own set of strings, to be used as axis labels.
Labels specified via setLabels take precedence: If a non-empty list is passed, KD Chart will use these strings as axis labels, instead of calculating them.
If you pass a smaller number of strings than the number of labels drawn at this axis, KD Chart will repeat the strings until all labels are drawn. As an example you could specify the seven days of the week as abscissa labels, which would be repeatedly used then.
By passing an empty QStringList you can reset the default behaviour.
See also
labels, setShortLabels
Definition at line 214 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsAbscissa().
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
setPosition()
void CartesianAxis::setPosition (Position p) virtual
Definition at line 472 of file KDChartCartesianAxis.cpp.
References d, layoutPlanes(), and setCachedSizeDirty().
setRulerAttributes()
void AbstractAxis::setRulerAttributes (const RulerAttributes & a) inherited
Use this to specify the attributes used to paint the axis ruler.
Every axis has a default set of ruler attributes that is exactly the same among them. Use this method to specify your own attributes.
See also
rulerAttributes
Definition at line 203 of file KDChartAbstractAxis.cpp.
References d.
setShortLabels()
void AbstractAxis::setShortLabels (const QStringList & list) inherited
Use this to specify your own set of strings, to be used as axis labels, in case the normal labels are too long.
Note
Setting done via setShortLabels will be ignored, if you did not pass a non-empty string list via setLabels too!
By passing an empty QStringList you can reset the default behaviour.
See also
shortLabels, setLabels
Definition at line 228 of file KDChartAbstractAxis.cpp.
References d.
setTextAttributes()
void AbstractAxis::setTextAttributes (const TextAttributes & a) inherited
Use this to specify the text attributes to be used for axis labels.
By default, the reference area will be set at painting time. It will be the then-valid coordinate plane's parent widget, so normally, it will be the KDChart::Chart. Thus the labels of all of your axes in all of your diagrams within that Chart will be drawn in same font size, by default.
See also
textAttributes, setLabels
Definition at line 188 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::setType().
setTitleSize()
void CartesianAxis::setTitleSize (qreal value)
use setTitleTextAttributes() instead
Deprecated:
Definition at line 600 of file KDChartCartesianAxis.cpp.
setTitleSpace()
void CartesianAxis::setTitleSpace (qreal value)
Deprecated:
Sets the spacing between the title and the diagram.
Be aware that setting this value can lead to collisions between axis labels and the title
Definition at line 590 of file KDChartCartesianAxis.cpp.
References d.
setTitleText()
void CartesianAxis::setTitleText (const QString & text)
Sets the optional text displayed as chart title.
Definition at line 428 of file KDChartCartesianAxis.cpp.
References d, layoutPlanes(), and setCachedSizeDirty().
setTitleTextAttributes()
void CartesianAxis::setTitleTextAttributes (const TextAttributes & a)
Definition at line 440 of file KDChartCartesianAxis.cpp.
References d, layoutPlanes(), and setCachedSizeDirty().
shortLabels()
QStringList AbstractAxis::shortLabels () const inherited
Returns a list of strings, that are used as axis labels, as set via setShortLabels.
Note
Setting done via setShortLabels will be ignored, if you did not pass a non-empty string list via setLabels too!
See also
setShortLabels
Definition at line 237 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::compare().
sizeHint()
QSize CartesianAxis::sizeHint () const virtual
pure virtual in QLayoutItem
Definition at line 1088 of file KDChartCartesianAxis.cpp.
References maximumSize().
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
textAttributes()
TextAttributes AbstractAxis::textAttributes () const inherited
Returns the text attributes to be used for axis labels.
See also
setTextAttributes
Definition at line 197 of file KDChartAbstractAxis.cpp.
References d.
Referenced by KDChart::AbstractAxis::compare(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), paintCtx(), KDChart::LeveyJenningsAxis::setType(), and titleTextAttributes().
tickLength
int CartesianAxis::tickLength (bool subUnitTicks = false) const virtual slot
Definition at line 1123 of file KDChartCartesianAxis.cpp.
References KDChart::RulerAttributes::majorTickMarkLength(), KDChart::RulerAttributes::minorTickMarkLength(), and KDChart::AbstractAxis::rulerAttributes().
Referenced by paintCtx().
titleSize()
qreal CartesianAxis::titleSize () const
Deprecated:
Definition at line 606 of file KDChartCartesianAxis.cpp.
titleSpace()
qreal CartesianAxis::titleSpace () const
Deprecated:
Definition at line 595 of file KDChartCartesianAxis.cpp.
References d.
titleText()
QString CartesianAxis::titleText () const
Definition at line 435 of file KDChartCartesianAxis.cpp.
References d.
Referenced by compare(), and paintCtx().
titleTextAttributes()
TextAttributes CartesianAxis::titleTextAttributes () const
Returns the text attributes that will be used for displaying the title text.
This is either the text attributes as specified by setTitleTextAttributes, or (if setTitleTextAttributes() was not called) the default text attributes.
See also
resetTitleTextAttributes, hasDefaultTitleTextAttributes
Definition at line 448 of file KDChartCartesianAxis.cpp.
References d, KDChart::TextAttributes::fontSize(), hasDefaultTitleTextAttributes(), KDChart::TextAttributes::setFontSize(), KDChart::Measure::setValue(), and KDChart::AbstractAxis::textAttributes().
Referenced by compare().
topOverlap()
int AbstractArea::topOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the top edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 90 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
update
void KDChart::AbstractAxis::update () slot inherited
Definition at line 259 of file KDChartAbstractAxis.cpp.
References d.
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartCartesianAxis.h
KDChartCartesianAxis.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/