KD Chart 2: KDGantt::ConstraintGraphicsItem Class Reference
KDGantt::ConstraintGraphicsItem Class Reference
#include <kdganttconstraintgraphicsitem.h>
Public Types
enum { Type = UserType + 43 }
Public Member Functions
QRectF boundingRect () const
const Constraint & constraint () const
ConstraintGraphicsItem (const Constraint &c, QGraphicsItem *parent=0, GraphicsScene *scene=0)
QPointF end () const
QString ganttToolTip () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Constraint proxyConstraint () const
GraphicsScene * scene () const
void setEnd (const QPointF &end)
void setStart (const QPointF &start)
QPointF start () const
int type () const
void updateItem (const QPointF &start, const QPointF &end)
virtual ~ConstraintGraphicsItem ()
Detailed Description
Definition at line 33 of file kdganttconstraintgraphicsitem.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 35 of file kdganttconstraintgraphicsitem.h.
Constructor & Destructor Documentation
ConstraintGraphicsItem()
ConstraintGraphicsItem::ConstraintGraphicsItem (const Constraint & c, QGraphicsItem * parent = 0, GraphicsScene * scene = 0) explicit
Definition at line 38 of file kdganttconstraintgraphicsitem.cpp.
~ConstraintGraphicsItem()
ConstraintGraphicsItem::~ConstraintGraphicsItem () virtual
Definition at line 59 of file kdganttconstraintgraphicsitem.cpp.
Member Function Documentation
boundingRect()
QRectF ConstraintGraphicsItem::boundingRect () const
Definition at line 80 of file kdganttconstraintgraphicsitem.cpp.
References KDGantt::ItemDelegate::constraintBoundingRect(), KDGantt::GraphicsScene::itemDelegate(), and scene().
constraint()
const Constraint& KDGantt::ConstraintGraphicsItem::constraint () const
Definition at line 50 of file kdganttconstraintgraphicsitem.h.
end()
QPointF KDGantt::ConstraintGraphicsItem::end () const
Definition at line 56 of file kdganttconstraintgraphicsitem.h.
Referenced by setEnd(), and updateItem().
ganttToolTip()
QString ConstraintGraphicsItem::ganttToolTip () const
Definition at line 93 of file kdganttconstraintgraphicsitem.cpp.
References KDGantt::Constraint::data().
Referenced by KDGantt::GraphicsScene::helpEvent().
paint()
void ConstraintGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0)
Definition at line 85 of file kdganttconstraintgraphicsitem.cpp.
References KDGantt::GraphicsScene::itemDelegate(), KDGantt::ItemDelegate::paintConstraintItem(), and scene().
proxyConstraint()
Constraint ConstraintGraphicsItem::proxyConstraint () const
Definition at line 73 of file kdganttconstraintgraphicsitem.cpp.
References KDGantt::Constraint::dataMap(), KDGantt::Constraint::endIndex(), KDGantt::Constraint::relationType(), scene(), KDGantt::Constraint::startIndex(), KDGantt::GraphicsScene::summaryHandlingModel(), and KDGantt::Constraint::type().
scene()
GraphicsScene * ConstraintGraphicsItem::scene () const
Definition at line 68 of file kdganttconstraintgraphicsitem.cpp.
Referenced by boundingRect(), paint(), and proxyConstraint().
setEnd()
void ConstraintGraphicsItem::setEnd (const QPointF & end)
Definition at line 105 of file kdganttconstraintgraphicsitem.cpp.
References end().
Referenced by KDGantt::GraphicsItem::addEndConstraint(), and updateItem().
setStart()
void ConstraintGraphicsItem::setStart (const QPointF & start)
Definition at line 98 of file kdganttconstraintgraphicsitem.cpp.
References start().
Referenced by KDGantt::GraphicsItem::addStartConstraint(), and updateItem().
start()
QPointF KDGantt::ConstraintGraphicsItem::start () const
Definition at line 54 of file kdganttconstraintgraphicsitem.h.
Referenced by setStart(), and updateItem().
type()
int ConstraintGraphicsItem::type () const
Definition at line 63 of file kdganttconstraintgraphicsitem.cpp.
References Type.
updateItem()
void ConstraintGraphicsItem::updateItem (const QPointF & start, const QPointF & end)
Definition at line 112 of file kdganttconstraintgraphicsitem.cpp.
References end(), setEnd(), setStart(), and start().
The documentation for this class was generated from the following files:
kdganttconstraintgraphicsitem.h
kdganttconstraintgraphicsitem.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/