KD Chart 2: KDChart::AbstractAreaBase Class Reference
KDChart::AbstractAreaBase Class Reference abstract
Base class for AbstractArea and AbstractAreaWidget: An area in the chart with a background, a frame, etc.
#include <KDChartAbstractAreaBase.h>
Public Member Functions
void alignToReferencePoint (const RelativePosition &position)
BackgroundAttributes backgroundAttributes () const
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
FrameAttributes frameAttributes () const
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
void setBackgroundAttributes (const BackgroundAttributes &a)
void setFrameAttributes (const FrameAttributes &a)
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Member Functions
AbstractAreaBase ()
virtual QRect areaGeometry () const =0
QRect innerRect () const
virtual void positionHasChanged ()
virtual ~AbstractAreaBase ()
Detailed Description
Base class for AbstractArea and AbstractAreaWidget: An area in the chart with a background, a frame, etc.
AbstractAreaBase is the base class for all chart elements that have a set of background attributes and frame attributes, such as legends or axes.
Note
Normally you should not use AbstractAreaBase directly, but derive your classes from AbstractArea or AbstractAreaWidget.
This classis not a QObject, so it is easier to inherit from it, if your are inheriting from a QObject too like AbstractAreaWidget does it.
See also
AbstractArea, AbstractAreaWidget
Definition at line 65 of file KDChartAbstractAreaBase.h.
Constructor & Destructor Documentation
AbstractAreaBase()
AbstractAreaBase::AbstractAreaBase () protected
Definition at line 52 of file KDChartAbstractAreaBase.cpp.
~AbstractAreaBase()
AbstractAreaBase::~AbstractAreaBase () protected virtual
Definition at line 57 of file KDChartAbstractAreaBase.cpp.
Member Function Documentation
alignToReferencePoint()
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position)
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
areaGeometry()
virtual QRect KDChart::AbstractAreaBase::areaGeometry () const protected pure virtual
Implemented in KDChart::AbstractArea, KDChart::AbstractAreaWidget, and KDChart::TextArea.
Referenced by innerRect().
backgroundAttributes()
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by compare(), and updateCommonBrush().
compare()
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References backgroundAttributes(), and frameAttributes().
Referenced by KDChart::Legend::compare().
frameAttributes()
FrameAttributes AbstractAreaBase::frameAttributes () const
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::Legend::clone(), compare(), and updateCommonBrush().
getFrameLeadings()
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by innerRect(), and KDChart::AbstractAreaWidget::paintAll().
innerRect()
QRect AbstractAreaBase::innerRect () const protected
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References areaGeometry(), and getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and KDChart::TextArea::paintAll().
paintBackground()
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintBackgroundAttributes()
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by paintBackground().
paintFrame()
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintFrameAttributes()
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by paintFrame().
positionHasChanged()
void AbstractAreaBase::positionHasChanged () protected virtual
Reimplemented in KDChart::AbstractArea, KDChart::AbstractAreaWidget, and KDChart::TextArea.
Definition at line 234 of file KDChartAbstractAreaBase.cpp.
Referenced by setBackgroundAttributes(), and setFrameAttributes().
setBackgroundAttributes()
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a)
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and positionHasChanged().
setFrameAttributes()
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a)
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and positionHasChanged().
Referenced by KDChart::Legend::clone().
The documentation for this class was generated from the following files:
KDChartAbstractAreaBase.h
KDChartAbstractAreaBase.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/