KD Chart 2: KDGantt::AbstractRowController Class Reference
KDGantt::AbstractRowController Class Reference abstract
Abstract baseclass for row controllers. A row controller is used by the GraphicsView to nagivate the model and to determine the row geometries.
#include <KDGanttAbstractRowController>
Public Member Functions
AbstractRowController ()
virtual int headerHeight () const =0
virtual QModelIndex indexAbove (const QModelIndex &idx) const =0
virtual QModelIndex indexAt (int height) const =0
virtual QModelIndex indexBelow (const QModelIndex &idx) const =0
virtual bool isRowExpanded (const QModelIndex &idx) const =0
virtual bool isRowVisible (const QModelIndex &idx) const =0
virtual int maximumItemHeight () const =0
virtual Span rowGeometry (const QModelIndex &idx) const =0
virtual int totalHeight () const =0
virtual ~AbstractRowController ()
Detailed Description
Abstract baseclass for row controllers. A row controller is used by the GraphicsView to nagivate the model and to determine the row geometries.
Definition at line 34 of file kdganttabstractrowcontroller.h.
Constructor & Destructor Documentation
AbstractRowController::AbstractRowController ()
Constructor. Does nothing
Definition at line 35 of file kdganttabstractrowcontroller.cpp.
AbstractRowController::~AbstractRowController () virtual
Destructor. Does nothing
Definition at line 40 of file kdganttabstractrowcontroller.cpp.
Member Function Documentation
int AbstractRowController::headerHeight () const pure virtual
Returns
The height of the header part of the view.
Implement this to control how much space is reserved at the top of the view for a header
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
QModelIndex AbstractRowController::indexAbove (const QModelIndex & idx) const pure virtual
Returns
The modelindex for the previous row before idx.
See also
QTreeView::indexAbove
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::DateTimeGrid::paintGrid().
virtual QModelIndex KDGantt::AbstractRowController::indexAt (int height) const pure virtual
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::DateTimeGrid::paintGrid().
QModelIndex AbstractRowController::indexBelow (const QModelIndex & idx) const pure virtual
Returns
The modelindex for the next row after idx.
See also
QTreeView::indexBelow
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::DateTimeGrid::paintGrid().
virtual bool KDGantt::AbstractRowController::isRowExpanded (const QModelIndex & idx) const pure virtual
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::GraphicsScene::updateRow().
bool AbstractRowController::isRowVisible (const QModelIndex & idx) const pure virtual
Returns
true if the row containing index idx is visible in the view.
Implement this to allow KDGantt to optimize how items on screen are created. It is not harmful to always return true here, but the View will not perform optimally.
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
virtual int KDGantt::AbstractRowController::maximumItemHeight () const pure virtual
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::GraphicsItem::updateItem().
Span AbstractRowController::rowGeometry (const QModelIndex & idx) const pure virtual
Returns
A Span consisting of the row offset and height for the row containing idx. A simple implementation might look like
Span MyRowCtrlr::rowGeometry(const QModelIndex& idx)
{
     return Span(idx.row()*10,10);
}
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::DateTimeGrid::paintGrid(), and KDGantt::GraphicsScene::updateRow().
int AbstractRowController::totalHeight () const pure virtual
Returns
the total height of the rows. For uniformly sized rows that would be number_of_rows*row_height.
Implemented in KDGantt::ListViewRowController, and KDGantt::TreeViewRowController.
Referenced by KDGantt::GraphicsView::resizeEvent(), and KDGantt::GraphicsView::updateSceneRect().
The documentation for this class was generated from the following files:
kdganttabstractrowcontroller.h
kdganttabstractrowcontroller.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/