KD Chart 2: KDChart::ZoomParameters Class Reference
KDChart::ZoomParameters Class Reference
ZoomParameters stores the center and the factor of zooming internally.
#include <KDChartZoomParameters.h>
Public Member Functions
const QPointF center () const
void setCenter (const QPointF &center)
ZoomParameters ()
ZoomParameters (qreal xFactor, qreal yFactor, const QPointF &center)
Public Attributes
qreal xCenter
qreal xFactor
qreal yCenter
qreal yFactor
Detailed Description
ZoomParameters stores the center and the factor of zooming internally.
Definition at line 44 of file KDChartZoomParameters.h.
Constructor & Destructor Documentation
ZoomParameters() [1/2]
KDChart::ZoomParameters::ZoomParameters ()
Definition at line 46 of file KDChartZoomParameters.h.
ZoomParameters() [2/2]
KDChart::ZoomParameters::ZoomParameters (qreal xFactor, qreal yFactor, const QPointF & center)
Definition at line 54 of file KDChartZoomParameters.h.
Member Function Documentation
center()
const QPointF KDChart::ZoomParameters::center () const
Definition at line 67 of file KDChartZoomParameters.h.
References xCenter, and yCenter.
Referenced by KDChart::AbstractCoordinatePlane::mousePressEvent(), and setCenter().
setCenter()
void KDChart::ZoomParameters::setCenter (const QPointF & center)
Definition at line 62 of file KDChartZoomParameters.h.
References center(), xCenter, and yCenter.
Member Data Documentation
xCenter
qreal KDChart::ZoomParameters::xCenter
Definition at line 75 of file KDChartZoomParameters.h.
Referenced by center(), and setCenter().
xFactor
qreal KDChart::ZoomParameters::xFactor
Definition at line 72 of file KDChartZoomParameters.h.
Referenced by KDChart::AbstractCoordinatePlane::mousePressEvent().
yCenter
qreal KDChart::ZoomParameters::yCenter
Definition at line 76 of file KDChartZoomParameters.h.
Referenced by center(), and setCenter().
yFactor
qreal KDChart::ZoomParameters::yFactor
Definition at line 73 of file KDChartZoomParameters.h.
Referenced by KDChart::AbstractCoordinatePlane::mousePressEvent().
The documentation for this class was generated from the following file:
KDChartZoomParameters.h
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/