KD Chart 2: KDGantt::SummaryHandlingProxyModel Class Reference
KDGantt::SummaryHandlingProxyModel Class Reference
Proxy model that supports summary gantt items.
#include <kdganttsummaryhandlingproxymodel.h>
Public Member Functions
int columnCount (const QModelIndex &idx=QModelIndex()) const
QVariant data (const QModelIndex &proxyIndex, int role=Qt::DisplayRole) const
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Qt::ItemFlags flags (const QModelIndex &idx) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
QMimeData * mimeData (const QModelIndexList &indexes) const
QStringList mimeTypes () const
QModelIndex parent (const QModelIndex &idx) const
int rowCount (const QModelIndex &idx=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setSourceModel (QAbstractItemModel *model)
SummaryHandlingProxyModel (QObject *parent=0)
Qt::DropActions supportedDropActions () const
virtual ~SummaryHandlingProxyModel ()
Protected Slots
virtual void sourceColumnsInserted (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsRemoved (const QModelIndex &idx, int start, int end)
virtual void sourceLayoutAboutToBeChanged ()
virtual void sourceModelAboutToBeReset ()
virtual void sourceRowsInserted (const QModelIndex &idx, int start, int end)
virtual void sourceRowsRemoved (const QModelIndex &, int start, int end)
Protected Member Functions
void sourceColumnsAboutToBeInserted (const QModelIndex &idx, int start, int end)
void sourceColumnsAboutToBeRemoved (const QModelIndex &idx, int start, int end)
void sourceDataChanged (const QModelIndex &from, const QModelIndex &to)
void sourceLayoutChanged ()
void sourceModelReset ()
void sourceRowsAboutToBeInserted (const QModelIndex &idx, int start, int end)
void sourceRowsAboutToBeRemoved (const QModelIndex &, int start, int end)
Detailed Description
Proxy model that supports summary gantt items.
This proxy model provides the functionality of summary items. A summary item is an item with type KDGantt::TypeSummary and zero or more children in the model that it summarizes. GraphicsView itself does not dictate any policy for summary items, instead the logic for making the summary items start and end points span it's children is provided by this proxy.
The start and end times of a summary is the min/max of the start/end times of it's children.
See also
GraphicsView::setModel
Definition at line 29 of file kdganttsummaryhandlingproxymodel.h.
Constructor & Destructor Documentation
SummaryHandlingProxyModel()
SummaryHandlingProxyModel::SummaryHandlingProxyModel (QObject * parent = 0) explicit
Constructor. Creates a new SummaryHandlingProxyModel with parent parent
Definition at line 122 of file kdganttsummaryhandlingproxymodel.cpp.
~SummaryHandlingProxyModel()
SummaryHandlingProxyModel::~SummaryHandlingProxyModel () virtual
Definition at line 129 of file kdganttsummaryhandlingproxymodel.cpp.
Member Function Documentation
columnCount()
int ForwardingProxyModel::columnCount (const QModelIndex & idx = QModelIndex()) const inherited
See also
QAbstractItemModel::columnCount
Definition at line 262 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapToSource().
data()
QVariant SummaryHandlingProxyModel::data (const QModelIndex & proxyIndex, int role = Qt::DisplayRole) const
See also
QAbstractItemModel::data
Definition at line 228 of file kdganttsummaryhandlingproxymodel.cpp.
References d, KDGantt::EndTimeRole, KDGantt::ForwardingProxyModel::mapToSource(), and KDGantt::StartTimeRole.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
dropMimeData()
bool ForwardingProxyModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) inherited
Definition at line 294 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::index(), KDGantt::ForwardingProxyModel::mapToSource(), KDGantt::ForwardingProxyModel::parent(), and KDGantt::ForwardingProxyModel::rowCount().
flags()
Qt::ItemFlags SummaryHandlingProxyModel::flags (const QModelIndex & idx) const
See also
QAbstractItemModel::flags
Definition at line 216 of file kdganttsummaryhandlingproxymodel.cpp.
References d, and KDGantt::ForwardingProxyModel::mapToSource().
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
index()
QModelIndex ForwardingProxyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const inherited
See also
QAbstractItemModel::index
Definition at line 268 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource(), KDGantt::ForwardingProxyModel::mapToSource(), and KDGantt::ForwardingProxyModel::parent().
Referenced by KDGantt::ProxyModel::data(), KDGantt::ForwardingProxyModel::dropMimeData(), KDAB_SCOPED_UNITTEST_SIMPLE(), setData(), and KDGantt::ForwardingProxyModel::setData().
mapFromSource()
QModelIndex ForwardingProxyModel::mapFromSource (const QModelIndex & sourceIndex) const inherited
Converts indexes in the source model to indexes in the proxy model
Definition at line 45 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::index(), KDGantt::ForwardingProxyModel::parent(), setData(), KDGantt::ForwardingProxyModel::sourceColumnsAboutToBeInserted(), KDGantt::ForwardingProxyModel::sourceColumnsAboutToBeRemoved(), sourceDataChanged(), KDGantt::ForwardingProxyModel::sourceDataChanged(), KDGantt::ForwardingProxyModel::sourceRowsAboutToBeInserted(), and KDGantt::ForwardingProxyModel::sourceRowsAboutToBeRemoved().
mapToSource()
QModelIndex ForwardingProxyModel::mapToSource (const QModelIndex & proxyIndex) const inherited
Converts indexes in the proxy model to indexes in the source model
Definition at line 72 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::columnCount(), data(), KDGantt::ForwardingProxyModel::dropMimeData(), flags(), KDGantt::ForwardingProxyModel::index(), KDGantt::ForwardingProxyModel::mimeData(), KDGantt::ForwardingProxyModel::parent(), KDGantt::ForwardingProxyModel::rowCount(), setData(), and KDGantt::ForwardingProxyModel::setData().
mimeData()
QMimeData * ForwardingProxyModel::mimeData (const QModelIndexList & indexes) const inherited
Definition at line 286 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapToSource().
mimeTypes()
QStringList ForwardingProxyModel::mimeTypes () const inherited
Definition at line 314 of file kdganttforwardingproxymodel.cpp.
parent()
QModelIndex ForwardingProxyModel::parent (const QModelIndex & idx) const inherited
See also
QAbstractItemModel::parent
Definition at line 274 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapFromSource(), and KDGantt::ForwardingProxyModel::mapToSource().
Referenced by KDGantt::ForwardingProxyModel::dropMimeData(), and KDGantt::ForwardingProxyModel::index().
rowCount()
int ForwardingProxyModel::rowCount (const QModelIndex & idx = QModelIndex()) const inherited
See also
QAbstractItemModel::rowCount
Definition at line 256 of file kdganttforwardingproxymodel.cpp.
References KDGantt::ForwardingProxyModel::mapToSource().
Referenced by KDGantt::ForwardingProxyModel::dropMimeData().
setData()
bool SummaryHandlingProxyModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
See also
QAbstractItemModel::setData
Definition at line 252 of file kdganttsummaryhandlingproxymodel.cpp.
References d, KDGantt::EndTimeRole, KDGantt::ForwardingProxyModel::index(), KDGantt::ForwardingProxyModel::mapFromSource(), KDGantt::ForwardingProxyModel::mapToSource(), and KDGantt::StartTimeRole.
setSourceModel()
void SummaryHandlingProxyModel::setSourceModel (QAbstractItemModel * model)
Sets the model to be used as the source model for this proxy. The proxy does not take ownership of the model.
See also
QAbstractProxyModel::setSourceModel
Definition at line 152 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
sourceColumnsAboutToBeInserted()
void SummaryHandlingProxyModel::sourceColumnsAboutToBeInserted (const QModelIndex & parentIdx, int start, int end) protected virtual
Called just before columns are inserted into the source model.
See also
QAbstractItemModel::columnsAboutToBeInserted()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 187 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
sourceColumnsAboutToBeRemoved()
void SummaryHandlingProxyModel::sourceColumnsAboutToBeRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual
Called just before columns are removed from the source model.
See also
QAbstractItemModel::columnsAboutToBeRemoved()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 195 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
sourceColumnsInserted
void ForwardingProxyModel::sourceColumnsInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after columns have been inserted into the source model.
See also
QAbstractItemModel::columnsInserted()
Definition at line 188 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceColumnsRemoved
void ForwardingProxyModel::sourceColumnsRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after columns have been removed from the source model.
See also
QAbstractItemModel::columnsRemoved()
Definition at line 209 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceDataChanged()
void SummaryHandlingProxyModel::sourceDataChanged (const QModelIndex & from, const QModelIndex & to) protected virtual
Called when the data in an existing item in the source model changes.
See also
QAbstractItemModel::dataChanged()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 170 of file kdganttsummaryhandlingproxymodel.cpp.
References d, KDGantt::ItemTypeRole, KDGantt::ForwardingProxyModel::mapFromSource(), and KDGantt::TypeSummary.
sourceLayoutAboutToBeChanged
void ForwardingProxyModel::sourceLayoutAboutToBeChanged () protected virtual slot inherited
Called just before the layout of the source model is changed.
See also
QAbstractItemModel::layoutAboutToBeChanged()
Definition at line 150 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceLayoutChanged()
void SummaryHandlingProxyModel::sourceLayoutChanged () protected virtual
Called when the layout of the source model has changed.
See also
QAbstractItemModel::layoutChanged()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 164 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
sourceModelAboutToBeReset
void ForwardingProxyModel::sourceModelAboutToBeReset () protected virtual slot inherited
Called when the source model is about to be reset.
See also
QAbstractItemModel::modelAboutToBeReset()
Definition at line 131 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceModelReset()
void SummaryHandlingProxyModel::sourceModelReset () protected virtual
Called when the source model is reset
See also
QAbstractItemModel::modelReset()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 158 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
sourceRowsAboutToBeInserted()
void SummaryHandlingProxyModel::sourceRowsAboutToBeInserted (const QModelIndex & parentIdx, int start, int end) protected virtual
Called just before rows are inserted into the source model.
See also
QAbstractItemModel::rowsAboutToBeInserted()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 203 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
sourceRowsAboutToBeRemoved()
void SummaryHandlingProxyModel::sourceRowsAboutToBeRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual
Called just before rows are removed from the source model.
See also
QAbstractItemModel::rowsAboutToBeRemoved()
Reimplemented from KDGantt::ForwardingProxyModel.
Definition at line 209 of file kdganttsummaryhandlingproxymodel.cpp.
References d.
sourceRowsInserted
void ForwardingProxyModel::sourceRowsInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after rows have been inserted into the source model.
See also
QAbstractItemModel::rowsInserted()
Definition at line 228 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
sourceRowsRemoved
void ForwardingProxyModel::sourceRowsRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot inherited
Called after rows have been removed from the source model.
See also
QAbstractItemModel::rowsRemoved()
Definition at line 247 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::ForwardingProxyModel::setSourceModel().
supportedDropActions()
Qt::DropActions ForwardingProxyModel::supportedDropActions () const inherited
Definition at line 319 of file kdganttforwardingproxymodel.cpp.
The documentation for this class was generated from the following files:
kdganttsummaryhandlingproxymodel.h
kdganttsummaryhandlingproxymodel.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/