KD Chart 2: KDChart::LeveyJenningsCoordinatePlane Class Reference
KDChart::LeveyJenningsCoordinatePlane Class Reference
Levey Jennings coordinate plane This is actually nothing real more than a plain cartesian coordinate plane.
#include <KDChartLeveyJenningsCoordinatePlane.h>
Public Types
enum AxesCalcMode {
Linear,
Logarithmic
}
Public Slots
void adjustHorizontalRangeToData ()
Adjust horizontal range settings to the ranges covered by the model's data values.
void adjustRangesToData ()
Adjust both, horizontal and vertical range settings to the ranges covered by the model's data values.
void adjustVerticalRangeToData ()
Adjust vertical range settings to the ranges covered by the model's data values.
void layoutPlanes ()
Calling layoutPlanes() on the plane triggers the global KDChart::Chart::slotLayoutPlanes()
void relayout ()
Calling relayout() on the plane triggers the global KDChart::Chart::slotRelayout()
void setGridNeedsRecalculate ()
Used by the chart to clear the cached grid data.
void update ()
Calling update() on the plane triggers the global KDChart::Chart::update()
Signals
void boundariesChanged ()
void destroyedCoordinatePlane (AbstractCoordinatePlane *)
Emitted when this coordinate plane is destroyed.
void geometryChanged (QRect, QRect)
Emitted after the geometry of the Coordinate Plane has been changed.
void internal_geometryChanged (QRect, QRect)
void needLayoutPlanes ()
Emitted when plane needs to trigger the Chart's layouting of the coord.
void needRelayout ()
Emitted when plane needs to trigger the Chart's layouting.
void needUpdate ()
Emitted when plane needs to update its drawings.
void positionChanged (AbstractArea *)
void propertiesChanged ()
Emitted upon change of a property of the Coordinate Plane or any of its components.
void viewportCoordinateSystemChanged ()
Emitted upon change of the view coordinate system.
Public Member Functions
void addDiagram (AbstractDiagram *diagram)
Adds a diagram to this coordinate plane.
void alignToReferencePoint (const RelativePosition &position)
const bool autoAdjustGridToZoom () const
Return the status of the built-in grid adjusting feature.
unsigned int autoAdjustHorizontalRangeToData () const
Returns the maximal allowed percent of the horizontal space covered by the coordinate plane that may be empty.
unsigned int autoAdjustVerticalRangeToData () const
Returns the maximal allowed percent of the vertical space covered by the coordinate plane that may be empty.
AxesCalcMode axesCalcModeX () const
AxesCalcMode axesCalcModeY () const
BackgroundAttributes backgroundAttributes () const
virtual int bottomOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
AbstractDiagram * diagram ()
QRectF diagramArea () const
Returns the (physical) area occupied by the diagram.
AbstractDiagramList diagrams ()
ConstAbstractDiagramList diagrams () const
bool doesIsometricScaling () const
Qt::Orientations expandingDirections () const
pure virtual in QLayoutItem
FrameAttributes frameAttributes () const
virtual QRect geometry () const
pure virtual in QLayoutItem
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
GridAttributes globalGridAttributes () const
LeveyJenningsGridAttributes gridAttributes () const
const GridAttributes gridAttributes (Qt::Orientation orientation) const
DataDimensionsList gridDimensionsList ()
Returns the dimensions used for drawing the grid lines.
bool hasFixedDataCoordinateSpaceRelation () const
bool hasOwnGridAttributes (Qt::Orientation orientation) const
QPair< qreal, qreal > horizontalRange () const
bool isCornerSpacersEnabled () const
virtual bool isEmpty () const
pure virtual in QLayoutItem
bool isHorizontalRangeReversed () const
bool isRubberBandZoomingEnabled () const
bool isVerticalRangeReversed () const
const bool isVisiblePoint (const QPointF &point) const
Tests, if a point is visible on the coordinate plane.
virtual int leftOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
LeveyJenningsCoordinatePlane (Chart *parent=0)
QRectF logicalArea () const
Returns the logical area, i.e., the rectangle defined by the very top left and very bottom right coordinate.
virtual QSize maximumSize () const
pure virtual in QLayoutItem
virtual QSize minimumSize () const
pure virtual in QLayoutItem
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void paint (QPainter *)
reimpl
virtual void paintAll (QPainter &painter)
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
virtual void paintIntoRect (QPainter &painter, const QRect &rect)
Draws the background and frame, then calls paint().
Chart * parent ()
const Chart * parent () const
QLayout * parentLayout ()
AbstractCoordinatePlane * referenceCoordinatePlane () const
There are two ways, in which planes can be caused to interact, in where they are put layouting wise: The first is the reference plane.
void removeFromParentLayout ()
virtual void replaceDiagram (AbstractDiagram *diagram, AbstractDiagram *oldDiagram=0)
Replaces the old diagram, or appends the diagram, it there is none yet.
void resetGridAttributes (Qt::Orientation orientation)
Reset the attributes to be used for grid lines drawn in horizontal direction (or in vertical direction, resp.).
virtual int rightOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
void setAutoAdjustGridToZoom (bool autoAdjust)
Disable / re-enable the built-in grid adjusting feature.
void setAutoAdjustHorizontalRangeToData (unsigned int percentEmpty=67)
Automatically adjust horizontal range settings to the ranges covered by the model's values, when ever the data have changed, and then emit horizontalRangeAutomaticallyAdjusted.
void setAutoAdjustVerticalRangeToData (unsigned int percentEmpty=67)
Automatically adjust vertical range settings to the ranges covered by the model's values, when ever the data have changed, and then emit verticalRangeAutomaticallyAdjusted.
void setAxesCalcModes (AxesCalcMode mode)
Specifies the calculation modes for all axes.
void setAxesCalcModeX (AxesCalcMode mode)
Specifies the calculation mode for all Abscissa axes.
void setAxesCalcModeY (AxesCalcMode mode)
Specifies the calculation mode for all Ordinate axes.
void setBackgroundAttributes (const BackgroundAttributes &a)
void setCornerSpacersEnabled (bool enable)
Enables or disables the use of spacers in the plane corners.
void setFixedDataCoordinateSpaceRelation (bool fixed)
Allows to specify a fixed data-space / coordinate-space relation.
void setFrameAttributes (const FrameAttributes &a)
void setGeometry (const QRect &r)
reimplemented from AbstractCoordinatePlane
void setGlobalGridAttributes (const GridAttributes &)
Set the grid attributes to be used by this coordinate plane.
void setGridAttributes (const LeveyJenningsGridAttributes &attr)
void setGridAttributes (Qt::Orientation orientation, const GridAttributes &)
Set the attributes to be used for grid lines drawn in horizontal direction (or in vertical direction, resp.).
void setHorizontalRange (const QPair< qreal, qreal > &range)
Set the boundaries of the visible value space displayed in horizontal direction.
void setHorizontalRangeReversed (bool reverse)
Sets whether the horizontal range should be reversed or not, i.e.
void setIsometricScaling (bool onOff)
If onOff is true, enforce that X and Y distances are scaled by the same factor.
void setParent (Chart *parent)
Called internally by KDChart::Chart.
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
void setReferenceCoordinatePlane (AbstractCoordinatePlane *plane)
Set another coordinate plane to be used as the reference plane for this one.
void setRubberBandZoomingEnabled (bool enable)
Enables or disables zooming with a rubber band using the mouse.
void setVerticalRange (const QPair< qreal, qreal > &range)
Set the boundaries of the visible value space displayed in vertical direction.
void setVerticalRangeReversed (bool reverse)
Sets whether the vertical range should be reversed or not, i.e.
void setXAxisStartAtZero (bool fixedStart)
Allows to fix the lower bound of X axis to zero when diagram is in first quadrant.
virtual void setZoomCenter (const QPointF &center)
virtual void setZoomFactors (qreal factorX, qreal factorY)
virtual void setZoomFactorX (qreal factor)
virtual void setZoomFactorY (qreal factor)
AbstractCoordinatePlane * sharedAxisMasterPlane (QPainter *p=0)
reimpl
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
virtual void takeDiagram (AbstractDiagram *diagram)
Removes the diagram from the plane, without deleting it.
virtual int topOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
const QPointF translate (const QPointF &diagramPoint) const
Translate the given point in value space coordinates to a position in pixel space.
QPair< qreal, qreal > verticalRange () const
QRectF visibleDataRange () const
Returns the currently visible data range.
QRectF visibleDiagramArea () const
Returns the visible part of the diagram area, i.e.
bool xAxisStartAtZero () const
virtual QPointF zoomCenter () const
virtual qreal zoomFactorX () const
virtual qreal zoomFactorY () const
~LeveyJenningsCoordinatePlane ()
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Slots
void slotLayoutChanged (AbstractDiagram *)
Protected Member Functions
QRectF adjustedToMaxEmptyInnerPercentage (const QRectF &r, unsigned int percentX, unsigned int percentY) const
virtual QRect areaGeometry () const
virtual QRectF calculateRawDataBoundingRect () const
bool doneSetZoomCenter (const QPointF &center)
bool doneSetZoomFactorX (qreal factor)
bool doneSetZoomFactorY (qreal factor)
virtual QRectF drawingArea () const
virtual DataDimensionsList getDataDimensionsList () const
QRectF getRawDataBoundingRectFromDiagrams () const
void handleFixedDataCoordinateSpaceRelation (const QRectF &geometry)
bool hasHeightForWidth () const
int heightForWidth (int w) const
QRect innerRect () const
void layoutDiagrams ()
Distribute the available space among the diagrams and axes.
void paintEvent (QPaintEvent *)
virtual void positionHasChanged ()
QSize sizeHint () const
pure virtual in QLayoutItem
const QPointF translateBack (const QPointF &screenPoint) const
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
Levey Jennings coordinate plane This is actually nothing real more than a plain cartesian coordinate plane.
The difference is, that only Levey Jennings Diagrams can be added to it.
Definition at line 40 of file KDChartLeveyJenningsCoordinatePlane.h.
Member Enumeration Documentation
enum KDChart::AbstractCoordinatePlane::AxesCalcMode inherited
Enumerator
Linear
Logarithmic
Definition at line 53 of file KDChartAbstractCoordinatePlane.h.
Constructor & Destructor Documentation
LeveyJenningsCoordinatePlane::LeveyJenningsCoordinatePlane (Chart * parent = 0) explicit
Definition at line 43 of file KDChartLeveyJenningsCoordinatePlane.cpp.
LeveyJenningsCoordinatePlane::~LeveyJenningsCoordinatePlane ()
Definition at line 48 of file KDChartLeveyJenningsCoordinatePlane.cpp.
Member Function Documentation
void LeveyJenningsCoordinatePlane::addDiagram (AbstractDiagram * diagram) virtual
Adds a diagram to this coordinate plane.
Parameters
diagram The diagram to add.
See also
replaceDiagram, takeDiagram
Reimplemented from KDChart::CartesianCoordinatePlane.
Definition at line 56 of file KDChartLeveyJenningsCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::addDiagram().
QRectF CartesianCoordinatePlane::adjustedToMaxEmptyInnerPercentage (const QRectF & r, unsigned int percentX, unsigned int percentY) const protected inherited
Definition at line 182 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::axesCalcModeX(), KDChart::CartesianCoordinatePlane::axesCalcModeY(), d, and KDChart::AbstractCoordinatePlane::Logarithmic.
Referenced by KDChart::CartesianCoordinatePlane::calculateRawDataBoundingRect().
void CartesianCoordinatePlane::adjustHorizontalRangeToData () slot inherited
Adjust horizontal range settings to the ranges covered by the model's data values.
See also
adjustRangesToData
Definition at line 666 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::adjustRangesToData () slot inherited
Adjust both, horizontal and vertical range settings to the ranges covered by the model's data values.
See also
setHorizontalRange, setVerticalRange
adjustHorizontalRangeToData, adjustVerticalRangeToData
setAutoAdjustHorizontalRangeToData, setAutoAdjustVerticalRangeToData
Definition at line 655 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::adjustVerticalRangeToData () slot inherited
Adjust vertical range settings to the ranges covered by the model's data values.
See also
adjustRangesToData
Definition at line 675 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position) inherited
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
QRect AbstractArea::areaGeometry () const protected virtual inherited
Implements KDChart::AbstractAreaBase.
Definition at line 151 of file KDChartAbstractArea.cpp.
Referenced by KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::TernaryCoordinatePlane::paint(), KDChart::CartesianAxis::paint(), KDChart::AbstractArea::paintAll(), and KDChart::CartesianAxis::paintCtx().
const bool CartesianCoordinatePlane::autoAdjustGridToZoom () const inherited
Return the status of the built-in grid adjusting feature.
See also
setAutoAdjustGridToZoom
Definition at line 776 of file KDChartCartesianCoordinatePlane.cpp.
References d.
unsigned int CartesianCoordinatePlane::autoAdjustHorizontalRangeToData () const inherited
Returns the maximal allowed percent of the horizontal space covered by the coordinate plane that may be empty.
Returns
A percent value indicating how much of the horizontal space may be empty. If more than this is empty, automatic range adjusting is applied. A return value of 100 indicates that no such automatic adjusting is done at all.
See also
setAutoAdjustHorizontalRangeToData, adjustRangesToData
Definition at line 708 of file KDChartCartesianCoordinatePlane.cpp.
References d.
unsigned int CartesianCoordinatePlane::autoAdjustVerticalRangeToData () const inherited
Returns the maximal allowed percent of the vertical space covered by the coordinate plane that may be empty.
Returns
A percent value indicating how much of the vertical space may be empty. If more than this is empty, automatic range adjusting is applied. A return value of 100 indicates that no such automatic adjusting is done at all.
See also
setAutoAdjustVerticalRangeToData, adjustRangesToData
Definition at line 713 of file KDChartCartesianCoordinatePlane.cpp.
References d.
CartesianCoordinatePlane::AxesCalcMode CartesianCoordinatePlane::axesCalcModeX () const inherited
Definition at line 573 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::adjustedToMaxEmptyInnerPercentage(), and KDChart::CartesianCoordinatePlane::getDataDimensionsList().
CartesianCoordinatePlane::AxesCalcMode CartesianCoordinatePlane::axesCalcModeY () const inherited
Definition at line 568 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::adjustedToMaxEmptyInnerPercentage(), and KDChart::CartesianCoordinatePlane::getDataDimensionsList().
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const inherited
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
int AbstractArea::bottomOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the bottom edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 98 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
void KDChart::AbstractCoordinatePlane::boundariesChanged () signal inherited
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::CartesianCoordinatePlane::setHorizontalRange(), and KDChart::CartesianCoordinatePlane::setVerticalRange().
QRectF CartesianCoordinatePlane::calculateRawDataBoundingRect () const protected virtual inherited
Definition at line 223 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::adjustedToMaxEmptyInnerPercentage(), d, and KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams().
Referenced by KDChart::CartesianCoordinatePlane::getDataDimensionsList().
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const inherited
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), and KDChart::AbstractAreaBase::frameAttributes().
Referenced by KDChart::Legend::compare().
void KDChart::AbstractCoordinatePlane::destroyedCoordinatePlane (AbstractCoordinatePlane *) signal inherited
Emitted when this coordinate plane is destroyed.
Referenced by KDChart::AbstractCoordinatePlane::~AbstractCoordinatePlane().
AbstractDiagram * AbstractCoordinatePlane::diagram () inherited
Returns
The first diagram associated with this coordinate plane.
Definition at line 130 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Widget::diagram(), findSharingAxisDiagrams(), KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::CartesianCoordinatePlane::setGeometry(), KDChart::PolarCoordinatePlane::setStartPosition(), KDChart::Widget::setType(), and KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
QRectF CartesianCoordinatePlane::diagramArea () const inherited
Returns the (physical) area occupied by the diagram.
Unless zoom is applied (which is also true when a fixed data coordinate / space relation is used),
diagramArea() == drawingArea()
.
See also
setFixedDataCoordinateSpaceRelation
drawingArea
Definition at line 354 of file KDChartCartesianCoordinatePlane.cpp.
References d, and KDChart::CartesianCoordinatePlane::logicalArea().
Referenced by KDChart::CartesianCoordinatePlane::visibleDiagramArea().
AbstractDiagramList AbstractCoordinatePlane::diagrams () inherited
Returns
The list of diagrams associated with this coordinate plane.
Definition at line 140 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by allAxisAnnotations(), KDChart::Chart::event(), KDChart::CartesianCoordinatePlane::getDataDimensionsList(), KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::Chart::mouseDoubleClickEvent(), KDChart::Chart::mouseMoveEvent(), KDChart::Chart::mousePressEvent(), KDChart::Chart::mouseReleaseEvent(), KDChart::TernaryCoordinatePlane::paint(), KDChart::PolarCoordinatePlane::paint(), KDChart::CartesianCoordinatePlane::paint(), KDChart::CartesianCoordinatePlane::setAxesCalcModes(), and KDChart::CartesianCoordinatePlane::setGeometry().
ConstAbstractDiagramList AbstractCoordinatePlane::diagrams () const inherited
Returns
The list of diagrams associated with this coordinate plane.
Definition at line 145 of file KDChartAbstractCoordinatePlane.cpp.
References d.
bool CartesianCoordinatePlane::doesIsometricScaling () const inherited
Definition at line 479 of file KDChartCartesianCoordinatePlane.cpp.
References d.
bool CartesianCoordinatePlane::doneSetZoomCenter (const QPointF & center) protected inherited
Definition at line 508 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), and KDChart::CartesianCoordinatePlane::setZoomCenter().
bool CartesianCoordinatePlane::doneSetZoomFactorX (qreal factor) protected inherited
Definition at line 484 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), KDChart::CartesianCoordinatePlane::setZoomFactors(), and KDChart::CartesianCoordinatePlane::setZoomFactorX().
bool CartesianCoordinatePlane::doneSetZoomFactorY (qreal factor) protected inherited
Definition at line 496 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), KDChart::CartesianCoordinatePlane::setZoomFactors(), and KDChart::CartesianCoordinatePlane::setZoomFactorY().
QRectF CartesianCoordinatePlane::drawingArea () const protected virtual inherited
Definition at line 321 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::AbstractArea::areaGeometry().
Referenced by KDChart::CartesianCoordinatePlane::layoutDiagrams(), KDChart::CartesianCoordinatePlane::paint(), KDChart::CartesianCoordinatePlane::setFixedDataCoordinateSpaceRelation(), KDChart::CartesianCoordinatePlane::setZoomCenter(), KDChart::CartesianCoordinatePlane::setZoomFactors(), KDChart::CartesianCoordinatePlane::setZoomFactorX(), KDChart::CartesianCoordinatePlane::setZoomFactorY(), KDChart::CartesianCoordinatePlane::visibleDataRange(), and KDChart::CartesianCoordinatePlane::visibleDiagramArea().
Qt::Orientations CartesianCoordinatePlane::expandingDirections () const virtual inherited
pure virtual in QLayoutItem
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 896 of file KDChartCartesianCoordinatePlane.cpp.
References d.
FrameAttributes AbstractAreaBase::frameAttributes () const inherited
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::Legend::clone(), KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
QRect KDChart::AbstractCoordinatePlane::geometry () const virtual inherited
pure virtual in QLayoutItem
Definition at line 248 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseDoubleClickEvent(), KDChart::Chart::mouseMoveEvent(), KDChart::Chart::mousePressEvent(), KDChart::Chart::mouseReleaseEvent(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::PolarCoordinatePlane::paint(), and KDChart::CartesianCoordinatePlane::setGeometry().
void KDChart::AbstractCoordinatePlane::geometryChanged (QRect , QRect) signal inherited
Emitted after the geometry of the Coordinate Plane has been changed.
and control has returned to the event loop.
Parameters are the old geometry, the new geometry.
DataDimensionsList CartesianCoordinatePlane::getDataDimensionsList () const protected virtual inherited
Implements KDChart::AbstractCoordinatePlane.
Definition at line 272 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::axesCalcModeX(), KDChart::CartesianCoordinatePlane::axesCalcModeY(), KDChart::CartesianCoordinatePlane::calculateRawDataBoundingRect(), KDChart::AbstractDiagram::datasetDimension(), KDChart::AbstractCoordinatePlane::diagrams(), KDChart::CartesianCoordinatePlane::gridAttributes(), KDChart::GridAttributes::gridGranularitySequence(), KDChart::GridAttributes::gridStepWidth(), KDChart::GridAttributes::gridSubStepWidth(), KDChart::BarDiagram::orientation(), and KDChart::AbstractCartesianDiagram::referenceDiagram().
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const inherited
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::innerRect(), and KDChart::AbstractAreaWidget::paintAll().
QRectF CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams () const protected inherited
Definition at line 156 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::AbstractDiagram::dataBoundaries(), KDChart::AbstractCoordinatePlane::diagram(), and KDChart::AbstractCoordinatePlane::diagrams().
Referenced by KDChart::CartesianCoordinatePlane::adjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::adjustRangesToData(), KDChart::CartesianCoordinatePlane::adjustVerticalRangeToData(), and KDChart::CartesianCoordinatePlane::calculateRawDataBoundingRect().
GridAttributes KDChart::AbstractCoordinatePlane::globalGridAttributes () const inherited
Returns
The grid attributes used by this coordinate plane.
See also
setGlobalGridAttributes
CartesianCoordinatePlane::gridAttributes
Definition at line 163 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::gridAttributes().
LeveyJenningsGridAttributes LeveyJenningsCoordinatePlane::gridAttributes () const
Definition at line 71 of file KDChartLeveyJenningsCoordinatePlane.cpp.
References d.
const GridAttributes CartesianCoordinatePlane::gridAttributes (Qt::Orientation orientation) const inherited
Returns
The attributes used for grid lines drawn in horizontal direction (or in vertical direction, resp.).
Note
This function always returns a valid set of grid attributes: If no special grid attributes were set foe this orientation the global attributes are returned, as returned by AbstractCoordinatePlane::globalGridAttributes.
See also
setGridAttributes
resetGridAttributes
AbstractCoordinatePlane::globalGridAttributes
hasOwnGridAttributes
Definition at line 737 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::globalGridAttributes(), and KDChart::CartesianCoordinatePlane::hasOwnGridAttributes().
Referenced by KDChart::CartesianCoordinatePlane::getDataDimensionsList().
KDChart::DataDimensionsList KDChart::AbstractCoordinatePlane::gridDimensionsList () inherited
Returns the dimensions used for drawing the grid lines.
Returned data is the result of (cached) grid calculations, so - if you need that information for your own tasks - make sure to call again this function after every data modification that has changed the data range, since grid calculation is based upon the data range, thus the grid start/end might have changed if the data was changed.
Note
Returned list will contain different numbers of DataDimension, depending on the kind of coordinate plane used. For CartesianCoordinatePlane two DataDimension are returned: the first representing grid lines in X direction (matching the Abscissa axes) and the second indicating vertical grid lines (or Ordinate axes, resp.).
Returns
The dimensions used for drawing the grid lines.
See also
DataDimension
Definition at line 168 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::PaintingHelpers::paintValueTracker().
void CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation (const QRectF & geometry) protected inherited
Definition at line 414 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::doneSetZoomCenter(), KDChart::CartesianCoordinatePlane::doneSetZoomFactorX(), KDChart::CartesianCoordinatePlane::doneSetZoomFactorY(), KDChart::AbstractCoordinatePlane::propertiesChanged(), KDChart::CartesianCoordinatePlane::zoomCenter(), KDChart::CartesianCoordinatePlane::zoomFactorX(), and KDChart::CartesianCoordinatePlane::zoomFactorY().
Referenced by KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::CartesianCoordinatePlane::setFixedDataCoordinateSpaceRelation().
bool CartesianCoordinatePlane::hasFixedDataCoordinateSpaceRelation () const inherited
Definition at line 396 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::TextAttributes::calculatedFont().
bool CartesianCoordinatePlane::hasHeightForWidth () const protected inherited
Definition at line 902 of file KDChartCartesianCoordinatePlane.cpp.
References d.
bool CartesianCoordinatePlane::hasOwnGridAttributes (Qt::Orientation orientation) const inherited
Returns
Returns whether the grid attributes have been set for the respective direction via setGridAttributes(orientation).
If false, the grid will use the global attributes set by AbstractCoordinatePlane::globalGridAttributes (or the default attributes, resp.)
See also
setGridAttributes
resetGridAttributes
AbstractCoordinatePlane::globalGridAttributes
Definition at line 758 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::gridAttributes().
int CartesianCoordinatePlane::heightForWidth (int w) const protected inherited
Definition at line 907 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::logicalArea().
Referenced by KDChart::CartesianCoordinatePlane::setGeometry(), and KDChart::CartesianCoordinatePlane::sizeHint().
QPair< qreal, qreal > CartesianCoordinatePlane::horizontalRange () const inherited
Returns
The largest and smallest visible horizontal value space value. If this is not explicitly set,or if both values are the same, the plane will use the union of the dataBoundaries of all associated diagrams.
See also
KDChart::AbstractDiagram::dataBoundaries
Definition at line 645 of file KDChartCartesianCoordinatePlane.cpp.
References d.
QRect AbstractAreaBase::innerRect () const protected inherited
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::areaGeometry(), and KDChart::AbstractAreaBase::getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and KDChart::TextArea::paintAll().
void KDChart::AbstractCoordinatePlane::internal_geometryChanged (QRect , QRect) signal inherited
bool KDChart::AbstractCoordinatePlane::isCornerSpacersEnabled () const inherited
Returns
Whether this plane should have spacers in the corners formed by the presence of axes.
Definition at line 295 of file KDChartAbstractCoordinatePlane.cpp.
References d.
bool KDChart::AbstractCoordinatePlane::isEmpty () const virtual inherited
pure virtual in QLayoutItem
Definition at line 204 of file KDChartAbstractCoordinatePlane.cpp.
bool CartesianCoordinatePlane::isHorizontalRangeReversed () const inherited
Returns
Whether the horizontal range is reversed or not
Definition at line 838 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::PaintingHelpers::paintValueTracker().
bool KDChart::AbstractCoordinatePlane::isRubberBandZoomingEnabled () const inherited
Returns
Whether zooming with a rubber band using the mouse is enabled.
Definition at line 282 of file KDChartAbstractCoordinatePlane.cpp.
References d.
bool CartesianCoordinatePlane::isVerticalRangeReversed () const inherited
Returns
Whether the vertical range is reversed or not
Definition at line 853 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::PaintingHelpers::paintValueTracker().
const bool KDChart::AbstractCoordinatePlane::isVisiblePoint (const QPointF & point) const inherited
Tests, if a point is visible on the coordinate plane.
Note
Before calling this function the point must have been translated into coordinate plane space.
Definition at line 426 of file KDChartAbstractCoordinatePlane.cpp.
References d.
void CartesianCoordinatePlane::layoutDiagrams () protected virtual inherited
Distribute the available space among the diagrams and axes.
Implements KDChart::AbstractCoordinatePlane.
Definition at line 368 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::AbstractCoordinatePlane::gridDimensionsList(), KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), KDChart::CartesianCoordinatePlane::logicalArea(), and KDChart::AbstractCoordinatePlane::update().
Referenced by KDChart::CartesianCoordinatePlane::adjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::adjustRangesToData(), KDChart::CartesianCoordinatePlane::adjustVerticalRangeToData(), KDChart::CartesianCoordinatePlane::setAutoAdjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::setAutoAdjustVerticalRangeToData(), KDChart::CartesianCoordinatePlane::setHorizontalRange(), KDChart::CartesianCoordinatePlane::setHorizontalRangeReversed(), KDChart::CartesianCoordinatePlane::setIsometricScaling(), KDChart::CartesianCoordinatePlane::setVerticalRange(), KDChart::CartesianCoordinatePlane::setVerticalRangeReversed(), and KDChart::CartesianCoordinatePlane::slotLayoutChanged().
void KDChart::AbstractCoordinatePlane::layoutPlanes () slot inherited
Calling layoutPlanes() on the plane triggers the global KDChart::Chart::slotLayoutPlanes()
Definition at line 265 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::AbstractCartesianDiagram::layoutPlanes(), KDChart::CartesianAxis::layoutPlanes(), KDChart::AbstractCoordinatePlane::replaceDiagram(), and KDChart::AbstractCoordinatePlane::takeDiagram().
int AbstractArea::leftOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the left edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 74 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
QRectF CartesianCoordinatePlane::logicalArea () const inherited
Returns the logical area, i.e., the rectangle defined by the very top left and very bottom right coordinate.
Definition at line 333 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::DataDimension::distance(), KDChart::DataDimension::end, and KDChart::DataDimension::start.
Referenced by KDChart::CartesianCoordinatePlane::diagramArea(), KDChart::CartesianCoordinatePlane::heightForWidth(), KDChart::CartesianCoordinatePlane::layoutDiagrams(), KDChart::CartesianCoordinatePlane::setZoomCenter(), KDChart::CartesianCoordinatePlane::setZoomFactors(), KDChart::CartesianCoordinatePlane::setZoomFactorX(), and KDChart::CartesianCoordinatePlane::setZoomFactorY().
QSize KDChart::AbstractCoordinatePlane::maximumSize () const virtual inherited
pure virtual in QLayoutItem
Definition at line 216 of file KDChartAbstractCoordinatePlane.cpp.
QSize KDChart::AbstractCoordinatePlane::minimumSize () const virtual inherited
pure virtual in QLayoutItem
Definition at line 223 of file KDChartAbstractCoordinatePlane.cpp.
void KDChart::AbstractCoordinatePlane::mouseDoubleClickEvent (QMouseEvent * event) virtual inherited
Definition at line 340 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseDoubleClickEvent().
void KDChart::AbstractCoordinatePlane::mouseMoveEvent (QMouseEvent * event) virtual inherited
Definition at line 407 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseMoveEvent().
void KDChart::AbstractCoordinatePlane::mousePressEvent (QMouseEvent * event) virtual inherited
Definition at line 300 of file KDChartAbstractCoordinatePlane.cpp.
References KDChart::ZoomParameters::center(), d, KDChart::ZoomParameters::xFactor, and KDChart::ZoomParameters::yFactor.
Referenced by KDChart::Chart::mousePressEvent().
void KDChart::AbstractCoordinatePlane::mouseReleaseEvent (QMouseEvent * event) virtual inherited
Definition at line 354 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseReleaseEvent().
void KDChart::AbstractCoordinatePlane::needLayoutPlanes () signal inherited
Emitted when plane needs to trigger the Chart's layouting of the coord.
planes.
void KDChart::AbstractCoordinatePlane::needRelayout () signal inherited
Emitted when plane needs to trigger the Chart's layouting.
void KDChart::AbstractCoordinatePlane::needUpdate () signal inherited
Emitted when plane needs to update its drawings.
void CartesianCoordinatePlane::paint (QPainter * painter) virtual inherited
reimpl
Implements KDChart::AbstractLayoutItem.
Definition at line 100 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::PaintContext::setCoordinatePlane(), KDChart::PaintContext::setPainter(), and KDChart::PaintContext::setRectangle().
void AbstractArea::paintAll (QPainter & painter) virtual inherited
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
Reimplemented from KDChart::AbstractLayoutItem.
Reimplemented in KDChart::TernaryAxis.
Definition at line 120 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::areaGeometry(), d, KDChart::AbstractAreaBase::innerRect(), KDChart::AbstractLayoutItem::paint(), KDChart::AbstractAreaBase::paintBackground(), and KDChart::AbstractAreaBase::paintFrame().
Referenced by KDChart::AbstractArea::paintIntoRect().
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static inherited
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by KDChart::AbstractAreaBase::paintBackground().
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual inherited
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
void KDChart::CartesianCoordinatePlane::paintEvent (QPaintEvent *) protected inherited
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static inherited
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::AbstractAreaBase::paintFrame().
void AbstractArea::paintIntoRect (QPainter & painter, const QRect & rect) virtual inherited
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite AbstractLayoutItem::paint() instead.
Definition at line 108 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::paintAll().
KDChart::Chart * KDChart::AbstractCoordinatePlane::parent () inherited
Definition at line 198 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::AbstractCoordinatePlane::AbstractCoordinatePlane(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), and KDChart::LeveyJenningsAxis::paintAsOrdinate().
const KDChart::Chart * KDChart::AbstractCoordinatePlane::parent () const inherited
Definition at line 193 of file KDChartAbstractCoordinatePlane.cpp.
References d.
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
void KDChart::AbstractArea::positionChanged (AbstractArea *) signal inherited
Referenced by KDChart::AbstractArea::positionHasChanged().
void AbstractArea::positionHasChanged () protected virtual inherited
Reimplemented from KDChart::AbstractAreaBase.
Definition at line 156 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::positionChanged().
void KDChart::AbstractCoordinatePlane::propertiesChanged () signal inherited
Emitted upon change of a property of the Coordinate Plane or any of its components.
Referenced by KDChart::CartesianCoordinatePlane::addDiagram(), KDChart::CartesianCoordinatePlane::adjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::adjustRangesToData(), KDChart::CartesianCoordinatePlane::adjustVerticalRangeToData(), KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), KDChart::CartesianCoordinatePlane::setAutoAdjustGridToZoom(), KDChart::CartesianCoordinatePlane::setAutoAdjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::setAutoAdjustVerticalRangeToData(), KDChart::CartesianCoordinatePlane::setAxesCalcModes(), KDChart::CartesianCoordinatePlane::setAxesCalcModeX(), KDChart::CartesianCoordinatePlane::setAxesCalcModeY(), KDChart::CartesianCoordinatePlane::setGridAttributes(), KDChart::CartesianCoordinatePlane::setHorizontalRange(), KDChart::CartesianCoordinatePlane::setHorizontalRangeReversed(), KDChart::CartesianCoordinatePlane::setIsometricScaling(), KDChart::CartesianCoordinatePlane::setVerticalRange(), KDChart::CartesianCoordinatePlane::setVerticalRangeReversed(), KDChart::CartesianCoordinatePlane::setZoomCenter(), KDChart::CartesianCoordinatePlane::setZoomFactors(), KDChart::CartesianCoordinatePlane::setZoomFactorX(), and KDChart::CartesianCoordinatePlane::setZoomFactorY().
AbstractCoordinatePlane * KDChart::AbstractCoordinatePlane::referenceCoordinatePlane () const inherited
There are two ways, in which planes can be caused to interact, in where they are put layouting wise: The first is the reference plane.
If such a reference plane is set, on a plane, it will use the same cell in the layout as that one. In addition to this, planes can share an axis. In that case they will be laid out in relation to each other as suggested by the position of the axis. If, for example Plane1 and Plane2 share an axis at position Left, that will result in the layout: Axis Plane1 Plane 2, vertically. If Plane1 also happens to be Plane2's reference plane, both planes are drawn over each other. The reference plane concept allows two planes to share the same space even if neither has any axis, and in case there are shared axis, it is used to decided, whether the planes should be painted on top of each other or laid out vertically or horizontally next to each other.
Returns
The reference coordinate plane associated with this one.
Definition at line 183 of file KDChartAbstractCoordinatePlane.cpp.
References d.
void KDChart::AbstractCoordinatePlane::relayout () slot inherited
Calling relayout() on the plane triggers the global KDChart::Chart::slotRelayout()
Definition at line 259 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), and KDChart::AbstractCoordinatePlane::takeDiagram().
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
void AbstractCoordinatePlane::replaceDiagram (AbstractDiagram * diagram, AbstractDiagram * oldDiagram = 0) virtual inherited
Replaces the old diagram, or appends the diagram, it there is none yet.
Parameters
diagram The diagram to be used instead of the old diagram. This parameter must not be zero, or the method will do nothing.
oldDiagram The diagram to be removed by the new diagram. This diagram will be deleted automatically. If the parameter is omitted, the very first diagram will be replaced. In case, there was no diagram yet, the new diagram will just be added.
Note
If you want to re-use the old diagram, call takeDiagram and addDiagram, instead of using replaceDiagram.
See also
addDiagram, takeDiagram
Definition at line 93 of file KDChartAbstractCoordinatePlane.cpp.
References KDChart::AbstractCoordinatePlane::addDiagram(), d, KDChart::AbstractCoordinatePlane::layoutDiagrams(), KDChart::AbstractCoordinatePlane::layoutPlanes(), KDChart::AbstractCoordinatePlane::takeDiagram(), and KDChart::AbstractCoordinatePlane::update().
Referenced by KDChart::Widget::setType().
void CartesianCoordinatePlane::resetGridAttributes (Qt::Orientation orientation) inherited
Reset the attributes to be used for grid lines drawn in horizontal direction (or in vertical direction, resp.).
By calling this method you specify that the global attributes set by AbstractCoordinatePlane::setGlobalGridAttributes be used.
See also
setGridAttributes, gridAttributes
setAutoAdjustGridToZoom
AbstractCoordinatePlane::globalGridAttributes
hasOwnGridAttributes
Definition at line 731 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::AbstractCoordinatePlane::update().
int AbstractArea::rightOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the right edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 82 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
void CartesianCoordinatePlane::setAutoAdjustGridToZoom (bool autoAdjust) inherited
Disable / re-enable the built-in grid adjusting feature.
By default additional lines will be drawn in a Linear grid when zooming in.
See also
autoAdjustGridToZoom, setGridAttributes
Definition at line 764 of file KDChartCartesianCoordinatePlane.cpp.
References d, and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setAutoAdjustHorizontalRangeToData (unsigned int percentEmpty = 67) inherited
Automatically adjust horizontal range settings to the ranges covered by the model's values, when ever the data have changed, and then emit horizontalRangeAutomaticallyAdjusted.
By default the horizontal range is adjusted automatically, if more than 67 percent of the available horizontal space would be empty otherwise.
Range setting is adjusted if more than percentEmpty percent of the horizontal space covered by the coordinate plane would otherwise be empty. Automatic range adjusting can happen, when either all of the data are positive or all are negative.
Set percentEmpty to 100 to disable automatic range adjusting.
Parameters
percentEmpty The maximal percentage of horizontal space that may be empty.
See also
horizontalRangeAutomaticallyAdjusted
autoAdjustHorizontalRangeToData, adjustRangesToData
setHorizontalRange, setVerticalRange
setAutoAdjustVerticalRangeToData
Definition at line 684 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setAutoAdjustVerticalRangeToData (unsigned int percentEmpty = 67) inherited
Automatically adjust vertical range settings to the ranges covered by the model's values, when ever the data have changed, and then emit verticalRangeAutomaticallyAdjusted.
By default the vertical range is adjusted automatically, if more than 67 percent of the available vertical space would be empty otherwise.
Range setting is adjusted if more than percentEmpty percent of the horizontal space covered by the coordinate plane would otherwise be empty. Automatic range adjusting can happen, when either all of the data are positive or all are negative.
Set percentEmpty to 100 to disable automatic range adjusting.
Parameters
percentEmpty The maximal percentage of horizontal space that may be empty.
See also
verticalRangeAutomaticallyAdjusted
autoAdjustVerticalRangeToData, adjustRangesToData
setHorizontalRange, setVerticalRange
setAutoAdjustHorizontalRangeToData
Definition at line 696 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setAxesCalcModes (AxesCalcMode mode) inherited
Specifies the calculation modes for all axes.
Definition at line 578 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), KDChart::AbstractCoordinatePlane::propertiesChanged(), KDChart::CartesianCoordinatePlane::slotLayoutChanged(), and KDChart::AbstractCoordinatePlane::viewportCoordinateSystemChanged().
void CartesianCoordinatePlane::setAxesCalcModeX (AxesCalcMode mode) inherited
Specifies the calculation mode for all Abscissa axes.
Definition at line 601 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::propertiesChanged(), and KDChart::AbstractCoordinatePlane::viewportCoordinateSystemChanged().
void CartesianCoordinatePlane::setAxesCalcModeY (AxesCalcMode mode) inherited
Specifies the calculation mode for all Ordinate axes.
Definition at line 591 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::propertiesChanged(), KDChart::AbstractCoordinatePlane::setGridNeedsRecalculate(), and KDChart::AbstractCoordinatePlane::viewportCoordinateSystemChanged().
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a) inherited
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
void KDChart::AbstractCoordinatePlane::setCornerSpacersEnabled (bool enable) inherited
Enables or disables the use of spacers in the plane corners.
Definition at line 287 of file KDChartAbstractCoordinatePlane.cpp.
References d.
void CartesianCoordinatePlane::setFixedDataCoordinateSpaceRelation (bool fixed) inherited
Allows to specify a fixed data-space / coordinate-space relation.
If set to true then fixed bar widths are used, so you see more bars as the window is made wider.
This allows to completely restrict the size of bars in a graph such that, upon resizing a window, the graphs coordinate plane will grow (add more ticks to x- and y-coordinates) rather than have the image grow.
Definition at line 389 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::drawingArea(), and KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation().
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a) inherited
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
Referenced by KDChart::Legend::clone().
void CartesianCoordinatePlane::setGeometry (const QRect & r) virtual inherited
reimplemented from AbstractCoordinatePlane
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 870 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::diagram(), KDChart::AbstractCoordinatePlane::diagrams(), KDChart::AbstractCoordinatePlane::geometry(), KDChart::CartesianCoordinatePlane::heightForWidth(), KDChart::AbstractDiagram::resize(), and KDChart::AbstractCoordinatePlane::setGeometry().
void KDChart::AbstractCoordinatePlane::setGlobalGridAttributes (const GridAttributes & a) inherited
Set the grid attributes to be used by this coordinate plane.
To disable grid painting, for example, your code should like this:
GridAttributes ga = plane->globalGridAttributes();
ga.setGlobalGridVisible(false);
plane->setGlobalGridAttributes(ga);
See also
globalGridAttributes
CartesianCoordinatePlane::setGridAttributes
Definition at line 157 of file KDChartAbstractCoordinatePlane.cpp.
References d.
void LeveyJenningsCoordinatePlane::setGridAttributes (const LeveyJenningsGridAttributes & attr)
Definition at line 76 of file KDChartLeveyJenningsCoordinatePlane.cpp.
References d.
void CartesianCoordinatePlane::setGridAttributes (Qt::Orientation orientation, const GridAttributes & a) inherited
Set the attributes to be used for grid lines drawn in horizontal direction (or in vertical direction, resp.).
To disable horizontal grid painting, for example, your code should like this:
GridAttributes ga = plane->gridAttributes(Qt::Horizontal);
ga.setGridVisible(false);
plane-setGridAttributes(Qt::Horizontal, ga);
Note
setGridAttributes overwrites the global attributes that were set by AbstractCoordinatePlane::setGlobalGridAttributes. To re-activate these global attributes you can call resetGridAttributes.
See also
resetGridAttributes, gridAttributes
setAutoAdjustGridToZoom
AbstractCoordinatePlane::setGlobalGridAttributes
hasOwnGridAttributes
Definition at line 718 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::propertiesChanged(), and KDChart::AbstractCoordinatePlane::update().
void KDChart::AbstractCoordinatePlane::setGridNeedsRecalculate () slot inherited
Used by the chart to clear the cached grid data.
Definition at line 173 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::setAxesCalcModeY().
void CartesianCoordinatePlane::setHorizontalRange (const QPair< qreal, qreal > & range) inherited
Set the boundaries of the visible value space displayed in horizontal direction.
This is also known as the horizontal viewport.
By default the horizontal range is adjusted to the range covered by the model's data, see setAutoAdjustHorizontalRangeToData for details. Calling setHorizontalRange with a valid range disables this default automatic adjusting, while on the other hand automatic adjusting will set these ranges.
To disable use of this range you can either pass an empty pair by using the default constructor QPair() or you can set both values to the same which constitutes a null range.
Note
By default the visible data range often is larger than the range calculated from the data model (or set by setHoriz.|Vert.Range(), resp.). This is due to the built-in grid calculation feature: The visible start/end values get adjusted so that they match a main-grid line. You can turn this feature off for any of the four bounds by calling GridAttributes::setAdjustBoundsToGrid() for either the global grid-attributes or for the horizontal/vertical attrs separately.
To set only one of the ends of the range to a fixed value while keeping the other dynamically adjusted, use std::numeric_limits< qreal >::quiet_NaN() for the dynamic value.
If you use user defined vertical ranges together with logarithmic scale, only positive values are supported. If you set it to negative values, the result is undefined.
Parameters
range a pair of values representing the smalles and the largest horizontal value space coordinate displayed.
See also
setAutoAdjustHorizontalRangeToData, setVerticalRange
GridAttributes::setAdjustBoundsToGrid()
Definition at line 621 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::AbstractCoordinatePlane::boundariesChanged(), d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setHorizontalRangeReversed (bool reverse) inherited
Sets whether the horizontal range should be reversed or not, i.e.
small values to the left and large values to the right (the default) or vice versa.
Parameters
reverse Whether the horizontal range should be reversed or not
Definition at line 828 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setIsometricScaling (bool onOff) inherited
If onOff is true, enforce that X and Y distances are scaled by the same factor.
This makes the plane's height a function of its width, and hasHeightForWidth() will return true.
Definition at line 470 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void KDChart::AbstractCoordinatePlane::setParent (KDChart::Chart * parent) inherited
Called internally by KDChart::Chart.
Definition at line 188 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::insertCoordinatePlane(), and KDChart::Chart::takeCoordinatePlane().
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
void KDChart::AbstractCoordinatePlane::setReferenceCoordinatePlane (AbstractCoordinatePlane * plane) inherited
Set another coordinate plane to be used as the reference plane for this one.
Parameters
plane The coordinate plane to be used the reference plane for this one.
See also
referenceCoordinatePlane
Definition at line 178 of file KDChartAbstractCoordinatePlane.cpp.
References d.
void KDChart::AbstractCoordinatePlane::setRubberBandZoomingEnabled (bool enable) inherited
Enables or disables zooming with a rubber band using the mouse.
Definition at line 271 of file KDChartAbstractCoordinatePlane.cpp.
References d.
void CartesianCoordinatePlane::setVerticalRange (const QPair< qreal, qreal > & range) inherited
Set the boundaries of the visible value space displayed in vertical direction.
This is also known as the vertical viewport.
By default the vertical range is adjusted to the range covered by the model's data, see setAutoAdjustVerticalRangeToData for details. Calling setVerticalRange with a valid range disables this default automatic adjusting, while on the other hand automatic adjusting will set these ranges.
To disable use of this range you can either pass an empty pair by using the default constructor QPair() or you can set setting both values to the same which constitutes a null range.
Note
By default the visible data range often is larger than the range calculated from the data model (or set by setHoriz.|Vert.Range(), resp.). This is due to the built-in grid calculation feature: The visible start/end values get adjusted so that they match a main-grid line. You can turn this feature off for any of the four bounds by calling GridAttributes::setAdjustBoundsToGrid() for either the global grid-attributes or for the horizontal/vertical attrs separately.
To set only one of the ends of the range to a fixed value while keeping the other dynamically adjusted, use std::numeric_limits< qreal >::quiet_NaN() for the dynamic value.
If you use user defined vertical ranges together with logarithmic scale, only positive values are supported. If you set it to negative values, the result is undefined.
Parameters
range a pair of values representing the smalles and the largest vertical value space coordinate displayed.
See also
setAutoAdjustVerticalRangeToData, setHorizontalRange
GridAttributes::setAdjustBoundsToGrid()
Definition at line 633 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::AbstractCoordinatePlane::boundariesChanged(), d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setVerticalRangeReversed (bool reverse) inherited
Sets whether the vertical range should be reversed or not, i.e.
small values at the bottom and large values at the top (the default) or vice versa.
Parameters
reverse Whether the vertical range should be reversed or not
Definition at line 843 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setXAxisStartAtZero (bool fixedStart) inherited
Allows to fix the lower bound of X axis to zero when diagram is in first quadrant.
The default behavior is to lower x or y bound to be 0. If this behaviour is not wanted, either CartesianCoordinatePlane::setHorizontalRange could be used instead of letting KDChart auto-adjust the ranges, or this method can be used to disable this behavior.
Definition at line 401 of file KDChartCartesianCoordinatePlane.cpp.
References d.
void CartesianCoordinatePlane::setZoomCenter (const QPointF & center) virtual inherited
See also
zoomCenter, setZoomFactorX, setZoomFactorY
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 544 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::doneSetZoomCenter(), KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::CartesianCoordinatePlane::logicalArea(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setZoomFactors (qreal factorX, qreal factorY) virtual inherited
See also
setZoomFactorX,setZoomFactorY
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 520 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::doneSetZoomFactorX(), KDChart::CartesianCoordinatePlane::doneSetZoomFactorY(), KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::CartesianCoordinatePlane::logicalArea(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setZoomFactorX (qreal factor) virtual inherited
See also
zoomFactorX, setZoomCenter
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 528 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::doneSetZoomFactorX(), KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::CartesianCoordinatePlane::logicalArea(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
void CartesianCoordinatePlane::setZoomFactorY (qreal factor) virtual inherited
See also
zoomFactorY, setZoomCenter
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 536 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::doneSetZoomFactorY(), KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::CartesianCoordinatePlane::logicalArea(), and KDChart::AbstractCoordinatePlane::propertiesChanged().
AbstractCoordinatePlane * CartesianCoordinatePlane::sharedAxisMasterPlane (QPainter * p = 0) virtual inherited
reimpl
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 781 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::AbstractCartesianDiagram::axes(), KDChart::AbstractAxis::coordinatePlane(), KDChart::AbstractCoordinatePlane::diagram(), KDChart::CartesianAxis::isAbscissa(), KDChart::CartesianAxis::isOrdinate(), and KDChart::CartesianCoordinatePlane::translate().
QSize CartesianCoordinatePlane::sizeHint () const protected virtual inherited
pure virtual in QLayoutItem
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 916 of file KDChartCartesianCoordinatePlane.cpp.
References d, KDChart::CartesianCoordinatePlane::heightForWidth(), and KDChart::AbstractCoordinatePlane::sizeHint().
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
void CartesianCoordinatePlane::slotLayoutChanged (AbstractDiagram *) protected slot inherited
Definition at line 151 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::layoutDiagrams().
Referenced by KDChart::CartesianCoordinatePlane::addDiagram(), and KDChart::CartesianCoordinatePlane::setAxesCalcModes().
void AbstractCoordinatePlane::takeDiagram (AbstractDiagram * diagram) virtual inherited
Removes the diagram from the plane, without deleting it.
The plane no longer owns the diagram, so it is the caller's responsibility to delete the diagram.
See also
addDiagram, replaceDiagram
Definition at line 114 of file KDChartAbstractCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::layoutDiagrams(), KDChart::AbstractCoordinatePlane::layoutPlanes(), KDChart::AbstractCoordinatePlane::relayout(), KDChart::AbstractDiagram::setCoordinatePlane(), and KDChart::AbstractCoordinatePlane::update().
Referenced by KDChart::AbstractCoordinatePlane::replaceDiagram().
int AbstractArea::topOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the top edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 90 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
const QPointF CartesianCoordinatePlane::translate (const QPointF & diagramPoint) const virtual inherited
Translate the given point in value space coordinates to a position in pixel space.
Parameters
diagramPoint The point in value coordinates.
Returns
The translated point.
Implements KDChart::AbstractCoordinatePlane.
Definition at line 456 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::LeveyJenningsAxis::paintAsOrdinate(), and KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane().
const QPointF LeveyJenningsCoordinatePlane::translateBack (const QPointF & screenPoint) const protected
Definition at line 81 of file KDChartLeveyJenningsCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::translateBack().
void KDChart::AbstractCoordinatePlane::update () slot inherited
Calling update() on the plane triggers the global KDChart::Chart::update()
Definition at line 253 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::PolarCoordinatePlane::adjustZoomAndRepaint(), KDChart::PolarCoordinatePlane::layoutDiagrams(), KDChart::CartesianCoordinatePlane::layoutDiagrams(), KDChart::AbstractCoordinatePlane::replaceDiagram(), KDChart::CartesianCoordinatePlane::resetGridAttributes(), KDChart::CartesianCoordinatePlane::setGridAttributes(), and KDChart::AbstractCoordinatePlane::takeDiagram().
QPair< qreal, qreal > CartesianCoordinatePlane::verticalRange () const inherited
Returns
The largest and smallest visible horizontal value space value. If this is not explicitly set, or if both values are the same, the plane will use the union of the dataBoundaries of all associated diagrams.
See also
KDChart::AbstractDiagram::dataBoundaries
Definition at line 650 of file KDChartCartesianCoordinatePlane.cpp.
References d.
void KDChart::AbstractCoordinatePlane::viewportCoordinateSystemChanged () signal inherited
Emitted upon change of the view coordinate system.
Referenced by KDChart::CartesianCoordinatePlane::setAxesCalcModes(), KDChart::CartesianCoordinatePlane::setAxesCalcModeX(), and KDChart::CartesianCoordinatePlane::setAxesCalcModeY().
QRectF CartesianCoordinatePlane::visibleDataRange () const inherited
Returns the currently visible data range.
Might be greater than the range of the grid.
Definition at line 858 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::drawingArea(), and KDChart::CartesianCoordinatePlane::translateBack().
Referenced by KDChart::Plotter::calcMergeRadius().
QRectF CartesianCoordinatePlane::visibleDiagramArea () const inherited
Returns the visible part of the diagram area, i.e.
diagramArea().intersected(drawingArea())
See also
diagramArea
Definition at line 363 of file KDChartCartesianCoordinatePlane.cpp.
References KDChart::CartesianCoordinatePlane::diagramArea(), and KDChart::CartesianCoordinatePlane::drawingArea().
Referenced by KDChart::Measure::sizeOfArea().
bool CartesianCoordinatePlane::xAxisStartAtZero () const inherited
Definition at line 409 of file KDChartCartesianCoordinatePlane.cpp.
References d.
QPointF CartesianCoordinatePlane::zoomCenter () const virtual inherited
See also
setZoomCenter, setZoomFactorX, setZoomFactorY
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 552 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation().
qreal CartesianCoordinatePlane::zoomFactorX () const virtual inherited
See also
setZoomFactorX, setZoomCenter
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 557 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation().
qreal CartesianCoordinatePlane::zoomFactorY () const virtual inherited
See also
setZoomFactorY, setZoomCenter
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 562 of file KDChartCartesianCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation().
Member Data Documentation
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartLeveyJenningsCoordinatePlane.h
KDChartLeveyJenningsCoordinatePlane.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/