KD Chart 2: KDGantt::DateTimeSpan Class Reference
KDGantt::DateTimeSpan Class Reference
#include <kdganttglobal.h>
Public Member Functions
DateTimeSpan ()
DateTimeSpan (const QDateTime &start, const QDateTime &end)
DateTimeSpan (const DateTimeSpan &other)
QDateTime end () const
bool equals (const DateTimeSpan &other) const
bool isValid () const
DateTimeSpan & operator= (const DateTimeSpan &other)
void setEnd (const QDateTime &end)
void setStart (const QDateTime &start)
QDateTime start () const
~DateTimeSpan ()
Detailed Description
Definition at line 267 of file kdganttglobal.h.
Constructor & Destructor Documentation
DateTimeSpan() [1/3]
DateTimeSpan::DateTimeSpan ()
Definition at line 82 of file kdganttglobal.cpp.
DateTimeSpan() [2/3]
DateTimeSpan::DateTimeSpan (const QDateTime & start, const QDateTime & end)
Definition at line 86 of file kdganttglobal.cpp.
DateTimeSpan() [3/3]
DateTimeSpan::DateTimeSpan (const DateTimeSpan & other)
Definition at line 91 of file kdganttglobal.cpp.
~DateTimeSpan()
DateTimeSpan::~DateTimeSpan ()
Definition at line 96 of file kdganttglobal.cpp.
Member Function Documentation
end()
QDateTime KDGantt::DateTimeSpan::end () const
Definition at line 282 of file kdganttglobal.h.
Referenced by operator<<().
equals()
bool DateTimeSpan::equals (const DateTimeSpan & other) const
Definition at line 114 of file kdganttglobal.cpp.
Referenced by KDGantt::operator!=(), and KDGantt::operator==().
isValid()
bool DateTimeSpan::isValid () const
Definition at line 109 of file kdganttglobal.cpp.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
operator=()
DateTimeSpan & DateTimeSpan::operator= (const DateTimeSpan & other)
Definition at line 100 of file kdganttglobal.cpp.
setEnd()
void KDGantt::DateTimeSpan::setEnd (const QDateTime & end)
Definition at line 281 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
setStart()
void KDGantt::DateTimeSpan::setStart (const QDateTime & start)
Definition at line 278 of file kdganttglobal.h.
Referenced by KDAB_SCOPED_UNITTEST_SIMPLE().
start()
QDateTime KDGantt::DateTimeSpan::start () const
Definition at line 279 of file kdganttglobal.h.
Referenced by operator<<().
The documentation for this class was generated from the following files:
kdganttglobal.h
kdganttglobal.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/