KD Chart 2: KDChart::PlotterDiagramCompressor::Iterator Class Reference
KDChart::PlotterDiagramCompressor::Iterator Class Reference
#include <KDChartPlotterDiagramCompressor.h>
Public Member Functions
void invalidate ()
bool isValid () const
Iterator (int dataSet, PlotterDiagramCompressor *parent)
bool operator!= (const Iterator &other) const
DataPoint operator* ()
Iterator & operator++ ()
Iterator operator++ (int)
Iterator & operator+= (int value)
Iterator & operator-- ()
Iterator operator-- (int)
Iterator & operator-= (int value)
bool operator== (const Iterator &other) const
~Iterator ()
Protected Member Functions
Iterator (int dataSet, PlotterDiagramCompressor *parent, QVector< DataPoint > buffer)
Detailed Description
Definition at line 80 of file KDChartPlotterDiagramCompressor.h.
Constructor & Destructor Documentation
Iterator() [1/2]
PlotterDiagramCompressor::Iterator::Iterator (int dataSet, PlotterDiagramCompressor * parent)
Definition at line 38 of file KDChartPlotterDiagramCompressor.cpp.
References KDChart::PlotterDiagramCompressor::data(), and KDChart::PlotterDiagramCompressor::rowCount().
~Iterator()
PlotterDiagramCompressor::Iterator::~Iterator ()
Definition at line 84 of file KDChartPlotterDiagramCompressor.cpp.
Iterator() [2/2]
PlotterDiagramCompressor::Iterator::Iterator (int dataSet, PlotterDiagramCompressor * parent, QVector< DataPoint > buffer) protected
Definition at line 59 of file KDChartPlotterDiagramCompressor.cpp.
References KDChart::PlotterDiagramCompressor::data(), KDChart::PlotterDiagramCompressor::datasetCount(), and KDChart::PlotterDiagramCompressor::rowCount().
Member Function Documentation
invalidate()
void PlotterDiagramCompressor::Iterator::invalidate ()
Definition at line 409 of file KDChartPlotterDiagramCompressor.cpp.
isValid()
bool PlotterDiagramCompressor::Iterator::isValid () const
Definition at line 93 of file KDChartPlotterDiagramCompressor.cpp.
operator!=()
bool PlotterDiagramCompressor::Iterator::operator!= (const Iterator & other) const
Definition at line 404 of file KDChartPlotterDiagramCompressor.cpp.
operator*()
PlotterDiagramCompressor::DataPoint PlotterDiagramCompressor::Iterator::operator* ()
Definition at line 389 of file KDChartPlotterDiagramCompressor.cpp.
operator++() [1/2]
PlotterDiagramCompressor::Iterator & PlotterDiagramCompressor::Iterator::operator++ ()
Definition at line 315 of file KDChartPlotterDiagramCompressor.cpp.
References KDChart::PlotterDiagramCompressor::data(), KDChart::PlotterDiagramCompressor::rowCount(), and KDChart::PlotterDiagramCompressor::SLOPE.
operator++() [2/2]
PlotterDiagramCompressor::Iterator PlotterDiagramCompressor::Iterator::operator++ (int)
Definition at line 356 of file KDChartPlotterDiagramCompressor.cpp.
operator+=()
PlotterDiagramCompressor::Iterator & PlotterDiagramCompressor::Iterator::operator+= (int value)
Definition at line 363 of file KDChartPlotterDiagramCompressor.cpp.
operator--() [1/2]
PlotterDiagramCompressor::Iterator & PlotterDiagramCompressor::Iterator::operator-- ()
Definition at line 369 of file KDChartPlotterDiagramCompressor.cpp.
operator--() [2/2]
PlotterDiagramCompressor::Iterator PlotterDiagramCompressor::Iterator::operator-- (int)
Definition at line 376 of file KDChartPlotterDiagramCompressor.cpp.
operator-=()
PlotterDiagramCompressor::Iterator & PlotterDiagramCompressor::Iterator::operator-= (int value)
Definition at line 383 of file KDChartPlotterDiagramCompressor.cpp.
operator==()
bool PlotterDiagramCompressor::Iterator::operator== (const Iterator & other) const
Definition at line 399 of file KDChartPlotterDiagramCompressor.cpp.
The documentation for this class was generated from the following files:
KDChartPlotterDiagramCompressor.h
KDChartPlotterDiagramCompressor.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/