KD Chart 2: KDChart::GridAttributes Class Reference
KDChart::GridAttributes Class Reference
A set of attributes controlling the appearance of grids.
#include <KDChartGridAttributes.h>
Public Member Functions
bool adjustLowerBoundToGrid () const
bool adjustUpperBoundToGrid () const
GridAttributes ()
GridAttributes (const GridAttributes &)
KDChartEnums::GranularitySequence gridGranularitySequence () const
Returns the granularity sequence to be used for calculating the grid lines.
QPen gridPen () const
qreal gridStepWidth () const
Returns the step width to be used for calculating the grid lines.
qreal gridSubStepWidth () const
Returns the sub-step width to be used for calculating the sub-grid lines.
bool isGridVisible () const
bool isOuterLinesVisible () const
bool isSubGridVisible () const
bool linesOnAnnotations () const
bool operator!= (const GridAttributes &other) const
GridAttributes & operator= (const GridAttributes &)
bool operator== (const GridAttributes &) const
void setAdjustBoundsToGrid (bool adjustLower, bool adjustUpper)
By default visible bounds of the data area are adjusted to match a main grid line.
void setGridGranularitySequence (KDChartEnums::GranularitySequence sequence)
Specify which granularity sequence is to be used to find a matching grid granularity.
void setGridPen (const QPen &pen)
void setGridStepWidth (qreal stepWidth=0.0)
Specifies the step width to be used for calculating the grid lines.
void setGridSubStepWidth (qreal subStepWidth=0.0)
Specifies the sub-step width to be used for calculating the grid sub-lines.
void setGridVisible (bool visible)
void setLinesOnAnnotations (bool)
When this is enabled, grid lines are drawn only where axis annotations are.
void setOuterLinesVisible (bool visible)
void setSubGridPen (const QPen &pen)
void setSubGridVisible (bool visible)
void setZeroLinePen (const QPen &pen)
QPen subGridPen () const
QPen zeroLinePen () const
~GridAttributes ()
Detailed Description
A set of attributes controlling the appearance of grids.
Definition at line 39 of file KDChartGridAttributes.h.
Constructor & Destructor Documentation
GridAttributes() [1/2]
GridAttributes::GridAttributes ()
Definition at line 74 of file KDChartGridAttributes.cpp.
GridAttributes() [2/2]
GridAttributes::GridAttributes (const GridAttributes & r)
Definition at line 80 of file KDChartGridAttributes.cpp.
~GridAttributes()
GridAttributes::~GridAttributes ()
Definition at line 95 of file KDChartGridAttributes.cpp.
Member Function Documentation
adjustLowerBoundToGrid()
bool GridAttributes::adjustLowerBoundToGrid () const
Definition at line 239 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator==().
adjustUpperBoundToGrid()
bool GridAttributes::adjustUpperBoundToGrid () const
Definition at line 243 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator==().
gridGranularitySequence()
KDChartEnums::GranularitySequence GridAttributes::gridGranularitySequence () const
Returns the granularity sequence to be used for calculating the grid lines.
See also
setGridGranularitySequence
Definition at line 229 of file KDChartGridAttributes.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::getDataDimensionsList(), and operator==().
gridPen()
QPen GridAttributes::gridPen () const
Definition at line 254 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
gridStepWidth()
qreal GridAttributes::gridStepWidth () const
Returns the step width to be used for calculating the grid lines.
See also
setGridStepWidth
Definition at line 165 of file KDChartGridAttributes.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::getDataDimensionsList(), and operator<<().
gridSubStepWidth()
qreal GridAttributes::gridSubStepWidth () const
Returns the sub-step width to be used for calculating the sub-grid lines.
See also
setGridStepWidth
Definition at line 196 of file KDChartGridAttributes.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::getDataDimensionsList(), and operator<<().
isGridVisible()
bool GridAttributes::isGridVisible () const
Definition at line 121 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
isOuterLinesVisible()
bool GridAttributes::isOuterLinesVisible () const
Definition at line 285 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator==().
isSubGridVisible()
bool GridAttributes::isSubGridVisible () const
Definition at line 264 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
linesOnAnnotations()
bool GridAttributes::linesOnAnnotations () const
Definition at line 131 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator==().
operator!=()
bool KDChart::GridAttributes::operator!= (const GridAttributes & other) const
Definition at line 110 of file KDChartGridAttributes.h.
References KDGantt::operator==().
operator=()
GridAttributes & GridAttributes::operator= (const GridAttributes & r)
Definition at line 85 of file KDChartGridAttributes.cpp.
References d.
operator==()
bool GridAttributes::operator== (const GridAttributes & r) const
Definition at line 101 of file KDChartGridAttributes.cpp.
References adjustLowerBoundToGrid(), adjustUpperBoundToGrid(), gridGranularitySequence(), gridPen(), isGridVisible(), isOuterLinesVisible(), isSubGridVisible(), linesOnAnnotations(), subGridPen(), and zeroLinePen().
setAdjustBoundsToGrid()
void GridAttributes::setAdjustBoundsToGrid (bool adjustLower, bool adjustUpper)
By default visible bounds of the data area are adjusted to match a main grid line.
If you set the respective adjust flag to false the bound will not start at a grid line's value but it will be the exact value of the data range set.
See also
CartesianCoordinatePlane::setHorizontalRange
CartesianCoordinatePlane::setVerticalRange
Definition at line 234 of file KDChartGridAttributes.cpp.
References d.
setGridGranularitySequence()
void GridAttributes::setGridGranularitySequence (KDChartEnums::GranularitySequence sequence)
Specify which granularity sequence is to be used to find a matching grid granularity.
Specifies the granularity sequence to be used for calculating the grid lines.
See details explained at KDChartEnums::GranularitySequence.
You might also want to use setAdjustBoundsToGrid for fine-tuning the start/end value.
See also
setAdjustBoundsToGrid, GranularitySequence
By default the GridAttributes class uses KDChartEnums::GranularitySequence_10_20.
Note
Granularity can be set for Linear axis calculation mode only, there is no way to specify a step width for Logarithmic axes.
The sequence specified by this method is ignored, if a fixed step width was specified via setStepWidth.
Parameters
sequence one of the sequences declared in KDChartEnums::GranularitySequence.
See also
gridGranularitySequence, setStepWidth
Definition at line 218 of file KDChartGridAttributes.cpp.
References d.
setGridPen()
void GridAttributes::setGridPen (const QPen & pen)
Definition at line 248 of file KDChartGridAttributes.cpp.
References d.
setGridStepWidth()
void GridAttributes::setGridStepWidth (qreal stepWidth = 0.0)
Specifies the step width to be used for calculating the grid lines.
Note
Step with can be set for Linear axis calculation mode only, there is no way to specify a step width for Logarithmic axes.
By default the GridAttributes class does not use a fixed step width, but it uses KDChartEnums::GranularitySequence_10_20.
Parameters
stepWidth the step width to be used. If this parameter is omitted (or set to Zero, resp.) the automatic step width calculation will be done, using the granularity sequence specified. This is the default.
See also
gridStepWidth, setGranularitySequence
Definition at line 154 of file KDChartGridAttributes.cpp.
References d.
setGridSubStepWidth()
void GridAttributes::setGridSubStepWidth (qreal subStepWidth = 0.0)
Specifies the sub-step width to be used for calculating the grid sub-lines.
Parameters
subStepWidth the sub-step width to be used. If this parameter is omitted (or set to Zero, resp.) the automatic calculation will be done, using the granularity sequence specified. This is the default.
See also
gridSubStepWidth
Definition at line 185 of file KDChartGridAttributes.cpp.
References d.
setGridVisible()
void GridAttributes::setGridVisible (bool visible)
Definition at line 116 of file KDChartGridAttributes.cpp.
References d.
setLinesOnAnnotations()
void GridAttributes::setLinesOnAnnotations (bool b)
When this is enabled, grid lines are drawn only where axis annotations are.
Otherwise annotations are disregarded as far as the grid is concerned.
The default is false.
Definition at line 126 of file KDChartGridAttributes.cpp.
References d.
setOuterLinesVisible()
void GridAttributes::setOuterLinesVisible (bool visible)
Definition at line 280 of file KDChartGridAttributes.cpp.
References d.
setSubGridPen()
void GridAttributes::setSubGridPen (const QPen & pen)
Definition at line 269 of file KDChartGridAttributes.cpp.
References d.
setSubGridVisible()
void GridAttributes::setSubGridVisible (bool visible)
Definition at line 259 of file KDChartGridAttributes.cpp.
References d.
setZeroLinePen()
void GridAttributes::setZeroLinePen (const QPen & pen)
Definition at line 290 of file KDChartGridAttributes.cpp.
References d.
subGridPen()
QPen GridAttributes::subGridPen () const
Definition at line 275 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
zeroLinePen()
QPen GridAttributes::zeroLinePen () const
Definition at line 296 of file KDChartGridAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
The documentation for this class was generated from the following files:
KDChartGridAttributes.h
KDChartGridAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/