KD Chart 2: KDAB::UnitTest::TestRegistry Class Reference
KDAB::UnitTest::TestRegistry Class Reference
#include <testregistry.h>
Public Member Functions
void registerTestFactory (const TestFactory *tf, const char *group)
unsigned int run () const
unsigned int run (const char *group) const
Static Public Member Functions
static void deleteInstance ()
static TestRegistry * instance ()
Detailed Description
Definition at line 41 of file testregistry.h.
Member Function Documentation
deleteInstance()
void KDAB::UnitTest::TestRegistry::deleteInstance () static
Definition at line 52 of file testregistry.cpp.
Referenced by KDAB::UnitTest::Runner::~Runner().
instance()
KDAB::UnitTest::TestRegistry * KDAB::UnitTest::TestRegistry::instance () static
Definition at line 45 of file testregistry.cpp.
Referenced by KDAB::UnitTest::GenericFactory< T_Test >::GenericFactory(), and KDAB::UnitTest::Runner::run().
registerTestFactory()
void KDAB::UnitTest::TestRegistry::registerTestFactory (const TestFactory * tf, const char * group)
Definition at line 56 of file testregistry.cpp.
Referenced by KDAB::UnitTest::GenericFactory< T_Test >::GenericFactory().
run() [1/2]
unsigned int KDAB::UnitTest::TestRegistry::run () const
runs all tests in all groups.
Returns
the number of failed tests (if any)
Definition at line 61 of file testregistry.cpp.
Referenced by KDAB::UnitTest::Runner::run().
run() [2/2]
unsigned int KDAB::UnitTest::TestRegistry::run (const char * group) const
runs only tests in group group
Returns
the number of failed tests (if any)
Definition at line 79 of file testregistry.cpp.
The documentation for this class was generated from the following files:
testregistry.h
testregistry.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/