KD Chart 2: KDChart::MarkerLayoutItem Class Reference
KDChart::MarkerLayoutItem Class Reference
Layout item showing a data point marker.
#include <KDChartLayoutItems.h>
Public Member Functions
virtual Qt::Orientations expandingDirections () const
virtual QRect geometry () const
virtual bool isEmpty () const
MarkerLayoutItem (AbstractDiagram *diagram, const MarkerAttributes &marker, const QBrush &brush, const QPen &pen, Qt::Alignment alignment=0)
virtual QSize maximumSize () const
virtual QSize minimumSize () const
virtual void paint (QPainter *)
virtual void paintAll (QPainter &painter)
Default impl: just call paint.
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
QLayout * parentLayout ()
void removeFromParentLayout ()
virtual void setGeometry (const QRect &r)
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
virtual QSize sizeHint () const
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
Static Public Member Functions
static void paintIntoRect (QPainter *painter, const QRect &rect, AbstractDiagram *diagram, const MarkerAttributes &marker, const QBrush &brush, const QPen &pen)
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
Layout item showing a data point marker.
Definition at line 220 of file KDChartLayoutItems.h.
Constructor & Destructor Documentation
MarkerLayoutItem()
KDChart::MarkerLayoutItem::MarkerLayoutItem (KDChart::AbstractDiagram * diagram, const MarkerAttributes & marker, const QBrush & brush, const QPen & pen, Qt::Alignment alignment = 0)
Definition at line 630 of file KDChartLayoutItems.cpp.
Member Function Documentation
expandingDirections()
Qt::Orientations KDChart::MarkerLayoutItem::expandingDirections () const virtual
Definition at line 642 of file KDChartLayoutItems.cpp.
geometry()
QRect KDChart::MarkerLayoutItem::geometry () const virtual
Definition at line 647 of file KDChartLayoutItems.cpp.
isEmpty()
bool KDChart::MarkerLayoutItem::isEmpty () const virtual
Definition at line 652 of file KDChartLayoutItems.cpp.
maximumSize()
QSize KDChart::MarkerLayoutItem::maximumSize () const virtual
Definition at line 657 of file KDChartLayoutItems.cpp.
minimumSize()
QSize KDChart::MarkerLayoutItem::minimumSize () const virtual
Definition at line 662 of file KDChartLayoutItems.cpp.
paint()
void KDChart::MarkerLayoutItem::paint (QPainter * painter) virtual
Implements KDChart::AbstractLayoutItem.
Definition at line 678 of file KDChartLayoutItems.cpp.
paintAll()
void KDChart::AbstractLayoutItem::paintAll (QPainter & painter) virtual inherited
Default impl: just call paint.
Derived classes like KDChart::AbstractArea are providing additional action here.
Reimplemented in KDChart::AbstractArea, KDChart::TextArea, and KDChart::TernaryAxis.
Definition at line 64 of file KDChartLayoutItems.cpp.
paintCtx()
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual inherited
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
paintIntoRect()
void KDChart::MarkerLayoutItem::paintIntoRect (QPainter * painter, const QRect & rect, AbstractDiagram * diagram, const MarkerAttributes & marker, const QBrush & brush, const QPen & pen) static
Definition at line 683 of file KDChartLayoutItems.cpp.
References KDChart::MarkerAttributes::markerSize(), and KDChart::AbstractDiagram::paintMarker().
Referenced by KDChart::LineWithMarkerLayoutItem::paint().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
setGeometry()
void KDChart::MarkerLayoutItem::setGeometry (const QRect & r) virtual
Definition at line 667 of file KDChartLayoutItems.cpp.
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
sizeHint()
QSize KDChart::MarkerLayoutItem::sizeHint () const virtual
Definition at line 672 of file KDChartLayoutItems.cpp.
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartLayoutItems.h
KDChartLayoutItems.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/