KD Chart 2: KDGantt::ItemDelegate Class Reference
KDGantt::ItemDelegate Class Reference
Class used to render gantt items in a KDGantt::GraphicsView.
#include <KDGanttItemDelegate>
Public Types
enum InteractionState {
State_None = 0,
State_Move,
State_ExtendLeft,
State_ExtendRight,
State_DragConstraint
}
Public Member Functions
virtual QRectF constraintBoundingRect (const QPointF &start, const QPointF &end, const Constraint &constraint) const
QBrush defaultBrush (ItemType type) const
QPen defaultPen (ItemType type) const
virtual InteractionState interactionStateFor (const QPointF &pos, const StyleOptionGanttItem &opt, const QModelIndex &idx) const
virtual Span itemBoundingSpan (const StyleOptionGanttItem &opt, const QModelIndex &idx) const
ItemDelegate (QObject *parent=0)
virtual void paintConstraintItem (QPainter *p, const QStyleOptionGraphicsItem &opt, const QPointF &start, const QPointF &end, const Constraint &constraint)
virtual void paintGanttItem (QPainter *p, const StyleOptionGanttItem &opt, const QModelIndex &idx)
void setDefaultBrush (ItemType type, const QBrush &brush)
void setDefaultPen (ItemType type, const QPen &pen)
virtual QString toolTip (const QModelIndex &idx) const
virtual ~ItemDelegate ()
Protected Member Functions
QPolygonF finishFinishArrow (const QPointF &start, const QPointF &end) const
QPolygonF finishFinishLine (const QPointF &start, const QPointF &end) const
QPolygonF finishStartArrow (const QPointF &start, const QPointF &end) const
QPolygonF finishStartLine (const QPointF &start, const QPointF &end) const
void paintFinishFinishConstraint (QPainter *p, const QStyleOptionGraphicsItem &opt, const QPointF &start, const QPointF &end, const Constraint &constraint)
void paintFinishStartConstraint (QPainter *p, const QStyleOptionGraphicsItem &opt, const QPointF &start, const QPointF &end, const Constraint &constraint)
void paintStartFinishConstraint (QPainter *p, const QStyleOptionGraphicsItem &opt, const QPointF &start, const QPointF &end, const Constraint &constraint)
void paintStartStartConstraint (QPainter *p, const QStyleOptionGraphicsItem &opt, const QPointF &start, const QPointF &end, const Constraint &constraint)
QPolygonF startFinishArrow (const QPointF &start, const QPointF &end) const
QPolygonF startFinishLine (const QPointF &start, const QPointF &end) const
QPolygonF startStartArrow (const QPointF &start, const QPointF &end) const
QPolygonF startStartLine (const QPointF &start, const QPointF &end) const
Detailed Description
Class used to render gantt items in a KDGantt::GraphicsView.
Definition at line 37 of file kdganttitemdelegate.h.
Member Enumeration Documentation
enum KDGantt::ItemDelegate::InteractionState
This enum is used for communication between the view and the delegate about user interaction with gantt items.
See also
KDGantt::ItemDelegate::interactionStateFor
Enumerator
State_None
State_Move
State_ExtendLeft
State_ExtendRight
State_DragConstraint
Definition at line 41 of file kdganttitemdelegate.h.
Constructor & Destructor Documentation
ItemDelegate::ItemDelegate (QObject * parent = 0) explicit
Constructor. Creates an ItemDelegate with parent parent
Definition at line 123 of file kdganttitemdelegate.cpp.
ItemDelegate::~ItemDelegate () virtual
Destructor
Definition at line 129 of file kdganttitemdelegate.cpp.
Member Function Documentation
QRectF ItemDelegate::constraintBoundingRect (const QPointF & start, const QPointF & end, const Constraint & constraint) const virtual
Returns
The bounding rectangle for the graphics used to represent a constraint between points start and end (typically an arrow)
Definition at line 400 of file kdganttitemdelegate.cpp.
References KDGantt::Constraint::FinishFinish, finishFinishArrow(), finishFinishLine(), KDGantt::Constraint::FinishStart, finishStartArrow(), finishStartLine(), KDGantt::Constraint::relationType(), KDGantt::Constraint::StartFinish, startFinishArrow(), startFinishLine(), KDGantt::Constraint::StartStart, startStartArrow(), and startStartLine().
Referenced by KDGantt::ConstraintGraphicsItem::boundingRect().
QBrush ItemDelegate::defaultBrush (ItemType type) const
Returns
The default brush for item type type
Todo:
Move this to GraphicsView to make delegate stateless.
Definition at line 151 of file kdganttitemdelegate.cpp.
References d.
Referenced by paintGanttItem().
QPen ItemDelegate::defaultPen (ItemType type) const
Returns
The default pen for item type type
Todo:
Move this to GraphicsView to make delegate stateless.
Definition at line 171 of file kdganttitemdelegate.cpp.
References d.
Referenced by paintGanttItem().
QPolygonF ItemDelegate::finishFinishArrow (const QPointF & start, const QPointF & end) const protected
Definition at line 527 of file kdganttitemdelegate.cpp.
Referenced by constraintBoundingRect(), and paintFinishFinishConstraint().
QPolygonF ItemDelegate::finishFinishLine (const QPointF & start, const QPointF & end) const protected
Definition at line 505 of file kdganttitemdelegate.cpp.
References TURN.
Referenced by constraintBoundingRect(), and paintFinishFinishConstraint().
QPolygonF ItemDelegate::finishStartArrow (const QPointF & start, const QPointF & end) const protected
Definition at line 481 of file kdganttitemdelegate.cpp.
Referenced by constraintBoundingRect(), and paintFinishStartConstraint().
QPolygonF ItemDelegate::finishStartLine (const QPointF & start, const QPointF & end) const protected
Definition at line 459 of file kdganttitemdelegate.cpp.
References TURN.
Referenced by constraintBoundingRect(), and paintFinishStartConstraint().
ItemDelegate::InteractionState ItemDelegate::interactionStateFor (const QPointF & pos, const StyleOptionGanttItem & opt, const QModelIndex & idx) const virtual
Returns
The interaction state for position pos on item idx when rendered with options opt. This is used to tell the view about how the item should react to mouse click/drag.
Override to implement new items or interactions.
Definition at line 238 of file kdganttitemdelegate.cpp.
References KDGantt::StyleOptionGanttItem::itemRect, KDGantt::ItemTypeRole, State_ExtendLeft, State_ExtendRight, State_Move, State_None, KDGantt::TypeEvent, KDGantt::TypeNone, and KDGantt::TypeSummary.
Referenced by KDGantt::GraphicsItem::hoverMoveEvent(), KDGantt::GraphicsItem::mouseDoubleClickEvent(), and KDGantt::GraphicsItem::mousePressEvent().
Span ItemDelegate::itemBoundingSpan (const StyleOptionGanttItem & opt, const QModelIndex & idx) const virtual
Returns
The bounding Span for the item identified by idx when rendered with options opt. This is often the same as the span given by the AbstractGrid for idx, but it might be larger in case there are additional texts or decorations on the item.
Override this to implement new itemtypes or to change the look of the existing ones.
Definition at line 200 of file kdganttitemdelegate.cpp.
References KDGantt::StyleOptionGanttItem::Center, KDGantt::StyleOptionGanttItem::displayPosition, KDGantt::StyleOptionGanttItem::Hidden, KDGantt::StyleOptionGanttItem::itemRect, KDGantt::ItemTypeRole, KDGantt::StyleOptionGanttItem::Left, KDGantt::StyleOptionGanttItem::Right, and KDGantt::TypeEvent.
Referenced by KDGantt::GraphicsItem::updateItem().
void ItemDelegate::paintConstraintItem (QPainter * painter, const QStyleOptionGraphicsItem & opt, const QPointF & start, const QPointF & end, const Constraint & constraint) virtual
Paints the constraint between points start and end using painter and opt.
Todo:
Review opt's type
Definition at line 426 of file kdganttitemdelegate.cpp.
References KDGantt::Constraint::FinishFinish, KDGantt::Constraint::FinishStart, paintFinishFinishConstraint(), paintFinishStartConstraint(), paintStartFinishConstraint(), paintStartStartConstraint(), KDGantt::Constraint::relationType(), KDGantt::Constraint::StartFinish, and KDGantt::Constraint::StartStart.
Referenced by KDGantt::ConstraintGraphicsItem::paint().
void ItemDelegate::paintFinishFinishConstraint (QPainter * p, const QStyleOptionGraphicsItem & opt, const QPointF & start, const QPointF & end, const Constraint & constraint) protected
Definition at line 492 of file kdganttitemdelegate.cpp.
References d, finishFinishArrow(), and finishFinishLine().
Referenced by paintConstraintItem().
void ItemDelegate::paintFinishStartConstraint (QPainter * p, const QStyleOptionGraphicsItem & opt, const QPointF & start, const QPointF & end, const Constraint & constraint) protected
Definition at line 446 of file kdganttitemdelegate.cpp.
References d, finishStartArrow(), and finishStartLine().
Referenced by paintConstraintItem().
void ItemDelegate::paintGanttItem (QPainter * painter, const StyleOptionGanttItem & opt, const QModelIndex & idx) virtual
Paints the gantt item idx using painter and opt
Definition at line 273 of file kdganttitemdelegate.cpp.
References KDGantt::StyleOptionGanttItem::boundingRect, KDGantt::StyleOptionGanttItem::Center, defaultBrush(), defaultPen(), KDGantt::StyleOptionGanttItem::displayPosition, KDGantt::StyleOptionGanttItem::Hidden, KDGantt::StyleOptionGanttItem::itemRect, KDGantt::ItemTypeRole, KDGantt::StyleOptionGanttItem::Left, KDGantt::StyleOptionGanttItem::Right, KDGantt::TaskCompletionRole, KDGantt::StyleOptionGanttItem::text, KDGantt::TypeEvent, KDGantt::TypeSummary, and KDGantt::TypeTask.
Referenced by KDGantt::Legend::drawItem(), and KDGantt::GraphicsItem::paint().
void ItemDelegate::paintStartFinishConstraint (QPainter * p, const QStyleOptionGraphicsItem & opt, const QPointF & start, const QPointF & end, const Constraint & constraint) protected
Definition at line 584 of file kdganttitemdelegate.cpp.
References d, startFinishArrow(), and startFinishLine().
Referenced by paintConstraintItem().
void ItemDelegate::paintStartStartConstraint (QPainter * p, const QStyleOptionGraphicsItem & opt, const QPointF & start, const QPointF & end, const Constraint & constraint) protected
Definition at line 538 of file kdganttitemdelegate.cpp.
References d, startStartArrow(), and startStartLine().
Referenced by paintConstraintItem().
void ItemDelegate::setDefaultBrush (ItemType type, const QBrush & brush)
Sets the default brush used for items of type type to brush. The default brush is used in the case when the model does not provide an explicit brush.
Todo:
Move this to GraphicsView to make delegate stateless.
Definition at line 142 of file kdganttitemdelegate.cpp.
References d.
void ItemDelegate::setDefaultPen (ItemType type, const QPen & pen)
Sets the default pen used for items of type type to pen. The default pen is used in the case when the model does not provide an explicit pen.
Todo:
Move this to GraphicsView to make delegate stateless.
Definition at line 162 of file kdganttitemdelegate.cpp.
References d.
QPolygonF ItemDelegate::startFinishArrow (const QPointF & start, const QPointF & end) const protected
Definition at line 621 of file kdganttitemdelegate.cpp.
Referenced by constraintBoundingRect(), and paintStartFinishConstraint().
QPolygonF ItemDelegate::startFinishLine (const QPointF & start, const QPointF & end) const protected
Definition at line 597 of file kdganttitemdelegate.cpp.
References TURN.
Referenced by constraintBoundingRect(), and paintStartFinishConstraint().
QPolygonF ItemDelegate::startStartArrow (const QPointF & start, const QPointF & end) const protected
Definition at line 573 of file kdganttitemdelegate.cpp.
Referenced by constraintBoundingRect(), and paintStartStartConstraint().
QPolygonF ItemDelegate::startStartLine (const QPointF & start, const QPointF & end) const protected
Definition at line 552 of file kdganttitemdelegate.cpp.
References TURN.
Referenced by constraintBoundingRect(), and paintStartStartConstraint().
QString ItemDelegate::toolTip (const QModelIndex & idx) const virtual
Returns
The tooltip for index idx
Definition at line 178 of file kdganttitemdelegate.cpp.
References KDGantt::EndTimeRole, and KDGantt::StartTimeRole.
Referenced by KDGantt::GraphicsItem::ganttToolTip().
The documentation for this class was generated from the following files:
kdganttitemdelegate.h
kdganttitemdelegate.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/