KD Chart 2: KDChart::PaintContext Class Reference
KDChart::PaintContext Class Reference
Stores information about painting diagrams.
#include <KDChartPaintContext.h>
Public Member Functions
AbstractCoordinatePlane * coordinatePlane () const
PaintContext ()
QPainter * painter () const
const QRectF rectangle () const
void setCoordinatePlane (AbstractCoordinatePlane *plane)
void setPainter (QPainter *painter)
void setRectangle (const QRectF &rect)
~PaintContext ()
Detailed Description
Stores information about painting diagrams.
Definition at line 41 of file KDChartPaintContext.h.
Constructor & Destructor Documentation
PaintContext::PaintContext ()
Definition at line 48 of file KDChartPaintContext.cpp.
PaintContext::~PaintContext ()
Definition at line 53 of file KDChartPaintContext.cpp.
Member Function Documentation
AbstractCoordinatePlane * PaintContext::coordinatePlane () const
Definition at line 78 of file KDChartPaintContext.cpp.
References d.
Referenced by KDChart::LeveyJenningsDiagram::drawDataPointSymbol(), KDChart::LeveyJenningsDiagram::drawFluidicsPackChangedSymbol(), KDChart::LeveyJenningsDiagram::drawLotChangeSymbol(), KDChart::LeveyJenningsDiagram::drawSensorChangedSymbol(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::RadarDiagram::paint(), KDChart::BarDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::Plotter::paint(), KDChart::LineDiagram::paint(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), KDChart::TernaryAxis::paintCtx(), KDChart::LeveyJenningsAxis::paintCtx(), KDChart::CartesianAxis::paintCtx(), and KDChart::PaintingHelpers::paintValueTracker().
QPainter * PaintContext::painter () const
Definition at line 68 of file KDChartPaintContext.cpp.
References d.
Referenced by KDChart::LeveyJenningsDiagram::drawDataPointSymbol(), KDChart::LeveyJenningsDiagram::drawFluidicsPackChangedSymbol(), KDChart::LeveyJenningsDiagram::drawLotChangeSymbol(), KDChart::LeveyJenningsDiagram::drawSensorChangedSymbol(), KDChart::TernaryPointDiagram::paint(), KDChart::TernaryLineDiagram::paint(), KDChart::RingDiagram::paint(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), KDChart::BarDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::Plotter::paint(), KDChart::LineDiagram::paint(), KDChart::PaintingHelpers::paintAreas(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), KDChart::LeveyJenningsAxis::paintAsOrdinate(), KDChart::TernaryAxis::paintCtx(), KDChart::AbstractLayoutItem::paintCtx(), KDChart::CartesianAxis::paintCtx(), KDChart::PaintingHelpers::paintElements(), KDChart::PaintingHelpers::paintPolyline(), KDChart::PaintingHelpers::paintThreeDLines(), KDChart::PaintingHelpers::paintValueTracker(), and setPainter().
const QRectF PaintContext::rectangle () const
Definition at line 58 of file KDChartPaintContext.cpp.
References d.
Referenced by KDChart::RingDiagram::paint(), KDChart::RadarDiagram::paint(), and KDChart::PolarDiagram::paint().
void PaintContext::setCoordinatePlane (AbstractCoordinatePlane * plane)
Definition at line 83 of file KDChartPaintContext.cpp.
References d.
Referenced by KDChart::TernaryCoordinatePlane::paint(), KDChart::CartesianAxis::paint(), KDChart::BarDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::Plotter::paint(), KDChart::LineDiagram::paint(), and KDChart::CartesianCoordinatePlane::paint().
void PaintContext::setPainter (QPainter * painter)
Definition at line 73 of file KDChartPaintContext.cpp.
References d, and painter().
Referenced by KDChart::TernaryCoordinatePlane::paint(), KDChart::CartesianAxis::paint(), KDChart::PolarCoordinatePlane::paint(), KDChart::CartesianCoordinatePlane::paint(), KDChart::RingDiagram::paintEvent(), KDChart::PieDiagram::paintEvent(), KDChart::RadarDiagram::paintEvent(), KDChart::PolarDiagram::paintEvent(), KDChart::BarDiagram::paintEvent(), KDChart::Plotter::paintEvent(), and KDChart::LineDiagram::paintEvent().
void PaintContext::setRectangle (const QRectF & rect)
Definition at line 63 of file KDChartPaintContext.cpp.
References d.
Referenced by KDChart::TernaryCoordinatePlane::paint(), KDChart::CartesianAxis::paint(), KDChart::CartesianCoordinatePlane::paint(), KDChart::RingDiagram::paintEvent(), KDChart::PieDiagram::paintEvent(), KDChart::RadarDiagram::paintEvent(), KDChart::PolarDiagram::paintEvent(), KDChart::BarDiagram::paintEvent(), KDChart::Plotter::paintEvent(), and KDChart::LineDiagram::paintEvent().
The documentation for this class was generated from the following files:
KDChartPaintContext.h
KDChartPaintContext.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/