KD Chart 2: KDGantt::Constraint Class Reference
KDGantt::Constraint Class Reference
A class used to represent a dependency.
#include <kdganttconstraint.h>
Public Types
enum ConstraintDataRole {
ValidConstraintPen = Qt::UserRole,
InvalidConstraintPen
}
typedef QMap< int, QVariant > DataMap
enum RelationType {
FinishStart = 0,
FinishFinish = 1,
StartStart = 2,
StartFinish = 3
}
enum Type {
TypeSoft = 0,
TypeHard = 1
}
Public Member Functions
bool compareIndexes (const Constraint &other) const
Constraint ()
Constraint (const QModelIndex &idx1, const QModelIndex &idx2, Type type=TypeSoft, RelationType relType=FinishStart, const DataMap &datamap=DataMap())
Constraint (const Constraint &other)
QVariant data (int role) const
QMap< int, QVariant > dataMap () const
QDebug debug (QDebug dbg) const
QModelIndex endIndex () const
uint hash () const
bool operator!= (const Constraint &other) const
Constraint & operator= (const Constraint &other)
bool operator== (const Constraint &other) const
RelationType relationType () const
void setData (int role, const QVariant &value)
void setDataMap (const QMap< int, QVariant > &datamap)
QModelIndex startIndex () const
Type type () const
~Constraint ()
Detailed Description
A class used to represent a dependency.
Instances of this class represent a dependency between the data items pointed to by a start-QModelIndex and an end-QModelIndex.
Definition at line 38 of file kdganttconstraint.h.
Member Typedef Documentation
DataMap
typedef QMap<int, QVariant> KDGantt::Constraint::DataMap
Definition at line 60 of file kdganttconstraint.h.
Member Enumeration Documentation
ConstraintDataRole
enum KDGantt::Constraint::ConstraintDataRole
Data roles used when specifying the pen to draw constraints with.
See also
setData
Enumerator
ValidConstraintPen
InvalidConstraintPen
Definition at line 54 of file kdganttconstraint.h.
RelationType
enum KDGantt::Constraint::RelationType
Enumerator
FinishStart
FinishFinish
StartStart
StartFinish
Definition at line 46 of file kdganttconstraint.h.
Type
enum KDGantt::Constraint::Type
This enum is unused for now.
Enumerator
TypeSoft
TypeHard
Definition at line 41 of file kdganttconstraint.h.
Constructor & Destructor Documentation
Constraint() [1/3]
Constraint::Constraint ()
Default constructor, created an invalid constraint.
Definition at line 93 of file kdganttconstraint.cpp.
Constraint() [2/3]
Constraint::Constraint (const QModelIndex & idx1, const QModelIndex & idx2, Constraint::Type type = TypeSoft, Constraint::RelationType relationType = FinishStart, const DataMap & datamap = DataMap())
Constructor. Creates a dependency for idx2 on idx1.
Parameters
type controls if the constraint is a soft one that is allowed to be broken (ie, go backwards in time) or a hard constraint that will not allow the user to move an item so that the constraint would have to go backwards. The default is TypeSoft.
Actually enforcing hard constraints is the responsibility of the AbstractGrid subclass used in the view.
Parameters
relationType defines how the tasks depends on each other. relationType can be FinishStart (default), FinishFinish, StartStart or StartFinish.
Definition at line 77 of file kdganttconstraint.cpp.
References relationType(), and type().
Constraint() [3/3]
Constraint::Constraint (const Constraint & other)
Copy-Constructor.
Definition at line 99 of file kdganttconstraint.cpp.
~Constraint()
Constraint::~Constraint ()
Destructor
Definition at line 105 of file kdganttconstraint.cpp.
Member Function Documentation
compareIndexes()
bool Constraint::compareIndexes (const Constraint & other) const
Definition at line 175 of file kdganttconstraint.cpp.
References endIndex(), and startIndex().
Referenced by KDGantt::ConstraintModel::hasConstraint(), and KDGantt::ConstraintModel::removeConstraint().
data()
QVariant Constraint::data (int role) const
Returns
The data associated with this index for the specified role.
Parameters
role The role to fetch the data for.
See also
ConstraintDataRole
Definition at line 144 of file kdganttconstraint.cpp.
Referenced by KDGantt::ConstraintGraphicsItem::ganttToolTip().
dataMap()
QMap< int, QVariant > Constraint::dataMap () const
Returns
all the data set on this constraint.
See also
setDataMap
Definition at line 169 of file kdganttconstraint.cpp.
Referenced by KDGantt::ConstraintModel::addConstraint(), and KDGantt::ConstraintGraphicsItem::proxyConstraint().
debug()
QDebug Constraint::debug (QDebug dbg) const
Definition at line 203 of file kdganttconstraint.cpp.
Referenced by operator<<().
endIndex()
QModelIndex Constraint::endIndex () const
Returns
The constrained index
Definition at line 135 of file kdganttconstraint.cpp.
Referenced by KDGantt::ConstraintModel::addConstraint(), KDGantt::ConstraintModel::cleanup(), compareIndexes(), KDGantt::ConstraintModel::constraintsForIndex(), KDGantt::GraphicsScene::insertItem(), KDGantt::ConstraintGraphicsItem::proxyConstraint(), and KDGantt::ConstraintModel::removeConstraint().
hash()
uint Constraint::hash () const
Definition at line 191 of file kdganttconstraint.cpp.
References KDGantt::qHash().
Referenced by KDGantt::qHash().
operator!=()
bool KDGantt::Constraint::operator!= (const Constraint & other) const
Definition at line 87 of file kdganttconstraint.h.
References KDGantt::operator==().
operator=()
Constraint & Constraint::operator= (const Constraint & other)
Assignment operator.
Definition at line 110 of file kdganttconstraint.cpp.
operator==()
bool Constraint::operator== (const Constraint & other) const
Compare two Constraint objects. Two Constraints are equal if the have the same start and end indexes
Definition at line 184 of file kdganttconstraint.cpp.
relationType()
Constraint::RelationType Constraint::relationType () const
This is unused for now.
Definition at line 123 of file kdganttconstraint.cpp.
Referenced by Constraint(), KDGantt::ItemDelegate::constraintBoundingRect(), KDGantt::ItemDelegate::paintConstraintItem(), and KDGantt::ConstraintGraphicsItem::proxyConstraint().
setData()
void Constraint::setData (int role, const QVariant & value)
Set data on this index for the specified role.
Parameters
role The role to set the data for.
value The data to set on the index.
See also
ConstraintDataRole
Definition at line 154 of file kdganttconstraint.cpp.
setDataMap()
void Constraint::setDataMap (const QMap< int, QVariant > & datamap)
Set data on this constraint to the keys/values in datamap. Clears any existing data from the constraint.
Definition at line 162 of file kdganttconstraint.cpp.
startIndex()
QModelIndex Constraint::startIndex () const
Returns
The dependency index
Definition at line 129 of file kdganttconstraint.cpp.
Referenced by KDGantt::ConstraintModel::addConstraint(), KDGantt::ConstraintModel::cleanup(), compareIndexes(), KDGantt::ConstraintModel::constraintsForIndex(), KDGantt::GraphicsScene::insertItem(), KDGantt::ConstraintGraphicsItem::proxyConstraint(), and KDGantt::ConstraintModel::removeConstraint().
type()
Constraint::Type Constraint::type () const
This is unused for now.
Definition at line 117 of file kdganttconstraint.cpp.
Referenced by Constraint(), KDAB_SCOPED_UNITTEST_SIMPLE(), and KDGantt::ConstraintGraphicsItem::proxyConstraint().
The documentation for this class was generated from the following files:
kdganttconstraint.h
kdganttconstraint.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/