KD Chart 2: KDGantt::ForwardingProxyModel Class Reference
KDGantt::ForwardingProxyModel Class Reference
#include <kdganttforwardingproxymodel.h>
Public Member Functions
int columnCount (const QModelIndex &idx=QModelIndex()) const
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
ForwardingProxyModel (QObject *parent=0)
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
QMimeData * mimeData (const QModelIndexList &indexes) const
QStringList mimeTypes () const
QModelIndex parent (const QModelIndex &idx) const
int rowCount (const QModelIndex &idx=QModelIndex()) const
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
void setSourceModel (QAbstractItemModel *model)
Qt::DropActions supportedDropActions () const
virtual ~ForwardingProxyModel ()
Protected Slots
virtual void sourceColumnsAboutToBeInserted (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsAboutToBeRemoved (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsInserted (const QModelIndex &idx, int start, int end)
virtual void sourceColumnsRemoved (const QModelIndex &idx, int start, int end)
virtual void sourceDataChanged (const QModelIndex &from, const QModelIndex &to)
virtual void sourceLayoutAboutToBeChanged ()
virtual void sourceLayoutChanged ()
virtual void sourceModelAboutToBeReset ()
virtual void sourceModelReset ()
virtual void sourceRowsAboutToBeInserted (const QModelIndex &idx, int start, int end)
virtual void sourceRowsAboutToBeRemoved (const QModelIndex &, int start, int end)
virtual void sourceRowsInserted (const QModelIndex &idx, int start, int end)
virtual void sourceRowsRemoved (const QModelIndex &, int start, int end)
Detailed Description
Definition at line 31 of file kdganttforwardingproxymodel.h.
Constructor & Destructor Documentation
ForwardingProxyModel::ForwardingProxyModel (QObject * parent = 0) explicit
Constructor. Creates a new ForwardingProxyModel with parent parent
Definition at line 35 of file kdganttforwardingproxymodel.cpp.
ForwardingProxyModel::~ForwardingProxyModel () virtual
Definition at line 40 of file kdganttforwardingproxymodel.cpp.
Member Function Documentation
int ForwardingProxyModel::columnCount (const QModelIndex & idx = QModelIndex()) const
See also
QAbstractItemModel::columnCount
Definition at line 262 of file kdganttforwardingproxymodel.cpp.
References mapToSource().
bool ForwardingProxyModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent)
Definition at line 294 of file kdganttforwardingproxymodel.cpp.
References index(), mapToSource(), and rowCount().
QModelIndex ForwardingProxyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
See also
QAbstractItemModel::index
Definition at line 268 of file kdganttforwardingproxymodel.cpp.
References mapFromSource(), and mapToSource().
Referenced by KDGantt::ProxyModel::data(), dropMimeData(), and KDAB_SCOPED_UNITTEST_SIMPLE().
QModelIndex ForwardingProxyModel::mapFromSource (const QModelIndex & sourceIndex) const
Converts indexes in the source model to indexes in the proxy model
Definition at line 45 of file kdganttforwardingproxymodel.cpp.
Referenced by KDGantt::View::ensureVisible(), index(), parent(), KDGantt::SummaryHandlingProxyModel::setData(), sourceColumnsAboutToBeInserted(), sourceColumnsAboutToBeRemoved(), KDGantt::SummaryHandlingProxyModel::sourceDataChanged(), sourceDataChanged(), sourceRowsAboutToBeInserted(), and sourceRowsAboutToBeRemoved().
QModelIndex ForwardingProxyModel::mapToSource (const QModelIndex & proxyIndex) const
Converts indexes in the proxy model to indexes in the source model
Definition at line 72 of file kdganttforwardingproxymodel.cpp.
Referenced by columnCount(), KDGantt::SummaryHandlingProxyModel::data(), dropMimeData(), KDGantt::SummaryHandlingProxyModel::flags(), index(), mimeData(), parent(), rowCount(), KDGantt::SummaryHandlingProxyModel::setData(), and setData().
QMimeData * ForwardingProxyModel::mimeData (const QModelIndexList & indexes) const
Definition at line 286 of file kdganttforwardingproxymodel.cpp.
References mapToSource().
QStringList ForwardingProxyModel::mimeTypes () const
Definition at line 314 of file kdganttforwardingproxymodel.cpp.
QModelIndex ForwardingProxyModel::parent (const QModelIndex & idx) const
See also
QAbstractItemModel::parent
Definition at line 274 of file kdganttforwardingproxymodel.cpp.
References mapFromSource(), and mapToSource().
int ForwardingProxyModel::rowCount (const QModelIndex & idx = QModelIndex()) const
See also
QAbstractItemModel::rowCount
Definition at line 256 of file kdganttforwardingproxymodel.cpp.
References mapToSource().
Referenced by dropMimeData().
bool ForwardingProxyModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
See also
QAbstractItemModel::setData
Definition at line 280 of file kdganttforwardingproxymodel.cpp.
References mapToSource().
void ForwardingProxyModel::setSourceModel (QAbstractItemModel * model)
Sets the model to be used as the source model for this proxy. The proxy does not take ownership of the model.
See also
QAbstractProxyModel::setSourceModel
Definition at line 93 of file kdganttforwardingproxymodel.cpp.
References sourceColumnsAboutToBeInserted(), sourceColumnsAboutToBeRemoved(), sourceColumnsInserted(), sourceColumnsRemoved(), sourceDataChanged(), sourceLayoutAboutToBeChanged(), sourceLayoutChanged(), sourceModelAboutToBeReset(), sourceModelReset(), sourceRowsAboutToBeInserted(), sourceRowsAboutToBeRemoved(), sourceRowsInserted(), and sourceRowsRemoved().
void ForwardingProxyModel::sourceColumnsAboutToBeInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called just before columns are inserted into the source model.
See also
QAbstractItemModel::columnsAboutToBeInserted()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 178 of file kdganttforwardingproxymodel.cpp.
References mapFromSource().
Referenced by setSourceModel().
void ForwardingProxyModel::sourceColumnsAboutToBeRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called just before columns are removed from the source model.
See also
QAbstractItemModel::columnsAboutToBeRemoved()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 199 of file kdganttforwardingproxymodel.cpp.
References mapFromSource().
Referenced by setSourceModel().
void ForwardingProxyModel::sourceColumnsInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called after columns have been inserted into the source model.
See also
QAbstractItemModel::columnsInserted()
Definition at line 188 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceColumnsRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called after columns have been removed from the source model.
See also
QAbstractItemModel::columnsRemoved()
Definition at line 209 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceDataChanged (const QModelIndex & from, const QModelIndex & to) protected virtual slot
Called when the data in an existing item in the source model changes.
See also
QAbstractItemModel::dataChanged()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 169 of file kdganttforwardingproxymodel.cpp.
References mapFromSource().
Referenced by setSourceModel().
void ForwardingProxyModel::sourceLayoutAboutToBeChanged () protected virtual slot
Called just before the layout of the source model is changed.
See also
QAbstractItemModel::layoutAboutToBeChanged()
Definition at line 150 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceLayoutChanged () protected virtual slot
Called when the layout of the source model has changed.
See also
QAbstractItemModel::layoutChanged()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 159 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceModelAboutToBeReset () protected virtual slot
Called when the source model is about to be reset.
See also
QAbstractItemModel::modelAboutToBeReset()
Definition at line 131 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceModelReset () protected virtual slot
Called when the source model is reset
See also
QAbstractItemModel::modelReset()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 139 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceRowsAboutToBeInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called just before rows are inserted into the source model.
See also
QAbstractItemModel::rowsAboutToBeInserted()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 220 of file kdganttforwardingproxymodel.cpp.
References mapFromSource().
Referenced by setSourceModel().
void ForwardingProxyModel::sourceRowsAboutToBeRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called just before rows are removed from the source model.
See also
QAbstractItemModel::rowsAboutToBeRemoved()
Reimplemented in KDGantt::SummaryHandlingProxyModel.
Definition at line 239 of file kdganttforwardingproxymodel.cpp.
References mapFromSource().
Referenced by setSourceModel().
void ForwardingProxyModel::sourceRowsInserted (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called after rows have been inserted into the source model.
See also
QAbstractItemModel::rowsInserted()
Definition at line 228 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
void ForwardingProxyModel::sourceRowsRemoved (const QModelIndex & parentIdx, int start, int end) protected virtual slot
Called after rows have been removed from the source model.
See also
QAbstractItemModel::rowsRemoved()
Definition at line 247 of file kdganttforwardingproxymodel.cpp.
Referenced by setSourceModel().
Qt::DropActions ForwardingProxyModel::supportedDropActions () const
Definition at line 319 of file kdganttforwardingproxymodel.cpp.
The documentation for this class was generated from the following files:
kdganttforwardingproxymodel.h
kdganttforwardingproxymodel.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/