KD Chart 2: KDChart::PolarCoordinatePlane Class Reference
KDChart::PolarCoordinatePlane Class Reference
Polar coordinate plane.
#include <KDChartPolarCoordinatePlane.h>
Public Types
enum AxesCalcMode {
Linear,
Logarithmic
}
typedef QList< CoordinateTransformation > CoordinateTransformationList
Public Slots
void layoutPlanes ()
Calling layoutPlanes() on the plane triggers the global KDChart::Chart::slotLayoutPlanes()
void relayout ()
Calling relayout() on the plane triggers the global KDChart::Chart::slotRelayout()
void setGridNeedsRecalculate ()
Used by the chart to clear the cached grid data.
void update ()
Calling update() on the plane triggers the global KDChart::Chart::update()
Signals
void boundariesChanged ()
void destroyedCoordinatePlane (AbstractCoordinatePlane *)
Emitted when this coordinate plane is destroyed.
void geometryChanged (QRect, QRect)
Emitted after the geometry of the Coordinate Plane has been changed.
void internal_geometryChanged (QRect, QRect)
void needLayoutPlanes ()
Emitted when plane needs to trigger the Chart's layouting of the coord.
void needRelayout ()
Emitted when plane needs to trigger the Chart's layouting.
void needUpdate ()
Emitted when plane needs to update its drawings.
void positionChanged (AbstractArea *)
void propertiesChanged ()
Emitted upon change of a property of the Coordinate Plane or any of its components.
void viewportCoordinateSystemChanged ()
Emitted upon change of the view coordinate system.
Public Member Functions
void addDiagram (AbstractDiagram *diagram)
Adds a diagram to this coordinate plane.
void alignToReferencePoint (const RelativePosition &position)
qreal angleUnit () const
BackgroundAttributes backgroundAttributes () const
virtual int bottomOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
bool compare (const AbstractAreaBase *other) const
Returns true if both areas have the same settings.
AbstractDiagram * diagram ()
AbstractDiagramList diagrams ()
ConstAbstractDiagramList diagrams () const
virtual Qt::Orientations expandingDirections () const
pure virtual in QLayoutItem
FrameAttributes frameAttributes () const
virtual QRect geometry () const
pure virtual in QLayoutItem
void getFrameLeadings (int &left, int &top, int &right, int &bottom) const
GridAttributes globalGridAttributes () const
const GridAttributes gridAttributes (bool circular) const
DataDimensionsList gridDimensionsList ()
Returns the dimensions used for drawing the grid lines.
bool hasOwnGridAttributes (bool circular) const
bool isCornerSpacersEnabled () const
virtual bool isEmpty () const
pure virtual in QLayoutItem
bool isRubberBandZoomingEnabled () const
const bool isVisiblePoint (const QPointF &point) const
Tests, if a point is visible on the coordinate plane.
virtual int leftOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
virtual QSize maximumSize () const
pure virtual in QLayoutItem
virtual QSize minimumSize () const
pure virtual in QLayoutItem
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void paint (QPainter *)
reimpl
virtual void paintAll (QPainter &painter)
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
virtual void paintBackground (QPainter &painter, const QRect &rectangle)
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
virtual void paintFrame (QPainter &painter, const QRect &rectangle)
virtual void paintIntoRect (QPainter &painter, const QRect &rect)
Draws the background and frame, then calls paint().
Chart * parent ()
const Chart * parent () const
QLayout * parentLayout ()
PolarCoordinatePlane (Chart *parent=0)
qreal radiusUnit () const
AbstractCoordinatePlane * referenceCoordinatePlane () const
There are two ways, in which planes can be caused to interact, in where they are put layouting wise: The first is the reference plane.
void removeFromParentLayout ()
virtual void replaceDiagram (AbstractDiagram *diagram, AbstractDiagram *oldDiagram=0)
Replaces the old diagram, or appends the diagram, it there is none yet.
void resetGridAttributes (bool circular)
Reset the attributes to be used for grid lines drawn in circular direction (or in sagittal direction, resp.).
virtual int rightOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
void setBackgroundAttributes (const BackgroundAttributes &a)
void setCornerSpacersEnabled (bool enable)
Enables or disables the use of spacers in the plane corners.
void setFrameAttributes (const FrameAttributes &a)
virtual void setGeometry (const QRect &r)
pure virtual in QLayoutItem
void setGlobalGridAttributes (const GridAttributes &)
Set the grid attributes to be used by this coordinate plane.
void setGridAttributes (bool circular, const GridAttributes &)
Set the attributes to be used for grid lines drawn in circular direction (or in sagittal direction, resp.).
void setParent (Chart *parent)
Called internally by KDChart::Chart.
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
void setReferenceCoordinatePlane (AbstractCoordinatePlane *plane)
Set another coordinate plane to be used as the reference plane for this one.
void setRubberBandZoomingEnabled (bool enable)
Enables or disables zooming with a rubber band using the mouse.
void setStartPosition (qreal degrees)
Specify the rotation of the coordinate plane.
virtual void setZoomCenter (const QPointF &center)
Set the point (in value coordinates) to be used as the center point in zoom operations.
virtual void setZoomFactors (qreal factorX, qreal factorY)
Sets both zoom factors in one go.
virtual void setZoomFactorX (qreal factor)
Sets the zoom factor in horizontal direction, that is applied to all coordinate transformations.
virtual void setZoomFactorY (qreal factor)
Sets the zoom factor in vertical direction, that is applied to all coordinate transformations.
virtual AbstractCoordinatePlane * sharedAxisMasterPlane (QPainter *p=0)
virtual QSize sizeHint () const
pure virtual in QLayoutItem
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
qreal startPosition () const
Retrieve the rotation of the coordinate plane.
virtual void takeDiagram (AbstractDiagram *diagram)
Removes the diagram from the plane, without deleting it.
virtual int topOverlap (bool doNotRecalculate=false) const
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
const QPointF translate (const QPointF &diagramPoint) const
Translate the given point in value space coordinates to a position in pixel space.
const QPointF translatePolar (const QPointF &diagramPoint) const
virtual QPointF zoomCenter () const
virtual qreal zoomFactorX () const
virtual qreal zoomFactorY () const
~PolarCoordinatePlane ()
Static Public Member Functions
static void paintBackgroundAttributes (QPainter &painter, const QRect &rectangle, const KDChart::BackgroundAttributes &attributes)
static void paintFrameAttributes (QPainter &painter, const QRect &rectangle, const KDChart::FrameAttributes &attributes)
Protected Slots
void adjustZoomAndRepaint ()
void slotLayoutChanged (AbstractDiagram *diagram)
Protected Member Functions
virtual QRect areaGeometry () const
virtual DataDimensionsList getDataDimensionsList () const
QRect innerRect () const
void layoutDiagrams ()
Distribute the available space among the diagrams and axes.
void paintEvent (QPaintEvent *)
virtual void positionHasChanged ()
void resizeEvent (QResizeEvent *)
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
Polar coordinate plane.
Definition at line 36 of file KDChartPolarCoordinatePlane.h.
Member Typedef Documentation
CoordinateTransformationList
typedef QList<CoordinateTransformation> KDChart::PolarCoordinatePlane::CoordinateTransformationList
Definition at line 44 of file KDChartPolarCoordinatePlane.h.
Member Enumeration Documentation
AxesCalcMode
enum KDChart::AbstractCoordinatePlane::AxesCalcMode inherited
Enumerator
Linear
Logarithmic
Definition at line 53 of file KDChartAbstractCoordinatePlane.h.
Constructor & Destructor Documentation
PolarCoordinatePlane()
PolarCoordinatePlane::PolarCoordinatePlane (Chart * parent = 0) explicit
Definition at line 47 of file KDChartPolarCoordinatePlane.cpp.
~PolarCoordinatePlane()
PolarCoordinatePlane::~PolarCoordinatePlane ()
Definition at line 53 of file KDChartPolarCoordinatePlane.cpp.
Member Function Documentation
addDiagram()
void PolarCoordinatePlane::addDiagram (AbstractDiagram * diagram) virtual
Adds a diagram to this coordinate plane.
Parameters
diagram The diagram to add.
See also
replaceDiagram, takeDiagram
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 63 of file KDChartPolarCoordinatePlane.cpp.
References KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::AbstractCoordinatePlane::diagram(), and slotLayoutChanged().
adjustZoomAndRepaint
void PolarCoordinatePlane::adjustZoomAndRepaint () protected slot
Definition at line 136 of file KDChartPolarCoordinatePlane.cpp.
References d, setZoomFactors(), and KDChart::AbstractCoordinatePlane::update().
alignToReferencePoint()
void AbstractAreaBase::alignToReferencePoint (const RelativePosition & position) inherited
Definition at line 80 of file KDChartAbstractAreaBase.cpp.
angleUnit()
qreal PolarCoordinatePlane::angleUnit () const
Definition at line 210 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by layoutDiagrams().
areaGeometry()
QRect AbstractArea::areaGeometry () const protected virtual inherited
Implements KDChart::AbstractAreaBase.
Definition at line 151 of file KDChartAbstractArea.cpp.
Referenced by KDChart::CartesianCoordinatePlane::drawingArea(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), layoutDiagrams(), KDChart::TernaryCoordinatePlane::paint(), KDChart::CartesianAxis::paint(), KDChart::AbstractArea::paintAll(), and KDChart::CartesianAxis::paintCtx().
backgroundAttributes()
BackgroundAttributes AbstractAreaBase::backgroundAttributes () const inherited
Definition at line 110 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
bottomOverlap()
int AbstractArea::bottomOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart:AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the bottom edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 98 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
boundariesChanged
void KDChart::AbstractCoordinatePlane::boundariesChanged () signal inherited
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::CartesianCoordinatePlane::setHorizontalRange(), and KDChart::CartesianCoordinatePlane::setVerticalRange().
compare()
bool AbstractAreaBase::compare (const AbstractAreaBase * other) const inherited
Returns true if both areas have the same settings.
Definition at line 70 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::backgroundAttributes(), and KDChart::AbstractAreaBase::frameAttributes().
Referenced by KDChart::Legend::compare().
destroyedCoordinatePlane
void KDChart::AbstractCoordinatePlane::destroyedCoordinatePlane (AbstractCoordinatePlane *) signal inherited
Emitted when this coordinate plane is destroyed.
Referenced by KDChart::AbstractCoordinatePlane::~AbstractCoordinatePlane().
diagram()
AbstractDiagram * AbstractCoordinatePlane::diagram () inherited
Returns
The first diagram associated with this coordinate plane.
Definition at line 130 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::TernaryCoordinatePlane::addDiagram(), addDiagram(), KDChart::LeveyJenningsCoordinatePlane::addDiagram(), KDChart::CartesianCoordinatePlane::addDiagram(), KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::Widget::diagram(), findSharingAxisDiagrams(), KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), layoutDiagrams(), KDChart::AbstractCoordinatePlane::replaceDiagram(), KDChart::CartesianCoordinatePlane::setGeometry(), setStartPosition(), KDChart::Widget::setType(), KDChart::CartesianCoordinatePlane::sharedAxisMasterPlane(), and KDChart::AbstractCoordinatePlane::takeDiagram().
diagrams() [1/2]
AbstractDiagramList AbstractCoordinatePlane::diagrams () inherited
Returns
The list of diagrams associated with this coordinate plane.
Definition at line 140 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by allAxisAnnotations(), KDChart::Chart::event(), KDChart::CartesianCoordinatePlane::getDataDimensionsList(), KDChart::CartesianCoordinatePlane::getRawDataBoundingRectFromDiagrams(), KDChart::TernaryCoordinatePlane::layoutDiagrams(), layoutDiagrams(), KDChart::Chart::mouseDoubleClickEvent(), KDChart::Chart::mouseMoveEvent(), KDChart::Chart::mousePressEvent(), KDChart::Chart::mouseReleaseEvent(), KDChart::TernaryCoordinatePlane::paint(), paint(), KDChart::CartesianCoordinatePlane::paint(), KDChart::CartesianCoordinatePlane::setAxesCalcModes(), and KDChart::CartesianCoordinatePlane::setGeometry().
diagrams() [2/2]
ConstAbstractDiagramList AbstractCoordinatePlane::diagrams () const inherited
Returns
The list of diagrams associated with this coordinate plane.
Definition at line 145 of file KDChartAbstractCoordinatePlane.cpp.
References d.
expandingDirections()
Qt::Orientations KDChart::AbstractCoordinatePlane::expandingDirections () const virtual inherited
pure virtual in QLayoutItem
Reimplemented in KDChart::CartesianCoordinatePlane.
Definition at line 211 of file KDChartAbstractCoordinatePlane.cpp.
frameAttributes()
FrameAttributes AbstractAreaBase::frameAttributes () const inherited
Definition at line 96 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::Legend::clone(), KDChart::AbstractAreaBase::compare(), and updateCommonBrush().
geometry()
QRect KDChart::AbstractCoordinatePlane::geometry () const virtual inherited
pure virtual in QLayoutItem
Definition at line 248 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), KDChart::Chart::mouseDoubleClickEvent(), KDChart::Chart::mouseMoveEvent(), KDChart::Chart::mousePressEvent(), KDChart::Chart::mouseReleaseEvent(), KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), paint(), and KDChart::CartesianCoordinatePlane::setGeometry().
geometryChanged
void KDChart::AbstractCoordinatePlane::geometryChanged (QRect , QRect) signal inherited
Emitted after the geometry of the Coordinate Plane has been changed.
and control has returned to the event loop.
Parameters are the old geometry, the new geometry.
getDataDimensionsList()
DataDimensionsList PolarCoordinatePlane::getDataDimensionsList () const protected virtual
Implements KDChart::AbstractCoordinatePlane.
Definition at line 310 of file KDChartPolarCoordinatePlane.cpp.
getFrameLeadings()
void AbstractAreaBase::getFrameLeadings (int & left, int & top, int & right, int & bottom) const inherited
Definition at line 212 of file KDChartAbstractAreaBase.cpp.
References d.
Referenced by KDChart::AbstractAreaBase::innerRect(), and KDChart::AbstractAreaWidget::paintAll().
globalGridAttributes()
GridAttributes KDChart::AbstractCoordinatePlane::globalGridAttributes () const inherited
Returns
The grid attributes used by this coordinate plane.
See also
setGlobalGridAttributes
CartesianCoordinatePlane::gridAttributes
Definition at line 163 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::gridAttributes().
gridAttributes()
const GridAttributes KDChart::PolarCoordinatePlane::gridAttributes (bool circular) const
Returns
The attributes used for grid lines drawn in circular direction (or in sagittal direction, resp.).
Note
This function always returns a valid set of grid attributes: If no special grid attributes were set for this direction the global attributes are returned, as returned by AbstractCoordinatePlane::globalGridAttributes.
See also
setGridAttributes
resetGridAttributes
AbstractCoordinatePlane::globalGridAttributes
hasOwnGridAttributes
Definition at line 339 of file KDChartPolarCoordinatePlane.cpp.
References d.
gridDimensionsList()
KDChart::DataDimensionsList KDChart::AbstractCoordinatePlane::gridDimensionsList () inherited
Returns the dimensions used for drawing the grid lines.
Returned data is the result of (cached) grid calculations, so - if you need that information for your own tasks - make sure to call again this function after every data modification that has changed the data range, since grid calculation is based upon the data range, thus the grid start/end might have changed if the data was changed.
Note
Returned list will contain different numbers of DataDimension, depending on the kind of coordinate plane used. For CartesianCoordinatePlane two DataDimension are returned: the first representing grid lines in X direction (matching the Abscissa axes) and the second indicating vertical grid lines (or Ordinate axes, resp.).
Returns
The dimensions used for drawing the grid lines.
See also
DataDimension
Definition at line 168 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::layoutDiagrams(), and KDChart::PaintingHelpers::paintValueTracker().
hasOwnGridAttributes()
bool KDChart::PolarCoordinatePlane::hasOwnGridAttributes (bool circular) const
Returns
Returns whether the grid attributes have been set for the respective direction via setGridAttributes(bool circular).
If false, the grid will use the global attributes set by AbstractCoordinatePlane::globalGridAttributes (or the default attributes, resp.)
See also
setGridAttributes
resetGridAttributes
AbstractCoordinatePlane::globalGridAttributes
Definition at line 374 of file KDChartPolarCoordinatePlane.cpp.
References d.
innerRect()
QRect AbstractAreaBase::innerRect () const protected inherited
Definition at line 224 of file KDChartAbstractAreaBase.cpp.
References KDChart::AbstractAreaBase::areaGeometry(), and KDChart::AbstractAreaBase::getFrameLeadings().
Referenced by KDChart::AbstractArea::paintAll(), and KDChart::TextArea::paintAll().
internal_geometryChanged
void KDChart::AbstractCoordinatePlane::internal_geometryChanged (QRect , QRect) signal inherited
isCornerSpacersEnabled()
bool KDChart::AbstractCoordinatePlane::isCornerSpacersEnabled () const inherited
Returns
Whether this plane should have spacers in the corners formed by the presence of axes.
Definition at line 295 of file KDChartAbstractCoordinatePlane.cpp.
References d.
isEmpty()
bool KDChart::AbstractCoordinatePlane::isEmpty () const virtual inherited
pure virtual in QLayoutItem
Definition at line 204 of file KDChartAbstractCoordinatePlane.cpp.
isRubberBandZoomingEnabled()
bool KDChart::AbstractCoordinatePlane::isRubberBandZoomingEnabled () const inherited
Returns
Whether zooming with a rubber band using the mouse is enabled.
Definition at line 282 of file KDChartAbstractCoordinatePlane.cpp.
References d.
isVisiblePoint()
const bool KDChart::AbstractCoordinatePlane::isVisiblePoint (const QPointF & point) const inherited
Tests, if a point is visible on the coordinate plane.
Note
Before calling this function the point must have been translated into coordinate plane space.
Definition at line 426 of file KDChartAbstractCoordinatePlane.cpp.
References d.
layoutDiagrams()
void PolarCoordinatePlane::layoutDiagrams () protected virtual
Distribute the available space among the diagrams and axes.
Implements KDChart::AbstractCoordinatePlane.
Definition at line 150 of file KDChartPolarCoordinatePlane.cpp.
References angleUnit(), KDChart::AbstractArea::areaGeometry(), d, KDChart::AbstractDiagram::dataBoundaries(), KDChart::AbstractCoordinatePlane::diagram(), KDChart::AbstractCoordinatePlane::diagrams(), radiusUnit(), startPosition(), KDChart::AbstractCoordinatePlane::update(), and KDChart::AbstractPolarDiagram::valueTotals().
Referenced by resizeEvent(), and slotLayoutChanged().
layoutPlanes
void KDChart::AbstractCoordinatePlane::layoutPlanes () slot inherited
Calling layoutPlanes() on the plane triggers the global KDChart::Chart::slotLayoutPlanes()
Definition at line 265 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), KDChart::AbstractCartesianDiagram::layoutPlanes(), KDChart::CartesianAxis::layoutPlanes(), KDChart::AbstractCoordinatePlane::replaceDiagram(), and KDChart::AbstractCoordinatePlane::takeDiagram().
leftOverlap()
int AbstractArea::leftOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the left edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 74 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
maximumSize()
QSize KDChart::AbstractCoordinatePlane::maximumSize () const virtual inherited
pure virtual in QLayoutItem
Definition at line 216 of file KDChartAbstractCoordinatePlane.cpp.
minimumSize()
QSize KDChart::AbstractCoordinatePlane::minimumSize () const virtual inherited
pure virtual in QLayoutItem
Definition at line 223 of file KDChartAbstractCoordinatePlane.cpp.
mouseDoubleClickEvent()
void KDChart::AbstractCoordinatePlane::mouseDoubleClickEvent (QMouseEvent * event) virtual inherited
Definition at line 340 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseDoubleClickEvent().
mouseMoveEvent()
void KDChart::AbstractCoordinatePlane::mouseMoveEvent (QMouseEvent * event) virtual inherited
Definition at line 407 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseMoveEvent().
mousePressEvent()
void KDChart::AbstractCoordinatePlane::mousePressEvent (QMouseEvent * event) virtual inherited
Definition at line 300 of file KDChartAbstractCoordinatePlane.cpp.
References KDChart::ZoomParameters::center(), d, KDChart::ZoomParameters::xFactor, and KDChart::ZoomParameters::yFactor.
Referenced by KDChart::Chart::mousePressEvent().
mouseReleaseEvent()
void KDChart::AbstractCoordinatePlane::mouseReleaseEvent (QMouseEvent * event) virtual inherited
Definition at line 354 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::mouseReleaseEvent().
needLayoutPlanes
void KDChart::AbstractCoordinatePlane::needLayoutPlanes () signal inherited
Emitted when plane needs to trigger the Chart's layouting of the coord.
planes.
needRelayout
void KDChart::AbstractCoordinatePlane::needRelayout () signal inherited
Emitted when plane needs to trigger the Chart's layouting.
needUpdate
void KDChart::AbstractCoordinatePlane::needUpdate () signal inherited
Emitted when plane needs to update its drawings.
paint()
void PolarCoordinatePlane::paint (QPainter * painter) virtual
reimpl
Implements KDChart::AbstractLayoutItem.
Definition at line 74 of file KDChartPolarCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::diagrams(), KDChart::AbstractCoordinatePlane::geometry(), KDChart::PolarDiagram::paint(), KDChart::PaintContext::setPainter(), zoomFactorX(), and zoomFactorY().
paintAll()
void AbstractArea::paintAll (QPainter & painter) virtual inherited
Call paintAll, if you want the background and the frame to be drawn before the normal paint() is invoked automatically.
Reimplemented from KDChart::AbstractLayoutItem.
Reimplemented in KDChart::TernaryAxis.
Definition at line 120 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::areaGeometry(), d, KDChart::AbstractAreaBase::innerRect(), KDChart::AbstractLayoutItem::paint(), KDChart::AbstractAreaBase::paintBackground(), and KDChart::AbstractAreaBase::paintFrame().
Referenced by KDChart::AbstractArea::paintIntoRect().
paintBackground()
void AbstractAreaBase::paintBackground (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 188 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintBackgroundAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintBackgroundAttributes()
void AbstractAreaBase::paintBackgroundAttributes (QPainter & painter, const QRect & rectangle, const KDChart::BackgroundAttributes & attributes) static inherited
Definition at line 117 of file KDChartAbstractAreaBase.cpp.
References KDChart::BackgroundAttributes::BackgroundPixmapModeCentered, KDChart::BackgroundAttributes::BackgroundPixmapModeNone, KDChart::BackgroundAttributes::BackgroundPixmapModeScaled, KDChart::BackgroundAttributes::BackgroundPixmapModeStretched, KDChart::BackgroundAttributes::brush(), KDChart::BackgroundAttributes::isVisible(), KDChart::BackgroundAttributes::pixmap(), and KDChart::BackgroundAttributes::pixmapMode().
Referenced by KDChart::AbstractAreaBase::paintBackground().
paintCtx()
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual inherited
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
paintEvent()
void KDChart::PolarCoordinatePlane::paintEvent (QPaintEvent *) protected
paintFrame()
void AbstractAreaBase::paintFrame (QPainter & painter, const QRect & rectangle) virtual inherited
Definition at line 204 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::paintFrameAttributes().
Referenced by KDChart::AbstractArea::paintAll(), KDChart::TextArea::paintAll(), and KDChart::AbstractAreaWidget::paintAll().
paintFrameAttributes()
void AbstractAreaBase::paintFrameAttributes (QPainter & painter, const QRect & rectangle, const KDChart::FrameAttributes & attributes) static inherited
Definition at line 167 of file KDChartAbstractAreaBase.cpp.
References KDChart::FrameAttributes::cornerRadius(), KDChart::FrameAttributes::isVisible(), KDChart::FrameAttributes::pen(), and KDChart::PrintingParameters::scalePen().
Referenced by KDChart::AbstractAreaBase::paintFrame().
paintIntoRect()
void AbstractArea::paintIntoRect (QPainter & painter, const QRect & rect) virtual inherited
Draws the background and frame, then calls paint().
In most cases there is no need to overwrite this method in a derived class, but you would overwrite AbstractLayoutItem::paint() instead.
Definition at line 108 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::paintAll().
parent() [1/2]
KDChart::Chart * KDChart::AbstractCoordinatePlane::parent () inherited
Definition at line 198 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::AbstractCoordinatePlane::AbstractCoordinatePlane(), KDChart::LeveyJenningsAxis::paintAsAbscissa(), and KDChart::LeveyJenningsAxis::paintAsOrdinate().
parent() [2/2]
const KDChart::Chart * KDChart::AbstractCoordinatePlane::parent () const inherited
Definition at line 193 of file KDChartAbstractCoordinatePlane.cpp.
References d.
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
positionChanged
void KDChart::AbstractArea::positionChanged (AbstractArea *) signal inherited
Referenced by KDChart::AbstractArea::positionHasChanged().
positionHasChanged()
void AbstractArea::positionHasChanged () protected virtual inherited
Reimplemented from KDChart::AbstractAreaBase.
Definition at line 156 of file KDChartAbstractArea.cpp.
References KDChart::AbstractArea::positionChanged().
propertiesChanged
void KDChart::AbstractCoordinatePlane::propertiesChanged () signal inherited
Emitted upon change of a property of the Coordinate Plane or any of its components.
Referenced by KDChart::CartesianCoordinatePlane::addDiagram(), KDChart::CartesianCoordinatePlane::adjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::adjustRangesToData(), KDChart::CartesianCoordinatePlane::adjustVerticalRangeToData(), KDChart::CartesianCoordinatePlane::handleFixedDataCoordinateSpaceRelation(), KDChart::CartesianCoordinatePlane::setAutoAdjustGridToZoom(), KDChart::CartesianCoordinatePlane::setAutoAdjustHorizontalRangeToData(), KDChart::CartesianCoordinatePlane::setAutoAdjustVerticalRangeToData(), KDChart::CartesianCoordinatePlane::setAxesCalcModes(), KDChart::CartesianCoordinatePlane::setAxesCalcModeX(), KDChart::CartesianCoordinatePlane::setAxesCalcModeY(), KDChart::CartesianCoordinatePlane::setGridAttributes(), KDChart::CartesianCoordinatePlane::setHorizontalRange(), KDChart::CartesianCoordinatePlane::setHorizontalRangeReversed(), KDChart::CartesianCoordinatePlane::setIsometricScaling(), KDChart::CartesianCoordinatePlane::setVerticalRange(), KDChart::CartesianCoordinatePlane::setVerticalRangeReversed(), KDChart::CartesianCoordinatePlane::setZoomCenter(), KDChart::CartesianCoordinatePlane::setZoomFactors(), KDChart::CartesianCoordinatePlane::setZoomFactorX(), and KDChart::CartesianCoordinatePlane::setZoomFactorY().
radiusUnit()
qreal PolarCoordinatePlane::radiusUnit () const
Definition at line 217 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by layoutDiagrams().
referenceCoordinatePlane()
AbstractCoordinatePlane * KDChart::AbstractCoordinatePlane::referenceCoordinatePlane () const inherited
There are two ways, in which planes can be caused to interact, in where they are put layouting wise: The first is the reference plane.
If such a reference plane is set, on a plane, it will use the same cell in the layout as that one. In addition to this, planes can share an axis. In that case they will be laid out in relation to each other as suggested by the position of the axis. If, for example Plane1 and Plane2 share an axis at position Left, that will result in the layout: Axis Plane1 Plane 2, vertically. If Plane1 also happens to be Plane2's reference plane, both planes are drawn over each other. The reference plane concept allows two planes to share the same space even if neither has any axis, and in case there are shared axis, it is used to decided, whether the planes should be painted on top of each other or laid out vertically or horizontally next to each other.
Returns
The reference coordinate plane associated with this one.
Definition at line 183 of file KDChartAbstractCoordinatePlane.cpp.
References d.
relayout
void KDChart::AbstractCoordinatePlane::relayout () slot inherited
Calling relayout() on the plane triggers the global KDChart::Chart::slotRelayout()
Definition at line 259 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), and KDChart::AbstractCoordinatePlane::takeDiagram().
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
replaceDiagram()
void AbstractCoordinatePlane::replaceDiagram (AbstractDiagram * diagram, AbstractDiagram * oldDiagram = 0) virtual inherited
Replaces the old diagram, or appends the diagram, it there is none yet.
Parameters
diagram The diagram to be used instead of the old diagram. This parameter must not be zero, or the method will do nothing.
oldDiagram The diagram to be removed by the new diagram. This diagram will be deleted automatically. If the parameter is omitted, the very first diagram will be replaced. In case, there was no diagram yet, the new diagram will just be added.
Note
If you want to re-use the old diagram, call takeDiagram and addDiagram, instead of using replaceDiagram.
See also
addDiagram, takeDiagram
Definition at line 93 of file KDChartAbstractCoordinatePlane.cpp.
References KDChart::AbstractCoordinatePlane::addDiagram(), d, KDChart::AbstractCoordinatePlane::diagram(), KDChart::AbstractCoordinatePlane::layoutDiagrams(), KDChart::AbstractCoordinatePlane::layoutPlanes(), KDChart::AbstractCoordinatePlane::takeDiagram(), and KDChart::AbstractCoordinatePlane::update().
Referenced by KDChart::Widget::setType().
resetGridAttributes()
void KDChart::PolarCoordinatePlane::resetGridAttributes (bool circular)
Reset the attributes to be used for grid lines drawn in circular direction (or in sagittal direction, resp.).
By calling this method you specify that the global attributes set by AbstractCoordinatePlane::setGlobalGridAttributes be used.
See also
setGridAttributes, gridAttributes
AbstractCoordinatePlane::globalGridAttributes
hasOwnGridAttributes
Definition at line 332 of file KDChartPolarCoordinatePlane.cpp.
resizeEvent()
void PolarCoordinatePlane::resizeEvent (QResizeEvent *) protected
Definition at line 144 of file KDChartPolarCoordinatePlane.cpp.
References d, and layoutDiagrams().
rightOverlap()
int AbstractArea::rightOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the right edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 82 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
setBackgroundAttributes()
void AbstractAreaBase::setBackgroundAttributes (const BackgroundAttributes & a) inherited
Definition at line 101 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
setCornerSpacersEnabled()
void KDChart::AbstractCoordinatePlane::setCornerSpacersEnabled (bool enable) inherited
Enables or disables the use of spacers in the plane corners.
Definition at line 287 of file KDChartAbstractCoordinatePlane.cpp.
References d.
setFrameAttributes()
void AbstractAreaBase::setFrameAttributes (const FrameAttributes & a) inherited
Definition at line 87 of file KDChartAbstractAreaBase.cpp.
References d, and KDChart::AbstractAreaBase::positionHasChanged().
Referenced by KDChart::Legend::clone().
setGeometry()
void KDChart::AbstractCoordinatePlane::setGeometry (const QRect & r) virtual inherited
pure virtual in QLayoutItem
Note
Do not call this function directly, unless you know exactly what you are doing. Geometry management is done by KD Chart's internal layouting measures.
Reimplemented in KDChart::CartesianCoordinatePlane.
Definition at line 235 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::setGeometry().
setGlobalGridAttributes()
void KDChart::AbstractCoordinatePlane::setGlobalGridAttributes (const GridAttributes & a) inherited
Set the grid attributes to be used by this coordinate plane.
To disable grid painting, for example, your code should like this:
GridAttributes ga = plane->globalGridAttributes();
ga.setGlobalGridVisible(false);
plane->setGlobalGridAttributes(ga);
See also
globalGridAttributes
CartesianCoordinatePlane::setGridAttributes
Definition at line 157 of file KDChartAbstractCoordinatePlane.cpp.
References d.
setGridAttributes()
void KDChart::PolarCoordinatePlane::setGridAttributes (bool circular, const GridAttributes & a)
Set the attributes to be used for grid lines drawn in circular direction (or in sagittal direction, resp.).
To disable circular grid painting, for example, your code should like this:
GridAttributes ga = plane->gridAttributes(bool);
ga.setGridVisible(false);
plane-setGridAttributes(bool, ga);
Note
setGridAttributes overwrites the global attributes that were set by AbstractCoordinatePlane::setGlobalGridAttributes. To re-activate these global attributes you can call resetGridAttributes.
See also
resetGridAttributes, gridAttributes
AbstractCoordinatePlane::setGlobalGridAttributes
hasOwnGridAttributes
Definition at line 319 of file KDChartPolarCoordinatePlane.cpp.
References d.
setGridNeedsRecalculate
void KDChart::AbstractCoordinatePlane::setGridNeedsRecalculate () slot inherited
Used by the chart to clear the cached grid data.
Definition at line 173 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::CartesianCoordinatePlane::setAxesCalcModeY().
setParent()
void KDChart::AbstractCoordinatePlane::setParent (KDChart::Chart * parent) inherited
Called internally by KDChart::Chart.
Definition at line 188 of file KDChartAbstractCoordinatePlane.cpp.
References d.
Referenced by KDChart::Chart::insertCoordinatePlane(), and KDChart::Chart::takeCoordinatePlane().
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
setReferenceCoordinatePlane()
void KDChart::AbstractCoordinatePlane::setReferenceCoordinatePlane (AbstractCoordinatePlane * plane) inherited
Set another coordinate plane to be used as the reference plane for this one.
Parameters
plane The coordinate plane to be used the reference plane for this one.
See also
referenceCoordinatePlane
Definition at line 178 of file KDChartAbstractCoordinatePlane.cpp.
References d.
setRubberBandZoomingEnabled()
void KDChart::AbstractCoordinatePlane::setRubberBandZoomingEnabled (bool enable) inherited
Enables or disables zooming with a rubber band using the mouse.
Definition at line 271 of file KDChartAbstractCoordinatePlane.cpp.
References d.
setStartPosition()
void PolarCoordinatePlane::setStartPosition (qreal degrees)
Specify the rotation of the coordinate plane.
In a pie diagram this indicates the position where the first pie starts, in a polar diagram it specifies the Zero position of the circular axis:
Illustration of "start position" property
See also
startPosition
Definition at line 229 of file KDChartPolarCoordinatePlane.cpp.
References d, and KDChart::AbstractCoordinatePlane::diagram().
setZoomCenter()
void PolarCoordinatePlane::setZoomCenter (const QPointF & center) virtual
Set the point (in value coordinates) to be used as the center point in zoom operations.
Parameters
center The point to use.
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 298 of file KDChartPolarCoordinatePlane.cpp.
References d.
setZoomFactors()
void PolarCoordinatePlane::setZoomFactors (qreal factorX, qreal factorY) virtual
Sets both zoom factors in one go.
See also
setZoomFactorX,setZoomFactorY
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 263 of file KDChartPolarCoordinatePlane.cpp.
References setZoomFactorX(), and setZoomFactorY().
Referenced by adjustZoomAndRepaint().
setZoomFactorX()
void PolarCoordinatePlane::setZoomFactorX (qreal factor) virtual
Sets the zoom factor in horizontal direction, that is applied to all coordinate transformations.
Parameters
factor The new zoom factor
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 269 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by setZoomFactors().
setZoomFactorY()
void PolarCoordinatePlane::setZoomFactorY (qreal factor) virtual
Sets the zoom factor in vertical direction, that is applied to all coordinate transformations.
Parameters
factor The new zoom factor
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 280 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by setZoomFactors().
sharedAxisMasterPlane()
AbstractCoordinatePlane * KDChart::AbstractCoordinatePlane::sharedAxisMasterPlane (QPainter * p = 0) virtual inherited
Reimplemented in KDChart::CartesianCoordinatePlane.
Definition at line 431 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::BarDiagram::paint(), KDChart::LeveyJenningsDiagram::paint(), KDChart::Plotter::paint(), and KDChart::LineDiagram::paint().
sizeHint()
QSize KDChart::AbstractCoordinatePlane::sizeHint () const virtual inherited
pure virtual in QLayoutItem
Reimplemented in KDChart::CartesianCoordinatePlane.
Definition at line 228 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::CartesianCoordinatePlane::sizeHint().
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
slotLayoutChanged
void PolarCoordinatePlane::slotLayoutChanged (AbstractDiagram * diagram) protected slot
Definition at line 224 of file KDChartPolarCoordinatePlane.cpp.
References d, and layoutDiagrams().
Referenced by addDiagram().
startPosition()
qreal PolarCoordinatePlane::startPosition () const
Retrieve the rotation of the coordinate plane.
See also
setStartPosition
Definition at line 242 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by layoutDiagrams(), and KDChart::RingDiagram::paint().
takeDiagram()
void AbstractCoordinatePlane::takeDiagram (AbstractDiagram * diagram) virtual inherited
Removes the diagram from the plane, without deleting it.
The plane no longer owns the diagram, so it is the caller's responsibility to delete the diagram.
See also
addDiagram, replaceDiagram
Definition at line 114 of file KDChartAbstractCoordinatePlane.cpp.
References d, KDChart::AbstractCoordinatePlane::diagram(), KDChart::AbstractCoordinatePlane::layoutDiagrams(), KDChart::AbstractCoordinatePlane::layoutPlanes(), KDChart::AbstractCoordinatePlane::relayout(), KDChart::AbstractDiagram::setCoordinatePlane(), and KDChart::AbstractCoordinatePlane::update().
Referenced by KDChart::AbstractCoordinatePlane::replaceDiagram().
topOverlap()
int AbstractArea::topOverlap (bool doNotRecalculate = false) const virtual inherited
This is called at layout time by KDChart::AutoSpacerLayoutItem::sizeHint().
The method triggers AbstractArea::sizeHint() to find out the amount of overlap at the top edge of the area.
Note
The default implementation is not using any caching, it might make sense to implement a more sophisticated solution for derived classes that have complex work to do in sizeHint(). All we have here is a primitive flag to be set by the caller if it is sure that no sizeHint() needs to be called.
Definition at line 90 of file KDChartAbstractArea.cpp.
References d.
Referenced by KDChart::AutoSpacerLayoutItem::sizeHint().
translate()
const QPointF PolarCoordinatePlane::translate (const QPointF & diagramPoint) const virtual
Translate the given point in value space coordinates to a position in pixel space.
Parameters
diagramPoint The point in value coordinates.
Returns
The translated point.
Implements KDChart::AbstractCoordinatePlane.
Definition at line 196 of file KDChartPolarCoordinatePlane.cpp.
References d.
translatePolar()
const QPointF PolarCoordinatePlane::translatePolar (const QPointF & diagramPoint) const
Definition at line 203 of file KDChartPolarCoordinatePlane.cpp.
References d.
update
void KDChart::AbstractCoordinatePlane::update () slot inherited
Calling update() on the plane triggers the global KDChart::Chart::update()
Definition at line 253 of file KDChartAbstractCoordinatePlane.cpp.
Referenced by KDChart::AbstractCoordinatePlane::addDiagram(), adjustZoomAndRepaint(), layoutDiagrams(), KDChart::CartesianCoordinatePlane::layoutDiagrams(), KDChart::AbstractCoordinatePlane::replaceDiagram(), KDChart::CartesianCoordinatePlane::resetGridAttributes(), KDChart::CartesianCoordinatePlane::setGridAttributes(), and KDChart::AbstractCoordinatePlane::takeDiagram().
viewportCoordinateSystemChanged
void KDChart::AbstractCoordinatePlane::viewportCoordinateSystemChanged () signal inherited
Emitted upon change of the view coordinate system.
Referenced by KDChart::CartesianCoordinatePlane::setAxesCalcModes(), KDChart::CartesianCoordinatePlane::setAxesCalcModeX(), and KDChart::CartesianCoordinatePlane::setAxesCalcModeY().
zoomCenter()
QPointF PolarCoordinatePlane::zoomCenter () const virtual
Returns
The center point (in value coordinates) of the coordinate plane, that is used for zoom operations.
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 291 of file KDChartPolarCoordinatePlane.cpp.
References d.
zoomFactorX()
qreal PolarCoordinatePlane::zoomFactorX () const virtual
Returns
The zoom factor in horizontal direction, that is applied to all coordinate transformations.
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 249 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by paint().
zoomFactorY()
qreal PolarCoordinatePlane::zoomFactorY () const virtual
Returns
The zoom factor in vertical direction, that is applied to all coordinate transformations.
Reimplemented from KDChart::AbstractCoordinatePlane.
Definition at line 256 of file KDChartPolarCoordinatePlane.cpp.
References d.
Referenced by paint().
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartPolarCoordinatePlane.h
KDChartPolarCoordinatePlane.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/