KD Chart 2: KDChart::Position Class Reference
KDChart::Position Class Reference
Defines a position, using compass terminology.
#include <KDChartPosition.h>
Public Types
enum Option {
IncludeCenter = 0x1,
IncludeFloating = 0x2
}
Public Member Functions
bool isCorner () const
bool isEastSide () const
bool isFloating () const
bool isNorthSide () const
bool isPole () const
bool isSouthSide () const
bool isUnknown () const
bool isWestSide () const
const char * name () const
Returns a non-translated string in English language, corresponding to this Position.
bool operator!= (const Position &) const
bool operator!= (int) const
bool operator== (const Position &) const
bool operator== (int) const
Position ()
Default constructor.
Position (KDChartEnums::PositionValue value)
Constructor.
QString printableName () const
Returns a translated string, corresponding to this Position.
KDChartEnums::PositionValue value () const
Returns an integer value corresponding to this Position.
Static Public Member Functions
static Position fromName (const char *name)
static Position fromName (const QByteArray &name)
static QList< QByteArray > names (Options options=Options(IncludeCenter|IncludeFloating))
Returns a list of all string, corresponding to the pre-defined positions.
static QStringList printableNames (Options options=Options(IncludeCenter|IncludeFloating))
Returns a list of all translated string, corresponding to the pre-defined positions.
Static Public Attributes
static const Position & Center = staticPositionCenter
static const Position & East = staticPositionEast
static const Position & Floating = staticPositionFloating
static const Position & North = staticPositionNorth
static const Position & NorthEast = staticPositionNorthEast
static const Position & NorthWest = staticPositionNorthWest
static const Position & South = staticPositionSouth
static const Position & SouthEast = staticPositionSouthEast
static const Position & SouthWest = staticPositionSouthWest
static const Position & Unknown = staticPositionUnknown
static const Position & West = staticPositionWest
Detailed Description
Defines a position, using compass terminology.
Using KDChartPosition you can specify one of nine pre-defined, logical points (see the static const getter methods below), in a similar way, as you would use a compass to navigate on a map.
For each piece (slice/bar, etc.) of a chart for example, you can specify the position of the value labels. Figure 1 illustrates which cardinal points refer to which points on a pie or bar chart, resp. In the graphic, "N" stands for North, "S" for South, etc.
Figure 1: Different interpretations of KDChart::Position within KDChart
Note
Often you will declare a Position together with the RelativePosition class, to specify a logical point, which then will be used to layout your chart at runtime, e.g. for specifying the location of a floating Legend box.
For comparing a Position's value with a switch () statement, you can use numeric values defined in KDChartEnums, like this:
switch (yourPosition().value()) {
    case KDChartEnums::PositionNorthWest:
        // your code ...
        break;
    case KDChartEnums::PositionNorth:
        // your code ...
        break;
}
See also
RelativePosition, KDChartEnums::PositionValue
Definition at line 75 of file KDChartPosition.h.
Member Enumeration Documentation
Option
enum KDChart::Position::Option
Enumerator
IncludeCenter
IncludeFloating
Definition at line 114 of file KDChartPosition.h.
Constructor & Destructor Documentation
Position() [1/2]
Position::Position ()
Default constructor.
Creates a new Position, defaulting it to Position::Unknown.
Definition at line 93 of file KDChartPosition.cpp.
Referenced by fromName().
Position() [2/2]
Position::Position (KDChartEnums::PositionValue value)
Constructor.
Creates a new Position, defaulting it to the respective value.
Valid values ranging from zero (unknown value) to 10. If invalid value is passed, a Position::Unknown is created.
Note
Normally there is no need to call this constructor, but you would rather use one of the nine pre-defined, static values, e.g. like this:
* const KDChart::Position myPosition = KDChart::Position::NorthEast;
*
Definition at line 117 of file KDChartPosition.cpp.
Member Function Documentation
fromName() [1/2]
Position Position::fromName (const char * name) static
Definition at line 230 of file KDChartPosition.cpp.
References name(), and Position().
Referenced by fromName().
fromName() [2/2]
Position Position::fromName (const QByteArray & name) static
Definition at line 238 of file KDChartPosition.cpp.
References fromName(), and name().
isCorner()
bool Position::isCorner () const
Definition at line 161 of file KDChartPosition.cpp.
References NorthEast, NorthWest, SouthEast, SouthWest, and value().
isEastSide()
bool Position::isEastSide () const
Definition at line 148 of file KDChartPosition.cpp.
References East, NorthEast, SouthEast, and value().
isFloating()
bool Position::isFloating () const
Definition at line 174 of file KDChartPosition.cpp.
References Floating, and value().
Referenced by KDChart::Chart::reLayoutFloatingLegends().
isNorthSide()
bool Position::isNorthSide () const
Definition at line 142 of file KDChartPosition.cpp.
References North, NorthEast, NorthWest, and value().
isPole()
bool Position::isPole () const
Definition at line 168 of file KDChartPosition.cpp.
References North, South, and value().
isSouthSide()
bool Position::isSouthSide () const
Definition at line 154 of file KDChartPosition.cpp.
References South, SouthEast, SouthWest, and value().
isUnknown()
bool Position::isUnknown () const
Definition at line 131 of file KDChartPosition.cpp.
References Unknown, and value().
isWestSide()
bool Position::isWestSide () const
Definition at line 136 of file KDChartPosition.cpp.
References NorthWest, SouthWest, value(), and West.
name()
const char * Position::name () const
Returns a non-translated string in English language, corresponding to this Position.
Definition at line 182 of file KDChartPosition.cpp.
Referenced by fromName(), and operator<<().
names()
QList< QByteArray > Position::names (Options options = Options(IncludeCenter | IncludeFloating)) static
Returns a list of all string, corresponding to the pre-defined positions.
Parameters
options if set to ExcludeCenter, the returned list does not contain the Center position.
Definition at line 203 of file KDChartPosition.cpp.
References IncludeCenter, and IncludeFloating.
operator!=() [1/2]
bool KDChart::Position::operator!= (const Position & other) const
Definition at line 138 of file KDChartPosition.h.
References operator==().
operator!=() [2/2]
bool KDChart::Position::operator!= (int other) const
Definition at line 139 of file KDChartPosition.h.
References operator==().
operator==() [1/2]
bool Position::operator== (const Position & r) const
Definition at line 242 of file KDChartPosition.cpp.
References value().
Referenced by operator!=().
operator==() [2/2]
bool Position::operator== (int value_) const
Definition at line 248 of file KDChartPosition.cpp.
References value().
printableName()
QString Position::printableName () const
Returns a translated string, corresponding to this Position.
Definition at line 190 of file KDChartPosition.cpp.
Referenced by printableNames().
printableNames()
QStringList Position::printableNames (Options options = Options(IncludeCenter | IncludeFloating)) static
Returns a list of all translated string, corresponding to the pre-defined positions.
Parameters
options if set to ExcludeCenter, the returned list does not contain the Center position.
Definition at line 220 of file KDChartPosition.cpp.
References IncludeCenter, IncludeFloating, and printableName().
value()
KDChartEnums::PositionValue Position::value () const
Returns an integer value corresponding to this Position.
Definition at line 126 of file KDChartPosition.cpp.
Referenced by KDChart::Chart::addHeaderFooter(), isCorner(), isEastSide(), isFloating(), isNorthSide(), isPole(), isSouthSide(), isUnknown(), isWestSide(), operator==(), KDChart::TernaryAxis::setPosition(), KDChart::PolarDiagram::setShowDelimitersAtPosition(), KDChart::PolarDiagram::setShowLabelsAtPosition(), KDChart::PolarDiagram::showDelimitersAtPosition(), and KDChart::PolarDiagram::showLabelsAtPosition().
Member Data Documentation
Center
const Position & Position::Center = staticPositionCenter static
Definition at line 101 of file KDChartPosition.h.
Referenced by KDChart::RadarDiagram::paint(), KDChart::PolarDiagram::paint(), and KDChart::PositionPoints::point().
East
const Position & Position::East = staticPositionEast static
Definition at line 105 of file KDChartPosition.h.
Referenced by isEastSide(), and KDChart::PositionPoints::point().
Floating
const Position & Position::Floating = staticPositionFloating static
Definition at line 111 of file KDChartPosition.h.
Referenced by isFloating(), and KDChart::Legend::setFloatingPosition().
North
const Position & Position::North = staticPositionNorth static
Definition at line 103 of file KDChartPosition.h.
Referenced by isNorthSide(), isPole(), and KDChart::PositionPoints::point().
NorthEast
const Position & Position::NorthEast = staticPositionNorthEast static
Definition at line 104 of file KDChartPosition.h.
Referenced by isCorner(), isEastSide(), isNorthSide(), and KDChart::PositionPoints::point().
NorthWest
const Position & Position::NorthWest = staticPositionNorthWest static
Definition at line 102 of file KDChartPosition.h.
Referenced by isCorner(), isNorthSide(), isWestSide(), and KDChart::PositionPoints::point().
South
const Position & Position::South = staticPositionSouth static
Definition at line 107 of file KDChartPosition.h.
Referenced by isPole(), isSouthSide(), and KDChart::PositionPoints::point().
SouthEast
const Position & Position::SouthEast = staticPositionSouthEast static
Definition at line 106 of file KDChartPosition.h.
Referenced by isCorner(), isEastSide(), isSouthSide(), and KDChart::PositionPoints::point().
SouthWest
const Position & Position::SouthWest = staticPositionSouthWest static
Definition at line 108 of file KDChartPosition.h.
Referenced by isCorner(), isSouthSide(), isWestSide(), and KDChart::PositionPoints::point().
Unknown
const Position & Position::Unknown = staticPositionUnknown static
Definition at line 100 of file KDChartPosition.h.
Referenced by isUnknown(), and KDChart::RelativePosition::resetReferencePosition().
West
const Position & Position::West = staticPositionWest static
Definition at line 109 of file KDChartPosition.h.
Referenced by isWestSide(), and KDChart::PositionPoints::point().
The documentation for this class was generated from the following files:
KDChartPosition.h
KDChartPosition.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/