KD Chart 2: KDChart::ValueTrackerAttributes Class Reference
KDChart::ValueTrackerAttributes Class Reference
Cell-specific attributes regarding value tracking.
#include <KDChartValueTrackerAttributes>
Public Member Functions
QBrush areaBrush () const
QBrush arrowBrush () const
bool isEnabled () const
QPen linePen () const
QBrush markerBrush () const
QPen markerPen () const
QSizeF markerSize () const
bool operator!= (const ValueTrackerAttributes &other) const
ValueTrackerAttributes & operator= (const ValueTrackerAttributes &)
bool operator== (const ValueTrackerAttributes &) const
Qt::Orientations orientations () const
QPen pen () const
void setAreaBrush (const QBrush &brush)
Set the brush the area below the value tracking lines should be filled with.
void setArrowBrush (const QBrush &brush)
void setEnabled (bool enabled)
Set whether value tracking should be enabled for a specific index or not.
void setLinePen (const QPen &pen)
void setMarkerBrush (const QBrush &brush)
void setMarkerPen (const QPen &pen)
void setMarkerSize (const QSizeF &size)
Set the size of the markers.
void setOrientations (Qt::Orientations orientations)
Set the orientations used to show the value tracking.
void setPen (const QPen &pen)
Set the pen the value tracking lines and markers will be drawn with.
ValueTrackerAttributes ()
ValueTrackerAttributes (const ValueTrackerAttributes &)
~ValueTrackerAttributes ()
Detailed Description
Cell-specific attributes regarding value tracking.
ValueTrackerAttributes groups the properties regarding value tracking, and how it is displayed. Value tracking can be used to emphasize on one or several specific points in a line diagram.
Definition at line 42 of file KDChartValueTrackerAttributes.h.
Constructor & Destructor Documentation
ValueTrackerAttributes() [1/2]
ValueTrackerAttributes::ValueTrackerAttributes ()
Definition at line 62 of file KDChartValueTrackerAttributes.cpp.
ValueTrackerAttributes() [2/2]
ValueTrackerAttributes::ValueTrackerAttributes (const ValueTrackerAttributes & r)
Definition at line 67 of file KDChartValueTrackerAttributes.cpp.
~ValueTrackerAttributes()
ValueTrackerAttributes::~ValueTrackerAttributes ()
Definition at line 82 of file KDChartValueTrackerAttributes.cpp.
Member Function Documentation
areaBrush()
QBrush ValueTrackerAttributes::areaBrush () const
Returns
The brush the area below the value tracking lines is filled with
Definition at line 157 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator==(), and KDChart::PaintingHelpers::paintValueTracker().
arrowBrush()
QBrush ValueTrackerAttributes::arrowBrush () const
Definition at line 147 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::paintValueTracker().
isEnabled()
bool ValueTrackerAttributes::isEnabled () const
Returns
Whether value tracking is enabled or not
Definition at line 187 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::paintElements().
linePen()
QPen ValueTrackerAttributes::linePen () const
Definition at line 117 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::paintValueTracker().
markerBrush()
QBrush ValueTrackerAttributes::markerBrush () const
Definition at line 137 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::paintValueTracker().
markerPen()
QPen ValueTrackerAttributes::markerPen () const
Definition at line 127 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::paintValueTracker().
markerSize()
QSizeF ValueTrackerAttributes::markerSize () const
Returns
The size of the markers
Definition at line 167 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::PaintingHelpers::paintValueTracker().
operator!=()
bool KDChart::ValueTrackerAttributes::operator!= (const ValueTrackerAttributes & other) const
Definition at line 119 of file KDChartValueTrackerAttributes.h.
References KDGantt::operator==().
operator=()
ValueTrackerAttributes & ValueTrackerAttributes::operator= (const ValueTrackerAttributes & r)
Definition at line 72 of file KDChartValueTrackerAttributes.cpp.
References d.
operator==()
bool ValueTrackerAttributes::operator== (const ValueTrackerAttributes & r) const
Definition at line 88 of file KDChartValueTrackerAttributes.cpp.
References areaBrush(), arrowBrush(), isEnabled(), linePen(), markerBrush(), markerPen(), and markerSize().
orientations()
Qt::Orientations ValueTrackerAttributes::orientations () const
Returns
The orientations used to show the value tracking. Using only a vertical line, horizontal line or both (the default).
Definition at line 172 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by KDChart::PaintingHelpers::paintValueTracker(), and setOrientations().
pen()
QPen ValueTrackerAttributes::pen () const
Returns
The pen the lines and markers are drawn with
Definition at line 107 of file KDChartValueTrackerAttributes.cpp.
References d.
Referenced by setLinePen(), setMarkerPen(), and setPen().
setAreaBrush()
void ValueTrackerAttributes::setAreaBrush (const QBrush & brush)
Set the brush the area below the value tracking lines should be filled with.
Default is a black brush with the style Qt::NoBrush.
Parameters
brush The brush the area should be filled with
Definition at line 152 of file KDChartValueTrackerAttributes.cpp.
References d.
setArrowBrush()
void ValueTrackerAttributes::setArrowBrush (const QBrush & brush)
Definition at line 142 of file KDChartValueTrackerAttributes.cpp.
References d.
setEnabled()
void ValueTrackerAttributes::setEnabled (bool enabled)
Set whether value tracking should be enabled for a specific index or not.
Parameters
enabled Whether value tracking should be enabled or not
Definition at line 182 of file KDChartValueTrackerAttributes.cpp.
References d.
setLinePen()
void ValueTrackerAttributes::setLinePen (const QPen & pen)
Definition at line 112 of file KDChartValueTrackerAttributes.cpp.
References d, and pen().
setMarkerBrush()
void ValueTrackerAttributes::setMarkerBrush (const QBrush & brush)
Definition at line 132 of file KDChartValueTrackerAttributes.cpp.
References d.
setMarkerPen()
void ValueTrackerAttributes::setMarkerPen (const QPen & pen)
Definition at line 122 of file KDChartValueTrackerAttributes.cpp.
References d, and pen().
setMarkerSize()
void ValueTrackerAttributes::setMarkerSize (const QSizeF & size)
Set the size of the markers.
This includes both the arrows at the axises and the circle at the data point.
Parameters
size The size of the markers
Definition at line 162 of file KDChartValueTrackerAttributes.cpp.
References d.
setOrientations()
void ValueTrackerAttributes::setOrientations (Qt::Orientations orientations)
Set the orientations used to show the value tracking.
Parameters
orientations The orientations of the value tracking lines.
Definition at line 177 of file KDChartValueTrackerAttributes.cpp.
References d, and orientations().
setPen()
void ValueTrackerAttributes::setPen (const QPen & pen)
Set the pen the value tracking lines and markers will be drawn with.
Parameters
pen The pen the lines and markers will be drawn with
Definition at line 99 of file KDChartValueTrackerAttributes.cpp.
References d, and pen().
The documentation for this class was generated from the following files:
KDChartValueTrackerAttributes.h
KDChartValueTrackerAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/