KD Chart 2: KDChart::MarkerAttributes Class Reference
KDChart::MarkerAttributes Class Reference
A set of attributes controlling the appearance of data set markers.
#include <KDChartMarkerAttributes.h>
Public Types
enum MarkerStyle {
MarkerCircle = 0,
MarkerSquare = 1,
MarkerDiamond = 2,
Marker1Pixel = 3,
Marker4Pixels = 4,
MarkerRing = 5,
MarkerCross = 6,
MarkerFastCross = 7,
NoMarker = 8,
PainterPathMarker = 9,
StartCustomMarkers = 10
}
typedef QMap< uint, uint > MarkerStylesMap
Public Member Functions
QPainterPath customMarkerPath () const
bool isVisible () const
MarkerAttributes ()
MarkerAttributes (const MarkerAttributes &)
QColor markerColor () const
QSizeF markerSize () const
uint markerStyle () const
MarkerStylesMap markerStylesMap () const
bool operator!= (const MarkerAttributes &) const
MarkerAttributes & operator= (const MarkerAttributes &)
bool operator== (const MarkerAttributes &) const
QPen pen () const
void setCustomMarkerPath (const QPainterPath &path)
void setMarkerColor (const QColor &color)
void setMarkerSize (const QSizeF &size)
Normally you need to specify a valid QSizeF here, but for Legends you can use the invalid size QSizeF(), to enable automatic marker size calculation:
void setMarkerStyle (uint style)
Set the marker-style to use.
void setMarkerStylesMap (const MarkerStylesMap &map)
void setPen (const QPen &pen)
void setThreeD (bool value)
void setVisible (bool visible)
bool threeD () const
~MarkerAttributes ()
Detailed Description
A set of attributes controlling the appearance of data set markers.
Definition at line 43 of file KDChartMarkerAttributes.h.
Member Typedef Documentation
MarkerStylesMap
typedef QMap<uint, uint> KDChart::MarkerAttributes::MarkerStylesMap
Definition at line 67 of file KDChartMarkerAttributes.h.
Member Enumeration Documentation
MarkerStyle
enum KDChart::MarkerAttributes::MarkerStyle
Enumerator
MarkerCircle
MarkerSquare
MarkerDiamond
Marker1Pixel
Marker4Pixels
MarkerRing
MarkerCross
MarkerFastCross
NoMarker
PainterPathMarker
StartCustomMarkers
Definition at line 52 of file KDChartMarkerAttributes.h.
Constructor & Destructor Documentation
MarkerAttributes() [1/2]
MarkerAttributes::MarkerAttributes ()
Definition at line 62 of file KDChartMarkerAttributes.cpp.
MarkerAttributes() [2/2]
MarkerAttributes::MarkerAttributes (const MarkerAttributes & r)
Definition at line 68 of file KDChartMarkerAttributes.cpp.
~MarkerAttributes()
MarkerAttributes::~MarkerAttributes ()
Definition at line 81 of file KDChartMarkerAttributes.cpp.
Member Function Documentation
customMarkerPath()
QPainterPath MarkerAttributes::customMarkerPath () const
Definition at line 177 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::AbstractDiagram::paintMarker().
isVisible()
bool MarkerAttributes::isVisible () const
Definition at line 117 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::AbstractDiagram::paintMarker().
markerColor()
QColor MarkerAttributes::markerColor () const
Definition at line 167 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::AbstractDiagram::paintMarker().
markerSize()
QSizeF MarkerAttributes::markerSize () const
Definition at line 157 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator==(), KDChart::MarkerLayoutItem::paintIntoRect(), and KDChart::AbstractDiagram::paintMarker().
markerStyle()
uint MarkerAttributes::markerStyle () const
Definition at line 147 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), and KDChart::AbstractDiagram::paintMarker().
markerStylesMap()
MarkerAttributes::MarkerStylesMap MarkerAttributes::markerStylesMap () const
Definition at line 137 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator<<(), and operator==().
operator!=()
bool KDChart::MarkerAttributes::operator!= (const MarkerAttributes & other) const
Definition at line 112 of file KDChartMarkerAttributes.h.
References operator==().
operator=()
MarkerAttributes & MarkerAttributes::operator= (const MarkerAttributes & r)
Definition at line 74 of file KDChartMarkerAttributes.cpp.
operator==()
bool MarkerAttributes::operator== (const MarkerAttributes & r) const
Definition at line 88 of file KDChartMarkerAttributes.cpp.
References customMarkerPath(), isVisible(), markerColor(), markerSize(), markerStyle(), markerStylesMap(), and pen().
Referenced by operator!=().
pen()
QPen MarkerAttributes::pen () const
Definition at line 187 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::AbstractDiagram::paintMarker(), and setPen().
setCustomMarkerPath()
void MarkerAttributes::setCustomMarkerPath (const QPainterPath & path)
Definition at line 172 of file KDChartMarkerAttributes.cpp.
References d.
setMarkerColor()
void MarkerAttributes::setMarkerColor (const QColor & color)
Definition at line 162 of file KDChartMarkerAttributes.cpp.
References d.
setMarkerSize()
void MarkerAttributes::setMarkerSize (const QSizeF & size)
Normally you need to specify a valid QSizeF here, but for Legends you can use the invalid size QSizeF(), to enable automatic marker size calculation:
For Markers shown in a Legend this means the marker size will be equal to the font height used for the labels that are shown next to the markers.
Definition at line 152 of file KDChartMarkerAttributes.cpp.
References d.
setMarkerStyle()
void MarkerAttributes::setMarkerStyle (uint style)
Set the marker-style to use.
This could be either one of the predefined MarkerStyle or a custom one that has a value bigger or equal to StartCustomMarkers.
Such a custom marker does then allow to fetch a custom pixmap for each point (value pair) from the model using the Qt::DecorationRole .
Definition at line 142 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by KDChart::TernaryLineDiagram::TernaryLineDiagram().
setMarkerStylesMap()
void MarkerAttributes::setMarkerStylesMap (const MarkerStylesMap & map)
Definition at line 132 of file KDChartMarkerAttributes.cpp.
References d.
setPen()
void MarkerAttributes::setPen (const QPen & pen)
Definition at line 182 of file KDChartMarkerAttributes.cpp.
References d, and pen().
setThreeD()
void MarkerAttributes::setThreeD (bool value)
Definition at line 122 of file KDChartMarkerAttributes.cpp.
References d.
setVisible()
void MarkerAttributes::setVisible (bool visible)
Definition at line 112 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by KDChart::TernaryLineDiagram::TernaryLineDiagram().
threeD()
bool MarkerAttributes::threeD () const
Definition at line 127 of file KDChartMarkerAttributes.cpp.
References d.
Referenced by KDChart::AbstractDiagram::paintMarker().
The documentation for this class was generated from the following files:
KDChartMarkerAttributes.h
KDChartMarkerAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/