KD Chart 2: KDChart::AbstractThreeDAttributes Class Reference
KDChart::AbstractThreeDAttributes Class Reference abstract
Base class for 3D attributes.
#include <KDChartAbstractThreeDAttributes.h>
Public Member Functions
AbstractThreeDAttributes ()
AbstractThreeDAttributes (const AbstractThreeDAttributes &)
qreal depth () const
bool isEnabled () const
bool isThreeDBrushEnabled () const
bool operator!= (const AbstractThreeDAttributes &other) const
AbstractThreeDAttributes & operator= (const AbstractThreeDAttributes &)
bool operator== (const AbstractThreeDAttributes &) const
void setDepth (qreal depth)
void setEnabled (bool enabled)
void setThreeDBrushEnabled (bool enabled)
virtual QBrush threeDBrush (const QBrush &brush, const QRectF &rect) const
qreal validDepth () const
virtual ~AbstractThreeDAttributes ()=0
Detailed Description
Base class for 3D attributes.
Definition at line 34 of file KDChartAbstractThreeDAttributes.h.
Constructor & Destructor Documentation
AbstractThreeDAttributes() [1/2]
AbstractThreeDAttributes::AbstractThreeDAttributes ()
Definition at line 44 of file KDChartAbstractThreeDAttributes.cpp.
AbstractThreeDAttributes() [2/2]
AbstractThreeDAttributes::AbstractThreeDAttributes (const AbstractThreeDAttributes & r)
Definition at line 49 of file KDChartAbstractThreeDAttributes.cpp.
~AbstractThreeDAttributes()
AbstractThreeDAttributes::~AbstractThreeDAttributes () pure virtual
Definition at line 64 of file KDChartAbstractThreeDAttributes.cpp.
Member Function Documentation
depth()
qreal AbstractThreeDAttributes::depth () const
Definition at line 99 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::PaintingHelpers::project(), and setDepth().
isEnabled()
bool AbstractThreeDAttributes::isEnabled () const
Definition at line 88 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator<<(), operator==(), KDChart::PaintingHelpers::paintAreas(), KDChart::PaintingHelpers::paintElements(), and validDepth().
isThreeDBrushEnabled()
bool AbstractThreeDAttributes::isThreeDBrushEnabled () const
Definition at line 110 of file KDChartAbstractThreeDAttributes.cpp.
References d.
Referenced by operator==(), and threeDBrush().
operator!=()
bool KDChart::AbstractThreeDAttributes::operator!= (const AbstractThreeDAttributes & other) const
Definition at line 57 of file KDChartAbstractThreeDAttributes.h.
References KDGantt::operator==().
operator=()
AbstractThreeDAttributes & AbstractThreeDAttributes::operator= (const AbstractThreeDAttributes & r)
Definition at line 54 of file KDChartAbstractThreeDAttributes.cpp.
References d.
operator==()
bool AbstractThreeDAttributes::operator== (const AbstractThreeDAttributes & r) const
Definition at line 70 of file KDChartAbstractThreeDAttributes.cpp.
References depth(), isEnabled(), and isThreeDBrushEnabled().
Referenced by KDChart::ThreeDPieAttributes::operator==(), KDChart::ThreeDLineAttributes::operator==(), and KDChart::ThreeDBarAttributes::operator==().
setDepth()
void AbstractThreeDAttributes::setDepth (qreal depth)
Definition at line 93 of file KDChartAbstractThreeDAttributes.cpp.
References d, and depth().
setEnabled()
void AbstractThreeDAttributes::setEnabled (bool enabled)
Definition at line 83 of file KDChartAbstractThreeDAttributes.cpp.
References d.
setThreeDBrushEnabled()
void AbstractThreeDAttributes::setThreeDBrushEnabled (bool enabled)
Definition at line 115 of file KDChartAbstractThreeDAttributes.cpp.
References d.
threeDBrush()
QBrush AbstractThreeDAttributes::threeDBrush (const QBrush & brush, const QRectF & rect) const virtual
Definition at line 120 of file KDChartAbstractThreeDAttributes.cpp.
References isThreeDBrushEnabled().
Referenced by KDChart::PaintingHelpers::paintAreas(), and KDChart::PaintingHelpers::paintThreeDLines().
validDepth()
qreal AbstractThreeDAttributes::validDepth () const
Definition at line 105 of file KDChartAbstractThreeDAttributes.cpp.
References d, and isEnabled().
Referenced by KDChart::BarDiagram::threeDItemDepth(), KDChart::Plotter::threeDItemDepth(), and KDChart::LineDiagram::threeDItemDepth().
The documentation for this class was generated from the following files:
KDChartAbstractThreeDAttributes.h
KDChartAbstractThreeDAttributes.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/