KD Chart 2: KDChart::TextBubbleLayoutItem Class Reference
KDChart::TextBubbleLayoutItem Class Reference
#include <KDChartLayoutItems.h>
Public Member Functions
const QObject * autoReferenceArea () const
virtual Qt::Orientations expandingDirections () const
pure virtual in QLayoutItem
virtual QRect geometry () const
pure virtual in QLayoutItem
virtual bool isEmpty () const
pure virtual in QLayoutItem
virtual QSize maximumSize () const
pure virtual in QLayoutItem
virtual QSize minimumSize () const
pure virtual in QLayoutItem
virtual void paint (QPainter *painter)
virtual void paintAll (QPainter &painter)
Default impl: just call paint.
virtual void paintCtx (PaintContext *context)
Default impl: Paint the complete item using its layouted position and size.
QLayout * parentLayout ()
void removeFromParentLayout ()
void setAutoReferenceArea (const QObject *area)
virtual void setGeometry (const QRect &r)
pure virtual in QLayoutItem
void setParentLayout (QLayout *lay)
virtual void setParentWidget (QWidget *widget)
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
void setText (const QString &text)
void setTextAttributes (const TextAttributes &a)
virtual QSize sizeHint () const
pure virtual in QLayoutItem
virtual void sizeHintChanged () const
Report changed size hint: ask the parent widget to recalculate the layout.
QString text () const
TextAttributes textAttributes () const
TextBubbleLayoutItem ()
TextBubbleLayoutItem (const QString &text, const TextAttributes &attributes, const QObject *autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation, Qt::Alignment alignment=0)
~TextBubbleLayoutItem ()
Protected Member Functions
int borderWidth () const
Protected Attributes
QWidget * mParent
QLayout * mParentLayout
Detailed Description
Definition at line 171 of file KDChartLayoutItems.h.
Constructor & Destructor Documentation
TextBubbleLayoutItem() [1/2]
KDChart::TextBubbleLayoutItem::TextBubbleLayoutItem ()
Definition at line 103 of file KDChartLayoutItems.cpp.
TextBubbleLayoutItem() [2/2]
KDChart::TextBubbleLayoutItem::TextBubbleLayoutItem (const QString & text, const TextAttributes & attributes, const QObject * autoReferenceArea, KDChartEnums::MeasureOrientation autoReferenceOrientation, Qt::Alignment alignment = 0)
Definition at line 93 of file KDChartLayoutItems.cpp.
~TextBubbleLayoutItem()
KDChart::TextBubbleLayoutItem::~TextBubbleLayoutItem ()
Definition at line 109 of file KDChartLayoutItems.cpp.
Member Function Documentation
autoReferenceArea()
const QObject * KDChart::TextBubbleLayoutItem::autoReferenceArea () const
Definition at line 119 of file KDChartLayoutItems.cpp.
borderWidth()
int KDChart::TextBubbleLayoutItem::borderWidth () const protected
Definition at line 196 of file KDChartLayoutItems.cpp.
expandingDirections()
Qt::Orientations KDChart::TextBubbleLayoutItem::expandingDirections () const virtual
pure virtual in QLayoutItem
Definition at line 149 of file KDChartLayoutItems.cpp.
geometry()
QRect KDChart::TextBubbleLayoutItem::geometry () const virtual
pure virtual in QLayoutItem
Definition at line 178 of file KDChartLayoutItems.cpp.
isEmpty()
bool KDChart::TextBubbleLayoutItem::isEmpty () const virtual
pure virtual in QLayoutItem
Definition at line 144 of file KDChartLayoutItems.cpp.
maximumSize()
QSize KDChart::TextBubbleLayoutItem::maximumSize () const virtual
pure virtual in QLayoutItem
Definition at line 154 of file KDChartLayoutItems.cpp.
minimumSize()
QSize KDChart::TextBubbleLayoutItem::minimumSize () const virtual
pure virtual in QLayoutItem
Definition at line 160 of file KDChartLayoutItems.cpp.
paint()
void KDChart::TextBubbleLayoutItem::paint (QPainter * painter) virtual
Implements KDChart::AbstractLayoutItem.
Definition at line 184 of file KDChartLayoutItems.cpp.
paintAll()
void KDChart::AbstractLayoutItem::paintAll (QPainter & painter) virtual inherited
Default impl: just call paint.
Derived classes like KDChart::AbstractArea are providing additional action here.
Reimplemented in KDChart::AbstractArea, KDChart::TextArea, and KDChart::TernaryAxis.
Definition at line 64 of file KDChartLayoutItems.cpp.
paintCtx()
void KDChart::AbstractLayoutItem::paintCtx (PaintContext * context) virtual inherited
Default impl: Paint the complete item using its layouted position and size.
Reimplemented in KDChart::CartesianAxis, KDChart::LeveyJenningsAxis, and KDChart::TernaryAxis.
Definition at line 72 of file KDChartLayoutItems.cpp.
References KDChart::PaintContext::painter().
parentLayout()
QLayout* KDChart::AbstractLayoutItem::parentLayout () inherited
Definition at line 78 of file KDChartLayoutItems.h.
removeFromParentLayout()
void KDChart::AbstractLayoutItem::removeFromParentLayout () inherited
Definition at line 82 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::takeCoordinatePlane(), and KDChart::Chart::takeHeaderFooter().
setAutoReferenceArea()
void KDChart::TextBubbleLayoutItem::setAutoReferenceArea (const QObject * area)
Definition at line 114 of file KDChartLayoutItems.cpp.
setGeometry()
void KDChart::TextBubbleLayoutItem::setGeometry (const QRect & r) virtual
pure virtual in QLayoutItem
Definition at line 172 of file KDChartLayoutItems.cpp.
setParentLayout()
void KDChart::AbstractLayoutItem::setParentLayout (QLayout * lay) inherited
Definition at line 74 of file KDChartLayoutItems.h.
Referenced by KDChart::Chart::addHeaderFooter(), and KDChart::Chart::takeHeaderFooter().
setParentWidget()
void KDChart::AbstractLayoutItem::setParentWidget (QWidget * widget) virtual inherited
Inform the item about its widget: This enables the item, to trigger that widget's update, whenever the size of the item's contents has changed.
Thus, you need to call setParentWidget on every item, that has a non-fixed size.
Definition at line 59 of file KDChartLayoutItems.cpp.
References KDChart::AbstractLayoutItem::mParent.
Referenced by KDChart::HeaderFooter::setParent(), and KDChart::AbstractCartesianDiagram::takeAxis().
setText()
void KDChart::TextBubbleLayoutItem::setText (const QString & text)
Definition at line 124 of file KDChartLayoutItems.cpp.
setTextAttributes()
void KDChart::TextBubbleLayoutItem::setTextAttributes (const TextAttributes & a)
Definition at line 134 of file KDChartLayoutItems.cpp.
sizeHint()
QSize KDChart::TextBubbleLayoutItem::sizeHint () const virtual
pure virtual in QLayoutItem
Definition at line 166 of file KDChartLayoutItems.cpp.
sizeHintChanged()
void KDChart::AbstractLayoutItem::sizeHintChanged () const virtual inherited
Report changed size hint: ask the parent widget to recalculate the layout.
Definition at line 81 of file KDChartLayoutItems.cpp.
text()
QString KDChart::TextBubbleLayoutItem::text () const
Definition at line 129 of file KDChartLayoutItems.cpp.
textAttributes()
KDChart::TextAttributes KDChart::TextBubbleLayoutItem::textAttributes () const
Definition at line 139 of file KDChartLayoutItems.cpp.
Member Data Documentation
mParent
QWidget* KDChart::AbstractLayoutItem::mParent protected inherited
Definition at line 92 of file KDChartLayoutItems.h.
Referenced by KDChart::AbstractLayoutItem::setParentWidget().
mParentLayout
QLayout* KDChart::AbstractLayoutItem::mParentLayout protected inherited
Definition at line 93 of file KDChartLayoutItems.h.
The documentation for this class was generated from the following files:
KDChartLayoutItems.h
KDChartLayoutItems.cpp
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/