KD Chart 2: kdganttglobal.h File Reference
kdganttglobal.h File Reference
Contains KDGantt macros.
#include <Qt>
#include <QDateTime>
#include <QDebug>
#include <QMetaType>
#include "kdchart_export.h"
#include <QtAlgorithms>
#include <algorithm>
Classes
class KDGantt::DateTimeSpan
class KDGantt::Span
A class representing a start point and a length.
Namespaces
KDGantt
Macros
#define KDAB_SET_OBJECT_NAME(x) __kdab__dereference_for_methodcall(x).setObjectName(QLatin1String(#x))
#define KDGANTT_DECLARE_PRIVATE_BASE_POLYMORPHIC(X)
#define KDGANTT_DECLARE_PRIVATE_BASE_POLYMORPHIC_QWIDGET(X)
#define KDGANTT_DECLARE_PRIVATE_BASE_VALUE(X)
#define KDGANTT_DECLARE_PRIVATE_DERIVED(X)
#define KDGANTT_DECLARE_PRIVATE_DERIVED_PARENT(X, ParentType)
#define KDGANTT_DECLARE_PRIVATE_DERIVED_QWIDGET(X) KDGANTT_DECLARE_PRIVATE_DERIVED_PARENT(X, QWidget*)
#define KDGANTT_DECLARE_SWAP_BASE(X)
#define KDGANTT_DECLARE_SWAP_DERIVED(X) void swap(X& other) { doSwap(other); }
#define KDGANTT_DECLARE_SWAP_SPECIALISATION(X)
#define KDGANTT_DECLARE_SWAP_SPECIALISATION_DERIVED(X) KDGANTT_DECLARE_SWAP_SPECIALISATION(X)
Enumerations
enum KDGantt::ItemDataRole {
KDGantt::KDGanttRoleBase = Qt::UserRole + 1174,
KDGantt::StartTimeRole = KDGanttRoleBase + 1,
KDGantt::EndTimeRole = KDGanttRoleBase + 2,
KDGantt::TaskCompletionRole = KDGanttRoleBase + 3,
KDGantt::ItemTypeRole = KDGanttRoleBase + 4,
KDGantt::LegendRole = KDGanttRoleBase + 5,
KDGantt::TextPositionRole = KDGanttRoleBase + 6
}
enum KDGantt::ItemType {
KDGantt::TypeNone = 0,
KDGantt::TypeEvent = 1,
KDGantt::TypeTask = 2,
KDGantt::TypeSummary = 3,
KDGantt::TypeMulti = 4,
KDGantt::TypeUser = 1000
}
Functions
template<typename T >
T & __kdab__dereference_for_methodcall (T &o)
template<typename T >
T & __kdab__dereference_for_methodcall (T *o)
bool KDGantt::operator!= (const Span &s1, const Span &s2)
bool KDGantt::operator!= (const DateTimeSpan &s1, const DateTimeSpan &s2)
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, KDGantt::ItemDataRole r)
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, KDGantt::ItemType t)
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, const KDGantt::Span &s)
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, const KDGantt::DateTimeSpan &s)
bool KDGantt::operator== (const Span &s1, const Span &s2)
bool KDGantt::operator== (const DateTimeSpan &s1, const DateTimeSpan &s2)
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDGantt::Span, Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO (KDGantt::DateTimeSpan, Q_MOVABLE_TYPE)
Detailed Description
Contains KDGantt macros.
Contains KDGantt macros.
Definition in file kdganttglobal.h.
Macro Definition Documentation
KDAB_SET_OBJECT_NAME
#define KDAB_SET_OBJECT_NAME (x) __kdab__dereference_for_methodcall(x).setObjectName(QLatin1String(#x))
Definition at line 54 of file kdganttglobal.h.
KDGANTT_DECLARE_PRIVATE_BASE_POLYMORPHIC
#define KDGANTT_DECLARE_PRIVATE_BASE_POLYMORPHIC (X)
Value:
protected:                                            \
    class Private;                                    \
        friend class Private;                         \
    Private * d_func() { return _d; }                 \
    const Private * d_func() const { return _d; }     \
    explicit inline X( Private * );                   \
private:                                              \
    void init();                                      \
    Private * _d;
Definition at line 131 of file kdganttglobal.h.
KDGANTT_DECLARE_PRIVATE_BASE_POLYMORPHIC_QWIDGET
#define KDGANTT_DECLARE_PRIVATE_BASE_POLYMORPHIC_QWIDGET (X)
Value:
protected:                                            \
    class Private;                                    \
        friend class Private;                         \
    Private * d_func() { return _d; }                 \
    const Private * d_func() const { return _d; }     \
    explicit inline X( Private *, QWidget* );         \
private:                                              \
    void init();                                      \
    Private * _d;
Definition at line 156 of file kdganttglobal.h.
KDGANTT_DECLARE_PRIVATE_BASE_VALUE
#define KDGANTT_DECLARE_PRIVATE_BASE_VALUE (X)
Value:
public:                                                      \
    inline void swap( X & other ) { qSwap( _d, other._d ); } \
protected:                                                   \
    class Private;                                           \
        friend class Private;                                \
    Private * d_func() { return _d; }                        \
    const Private * d_func() const { return _d; }            \
private:                                                     \
    void init();                                             \
    Private * _d;
Definition at line 106 of file kdganttglobal.h.
KDGANTT_DECLARE_PRIVATE_DERIVED
#define KDGANTT_DECLARE_PRIVATE_DERIVED (X)
Value:
protected:                                        \
    class Private;                                \
        friend class Private;                     \
    inline Private * d_func();                    \
    inline const Private * d_func() const;        \
    explicit inline X( Private * );               \
private:                                          \
    void init();
Definition at line 69 of file kdganttglobal.h.
KDGANTT_DECLARE_PRIVATE_DERIVED_PARENT
#define KDGANTT_DECLARE_PRIVATE_DERIVED_PARENT (X, ParentType)
Value:
protected:                                        \
    class Private;                                \
        friend class Private;                     \
    inline Private * d_func();                    \
    inline const Private * d_func() const;        \
    explicit inline X( Private *, ParentType );   \
private:                                          \
    void init();
Definition at line 92 of file kdganttglobal.h.
KDGANTT_DECLARE_PRIVATE_DERIVED_QWIDGET
#define KDGANTT_DECLARE_PRIVATE_DERIVED_QWIDGET (X) KDGANTT_DECLARE_PRIVATE_DERIVED_PARENT(X, QWidget*)
Definition at line 103 of file kdganttglobal.h.
KDGANTT_DECLARE_SWAP_BASE
#define KDGANTT_DECLARE_SWAP_BASE (X)
Value:
protected: \
    void doSwap( X& other ) \
    { qSwap( _d, other._d); }
Definition at line 198 of file kdganttglobal.h.
KDGANTT_DECLARE_SWAP_DERIVED
#define KDGANTT_DECLARE_SWAP_DERIVED (X) void swap(X& other) { doSwap(other); }
Definition at line 203 of file kdganttglobal.h.
KDGANTT_DECLARE_SWAP_SPECIALISATION
#define KDGANTT_DECLARE_SWAP_SPECIALISATION (X)
Value:
QT_BEGIN_NAMESPACE                                          \
    template <> inline void qSwap<X>( X & lhs, X & rhs )    \
    { lhs.swap( rhs ); }                                    \
QT_END_NAMESPACE                                            \
    namespace std {                                         \
        template <> inline void swap<X>( X & lhs, X & rhs ) \
        { lhs.swap( rhs ); }                                \
    }
Definition at line 178 of file kdganttglobal.h.
KDGANTT_DECLARE_SWAP_SPECIALISATION_DERIVED
#define KDGANTT_DECLARE_SWAP_SPECIALISATION_DERIVED (X) KDGANTT_DECLARE_SWAP_SPECIALISATION(X)
Definition at line 195 of file kdganttglobal.h.
Function Documentation
__kdab__dereference_for_methodcall() [1/2]
template<typename T > T& __kdab__dereference_for_methodcall (T & o)
Definition at line 45 of file kdganttglobal.h.
__kdab__dereference_for_methodcall() [2/2]
template<typename T > T& __kdab__dereference_for_methodcall (T * o)
Definition at line 50 of file kdganttglobal.h.
operator<<() [1/4]
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, KDGantt::ItemDataRole r)
Definition at line 121 of file kdganttglobal.cpp.
References KDGantt::EndTimeRole, KDGantt::ItemTypeRole, KDGantt::LegendRole, KDGantt::StartTimeRole, and KDGantt::TaskCompletionRole.
operator<<() [2/4]
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, KDGantt::ItemType t)
Definition at line 134 of file kdganttglobal.cpp.
References KDGantt::TypeEvent, KDGantt::TypeMulti, KDGantt::TypeNone, KDGantt::TypeSummary, KDGantt::TypeTask, and KDGantt::TypeUser.
operator<<() [3/4]
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, const KDGantt::Span & s)
Definition at line 148 of file kdganttglobal.cpp.
References KDGantt::Span::length(), and KDGantt::Span::start().
operator<<() [4/4]
QDebug KDGANTT_EXPORT operator<< (QDebug dbg, const KDGantt::DateTimeSpan & s)
Definition at line 153 of file kdganttglobal.cpp.
References KDGantt::DateTimeSpan::end(), and KDGantt::DateTimeSpan::start().
Q_DECLARE_TYPEINFO() [1/2]
QT_BEGIN_NAMESPACE Q_DECLARE_TYPEINFO (KDGantt::Span , Q_MOVABLE_TYPE)
Q_DECLARE_TYPEINFO() [2/2]
Q_DECLARE_TYPEINFO (KDGantt::DateTimeSpan , Q_MOVABLE_TYPE)
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/