KD Chart 2: kdganttglobal.cpp File Reference
kdganttglobal.cpp File Reference
#include "kdganttglobal.h"
#include <ostream>
#include "unittest/test.h"
Macros
#define QT_VERSION_CHECK(major, minor, patch) ((major<<16)|(minor<<8)|(patch))
Functions
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt, Span, "test")
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt, DateTimeSpan, "test")
QDebug operator<< (QDebug dbg, KDGantt::ItemDataRole r)
QDebug operator<< (QDebug dbg, KDGantt::ItemType t)
QDebug operator<< (QDebug dbg, const KDGantt::Span &s)
QDebug operator<< (QDebug dbg, const KDGantt::DateTimeSpan &s)
static std::ostream & operator<< (std::ostream &os, const Span &span)
static std::ostream & operator<< (std::ostream &os, const DateTimeSpan &span)
Macro Definition Documentation
QT_VERSION_CHECK
#define QT_VERSION_CHECK (major, minor, patch) ((major<<16)|(minor<<8)|(patch))
Definition at line 29 of file kdganttglobal.cpp.
Function Documentation
KDAB_SCOPED_UNITTEST_SIMPLE() [1/2]
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt , Span , "test")
Definition at line 185 of file kdganttglobal.cpp.
References assertEqual, assertFalse, KDGantt::Span::isValid(), KDGantt::Span::length(), KDGantt::Span::setLength(), KDGantt::Span::setStart(), and KDGantt::Span::start().
KDAB_SCOPED_UNITTEST_SIMPLE() [2/2]
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt , DateTimeSpan , "test")
Definition at line 195 of file kdganttglobal.cpp.
References assertEqual, assertFalse, assertNotEqual, assertTrue, KDGantt::DateTimeSpan::isValid(), KDGantt::DateTimeSpan::setEnd(), and KDGantt::DateTimeSpan::setStart().
operator<<() [1/6]
QDebug operator<< (QDebug dbg, KDGantt::ItemDataRole r)
Definition at line 121 of file kdganttglobal.cpp.
References KDGantt::EndTimeRole, KDGantt::ItemTypeRole, KDGantt::LegendRole, KDGantt::StartTimeRole, and KDGantt::TaskCompletionRole.
operator<<() [2/6]
QDebug operator<< (QDebug dbg, KDGantt::ItemType t)
Definition at line 134 of file kdganttglobal.cpp.
References KDGantt::TypeEvent, KDGantt::TypeMulti, KDGantt::TypeNone, KDGantt::TypeSummary, KDGantt::TypeTask, and KDGantt::TypeUser.
operator<<() [3/6]
QDebug operator<< (QDebug dbg, const KDGantt::Span & s)
Definition at line 148 of file kdganttglobal.cpp.
References KDGantt::Span::length(), and KDGantt::Span::start().
operator<<() [4/6]
QDebug operator<< (QDebug dbg, const KDGantt::DateTimeSpan & s)
Definition at line 153 of file kdganttglobal.cpp.
References KDGantt::DateTimeSpan::end(), and KDGantt::DateTimeSpan::start().
operator<<() [5/6]
static std::ostream& operator<< (std::ostream & os, const Span & span) static
Definition at line 165 of file kdganttglobal.cpp.
References KDGantt::Span::length(), and KDGantt::Span::start().
operator<<() [6/6]
static std::ostream& operator<< (std::ostream & os, const DateTimeSpan & span) static
Definition at line 171 of file kdganttglobal.cpp.
References KDGantt::DateTimeSpan::end(), and KDGantt::DateTimeSpan::start().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/