KD Chart 2: kdganttconstraintmodel.cpp File Reference
kdganttconstraintmodel.cpp File Reference
#include "kdganttconstraintmodel.h"
#include "kdganttconstraintmodel_p.h"
#include <QDebug>
#include <cassert>
#include <algorithm>
#include <functional>
#include <QStandardItemModel>
#include "unittest/test.h"
#include "moc_kdganttconstraintmodel.cpp"
Macros
#define d d_func()
Functions
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt, ConstraintModel, "test")
QDebug operator<< (QDebug dbg, const KDGantt::ConstraintModel &model)
std::ostream & operator<< (std::ostream &os, const QModelIndex &idx)
Macro Definition Documentation
d
#define d d_func()
Definition at line 91 of file kdganttconstraintmodel.cpp.
Referenced by KDGantt::ConstraintModel::addConstraint(), KDGantt::ConstraintModel::cleanup(), KDGantt::ConstraintModel::constraints(), KDGantt::ConstraintModel::constraintsForIndex(), KDGantt::ConstraintModel::hasConstraint(), and KDGantt::ConstraintModel::removeConstraint().
Function Documentation
KDAB_SCOPED_UNITTEST_SIMPLE()
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt , ConstraintModel , "test")
Definition at line 280 of file kdganttconstraintmodel.cpp.
References KDGantt::ConstraintModel::addConstraint(), assertEqual, assertFalse, assertTrue, KDGantt::ConstraintModel::constraints(), KDGantt::ConstraintModel::constraintsForIndex(), KDGantt::ConstraintModel::hasConstraint(), and KDGantt::ConstraintModel::removeConstraint().
operator<<() [1/2]
QDebug operator<< (QDebug dbg, const KDGantt::ConstraintModel & model)
Definition at line 248 of file kdganttconstraintmodel.cpp.
References KDGantt::ConstraintModel::constraints().
Referenced by operator<<().
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const QModelIndex & idx)
Definition at line 268 of file kdganttconstraintmodel.cpp.
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/