KD Chart 2: kdganttconstraint.cpp File Reference
kdganttconstraint.cpp File Reference
#include "kdganttconstraint.h"
#include "kdganttconstraint_p.h"
#include <QDateTime>
#include <QStandardItemModel>
#include "unittest/test.h"
Functions
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt, Constraint, "test")
QDebug operator<< (QDebug dbg, const Constraint &c)
Function Documentation
KDAB_SCOPED_UNITTEST_SIMPLE()
KDAB_SCOPED_UNITTEST_SIMPLE (KDGantt , Constraint , "test")
Definition at line 217 of file kdganttconstraint.cpp.
References assertEqual, assertFalse, assertNotEqual, assertTrue, KDGantt::qHash(), KDGantt::Constraint::type(), and KDGantt::Constraint::TypeSoft.
operator<<()
QDebug operator<< (QDebug dbg, const Constraint & c)
Definition at line 198 of file kdganttconstraint.cpp.
References KDGantt::Constraint::debug().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/