KD Chart 2: KDChart::PaintingHelpers Namespace Reference
KDChart::PaintingHelpers Namespace Reference
Functions
void paintAreas (AbstractDiagram::Private *diagramPrivate, PaintContext *ctx, const QModelIndex &index, const QList< QPolygonF > &areas, uint opacity)
void paintElements (AbstractDiagram::Private *diagramPrivate, PaintContext *ctx, const LabelPaintCache &lpc, const LineAttributesInfoList &lineList)
void paintPolyline (PaintContext *ctx, const QBrush &brush, const QPen &pen, const QPolygonF &points)
void paintThreeDLines (PaintContext *ctx, AbstractDiagram *diagram, const QModelIndex &index, const QPointF &from, const QPointF &to, const ThreeDLineAttributes &tdAttributes, ReverseMapper *reverseMapper)
void paintValueTracker (PaintContext *ctx, const ValueTrackerAttributes &vt, const QPointF &at)
const QPointF project (const QPointF &point, const ThreeDLineAttributes &tdAttributes)
static ThreeDLineAttributes threeDLineAttributes (AbstractDiagram *diagram, const QModelIndex &index)
static ValueTrackerAttributes valueTrackerAttributes (AbstractDiagram *diagram, const QModelIndex &index)
Function Documentation
void KDChart::PaintingHelpers::paintAreas (AbstractDiagram::Private * diagramPrivate, PaintContext * ctx, const QModelIndex & index, const QList< QPolygonF > & areas, uint opacity)
Definition at line 263 of file PaintingHelpers_p.cpp.
References KDChart::AbstractDiagram::antiAliasing(), KDChart::AbstractDiagram::brush(), KDChart::AbstractThreeDAttributes::isEnabled(), KDChart::PaintContext::painter(), KDChart::AbstractDiagram::pen(), KDChart::PrintingParameters::scalePen(), KDChart::AbstractThreeDAttributes::threeDBrush(), and threeDLineAttributes().
void KDChart::PaintingHelpers::paintElements (AbstractDiagram::Private * diagramPrivate, PaintContext * ctx, const LabelPaintCache & lpc, const LineAttributesInfoList & lineList)
Definition at line 206 of file PaintingHelpers_p.cpp.
References KDChart::AbstractDiagram::antiAliasing(), KDChart::AbstractDiagram::brush(), KDChart::AbstractThreeDAttributes::isEnabled(), KDChart::ValueTrackerAttributes::isEnabled(), KDChart::PaintContext::painter(), paintPolyline(), paintThreeDLines(), paintValueTracker(), KDChart::AbstractDiagram::pen(), threeDLineAttributes(), and valueTrackerAttributes().
void KDChart::PaintingHelpers::paintPolyline (PaintContext * ctx, const QBrush & brush, const QPen & pen, const QPolygonF & points)
Definition at line 56 of file PaintingHelpers_p.cpp.
References KDChart::PaintContext::painter(), and KDChart::PrintingParameters::scalePen().
Referenced by paintElements().
void KDChart::PaintingHelpers::paintThreeDLines (PaintContext * ctx, AbstractDiagram * diagram, const QModelIndex & index, const QPointF & from, const QPointF & to, const ThreeDLineAttributes & tdAttributes, ReverseMapper * reverseMapper)
Definition at line 73 of file PaintingHelpers_p.cpp.
References KDChart::ReverseMapper::addPolygon(), KDChart::AbstractDiagram::antiAliasing(), KDChart::AbstractDiagram::brush(), KDChart::PaintContext::painter(), KDChart::AbstractDiagram::pen(), project(), KDChart::PrintingParameters::scalePen(), and KDChart::AbstractThreeDAttributes::threeDBrush().
Referenced by paintElements().
void KDChart::PaintingHelpers::paintValueTracker (PaintContext * ctx, const ValueTrackerAttributes & vt, const QPointF & at)
Definition at line 94 of file PaintingHelpers_p.cpp.
References KDChart::ValueTrackerAttributes::areaBrush(), KDChart::ValueTrackerAttributes::arrowBrush(), KDChart::PaintContext::coordinatePlane(), KDChart::AbstractCoordinatePlane::gridDimensionsList(), KDChart::CartesianCoordinatePlane::isHorizontalRangeReversed(), KDChart::CartesianCoordinatePlane::isVerticalRangeReversed(), KDChart::ValueTrackerAttributes::linePen(), KDChart::ValueTrackerAttributes::markerBrush(), KDChart::ValueTrackerAttributes::markerPen(), KDChart::ValueTrackerAttributes::markerSize(), KDChart::ValueTrackerAttributes::orientations(), KDChart::PaintContext::painter(), KDChart::PrintingParameters::scalePen(), and KDChart::AbstractCoordinatePlane::translate().
Referenced by paintElements().
const QPointF KDChart::PaintingHelpers::project (const QPointF & point, const ThreeDLineAttributes & tdAttributes)
Projects a point in a space defined by its x, y, and z coordinates into a point on a plane, given two rotation angles around the x resp. y axis.
Definition at line 47 of file PaintingHelpers_p.cpp.
References KDChart::AbstractThreeDAttributes::depth(), KDChart::ThreeDLineAttributes::lineXRotation(), and KDChart::ThreeDLineAttributes::lineYRotation().
Referenced by paintThreeDLines().
static ThreeDLineAttributes KDChart::PaintingHelpers::threeDLineAttributes (AbstractDiagram * diagram, const QModelIndex & index) static
Definition at line 184 of file PaintingHelpers_p.cpp.
Referenced by paintAreas(), and paintElements().
static ValueTrackerAttributes KDChart::PaintingHelpers::valueTrackerAttributes (AbstractDiagram * diagram, const QModelIndex & index) static
Definition at line 195 of file PaintingHelpers_p.cpp.
Referenced by paintElements().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/