KD Chart 2: KDGantt Namespace Reference
KDGantt Namespace Reference
Classes
class AbstractGrid
Abstract baseclass for grids. A grid is used to convert between QModelIndex'es and gantt chart values (qreals) and to paint the background and header of the view.
class AbstractRowController
Abstract baseclass for row controllers. A row controller is used by the GraphicsView to nagivate the model and to determine the row geometries.
class Constraint
A class used to represent a dependency.
class ConstraintGraphicsItem
class ConstraintModel
class ConstraintProxy
class DateTimeGrid
class DateTimeScaleFormatter
class DateTimeSpan
class ForwardingProxyModel
class GraphicsItem
class GraphicsScene
class GraphicsView
The GraphicsView class provides a model/view implementation of a gantt chart.
class ItemDelegate
Class used to render gantt items in a KDGantt::GraphicsView.
class Legend
Legend showing an image and a description for Gantt items.
class ListViewRowController
class ProxyModel
class Span
A class representing a start point and a length.
class StyleOptionGanttItem
QStyleOption subclass for gantt items.
class SummaryHandlingProxyModel
Proxy model that supports summary gantt items.
class TreeViewRowController
class View
This widget that consists of a QTreeView and a GraphicsView.
Enumerations
enum ItemDataRole {
KDGanttRoleBase = Qt::UserRole + 1174,
StartTimeRole = KDGanttRoleBase + 1,
EndTimeRole = KDGanttRoleBase + 2,
TaskCompletionRole = KDGanttRoleBase + 3,
ItemTypeRole = KDGanttRoleBase + 4,
LegendRole = KDGanttRoleBase + 5,
TextPositionRole = KDGanttRoleBase + 6
}
enum ItemType {
TypeNone = 0,
TypeEvent = 1,
TypeTask = 2,
TypeSummary = 3,
TypeMulti = 4,
TypeUser = 1000
}
Functions
bool operator!= (const Span &s1, const Span &s2)
bool operator!= (const DateTimeSpan &s1, const DateTimeSpan &s2)
bool operator== (const Span &s1, const Span &s2)
bool operator== (const DateTimeSpan &s1, const DateTimeSpan &s2)
uint qHash (const Constraint &c)
Enumeration Type Documentation
enum KDGantt::ItemDataRole
The values of this enum are used for the special data roles for gantt items
KDGantt::KDGanttRoleBase The base value used for the KDGantt role enum values. The actual roles have values base+1, base+2, ...
KDGantt::StartTimeRole Start time (or other start value) for a gantt item.
KDGantt::EndTimeRole End time (or other end value) for a gantt item.
KDGantt::TaskCompletionRole Task completetion percentage used by Task items. Should be an integer og a qreal between 0 and 100.
KDGantt::ItemTypeRole The item type.
See also
KDGantt::ItemType.
KDGantt::TextPositionRole The position of the text label on the item. The type of this value is KDGantt::StyleOptionGanttItem::Position and the default values is Right.
Enumerator
KDGanttRoleBase
StartTimeRole
EndTimeRole
TaskCompletionRole
ItemTypeRole
LegendRole
TextPositionRole
Definition at line 216 of file kdganttglobal.h.
enum KDGantt::ItemType
The values of this enum are used to represent the different types of gantt items that KDGantt understands. The itemtype is served through the KDGantt::ItemTypeRole role
Enumerator
TypeNone
TypeEvent
TypeTask
TypeSummary
TypeMulti
TypeUser
Definition at line 225 of file kdganttglobal.h.
Function Documentation
bool KDGantt::operator!= (const Span & s1, const Span & s2)
Definition at line 264 of file kdganttglobal.h.
References KDGantt::Span::equals().
bool KDGantt::operator!= (const DateTimeSpan & s1, const DateTimeSpan & s2)
Definition at line 290 of file kdganttglobal.h.
References KDGantt::DateTimeSpan::equals().
bool KDGantt::operator== (const Span & s1, const Span & s2)
Definition at line 263 of file kdganttglobal.h.
References KDGantt::Span::equals().
Referenced by KDChart::ThreeDPieAttributes::operator!=(), KDChart::StockBarAttributes::operator!=(), KDChart::ThreeDLineAttributes::operator!=(), KDChart::TextAttributes::operator!=(), KDChart::ThreeDBarAttributes::operator!=(), KDChart::AbstractThreeDAttributes::operator!=(), KDChart::FrameAttributes::operator!=(), KDChart::DataValueAttributes::operator!=(), KDChart::BackgroundAttributes::operator!=(), KDChart::BarAttributes::operator!=(), KDChart::LeveyJenningsGridAttributes::operator!=(), KDChart::PieAttributes::operator!=(), KDGantt::Constraint::operator!=(), KDChart::LineAttributes::operator!=(), KDChart::GridAttributes::operator!=(), KDChart::Measure::operator!=(), KDChart::ValueTrackerAttributes::operator!=(), KDChart::Position::operator!=(), and KDChart::RulerAttributes::operator!=().
bool KDGantt::operator== (const DateTimeSpan & s1, const DateTimeSpan & s2)
Definition at line 289 of file kdganttglobal.h.
References KDGantt::DateTimeSpan::equals().
uint KDGantt::qHash (const Constraint & c)
Definition at line 100 of file kdganttconstraint.h.
References KDGantt::Constraint::hash().
Referenced by KDGantt::Constraint::hash(), and KDAB_SCOPED_UNITTEST_SIMPLE().
Klarälvdalens Datakonsult AB (KDAB)
Qt-related services and products
http://www.kdab.com/
http://www.kdab.com/products/kd-chart/